### ISSUE TITLE
Apropiación de Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#1]
Se requiere realizar la apropiación del sistema Oikos V2 para lograr un correcto entendimiento del sistema y posteriormente realizar la depreciación de Oikos V1.

**Sub Tareas**

- [x] Analizar y entender el organigrama general que se usa en planeación 
- [x] Clonar el [repositorio ](https://github.com/udistrital/oikos_api) de Oikos
- [x] Analizar el código del repositorio para entender de mejor manera el funcionamiento.

**Criterios de aceptación**

- [x] Analisis del organigrama.
- [x] Clonación de repositorio.
- [x] Analisis de código en el repositorio.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by kikeavella** [comment]
Anexo un pantallazo para evidenciar que fue clonado el repositorio en mi pc, para hacer el respectivo análisis.

<img width="959" alt="Captura de pantalla 2024-05-02 114419" src="https://github.com/udistrital/core_documentacion/assets/69371935/b90dedc7-9521-42b4-9a84-b0c3cc2019c0">

**Comment by xDa04vidx** [comment]
Anexo clonación del repositorio de OIKOS

![imagen_2024-05-02_115616806](https://github.com/udistrital/core_documentacion/assets/168471458/ac5acfcf-edc7-4d5d-9c2a-a4c93d916158)

**Comment by kikeavella** [comment]
un análisis mío del código es: OIKOS API es una herramienta para gestionar dependencias y espacios físicos dentro de la Universidad Distrital. Permite crear, leer, actualizar y eliminar datos relacionados con diferentes aspectos de la infraestructura universitaria.

Versiones de la API
v1
Operaciones: Cuenta con operaciones para tipos de uso, dependencias, espacios físicos, asignaciones y campos.
Definición de Rutas y Métodos: Las rutas y métodos HTTP están definidos en el código para cada controlador. Por ejemplo, para la asignación de espacios físicos a dependencias, se pueden realizar operaciones como crear, leer, actualizar y eliminar asignaciones.
v2
Nuevos Recursos: Incluye recursos adicionales como centros de costos y proyectos curriculares.
Controladores Específicos: Los controladores se han ajustado y se han agregado nuevos para manejar estos nuevos recursos.
Especificaciones Técnicas
Tecnologías Utilizadas: Golang, BeeGo, Docker y Docker Compose.
Variables de Entorno: Se utilizan para configurar aspectos como el puerto HTTP, el modo de ejecución, la base de datos PostgreSQL, etc.
Ejecución del Proyecto: Se proporcionan instrucciones para ejecutar el proyecto tanto localmente como mediante Docker.

**Comment by xDa04vidx** [comment]
**Análisis**

La API CRUD de OIKOS cuenta con dos versiones que son bastante similares entre sí. En términos generales, OIKOS nos proporciona una herramienta para comprender el organigrama de la universidad y para hacer frente a posibles cambios que puedan surgir en este organigrama.

Ambas versiones, v1 y v2, tienen controladores dedicados. En la versión 2, se incluyen campos adicionales que no están presentes en la v1, como la fecha de creación y la fecha de modificación. Además, en estos controladores, se realizan múltiples solicitudes, principalmente de tipo PUT y DELETE. Sin embargo, en lugar de devolver el ID como se especifica en los lineamientos, la respuesta es simplemente "OK".

Por último, en los modelos de datos se están utilizando nuevas estructuras para cumplir con los requisitos de la oficina, añadiendo los campos faltantes mencionados anteriormente en los controladores. En resumen, no hay cambios significativos entre la versión 1 y la versión 2, más allá de una mejora en las prácticas y la adición de dos nuevos controladores y modelos.
