### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#10]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se intentado el primer intento de contacto con los clientes para concertar una reunión.

**Comment by mantnicot** [comment]
Se ha podido realizar el contacto y se ha agendado la reunión con Eduar y John para 15/05/2024 a las 10:00 am


[Link de reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmRhYjI3MTItMWU2My00Y2JhLWIyNzctYjczODJjNTQ0ZjJk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha realizado la reunión y se deja el acta a espera de firma de los asistentes


[ACTA SIN FIRMAS](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EevnZlAbPdJBjQTOKxBphNwBCwRcAgK-cky49tyZukXSAA?e=DEwAYC)

**Comment by jcmurilloa** [comment]
Se generan revisión y modificaciones al acta, el documento cuenta con VoBo para la respectiva recolección de firmas por parte de los asistentes.

**Comment by mantnicot** [comment]
Se ha registrado las firmas en el acta

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ERABZnwZ8IdIm7je_ZQULPgB9fT9MxqLNB4hOc4Durnlhw?e=1LAuLp)

**Comment by jcmurilloa** [comment]
Muy buen desempeño Cristian!
