### ISSUE TITLE
Creación de lógica en cliente de registro y gestión de dependencias para consulta de dependencias - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#100]
Se requiere realizar la implementación de los desplegables de facultad y vicerrectoria realizando peticiones al CRUD de Oikos y mostrar la respectiva lista en esta vista.

**Sub Tareas**

- [x] Realizar consultas al crud para obtener listado de facultades y vicerrectorias.
- [x] Implementar las respuestas anteriores a los desplegables de la vista de gestión.
- [x] Comprobar correcto funcionamiento.

**Criterios de aceptación**

- [x] Consultas CRUD realizadas.
- [x] Implementación de desplegables realizada.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se logra mostrar los datos correctos
Se muestran los datos correctos para los desplegables de:

- Facultad
![Image](https://github.com/user-attachments/assets/61d1b58c-c942-4b84-b7d5-1b722a304f3a)

- Vicerrectoría
![Image](https://github.com/user-attachments/assets/9c96ccbd-129e-4518-9ac9-4164182114a1)

Para ello se realiza una búsqueda global a todas las dependencias y se crea un filtro para solo tener en cuenta las dependencias con tipo "FACULTAD" o "VICERRECTORIA"

![Image](https://github.com/user-attachments/assets/07a141f8-c5c3-4bc9-9f42-79e5e54c51c5)

Además se guardan los id's correspondientes a las dependencias encontradas
