### ISSUE TITLE
Corregir implementación de X-Ray para que en AWS se muestren los códigos de respuesta

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#101]
Se requiere realizar la corrección en la implementación de X-Ray para que en AWS se muestren los respectivos códigos de respuesta que dan las peticiones, esto teniendo en cuenta que actualmente para las Apis de python si bien se realiza el mapeo cuando se va a ver las caracteristicas de las peticiones estas no muestran los códigos de respuesta.

**Sub Tareas**

- [x] Análizar el por que no muestra los códigos de respuesta en AWS.
- [x] Realizar los respectivos ajustes para que estos códigos se muestren en el análisis de trazas que se visualizan desde AWS.
- [x] Comprobar correcto funcionamiento una vez se realicen los ajustes.

**Criterios de aceptación**

- [x] Análisis realizado.
- [x] Ajustes realizados
- [x] Comprobación de funcionamiento correcto realizado.
- [x] Documentación de issue realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hace la respectiva corrección para que en los metadatos queden guardados la url de la solicitud, método de solicitud o petición http y el código de respuesta de dicha petición, además se corrige el error para que rastre los subsegmentos ya que no lo hacia, es decir que si hacemos una petición a una api y esa api hace otra petición a otra api, quede el rastro en todo el seguimiento que tuvo la petición como se ve en la imagen:

<img width="121" alt="image" src="https://github.com/user-attachments/assets/2643e2a1-8fa8-4975-8b14-c04e6e94c5bd">

Se hacen las siguientes peticiones desde postman:

* Petición Get:

<img width="670" alt="image" src="https://github.com/user-attachments/assets/fc3ee043-f0e6-4e6b-8542-b90d4e6d44ee">

Respuesta en aws con la información de los metadatos

<img width="959" alt="image" src="https://github.com/user-attachments/assets/b1063188-7c70-4ffa-93fc-56f45aeee026">

* Petición Post:

<img width="675" alt="image" src="https://github.com/user-attachments/assets/7a7c6645-2082-45b4-887e-f13bc1a67005">

Respuesta en aws con la información de los metadatos

<img width="959" alt="image" src="https://github.com/user-attachments/assets/57ba742d-7688-424e-9eb8-c4c1db1fec46">

* Petición Put:

<img width="673" alt="image" src="https://github.com/user-attachments/assets/bd42a169-c0d8-412d-aa66-2dc75af9fe43">

Respuesta en aws con la información de los metadatos

<img width="959" alt="image" src="https://github.com/user-attachments/assets/70e7704d-f314-4881-8a80-871c39eea9e5">

**Comment by diagutierrezro** [comment]
Se valida el correcto funcionamiento en X-Ray de AWS. Gran trabajo Julian.
