### ISSUE TITLE
Revisar implementación del cliente de evaluación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#102]
Se requiere realizar la corrección en el cliente de evaluación ya que en la firma de certificaciones CPS el firmante se está quemando siempre por el mismo firmante por lo que esta firma debe ser dinamica.

**Sub Tareas**

- [x] Buscar manera en la que la consulta se haga por cargo o por fechas pero que no se queme el id del cargo ya que nada garantiza que el id de este cargo sea el mismo en pruebas y producción.
- [x] Realizar el respectivo ajuste en cliente de evaluación para modificar dicha consulta.

**Criterios de aceptación**

- [x] Busqueda de cambio en consulta realizada.
- [x] Cambio realizado.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 31/07/24

Se identifican los ajustes necesarios para corregir variables sensibles quemadas.

1. Con ayuda del líder de equipo se logró identificar una forma de reemplazar en los archivos crear-certificacion.component.ts y crear-certificacion-sin-novedad.component.ts las diferentes variables quemadas:

- Para los id de cargos quemados se reemplazó por el cargo adecuado y se realizó la consulta por un dato menos sensible mejorando la verificación de la validez del cargo por medio de la consulta de fechas:

![image](https://github.com/user-attachments/assets/eedb0f29-8ed1-4461-bbf9-283ac316fb51)

En ambos archivos se realizó el mismo proceso creando un método que traiga la fecha actual y consultando el cargo por el nombre con la condicional de que la fecha actual esté dentro de la vigencia del registro más nuevo del cargo consultado. Se probó y se obtuvo un resultado de éxito:

![Captura de pantalla 2024-07-31 180128](https://github.com/user-attachments/assets/e94beec7-af05-475e-8993-700a933c91ae)


2. Y como se evidencia en la captura anterior también se probó la modificación de la variable quemada de tipo de documento, cambiando esto por la búsqueda por el código de abreviación y utilizando la respuesta de la consulta para obtener el id, y así poder obtener el tipo de documento (además se corrigió el tipo de documento utilizado):

![Captura de pantalla 2024-07-31 181951](https://github.com/user-attachments/assets/07d8358a-3502-453b-9ea8-c27afc066dd3)

Así se pasa este issue a in review

**Comment by diagutierrezro** [comment]
Se aprueban PR y se envía al ambiente de pruebas, gracias Andres.
