### ISSUE TITLE
Generar el despliegue en producción de firma electrónica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#103]
Se requiere realizar el despliegue en producción de firma electrónica

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2
- [x] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [ ] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento técnico

**Nota:** Este sistema tiene creado un ambiente de producción para las APIs MID y CRUD y para el Cliente, por lo que se requiere tener mucho cuidado con el incremento para no afectar data en producción.

**Comment by diagutierrezro** [comment]
**Aprobado funcionamiento:** La primera versión de firma electrónica se aprueba por funcionamiento el dia 18 de junio https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Socializaci%C3%B3n%20Firma%20electr%C3%B3nica%20inversi%C3%B3n-20240618_113231-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=xfdCFC

**Pruebas funcionales:** Las pruebas funcionales se realizan en el issue #39 

**Pruebas de carga y seguridad:** Las pruebas de carga y seguridad se solicitan en el siguiente [kanban](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?tracker=697&aid=61880) y las ajustes se realizan en los issues #78 #79 y #86 , estos ajustes ya fueron socializados y se dió aprobación para despliegue a producción

**Documento tecnico:** Los documentos se realizaron en #53 sin embargo en la última reunión se solicitó otro documento donde se especifique los puntos importantes a tener en cuenta para implementar firma electrónica, este documento se realizará en #114 

Se crean los respectivos kanban para el despliegue del [mid](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63043) y del [cliente de verificación](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63044), el despliegue se realiza de manera satisfactoria, visualmente se puede evidenciar el despliegue del cliente de verificación en el siguiente link https://verificacion.portaloas.udistrital.edu.co/

Este despliegue no consume información directa desde bases de datos por lo que la revisión de sincronización y ETL no es necesaria.

**Comment by diagutierrezro** [comment]
Se realizan las pruebas unitarias en #126, pendiente por realizar ajuste en despliegue para la respectiva ejecución.
