### ISSUE TITLE
Participar de reunión sobre cliente en académica e iniciar un plan sobre como implementar firma electrónica allí.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#105]
Se requiere realizar la participación en la reunión que se llevará con funcionamiento, especificamente con el responsable de académica, importante tener claro en esa reunión la información que se requiere para implementar la firma. Una vez finalizada la reunión realizar un análisis sobre posibles formas de llevar a cabo esta implementación de firma electrónica en el sistema que se nos indique.

**Sub Tareas**

- [x] Participar de la reunión con lo items claros a preguntar.
- [x] Realizar un análisis sobre como se podría llevar a cabo esta implementación de la firma electrónica.
- [x] Documentar el análisis en el issue.

**Criterios de aceptación**

- [x] Participación en la reunión.
- [x] Análisis realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 02/08/24

Como resultado de la reunión se tuvo como conclusión los siguientes puntos:

- Del conjunto de documentos  de SGA el más utilizado y por tanto al cual se implementará primero la firma electrónica será al certificado de notas o sábana de notas.
- Sólo se requiere un firmante ya que no tiene flujo de aprobación.
- Se mostró tanto la nueva firma electrónica, como los requerimientos para llevarse a cabo, así como su verificación
- La implementación será responsabilidad del equipo de SGA, por tanto se les suministró la información concerniente a campos necesarios de datos para enviar a API firma electrónica para realizar la firma, aclaración de dónde se alojarán los documentos y un ejemplo del json que debe enviarse a la API para realizar la firma.
