### ISSUE TITLE
Documentar la solución al alcance relacionado con la caducidad de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#106]
Se requiere realizar la documentación de la solución al alcance relacionado con la caducidad de roles

**Sub Tareas**

- [x] Revisión del job referenciado por responsable
- [x] Generación de conclusiones relacionadas

**Criterios de aceptación**

- [x] Documento de referencia

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
No se ha podido obtener la información para documentar el avance en caducidad de roles a espera de evidencia de parte del arquitecto



![Image](https://github.com/user-attachments/assets/b3d8445e-6508-4b98-bd71-82e9202f1099)

**Comment by mantnicot** [comment]
Se sigue esperando la respuesta del arquitecto para la evidencia



![Image](https://github.com/user-attachments/assets/b57e323f-c0d2-4f6a-8173-f09b327536e8)

**Comment by mantnicot** [comment]
Se ha realizado un documento con base a la información dada por el arquitecto

[Documento de caducidad de roles](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESduZEcotq9JoTlYfA-5QkkBMH9CDWk7eW4BuCoKug4agw?e=yhaqd0)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, documento muy completo!
