### ISSUE TITLE
Prueba de concepto de creación de librería

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#107]
Se requiere realizar una prueba de concepto para la creación de la librería de python donde se manejaría la implementación del X-Ray para python, teniendo en cuenta lo investigado en #96 se creará un nuevo [repositorio](https://github.com/udistrital/utils_python) donde se adicionarán los archivos de request y SDK y adicional se creará la configuración para que este repositorio actúe como una librería que se pueda instalar mediante "pip install ..."

**Sub Tareas**

- [x] Adicionar archivos requeridos para funcionamiento de X-Ray.
- [x] Agregar configuración para que este repositorio actúe como una librería.

**Criterios de aceptación**

- [x] Adición de archivos realizada.
- [x] Configuración de repositorio agregada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se crea la libreria del sdk de xray para python y se sube a un nuevo repositorio en github, donde solo este repositorio tendra funciones transversales con código en python:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/a0aecd93-b4f8-49ed-9c41-81d413f68d42">
