### ISSUE TITLE
Ajustar gestor_documental para prueba de concepto con libreria - parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#108]
Se requiere realizar ajuste en el gestor_documental_mid de tal manera que se realice la instalación de la librería creda en #107 mediante "pip install" y una vez se realice esto realizar los ajustes necesarios para poder usar X-Ray desde dicha librería.

**Sub Tareas**

- [x] Instalar librería creada.
- [x] Ajustar Api para usar X-Ray desde la librería instalada.

**Criterios de aceptación**

- [x] Librería instalada.
- [x] Ajustes en gestor_documental_mid realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se instala mediante el comando pip install los archivos distribuidos de la libreria creada:
<img width="617" alt="image" src="https://github.com/user-attachments/assets/34b978a3-d1dc-4377-9675-65f25120ea00">
<img width="601" alt="image" src="https://github.com/user-attachments/assets/9eb840ff-8f1b-448f-a589-a015b1e1a107">

Ahora se procede a probar e importar en los archivos de la api

**Comment by JulianAvella** [comment]
Además toco crear un realese para subir los archivos de instalación como se ve arriba porque si se dejan una rama no se puede instalar la libreria mediante el comando pip install, como se ve a continuación: 
<img width="589" alt="image" src="https://github.com/user-attachments/assets/ef43919d-b092-4416-a0bf-99783d66147f">

**Comment by JulianAvella** [comment]
Se tiene el error de que no reconoce el modulo xray en el archivo request_tools.py de la libreria creada, se han intentado varias soluciones pero aún no se ha dado con la solución:

<img width="643" alt="image" src="https://github.com/user-attachments/assets/ee86e04e-cff3-4981-83a3-79f8e6755d4c">

**Comment by diagutierrezro** [comment]
Se continuará con la prueba de concepto en otro issue, buen trabajo Julian
