### ISSUE TITLE
Implementación de lógica para gestión de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#109]
Se requiere realizar la implementación de la lógica que se está realizando en #98 en el cliente donde al presionar el botón de buscar se ejecute el query para traer la información según los parametros que se hayan llenado (ej: Solo se puso una facultad, la respuesta sería las dependencias que tienen como dependencia_padre dicha facultad).

**Sub Tareas**

- [x] Implementar de manera inicial consultas basicas.
- [x] Comprobar funcionamiento correcto con diferentes consultas.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Comprobación de funcionamiento realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se termina issue
**Vista inicial de gestión:**
![Image](https://github.com/user-attachments/assets/6aec30a6-2413-47ec-8a00-b37fe6d694af)

**Loader**
Se ubica loader, aun no se muestra al lider @diagutierrezro  para correcciones
![Image](https://github.com/user-attachments/assets/85aeead7-e6a5-4847-8b47-b2d8b18cd4c2)

**Búsqueda por nombre**
Solo aparece la dependencia con ese nombre:
![Image](https://github.com/user-attachments/assets/da3e46d0-fc89-47a9-9b43-7024631fbf91)

**Búsqueda por tipo**
![Image](https://github.com/user-attachments/assets/8793dfe8-86f3-4381-8f51-40bbbd94c5b8)

**Búsqueda por facultad y vicerrectoría**
![Image](https://github.com/user-attachments/assets/34b40015-1fb0-46af-8322-c4c235278937)

**Sin repetidos**
![Image](https://github.com/user-attachments/assets/d4e5caa1-72a8-4e47-8904-9f4b353f68bb)


**Nota**
Hace falta corregir la paginación, ya se había solucionado este error, pero se volvió a presentar.
