### ISSUE TITLE
Realizar una nueva proyección de costos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#11]

**Comment by mantnicot** [comment]
Se ha realizado el contacto con el encargado Jaime , así mismo se ha compartido la documentación basica de los costos de [Amazon](https://aws.amazon.com/es/xray/pricing/) y se espera poder reunirnos para explicación de proyección y analisis

**Comment by mantnicot** [comment]
Se ha hablado con Jaime con respecto a la proyección y se esta concretando un reunión , mientras tanto ha mandado a revisión el link de la calculadora de AMAZON


[CALCULADORA](https://calculator.aws/#/estimate)

**Comment by mantnicot** [comment]
Se ha generado el acta de la reunión que se tuvo con Jaime con respecto a costos y a proyección.

La nueva ruta indica que se debe trabajar con Brayan para estimar los valores a proyectar.


[Acta sin firmar](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ETXzqVGiJitKoxIObNyCxUQBuAF8EunKD6htd74IdzhQjA?e=MzJ0ld)

**Comment by jcmurilloa** [comment]
Muy buena descripción del avance en el acta, pendiente recoger firmas e información de Brayan.

**Comment by mantnicot** [comment]
Ya se realizo la proyección de costos después de cuadrar los dos escenario de proyección con Brayan


[Proyección](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbWltRVHY1dMjQ20sw6PNSsBAyDR5PjSJapsjFC8yiSz0w?e=MAC58P)

**Comment by jcmurilloa** [comment]
Muy buen trabajo Cristian!
