### ISSUE TITLE
Crear lógica en el mid de gestión de dependencias de oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#110]
Se requiere realizar la lógica que se usará para la edición de dependencias, es importante que esta logica tambien se maneje mediante transacciones para que en dado caso de que falle alguna transacción todo quede como estaba originalmente. Tener presente que en una edición de dependencia se pueden hacer cambios en la tabla dependencia, dependencia_tipo_dependencia y dependencia_padre. Esta lógica se crea en un nuevo controlador y servicio en el [repositorio](https://github.com/udistrital/gestion_dependencias_mid/tree/develop)

**Sub Tareas**

- [x] Crear lógica como una transacción para edición de dependencias.
- [x] Probar funcionamiento correcto.
- [x] Documentar evidencias de que los PUT se realizan correctamente.

**Criterios de aceptación**

- [x] Logica creada.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto del Issue

**Sobre la dependencia**
Se logra editar los datos básicos de la dependencia: nombre, teléfono y correo:
**Antes**
![Image](https://github.com/user-attachments/assets/2f40f59d-839a-43e3-978b-c16f1edf4fe5)
**Después**
Se muestra el json para el envió del endpoint

- Endpoint
   ![Image](https://github.com/user-attachments/assets/2b80b4fd-de31-44b6-a392-7e292d9ad826)
- Cambio
![Image](https://github.com/user-attachments/assets/1e4c61d3-2698-4c85-b83b-73d86e3a138f)

**Tipo de dependencia**
El ajuste de esta característica resultó ser más complejo de lo esperado, ya que una dependencia podía tener varios tipos asociados. Después de una reunión con el líder @diagutierrezro y el analista @mantnicot , se decidió utilizar el campo "activo" como una bandera para indicar qué tipo está activo en cada dependencia. Esta nueva interpretación de la funcionalidad generó varios casos a considerar.

Los siguientes casos se resolverán en la dependencia con el ID 295. Esta dependencia solo tiene asociado el tipo FACULTAD con el ID 2.
![Image](https://github.com/user-attachments/assets/e9a24335-d1e1-47c2-849c-edba27c3ed4e)

- Cuando se pasa un nuevo tipo que no ha tenido antes
  Para este ejemplo se agrega el tipo de dependencia 3 a la ya existente 2.
   - Entrada
      ![Image](https://github.com/user-attachments/assets/2b824338-8736-4f32-9d12-94b2e7f7c72c)
   - Salida
      ![Image](https://github.com/user-attachments/assets/19fbaf83-9cc8-468e-9873-48605054bb6d)
  Se observa que ambos tipos se encuentran en true para esta dependencia 

- Cuando se pasa un nuevo tipo que se ha registrado antes
   Para este ejemplo se pasara solamente el tipo de dependencia 3.
   - Entrada
      ![Image](https://github.com/user-attachments/assets/8d0dfb63-3b56-4cb4-94b2-fe52d75ba430)
   - Salida
      ![Image](https://github.com/user-attachments/assets/4342f968-a253-4818-8cec-f1d5739d9569)
  Se observa que solamente el tipo 3 se encuentra en true y el 2 en false.

- Cuando en los tipos que se pasan no se encuentra algún tipo activo anteriormente 
   Para este ejemplo se pasaran los tipos 4 y 5.
   - Entrada
      ![Image](https://github.com/user-attachments/assets/ad893cd8-366f-4880-b5ac-0241853fa3f5)
   - Salida
      ![Image](https://github.com/user-attachments/assets/9a2e4339-d9d6-446a-a07f-03ba0f2c32d5)
      ![Image](https://github.com/user-attachments/assets/a2ef5cf1-654b-4ad0-a5c4-eedcd4d40512)
  Se observa que solamente los nuevos tipos están en true y los anteriores (2 y 3) se encuentran en false.

**Comment by xDa04vidx** [comment]
### Problemas

- La complejidad del issue aumento considerablemente.

- Al intentar editar la dependencia asociada o dependencia padre, se trató de replicar el proceso utilizado para la edición del tipo de dependencia. Sin embargo, al intentar registrar una nueva dependencia padre, se produjo un error y el registro no se agregó a la base de datos. Esta funcionalidad fue probada durante el viernes 16 de agosto, pero no se obtuvieron resultados exitosos.

   La lógica planteada fue la siguiente: si se registra una nueva dependencia asociada, debería crearse un nuevo registro con esta relación, si no existía previamente, y marcar el actual como false. En caso de que la relación existiera pero estuviera marcada como false, este registro debería cambiar a true, mientras que el actual se marcaría como false.

    **Problema**
    Tras varios intentos, se inspeccionó la base de datos y se encontraron dos restricciones de unicidad. Estas restricciones especifican que solo se puede tener una relación hija y asociaciones únicas de padre a hija. Debido a estas condiciones, se cree que esta es la razón por la cual no se pueden crear más registros para esta tabla.
    ![Image](https://github.com/user-attachments/assets/4dc0f66e-c7ce-445b-a298-9685e39a14be)

**Comment by xDa04vidx** [comment]
### Nueva lógica para editar dependencia padre
Se estableció una reunión con el líder @diagutierrezro, donde se decidió editar el registro actual de la dependencia en lugar de crear nuevos registros. Además, el líder @diagutierrezro se comprometió a comunicar este cambio a los analistas correspondientes.

**Se muestra a continuación el cambio funcionando**
La dependencia 295 actualmente tiene la dependencia asociada 9
![Image](https://github.com/user-attachments/assets/e4dc05c9-3a7f-4abe-a70f-6f2813f42803)

- Petición
  Se cambiara por la dependencia 8
  ![Image](https://github.com/user-attachments/assets/38a8ceec-9887-43b1-9d1d-7166385c3a83)

- Cambio
   Se observa que el cambio se realizo con éxito. 
   ![Image](https://github.com/user-attachments/assets/7e111722-c5cd-4ace-a583-4bf699b7ec2d)

**Comment by xDa04vidx** [comment]
### Pull request
Se agrega al pull request anterior en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)


![Image](https://github.com/user-attachments/assets/cd58d51a-6f71-46a4-8885-321d562884b1)
