### ISSUE TITLE
Implementación inicial de firma electrónica en sistema de cumplidos cps

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#111]
Se requiere realizar la implementación inicial de firma electrónica en el sistema de cumplidos cps con el fin de poder mostrar como sería el funcionamento con multiples firmantes, la idea principal es obtener la información de los firmantes desde cumplidos y llamar al endpoint de firma electrónica, el documento por ahora se puede visualizar directamente desde nuxeo.

**Sub Tareas**

- [x] Obtención de información de firmantes en cumplidos.
- [x] Llamado a endpoint de firma electrónica para agregar la firma.
- [x] Visualización del documento en nuxeo correctamente firmado.

**Criterios de aceptación**

- [x] Información de firmantes obtenida.
- [x] Llamado a endpoint de firma electrónica realizado.
- [x] Visualización de documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 09/08/24

Se realiza la implementación inicial:

1. Se agrega una variable de entorno que por el momento apunta a la dirección local de la API de firma electrónica.
2. Se crea un firma_electronica_mid_service.js para alojar el endpoint de firma electrónica para firmar.

![image](https://github.com/user-attachments/assets/d48aa903-6fb4-49f6-8306-af84572e83f9)

3. Se agrega la referencia a dicho service en index.html y app.js
4. Ya que la firma debe realizarse con la información de contratista y supervisor, esta se realizará cuando el supervisor de el visto bueno, por lo tanto, en aprobacion_supervisor.js en el método de dar_visto_bueno se realiza la implementación preliminar en la cual se obtienen todos los datos para la firma y se realiza dicho proceso llamando al endpoint de firma electrónica:

![image](https://github.com/user-attachments/assets/970f793c-ddc0-4c6a-bc1b-08674425e62d)
![image](https://github.com/user-attachments/assets/b356c620-cd54-497b-a9da-f2ee2ab43ce3)
![image](https://github.com/user-attachments/assets/658d7752-ea11-47da-b37b-74dfaef17916)


5. Finalmente se comentarea la antigua firma en informe_gestion_y_certificado_cumplimiento.js.

Como resultado se obtiene el documento firmado con multiples firmantes en nuxeo:

![image](https://github.com/user-attachments/assets/67bdca14-c1fd-48a4-921a-e50efa86e337)

**Comment by diagutierrezro** [comment]
Se realiza la presentación al equipo de funcionamiento, dan visto bueno, posteriormente se cotinuará con los ajustes al cliente de cumplidos cps para finalizar la implementación. Muchas gracias Andres.
