### ISSUE TITLE
Ajustar gestor_documental para prueba de concepto con libreria - Parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#112]
Se requiere realizar la continuación de la pruebas de concepto para la implementación de la librería que se usará con el SDK de X-Ray y el manejo de peticiones http que se inició en #108, ahora será necesario realizar ajustes a las pruebas que se han realizado antes para corregir los errores encontradso

**Sub Tareas**

- [x] Ajustes realizados al repositorio.
- [x] Documentar cambios que se vayan realizando.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
En la prueba del concepto de la librería surgieron varios errores, el primero que surgio fue que la librería que se había subido a una rama del repositorio, no se podía instalar como una librería en la api de python, entonces después de investigar y de prueba y error, se encontro que para subir una librería correctamente con python en github, se debe crear un "release" que sirve para empaquetar y poner a disposición de descarga y uso lo que subamos, en este caso sería la librería, entonces para que podamos instalar la librería mediante el comando pip install, se debe desde el proyecto de la librería que tenemos la estructura:

xray_python/
├── xray_python/
│ ├── init.py
│ ├── request_tools.py
│ ├── xray.py
├── README.md
├── setup.py

Se ejecuta el comando en la terminal: python3 setup.py sdist bdist_wheel, el cual empaqueta el código fuente en un archivo comprimido con extención '.tar.gz' y en un archivo binario con extención '.whl', estos dos archivos se encuentran en la carpeta dist que crea el comando, además de dos carpetas más que son build y xray_python.egg-info, entonces la estructura del proyecto queda de la forma:

xray_python/
├── build/
│ ├── bdist.linux-x86_64/
│ ├── lib/
│ │ ├── xray_python/
│ │ │ ├── init.py
│ │ │ ├── request_tools.py
│ │ │ ├── xray.py
├── dist/
│ ├── xray_python-0.1.0-py3-none-any.whl
│ ├── xray_python-0.1.0.tar.gz
├── xray_python/
│ ├── init.py
│ ├── request_tools.py
│ ├── xray.py
├── xray_python.egg-info/
│ ├── dependency_links.txt
│ ├── PKG-INFO
│ ├── requires.txt
│ ├── SOURCES.txt
│ ├── top_level.txt
├── README.md
├── setup.py

Entonces de crea el release en el repositorio de github y se suben los dos archivos de la carpeta dist "xray_python-0.1.0-py3-none-any.whl y xray_python-0.1.0.tar.gz", como se hizo para el proyecto:

https://github.com/udistrital/utils_python/releases/tag/Instalacion

**Comment by JulianAvella** [comment]
La anterior solución resuelve el siguiente error que genera al instalar la librería desde una rama del repositorio en github:

<img width="698" alt="image" src="https://github.com/user-attachments/assets/c938584f-158b-4845-9bce-4908f51038b1">

Entonces al subir los archivos anteriormente mencionados en release al repositorio en github, se puede instalar correctamente la librería mediante el comando; pip install https://github.com/udistrital/utils_python/releases/download/Instalacion/xray_python-0.1.0-py3-none-any.whl:

<img width="697" alt="image" src="https://github.com/user-attachments/assets/aefadc89-b7d0-4030-909e-4c46968af3fa">

Para poder instalar la librería se siguen los siguientes pasos:

1. Se ingresa al release del repositorio, https://github.com/udistrital/utils_python/releases/tag/Instalacion:
2. En el archivo con extención '.whl' encima de este archivo de da clic derecho y se selecciona la opción "Copiar dirección del vínculo":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/69ced288-2742-4cf1-b840-713709f02cd0">
3. En la raiz del proyecto en python al que queremos instalar la libreria, se abre la terminar y escribe pip install y luego pega el link que obtuvo del segundo paso y ejecuta el comando.

Haciendo los anteriores pasos se instala correctamente la libreria.

**Comment by JulianAvella** [comment]
Después de colocar el código respectivo de la libreria del sdk de xray en la api que esta en la rama develop, se hacen las siguientes pruebas en las peticiones http;

* Petición GET:

<img width="673" alt="image" src="https://github.com/user-attachments/assets/2f0a4784-4080-4d26-b484-7e07395b3476">

* Petición POST:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/acaee594-23cd-4e5f-b61d-9eb45831295c">

* Petición PUT:

<img width="675" alt="image" src="https://github.com/user-attachments/assets/622d012b-3acd-4263-be00-bc12a43518e2">

Se verifica que quede el registro de la traza en aws con sus respectivos metadatos:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/861ec64d-32c9-4e04-9fa9-9cd0c87f8e46">

<img width="959" alt="image" src="https://github.com/user-attachments/assets/613c4ca9-b90c-4e9a-bd4f-0c525652f570">

**Comment by JulianAvella** [comment]
Se sube el código a una nueva rama en el repositorio de la api de gestor_documental_mid llamada feature/X-Ray-libreria y se pide el pull requests:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/ec73da8c-71cd-4c4d-a37c-82f8c8aab9f9">
