### ISSUE TITLE
Implementar lógica para mapeo de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#113]
Se requiere realizar la implementación de la lógica creada en #98 para el filtro inicial del mapeo de dependencias según los [mockups](https://github.com/udistrital/core_documentacion/issues/33), teniendo en cuenta que el filtro que se usa para esta vista es el mismo que se usa para la gestión de dependencias, se puede usar la misma lógica de este módulo que se implementó en #109 .

**Sub Tareas**

- [x] Implementar consultas basicas para realizar el filtro.
- [x] Comprobar funcionamiento correcto.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Comprobación de funcionamiento realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto

**Vista inicial**
![Image](https://github.com/user-attachments/assets/42ece84b-69da-4140-8a88-d8f1211f6f09)

**Loader**
Se pone el mismo loader de gestión, este loader se mejorara 
![Image](https://github.com/user-attachments/assets/8ccb5297-eab1-44af-ab5c-5fbed36f5cd0)

**Búsqueda por nombre**
![Image](https://github.com/user-attachments/assets/35534ee1-0975-4151-9ea3-23434221a9c3)

**Búsqueda por tipo**
![Image](https://github.com/user-attachments/assets/0c7e0370-2bb5-41f7-b150-9c45b12e35f3)

**Sin repetidos**
![Image](https://github.com/user-attachments/assets/6d6b6c31-1311-4690-812f-25e02dfd4e5d)

**Nota**
Hace falta corregir la paginación.

**Comment by diagutierrezro** [comment]
Las correcciones visuales como el loading y la paginación se corregiran mas adelante.

**Comment by xDa04vidx** [comment]
### Pull Request
Se realiza pull request en [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)


![Image](https://github.com/user-attachments/assets/eff72258-fc4e-44fa-b061-f2168df6a933)
