### ISSUE TITLE
Crear documentación sobre como implementar firma electrónica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#114]
Se requiere realizar un documento tecnico donde se explique detalladamente los aspectos a tener en cuenta para realizar la implementación de firma electrónica en un sistema. Si bien cada sistema va a tener sus particularidades al momento de implementar la firma se debe definir en dicho documento los aspectos fundamentales a tener en cuenta, por ejemplo, en multiples firmantes el sistema de firma electrónica solo recibirá la firma final una vez todos los firmantes hayan firmado, el tipo de documento debe coindicir con el del api de documentos_crud, el formato de la información de los firmantes, representantes, etc.

**Sub Tareas**

- [x] Realizar documento tecnico donde se expliquen los aspectos mas importantes para implementar la firma electrónica.

**Criterios de aceptación**

- [x] Documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

Este documento debe ser validado por @diagutierrezro y @mantnicot 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/08/24

Se realiza la documentación técnica requerida y se envía a revisión. A continuación se adjunta enlace de One drive donde se podrá visualizar el documento como tal:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/EduV40kCqS5GvE0uGyWcSQIBYHavlpo4j6kLzxghZJKfdA?e=Cfgn0j
