### ISSUE TITLE
Realizar investigación para crear pruebas unitarias en firma_electronica_mid

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#116]
Se requiere realizar una investigación sobre como implementar pruebas unitarias con python en el framework de flask, se requiere que se vaya documentando el issue con las opciones encontradas teniendo en cuenta la manera en la que se implementarían en el Api.

**Sub Tareas**

- [x] Realizar investigación para crear las pruebas unitarias en firma_electronica_mid
- [x] Documentar en el issue las opciones encontradas.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/08/24

Se comenzó la investigación preliminar en la cual por el momento se encontraron las siguientes configuraciones de librerías:
- Pytest (con o sin coverage): Hasta donde se investigó es la librería más utilizada para este propósito, Pytest permite realizar las pruebas unitarias, y el uso de coverage es opcional, ya que lo que permite es identificar los fragmentos de código que son ejecutados en las pruebas y cuales no, logrando identificar la efectividad de las mismas y localizar código que no esté utilizando en el flujo. Se está consultando información y la documentación referida a continuación: 

https://docs.pytest.org/en/stable/
https://coverage.readthedocs.io/en/7.6.1/
https://flask.palletsprojects.com/es/main/tutorial/tests/

-Flask testing: Una librería alternativa para realizar pruebas unitarias, también se está investigando a fondo, y su documentación se puede encontrar aquí: https://flask-testing.readthedocs.io/en/latest/

- unittest: Es un framework que también permite realizar pruebas unitarias. Citando su documentación: "Admite la automatización de pruebas, el uso compartido del código de configuración y apagado de las pruebas, la agregación de pruebas en colecciones y la independencia de las pruebas del marco de elaboración de informes.", dicha documentación se encuentra aquí: https://docs.python.org/3/library/unittest.html

La investigación realizada hasta esta actualización es superficial, se debe ahondar en la forma de implementar, utilizar, desarrollar y ejecutar cada librería para poder tener una comprensión completa, sin embargo se tienen listadas estas 4 al ser las más usadas. Por lo tanto queda pendiente profundizar en el uso, instalación y ejecución de dichas librerías
