### ISSUE TITLE
Finalizar implementación de firma electrónica en cumplidos CPS - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#117]
Se requiere realizar la finalización de la implementación de firma electrónica en el sistema de [cumplidos CPS](https://github.com/udistrital/cumplidos_cliente), como tareas pendientes para esta issue se debe mover la lógica de firma hacia una nueva función que despues será llamada en la función de dar_visto_bueno, adicional a esto se debe reemplazar el id del documento asociado como soporte del cumplido, verificar que al cambiar dicho ID se pueda visualizar el documento firmado electrónicamente.

**Sub Tareas**

- [x] Mover lógica realizada para firmar electrónicamente hacia una nueva función que despues debe ser llamada en dar_visto_bueno().
- [x] Reemplazar id del documento asociado al cumplido en la base de datos.
- [x] Verificar que el documento si se modificó por el que se firma electronicamente.

**Criterios de aceptación**

- [x] Logica separada en una nueva función.
- [x] Reemplazo de id de documentos realizado.
- [x] Verificación del documento realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 14/08/24

Se inicia con le traslado de las instrucciones de firma electrónica a una función aparte:

![image](https://github.com/user-attachments/assets/71e18ca6-4721-4c66-badc-1941f21ce72d)

Y se llama de la siguiente forma:

![image](https://github.com/user-attachments/assets/c0edd01d-49e5-46f2-856b-8df505373f0b)

Se está por tanto realizando la implementación de la modificación del id del documento asociado al cumplido

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 15/08/24

Se realiza una promesa de prueba para evaluar si se logra actualizar el registro que se está usando en el desarrollo de la funcionalidad con un número quemado para luego si esto funciona, cambiar el número quemado por el id del documento firmado luego de realizarse el proceso de firma:

![image](https://github.com/user-attachments/assets/61ebfc04-a806-40c0-a56d-f73ab4edf24c)

Sin embargo al momento de probarlo se obtiene un error de CORS por parte de Cumplidos CRUD:

![image](https://github.com/user-attachments/assets/cf6a3105-0895-4d73-bbf1-b9189df3d6ba)

Por lo tanto se informará al líder de esta situación para usar cumplidos crud en ambiente local para poder deshabilitar el CORS y para ello se solicitarán indicaciones para su respectiva ejecución en local, por el momento ya se descargó el repositorio para poder ser usado una vez se den indicaciones de su correcta ejecución. Una vez desactivado el CORS sólo restaría probar la consulta y en caso de ser exitosa, reemplazar la variable quemada y quedaría funcional

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/08/24

Se logró resolver el tema del CORS creando una rama en cumplidos CRUD en la cual se habilitan todos los dominios y subiendo dicho cambio a pruebas de manera temporal:

![image](https://github.com/user-attachments/assets/d7200eb4-54d7-41b6-abb5-4e5cc91ed117)

Posterior a esto se continuó con el desarrollo de la actualización del documento:

Se identificó que se debía construir un JSON para enviar al endpoint de cumplidos CRUD por lo que se realizaron las consultas y asignaciones pertinentes, además de agregar en dicho JSON el id del documento recién firmado, que es el dato que se reemplazará, el resto de datos de ese registro continúan igual:

![image](https://github.com/user-attachments/assets/1494259e-00f9-4724-8738-9c0ab4d95893)

Con estos datos se realiza la consulta y se imprime el resultado del put:

![image](https://github.com/user-attachments/assets/66b9a949-dd7b-40da-9050-359b8c8a7ced)

Se realizó la respectiva prueba, siendo que el anterior ID del documento en el registro era el siguiente:

![image](https://github.com/user-attachments/assets/92b1cd8e-1d2d-4e49-88cd-3c62c2ea2b06)

En la consola se evidencia el número del documento firmado:

![image](https://github.com/user-attachments/assets/fa18d8bb-826a-412a-85ec-b297ac375c71)

La respuesta exitosa del put:

![image](https://github.com/user-attachments/assets/35732c9c-020a-49b1-82a0-f5444dabb6a5)

Y el registro cambiado en la base de datos:

![image](https://github.com/user-attachments/assets/325c248b-aa2a-42b2-b5ce-7d1760da3470)

Por tanto se coloca el issue en review ya que se cumplió con los objetivos.
