### ISSUE TITLE
Implementación de lógica para edición de dependencias en el mf - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#118]
Se requiere realizar la implementación de la lógica creada en #110 para la edición de dependencias. Se requiere inicialmente que cuando se ingrese a la vista se muestre la información actual de la dependencia seleccionada, esta información puede ser editable, una vez se hagan los cambios correspondientes se debe implementar la lógica de edición creada en el mid la cual se ejecutará una vez se presione el botón de edición.

Tener en cuenta que una dependencia puede tener multiples tipos de dependencia por lo que esta lista es un desplegable en el que se pueden seleccionar multiples tipos de dependencia, la vista debe ser algo similar a lo siguiente.

![Image](https://github.com/user-attachments/assets/9e960a8e-7ab5-42ae-97c1-833ead349945)

**Sub Tareas**

- [x] Llenar los diferentes campos con la información actual de la dependencia.
- [x] Ajustar listado de tipos de dependencia para que se muestre el listado de tipos de dependencia y en este se permitan seleccionar multiples opciones.
- [x] Ajustar el json que se va a enviar hacia el mid para que cumpla el formato que se requiere en el Api.
- [x] Crear las respectivas alertas al momento de dar clic en el botón de "Editar dependencia" para que el usuario deba confirmar que si quiere hacer esa acción.

**Criterios de aceptación**

- [x] Información actual puesta en el formulario.
- [x] Ajuste a listado de tipos de dependencias realizado.
- [x] Ajuste de json realizado.
- [x] Alertas creadas.
- [x] Documentación de issuea realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Checklist
La selección múltiple se ha implementado exitosamente utilizando Angular Material.

![Image](https://github.com/user-attachments/assets/7ac07b6e-416d-4aca-a341-0ba03e713d90)

**Comment by xDa04vidx** [comment]
### Avance
Se logra hacer que se previsualice los datos de la dependencia seleccionada (los tipos y la dependencia asociada).

Para este ejemplo se utiliza la dependencia "VICERRECTORIA ACADEMICA" que tiene varios tipos.

**Selección**
![Image](https://github.com/user-attachments/assets/532098af-5e74-47ab-9c9b-e1100122b1b7)
**Respuesta**
![Image](https://github.com/user-attachments/assets/e69d9c93-7a83-4b65-acad-bf4410c1d359)

Se observa que se preselecciono los tipos y la dependencia asociada, de manera satisfactoria.

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra precargar la información de la dependencia (nombre, teléfono y correo)
![Image](https://github.com/user-attachments/assets/e9cf89f7-2a7b-4f28-aaca-d442849045e4)

**Comment by xDa04vidx** [comment]
### Se relaciona el botón de editar con el Endpoint
Se logra relacionar el endpoint con el frontend de manera exitosa.
Se trabajara sobre la siguiente dependencia

![Image](https://github.com/user-attachments/assets/504351b0-a314-44f8-b45a-0f5821845152)


Casos:
**Editar nombre y teléfono**
Se cambia nombre y teléfono

- **Entrada**
   ![Image](https://github.com/user-attachments/assets/f35d7efb-e943-4247-8c81-050e2992addb)
- **Salida**
   ![Image](https://github.com/user-attachments/assets/b7b98364-f4ab-4374-b476-13a93b383a65)
- **Comprueba**
  ![Image](https://github.com/user-attachments/assets/663d76db-ce21-48a4-94e4-94d1b8fd67a2)
  ![Image](https://github.com/user-attachments/assets/133e7586-7d17-4cb7-9fc7-1af71aa69e78)

**Se quitan tipos de la dependencia**

- **Estado inicial**
  ![Image](https://github.com/user-attachments/assets/252c874c-0590-4c3f-9409-aa1c48614f36)

- **Cambio**
   ![Image](https://github.com/user-attachments/assets/33cc2161-8acb-481f-bd85-700939b1ed07)

- **Cambio en la tabla**
   ![Image](https://github.com/user-attachments/assets/7b4c4d40-a6cc-4218-af3a-370db1cb118c)

**Cambio en dependencia asociada**
**Se quitan tipos de la dependencia**

- **Estado inicial**
  ![Image](https://github.com/user-attachments/assets/342039e6-9cb7-466b-af7b-0d71fb0fe16a)

- **Cambio**
   ![Image](https://github.com/user-attachments/assets/fd05e27c-d4f7-44ac-924c-3bf344b97396)

- **Cambio en la tabla**
   ![Image](https://github.com/user-attachments/assets/1bca6dcd-2bad-4335-b527-08e5d7392353)

**Comment by xDa04vidx** [comment]
### Pull Request
Se realiza pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)

![Image](https://github.com/user-attachments/assets/c5325a5b-9a63-41aa-8116-0a431b629bd7)

**Comment by diagutierrezro** [comment]
Los ajustes visuales se realizarán mas adelante en otras issues. Muy buen trabajo David.
