### ISSUE TITLE
Corregir error en mapeo de peticiones

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#119]
Se requiere realizar la corrección en el mapeo de peticiones post y put donde la traza que se hace desde un "cliente" hacia el api se sobreescribe con las otras peticiones que se realizan hacia las demas apis, por ejemplo cuando llamamos petición post hacia el gestor_documental_mid este realzia una petición get y una petición post al Api de documentos_crud, en AWS la traza debería de quedar con una petición del cliente hacia el gestor_documental_mid y desde el gestor con dos peticiones hacia el crud, pero actualmente las dos trazas que van desde el mid hacia el crud tambien se muestran desde el cliente hacia el mid

**Sub Tareas**

- [x] Revisión para realizar mapeo correcto en el mid.
- [x] Realizar ajustes para corregir el mapeo.
- [x] Documentar pruebas realizadas y errores encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Correacciones realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se llega a una solución, donde el cliente que hace una petición http:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/c275b1b8-0677-4b70-bd25-e6d69b598395">

Se guarda la petición completa en los metadatos que registra xray:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/61950e28-2d34-424f-81f7-4785fc07e74f">

Se puede ver en la parte derecha inferior donde dice url de solicitud:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/a544cdd2-8986-42db-8551-996ec07ca407">

Luego cuando llega al mid y esta hace una petición a otra api, en esa api también queda correctamente mapeada la url que le llega:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/112d346f-ddb8-46e8-ad56-512f4a5ad431">

Esta solución queda para hablarlo en el daily y saber si es la más óptima
