### ISSUE TITLE
Reunión aclaratoria jobs con cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#12]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha intentado el primer contacto por medio de teams para agendar la reunión.


Se comento que el contacto puede ser por medio de telegram pero no se ha confirmado si se necesita el permiso de Eduar para generar el contacto por ese medio

**Comment by mantnicot** [comment]
Se ha creado la reunión con los encargados del job de oikos, se ha definido que se genere una bajón de sistema para poder visualizar el job que genera el fallo.

**Comment by jcmurilloa** [comment]
Pendiente generación de acta Cristian, poco a poco sacamos OIKOS adelante!

**Comment by mantnicot** [comment]
Ya se creo el acta respectiva , falta a espera de firmas 

[Acta sin firmas ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcSX9VFG9tVFrizyGDi5FhMBe9XvstncCBNZl-Zge6hAMA?e=IUZYgM)

**Comment by jcmurilloa** [comment]
@mantnicot por favor dejar evidencia de los múltiples intentos por recoger esta firma pendiente en la issue, con el fin de cerrar, el acta se documentará con las firmas recopiladas y con la observación de que no fue posible lograr la firma del responsable.

**Comment by mantnicot** [comment]
Se agrega la evidencia de los múltiples intentos que se han realizado para obtener la firmas 
![Image](https://github.com/user-attachments/assets/20fc1c55-363e-4ff1-92e2-341369b00308)

**Comment by jcmurilloa** [comment]
Se documentará la acta en mención sin la firma del responsable a quien no se logró obtener la firma, a pesar de múltiples intentos.
