### ISSUE TITLE
Finalizar implementación de firma electrónica en cumplidos CPS - Parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#120]
Se requiere realizar la finalización de la implementación de firma electrónica en cumplidos CPS continuando lo que se realizó en #117, para este issue se debe
- Agregar metadatos necesarios para los documentos, nombre del documento y tipo de archivo (se sugiere obtener esa información haciendo una petición GET al registro original).
-  Crear un popup que le avise al usuario que el documento se firmará electrónicamente y una vez el confirme se aplique la firma electrónica.

**Sub Tareas**

- [x] Crear pop-up en el cliente avisando la firma electrónica.
- [x] Implementar firma electrónica una vez el usuario confirme.
- [x] En caso exitoso o de algún error esto tambien se debe informar al usuario mediante otros pop-up indicandole al usuario la respuesta del sistema.

**Criterios de aceptación**

- [x] Pop-up de aviso creado.
- [x] Implementación de firma una vez el usuario acepte realizada.
- [x] Pop-up según respuesta del sistema creado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 20/08/24

Se agregan los metadatos necesarios para que el documento se muestre en la vista del ordenador:

![image](https://github.com/user-attachments/assets/5ab5b125-dafe-43d3-9f52-ddd8c6678435)

La razón por la cual el tipo está quemado es que en el html de aprobación ordenador se compara con dicha cadena para mostrar el componente:

![image](https://github.com/user-attachments/assets/8ea43d60-0feb-4798-b123-0c211ea3d944)

Y consultando en la base de datos de documentos, en la tabla tipo de documento, no hay ningún tipo que se llame así:

![image](https://github.com/user-attachments/assets/682cd010-358f-430e-8cd2-f2351fb88aab)

Por tanto, una vez agregados estos metadatos se realiza una firma electrónica en la cual el flujo se complete totalmente:

![image](https://github.com/user-attachments/assets/73e54867-b8f7-4ffe-af75-f8135171ea8e)

Y ahora se consulta con el usuario del ordenador dicho documento y ahora es posible visualizarlo:

![image](https://github.com/user-attachments/assets/00724121-f25d-492d-958b-dfb9636852c7)

![image](https://github.com/user-attachments/assets/62d407c5-0cdd-4ed0-8969-7ae0404bc1f7)

![image](https://github.com/user-attachments/assets/d6795fd4-4207-4012-b667-6664612760bc)

Además se agrega el pop up de confirmación de firma y visto bueno:

![image](https://github.com/user-attachments/assets/782b25bc-bfc9-4fec-b5c4-660e3582b5cc)

y se colocan pop ups en la captura de cada promesa del proceso de firmado:

![image](https://github.com/user-attachments/assets/4f63b042-c218-4b6d-887b-49af0147e461)

Sin embargo se debe revisar la implementación de los errores de firma electrónica para que el resto del flujo no continúe si se presenta un fallo

Por tanto queda pendiente el ajuste de dichos errores y el desarrollo del pop up que indique que se está realizando el proceso de firma

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/08/24

Se logró finalizar la implementación de pop ups y alertas de error.

Se tuvo que modificar en cierta medida las funciones. Primero se estaba presentando la situación de que a pesar de que firma electrónica no finalizara sus instrucciones el resto del flujo se ejecutaba por lo que se cambió un poco la estructura para convertirla en una promesa:

![image](https://github.com/user-attachments/assets/7bdfae30-f0a4-4448-8035-990e3fd2f5f1)

Por tanto en la función se tuvo que retornar una promesa y ajustar los errores, siendo que ahora ya no son tan específicos por lo que para que el sistema fuese funcional era necesario realizar los reject y estos no permitian que los swal se mostrasen sin que el catch de afuera los reemplazase:

![image](https://github.com/user-attachments/assets/5aba447c-3148-467b-a209-66d7d79bf8f5)

Y así se terminó manejando el retorno del resolve y reject:

![image](https://github.com/user-attachments/assets/594e2ca8-1e52-4a39-916d-25f19536fb73)


Como resultado el proceso muestra el pop up de confirmación:


![Captura de pantalla 2024-08-21 223418](https://github.com/user-attachments/assets/c10a1278-5419-4993-a15c-cb9a23ae8adc)

Luego el aviso de "cargando":

![Captura de pantalla 2024-08-21 223423](https://github.com/user-attachments/assets/4b64b6ac-2a96-4ec6-8f7d-53b85d9e980e)


El ya previamente existente aviso de que el proceso se completó:


![Captura de pantalla 2024-08-21 223431](https://github.com/user-attachments/assets/be9b6ee0-7a52-4752-8c7a-e7377a96cd35)


Y se comprueba con el usuario de ordenador la firma:

![Captura de pantalla 2024-08-21 224121](https://github.com/user-attachments/assets/efed1917-c96a-4c23-97cf-3e3fd27c9311)

Si un error resulta del proceso de firma se mostrará este aviso y se suspenderá la ejecución del visto bueno:

![Captura de pantalla 2024-08-21 223909](https://github.com/user-attachments/assets/bfc6b784-9930-4a78-8ef1-6504f0ae74f9)


Por lo tanto se coloca el issue en in review al completar las metas.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres, queda pendiente socialización con Juan Camilo para aprobar los cambios y desplegar en ambiente de pruebas.
