### ISSUE TITLE
Realizar prueba de despliegue a ambiente de pruebas

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#121]
Se requiere realizar el despliegue en ambiente de pruebas del Api gestor_documental_mid donde se implementa el uso de la librería creada en #107 y que se estuvo adaptando en #108 y #112, este proceso se debe realizar junto con @diagutierrezro para realizar la respectiva notificación de esta prueba a los demás equipos de desarrollo.

**Sub Tareas**

- [x] Reunión con el lider para realizar el respectivo despliegue.
- [x] Probar funcionamiento normal del Api.
- [x] Probar mapeo de Xray según a como se espera.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Reunión realizada.
- [x] Pruebas de funcionamiento del api realizadas.
- [x] Prueba de mapeo de xray realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se realiza el despliegue en el ambiente de pruebas junto al líder, el cual salio satisfactoriamente como se muestra a continuación, en donde se valida si funciona la libreria creada con el SDK de xray para python, aplicada en la api gestor_documental_mid:

Se hace la petición get:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/da1482cb-2e61-4051-88eb-bd53445cd2e7">


Se hace la petición post:

<img width="675" alt="image" src="https://github.com/user-attachments/assets/66d4cd5c-4386-4673-99a0-3644c57bb7ea">

Se hace la petición put:

<img width="677" alt="image" src="https://github.com/user-attachments/assets/8fed548e-84f7-44cf-9410-98633a2c697a">


Se verifica que deja el registro con xray en aws:

<img width="813" alt="image" src="https://github.com/user-attachments/assets/2c32268b-c495-48cf-b8bb-b049dd4493b0">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/8e028259-16bb-49ce-8e2e-8b701f8da3f1">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d17d473d-7aff-44ea-9ed2-9bd206c6cba8">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/e78a3695-5f86-49c3-9e21-7d68c112b0d8">

**Comment by diagutierrezro** [comment]
Muchas gracias Julian.
