### ISSUE TITLE
Implementar pruebas unitarias al Api de firma_electronica_mid

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#122]
Se requiere realizar la implementación de las pruebas unitarias con la herramienta definida, según lo investigado en #116 

**Sub Tareas**

- [x] Realiza pruebas unitarias para el Api de firma electronica.

**Criterios de aceptación**

- [x] Pruebas unitarias realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 22/05/24

Se realiza implementación de pruebas unitarias para los métodos de postFirma electrónica y postVerify.

Para ello se descargó la librería Pytest, y se creó la siguiente carpeta con los siguientes archivos:

![Captura de pantalla 2024-08-22 212632](https://github.com/user-attachments/assets/4730dbe8-e86b-4ba7-8260-ed23173437ac)

Luego en test_firmaElectronica.py se agregó el método para probar de la siguiente forma:


![Captura de pantalla 2024-08-22 212624](https://github.com/user-attachments/assets/b30fc1ae-663d-47cf-b093-f5ab61f5b348)

El comando assert compara el resultado de la prueba con un valor esperado. Por lo tanto se realiza la prueba en un inicio ejecutando el comando "pytest" en la terminal obteniendo un resultado exitoso:

![Captura de pantalla 2024-08-22 212655](https://github.com/user-attachments/assets/4b77b15d-305f-42ba-a346-e41cbf0aeb32)

Se puede evidenciar el documento subido a nuxeo:

![Captura de pantalla 2024-08-22 212611](https://github.com/user-attachments/assets/4e4a28d3-c823-467c-906d-55147d84faab)

Ahora bien, se agregó el método de verificación de firma electrónica a las pruebas:

![Captura de pantalla 2024-08-22 214203](https://github.com/user-attachments/assets/95bd3978-4d94-41c7-a3bc-dac5c6529f32)

Esta vez usando el comando "pytest -v" se puede apreciar mejor el proceso de prueba. Ahora ejecutará la prueba de firma electrónica y de verificación:

![Captura de pantalla 2024-08-22 214230](https://github.com/user-attachments/assets/9514cf72-b9ab-4c2e-9f19-8c517ea3251e)

El documento en nuxeo evidencia el éxito de la prueba:

![Captura de pantalla 2024-08-22 214259](https://github.com/user-attachments/assets/4f6ab913-8f61-4e21-bfd7-a78be6d0b4c8)

Para optimizar el proceso, se puede agregar una marca para definir diferentes parámetros y probar varias veces la misma función con valores distintos:

![Captura de pantalla 2024-08-22 215309](https://github.com/user-attachments/assets/e685aa12-fbb4-4d35-86f5-fdca19a385ca)

Probando la ejecución sólo del método de verificación se confirma que se prueba en este caso tres veces con éxito:

![Captura de pantalla 2024-08-22 215317](https://github.com/user-attachments/assets/f74fa7eb-73cf-459d-b111-70207d3088d7)

Ahora bien modificando uno de los códigos de verificación de prueba para que de una respuesta incorrecta el sistema detecta la falla y la muestra de forma explicativa:

![Captura de pantalla 2024-08-22 215411](https://github.com/user-attachments/assets/e7f52026-c75f-49eb-8d6a-0ed001935b76)


Finalmente, se ejecutan las 4 pruebas: 1 de firma y tres de verificación:

![Captura de pantalla 2024-08-22 215458](https://github.com/user-attachments/assets/e760b270-f2e5-4b33-9890-63a263ad5352)

Queda pendiente definir con el líder si hay que realizar ajustes a la implementación para colocar el issue en in review

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/08/24

Se termina de implementar algunas pruebas unitarias que hacían falta tener en cuenta:

Se agregan pruebas de fallo para firma electrónica y para verificación:

Para firma electrónica se agregó una prueba en la cual debía responder con código 400 si el base 64 no era un pdf, además se agregaron pruebas unitarias para responder correctamente a la ausencia de algún campo en el json, y también a la validación de la longitud del base 64.

Por su parte para verify se agregó una prueba de respuesta correcta ante un json sin código de autenticación:

![image](https://github.com/user-attachments/assets/41e51377-e414-468d-8263-a83acd66fa07)
![image](https://github.com/user-attachments/assets/bca496a9-674c-442a-84dd-2ce8e12aa84c)
![image](https://github.com/user-attachments/assets/b78fd15e-f97b-4551-96b8-2710ba1a1ac1)
![image](https://github.com/user-attachments/assets/a78d3ea6-dde1-4cd6-8473-033fef5e7662)
![image](https://github.com/user-attachments/assets/d2ed6915-ec6e-405a-9ac4-1bce65671f91)
![image](https://github.com/user-attachments/assets/28ed803b-c7ff-4ded-9498-6ada8bbd761f)

Como resultado todas las pruebas fueron exitosas:

![image](https://github.com/user-attachments/assets/75271b3c-8b07-4834-828b-21205d0cac42)


Con esto se coloca el issue en in review.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres, en otra issue se deben pulir un poco mejor estas pruebas para probar los diferentes metodos de manera individual y en los casos en los que se hacen peticiones http se deben mockear las respuestas para no afectar bases de datos u otros sistema como nuxeo.
