### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente para caducidad de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#123]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente para mostrar los resultados finales relacionados con la caducidad de roles.

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha intentado hablar con la persona encargada de funcionamiento para agendar la reunión pero no se ha dado respuesta , se espera poder concertar pronto para muestra




![Image](https://github.com/user-attachments/assets/a978c244-6728-498f-8784-3c8a64273cce)

**Comment by jcmurilloa** [comment]
Seguiremos intentando el contacto ñ!

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente a la reunión , se espera aprobación para enviar a firmas

[Acta sin firma](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWgZL8Gt9iJIqBd_sWjYvuABHgrL0MUqkrWkVwY1dX_cKg?e=yeVtLb)

**Comment by jcmurilloa** [comment]
Acta revisada y aprobada para recolección de firmas.

**Comment by mantnicot** [comment]
Se ha recolectado la firmas 

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Ed-YbS5XWtxBlrobF3UPdbYB-WrwBEb3G4BuG8WOAVSZFA?e=a4kdde)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
