### ISSUE TITLE
Generar la exploración inicial en lo relacionado con la reducción de tiempo de operación del demonio

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#124]
Se requiere realizar la exploración inicial en lo relacionado con la reducción de tiempo de operación del demonio

**Sub Tareas**

- [x] Contacto inicial con responsables
- [x] Generar la reunión con el responsable
- [x] Definir la ruta de gestión de desarrollo

**Criterios de aceptación**

- [x] Ruta de gestiónd e desarrollo definida

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido realizar el día 20/08/2024 con la parte de infraestructura y de seguridad

[Reunión ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTA0N2ZlY2UtZjczZi00YjZmLWFmNDAtNGJiNjgwYWJlMGZj%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%222bb2c118-ac47-42a4-8f32-9bf75c80b71f%22%7d)

El requerimiento esta principalmente en querer mejorar y facilitar el consumo del demonio por medio de útil oas.

Se define la siguiente ruta para solucionar el requerimiento : 

- Primero = Se identifica que la id - dirección de instancia ( la cuales a veces funciona y otras no ) 
- Segundo = Se comienza a revisar la variable de entorno de Daemon Addr 
- Tercero = Se nota que el setea el valor y esta quemado en el código 
- Cuarta = se debe cambiar ese valor quemado y hacer pruebas para rectificar el funcionamiento
- Quinta = Presentar ante los lideres e infraestructura y seguridad para su aceptación

**Comment by jcmurilloa** [comment]
Excelente y oportuno trabajo @mantnicot. Definida ya la ruta, la utilizaremos para definir issues en los siguientes sprints e ir logrando el alcance.
