### ISSUE TITLE
Ajustar pruebas unitarias en firma electrónica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#126]
Se requiere realizar ajustes a las pruebas unitarias para que estas se creen sobre cada función y usando mocks para no afectar otros sistemas ni generar registros de esta ejecución de pruebas, para esto se deben primero crear los mocks que simulen las respuestas de las apis.

**Sub Tareas**

- [x] Creación de mocks que simulen respuestas de las apis.
- [x] Ajuste de pruebas unitarias creadas.
- [x] Creación de nuevas pruebas unitarias por función.
- [x] Probar funcionamiento.

**Criterios de aceptación**

- [x] Mocks creados.
- [x] Ajuste de pruebas unitarias realizado.
- [x] Nuevas pruebas unitarias creadas.
- [x] Funcionamiento probado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/08/24

Se inicia con el ajuste de las pruebas unitarias. Para poder crear los Mocks es necesario utilizar una librería nativa de python que se llama unittest, la cual se realiza la importación:

![image](https://github.com/user-attachments/assets/6967ad79-3a27-4907-a970-ab3747c0e4e0)

Posteriormente, para motivos de practicidad sólo se dejará sin comentarear una función de prueba unitaria de postVerify hasta que se confirme que la adición de los mocks funcione correctamente y se pueda implementar en las demás pruebas. Se agrega un decorador a la prueba y se indica el tipo de respuesta que debe tener:

![image](https://github.com/user-attachments/assets/11bcec9b-d7d6-43b8-84c1-f60d6bbb9457)

Sin embargo se genera un error que se está tratando de arreglar

![image](https://github.com/user-attachments/assets/271c3ff8-e32d-4b84-8f41-763b4dad4c19)

Queda pendiente la revisión de este error, la confirmación de que los mocks funcionan y la implementación en las demás pruebas unitarias.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 27/08/24

Se corrige el error presentado el día anterior, se estaba referenciando de forma incorrecta el método:

![image](https://github.com/user-attachments/assets/abc1e603-5c57-408f-8555-dcc45ca03f7c)

Se corrigió la referenciación y se corrió la prueba dando un resultado satisfactorio:

![image](https://github.com/user-attachments/assets/548ab20c-f859-4d35-bd33-902aeb52490c)

Sin embargo, al momento de implementar las demás pruebas, se recibían errores 500 y según los logs, se estaban realizando intentos de conexiones a la API en vez de utilizar los Mocks:

![image](https://github.com/user-attachments/assets/5bbc3cc4-4c47-4be4-91e9-5350a94fab0b)
![image](https://github.com/user-attachments/assets/fbb80070-bc33-4ca2-9630-b52548f11d59)

Investigando se encontró que era necesario también crear los mocks de las peticiones internas del método de firma electrónica y de verificación (post, get, put, etc), por lo que se comienza a realizar esta implementación

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/08/24

Se logró encontrar el modo de mockear las peticiones internas. Por el momento se está probando sólo los casos de éxito de postVerify.

Primero se deben mockear las variables de entorno involucradas:

![image](https://github.com/user-attachments/assets/f6eb6221-17e1-4fac-b71e-bb756aaaf8b3)

Ahora se debe simular la respuesta, capturando primero todas las consultas request (en este caso sólo get), para luego con el propósito de mockear las respuestas se genera un json dummy acorde a la respuesta real de la api para cada uno de los distintos códigos de verificación omitiendo las clave valor que no necesite el método para funcionar:

![image](https://github.com/user-attachments/assets/dff5c4c6-8399-4ff1-bfc4-ee65f659484a)

Se modifica el código de la prueba para poder implementar estos cambios:

![image](https://github.com/user-attachments/assets/e40311f9-35d2-493e-bbb5-3ff35f82b096)

Sin embargo al momento de ejecutar se registra este error:

![image](https://github.com/user-attachments/assets/e232e58c-0ae2-4278-9205-48192eca17fd)

El motivo de dicho error radica en esta línea del método postVerify:

![image](https://github.com/user-attachments/assets/06f3ab83-d432-4072-9c63-cd73519de7a7)

Al parecer el mock a pesar de tener la estructura correcta del json, esta debe tener un formato distinto, por lo que se debe agregar este mock con la respuesta real de la API sin formatear (cosa que no se puede ver en postman), sin embargo la ejecución local para poder observar esta información no es posible por temas del computador en el que se está realizando el desarrollo. Por lo tanto se centrarán los esfuerzos en volver a habilitar las peticiones locales para poder resolver este apartado y que puedan funcionar las pruebas unitarias

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 01/09/24

Se termina de realizar el ajuste a las pruebas unitarias. En primera instancia se logró resolver el problema del equipo en el que se estaba desarrollando.

Gracias a lo anterior se pudieron rescatar las respuestas originales de las apis para poder realizar el proceso de mocking, quedando el método de verificación así:

![image](https://github.com/user-attachments/assets/160f61fb-1d2f-48b0-a097-97d257a2fc28)

Como se evidencia ahora las respuestas son simuladas cono un bytearray.

Para firma electrónica el proceso de ajuste fué bastante extenso, ya que habían más respuestas de distintos tipos que mockear. Sin embargo se logró realizar el ajuste, agregando las respuestas de las APIs en formato byteArray, además de configurar por separado los mocks de los get, post y put, quedando la función de prueba unitaria de la siguiente manera:

![image](https://github.com/user-attachments/assets/6caa2a0d-6756-4144-a493-3aad272ec21d)
![image](https://github.com/user-attachments/assets/5f72ffa4-64fc-4361-8621-273bac211e22)


Con las pruebas de fallo correcto de firma electrónica el proceso fué similar, agregando al decorador de parámetros las respuestas configuradas del método de respuesta normal, siendo el resto muy similar al anterior expuesto:

![image](https://github.com/user-attachments/assets/0d908019-d975-4db2-a71e-d13d95fef251)
![image](https://github.com/user-attachments/assets/64c23186-0fb5-4b64-b9a5-b7ce8e8631ba)


Como resultado final no se crean registros en la base de datos ni en Nuxeo si no que las pruebas unitarias son realizadas correctamente (los warnings son relativos a versiones de algunos métodos de bibliotecas):

![image](https://github.com/user-attachments/assets/f9eebc64-7007-45bd-8398-7aa5184357c7)

Por tanto se coloca en in review

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres.
