### ISSUE TITLE
Crear lógica para poder mostrar los organigramas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#128]
Se requiere realizar la creación de la lógica para mostrar los organigramas de las dependenicas, se plantea realizar dos peticiones "grandes" donde se traigan todas los registros de la tabla dependencia y todas los registros de la tabla dependencia_padre y una vez se tenga esta información se manejará la lógica para crear la estructura directamente en el mid, esto con la finalidad de evitar hacer muchas peticiones http hacia otras Apis.

**Sub Tareas**

- [x] Realizar petición para obtener dependencias.
- [x] Realizar petición para obtener información de dependencias padres e hijas.
- [x] Crear lógica para ajustar estructura que debe responder el Api.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Petición para obtener dependencias realizada.
- [x] Petición para obtener información de dependencias padres realizada.
- [x] Lógica para creación de estructura realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Por favor, hemos revisado la issue de @xDa04vidx y notamos que no se ha documentado. Recordemos la importancia de documentar las issues, tal como discutimos en la sesión conjunta del equipo. Es esencial que se reflejen tanto los avances como los problemas, para asegurar la visibilidad del trabajo realizado.

**Comment by xDa04vidx** [comment]
### Adelanto 1
Se logra implementar la respuesta del endpoint, para su futura logica


![Image](https://github.com/user-attachments/assets/c9b2e6d6-491c-4671-ab01-df3d797612b6)

**Comment by xDa04vidx** [comment]
### Adelanto 2
Se logra implementar de manera parcial la estructura deseada, hace falta realizar comprobaciones para determinar si se esta realizando de manera correcta


![Image](https://github.com/user-attachments/assets/2bf21457-d83b-4246-b3b2-06bf646c83de)

**Comment by xDa04vidx** [comment]
### Problema
En la solución anterior se detecto el problema de que se están repitiendo las dependencias

![Image](https://github.com/user-attachments/assets/0605f897-feb4-41e5-834e-97815cd380fe)

Se esta trabajando en la solución de este error

**Comment by xDa04vidx** [comment]
### Solución de error
Gracias a la ayuda del líder @diagutierrezro  se logra solucionar el error existente en el árbol anterior, se logra obtener un código mas limpio y optimo en la ejecución. 


![Image](https://github.com/user-attachments/assets/a93ab514-70e9-4970-b87a-29c8af49ab14)

**Comment by xDa04vidx** [comment]
### Pull Request

Se realiza pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)
![Image](https://github.com/user-attachments/assets/ea653819-86de-4d0c-ad7a-060eda48159b)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David, muchas gracias.
