### ISSUE TITLE
Realizar la entrega del primer alcance de caducidad de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#129]
Se requiere realizar la entrega de lo relacionado con el primer alcance de caducidad de roles, teniendo en cuenta lo planteado en la reunión con el equipo responsable.

**Sub Tareas**

- [x] Documentar la entrega.
- [x] Generar la revisión por parte del responsable en funcionamiento.

**Criterios de aceptación**

- [x] Documento con la trazabilidad.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se hablo con Jhon y se espera que se envie un registro o evidencia para dejarlo en el documento

[Documento de entrega de solución](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESduZEcotq9JoTlYfA-5QkkBMH9CDWk7eW4BuCoKug4agw?e=7BLVws)

**Comment by jcmurilloa** [comment]
Esperemos que esta evidencia llegue pronto y podamos de esta manera agendar la reunión con funcionamiento para levantar acta de solución al alcance inicial y así dar por terminada esta issue.

**Comment by mantnicot** [comment]
Por falta de entrega de parte de Jhon no se ha podido dar el registro de ficheros o evidencia.



![Image](https://github.com/user-attachments/assets/ea8d08c9-7ca7-4547-8c00-6be4afc64d4a)

**Comment by jcmurilloa** [comment]
Por favor insistir nuevamente con el responsable para los ficheros y avanzar en el cierre de la issue.

**Comment by mantnicot** [comment]
Se ha insistido toda la semana pero el arquitecto ha tenido problemas de agenda y de información para realizar los ficheros 


![Image](https://github.com/user-attachments/assets/8c34a2d7-d61b-466e-932e-fe7ba17b6820)

**Comment by mantnicot** [comment]
Se ha actualizado el documento en la parte final del documento donde se adjunta evidencia tanto del trabajo como la data que fue afectada por el levantamiento del job

[Documento para entregar](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESduZEcotq9JoTlYfA-5QkkBMH9CDWk7eW4BuCoKug4agw?e=vELkNK)

Se espera revisión del equipo para hacer cambios y hacer entrega del mismo

**Comment by jcmurilloa** [comment]
Lo revisaremos en el review detenidamente, con el fin de dar por cumplidas las subtareas de la issue.

**Comment by jcmurilloa** [comment]
Un documento bastante valioso para darle solución a la caducidad de roles, como alcance a proyecto de core. De esta manera se debe articular con el responsable de funcionamiento para su implementación.
