### ISSUE TITLE
Levantar los requerimientos para el segundo alcance de la caducidad de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#130]
Se requiere realizar el levantamiento de la información relacionada con el segundo alcance de caducidad de roles

**Sub Tareas**

- [x] Realizar la investigación de acceso.
- [x] Documentar la investigación.

**Criterios de aceptación**

- [x] Documento con la investigación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha intentado obtener las matrices pero no se ha dado respuesta de parte de funcionamiento aún



![Image](https://github.com/user-attachments/assets/eea6483a-3fbc-400e-83a3-33381556fc48)

**Comment by jcmurilloa** [comment]
Como nos marca la tendencia, debemos continuar la insistencia frente a este requerimiento, con el fin de avanzar en el desarrollo de la issue.

**Comment by mantnicot** [comment]
Por cuestiones de agenda de funcionamiento se espera poder obtener los valores de de las matrices de acceso apra el requerimiento

**Comment by mantnicot** [comment]
Se espera que pronto se pueda dar las matrices pues Eduard no por cuestiones de tiempo no ha podido levantarlas y entregarlas

**Comment by jcmurilloa** [comment]
Debemos insistir este sprint para sacar adelante la investigación.

**Comment by mantnicot** [comment]
De parte de Eduar no se ha dado entrega de las matrices , se espera poder recibir esta semana esas matrices

**Comment by mantnicot** [comment]
Se ha dado la entrega de la matriz , se procede a analizarla para trabajar en este nuevo alcance

[Matriz de acceso](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/En0ImmT5utlGhGp7rXFy4zsBmlxOt_CskL_O97pSY0t1wg?e=IhVmDv)

**Comment by mantnicot** [comment]
Se ha analizado por cantidad de módulos y submódulos los cuales entre más tengan más opciones tienen dentro de los sistemas de la universidad, quedan la prioridad al momento de dar caducidad de la siguiente manera: 

 

URANO: 203 submódulos  

 

	Admisiones registros: 45 submódulos 

	Asesor: 41 submódulos 

 

ARGO: 48 submódulos  

 

	Administrador general: 8 submódulos 

	Gestión compras: 11 submódulos 

	Gestión contractual: 11 submódulos 

 

ARKA |: 69 Submódulos 

 

	Administración: 12 submódulos 
        
	Jefe de almacén: 14 submódulos 


Por lo cual para poder seguir con el segundo alcance se puede dar prioridad a dar caducidad con base a requerimientos con respecto a estos roles

**Comment by jcmurilloa** [comment]
Esto permite definir la hoja de ruta teniendo en cuenta la información recopilada. Excelente trabajo!
