### ISSUE TITLE
Concertar, desarrollar y levantar un acta de exploración inicial para la línea de acción auditoría

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#131]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente para la línea de acción auditoría

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la reunión el día 30/09/2024 se ha creado el acta de la respectiva reunión 

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdnEoJSjQAxLqdmtmrY0YfUByg4R9OyyhrRsXByHunTDZw?e=UKpW6E)

**Comment by jcmurilloa** [comment]
Acta revisada, se generará un resumen en el review de lo sostenido y el rumbo a seguir con el equipo de desarrollo. Muy buen trabajo, pendiente recoger firmas.

**Comment by mantnicot** [comment]
Se ha levantado las firmas correspondientes 
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EensLTyl2pxEgRrFHSdcntEB2G0_ttfebMpCANbHcS6cng?e=KVVTCm)

**Comment by jcmurilloa** [comment]
Muy buen trabajo!
