### ISSUE TITLE
Instrumentalizar firma_electronica_mid con X-Ray

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#134]
Se requiere realizar la instrumentalización del Api de [firma electrónica](https://github.com/udistrital/firma_electronica_mid) con X-Ray usando la librería creada, tener presente la librería que hay que agregar en el archivo de requirements (basarse de la implementación en gestor_documental_mid)

**Sub Tareas**

- [x] Implementar X-Ray usando la librería creada en utils_python.
- [x] Comprobar funcionamiento del mapeo en AWS.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] X-Ray con librería implementado.
- [x] Funcionamiento comprobado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hace las pruebas de los endpoints antes de la implementación:

* http://localhost:4000/v1/verify 

<img width="675" alt="image" src="https://github.com/user-attachments/assets/9e4aebe8-b347-490e-8be6-ec8291f53ecc">

* http://localhost:4000/v1/firma_electronica

<img width="677" alt="image" src="https://github.com/user-attachments/assets/33c1b8d9-af43-4a5f-9086-b4ef7b0132d2">

Después de la corrección de errores que surgieron en la implementación de la libreria del SDK, se muestra que responde la misma forma:

* http://localhost:4000/v1/verify

<img width="676" alt="image" src="https://github.com/user-attachments/assets/eb1b3449-06ab-4053-a3e3-36b85c46a27c">

* http://localhost:4000/v1/firma_electronica

<img width="674" alt="image" src="https://github.com/user-attachments/assets/a1f2fce5-7822-4781-8a82-f729b78d41c1">

Por último se muestra que deja la traza de las apis a las que se apuntan en AWS:

<img width="293" alt="image" src="https://github.com/user-attachments/assets/c7d2d461-650b-4cee-bfda-a60fd83c2a01">

<img width="671" alt="image" src="https://github.com/user-attachments/assets/c9dca7b7-776f-4e71-b29b-63f765befca7">

Falta publicar el código fuente porque no se tiene permiso en el repositorio de firma_electronica_mid para subir dicho código:

<img width="626" alt="image" src="https://github.com/user-attachments/assets/e6dbd1fd-dc2d-4f32-8971-6207e30e9e84">

**Comment by diagutierrezro** [comment]
Se brindan los respectivos permisos.
Teniendo en cuenta la imagen suministrada sobre el mapeo realizado en X-Ray se debe revisar porque pareciera que la petición que se envía desde firma_electronica_mid hacia el gestor_documental_mid no está obteniendo el puerto.
