### ISSUE TITLE
Implementar la lógica creada en la visualización de organigramas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#135]
Se requiere realizar la implementación de la lógica creada en #128 para mostrar el organigrama general con los datos reales de las dependencias.

**Sub Tareas**

- [x] Implementar lógica de organigrama general.
- [x] Realizar pruebas de funcionamiento.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Lógica implementada.
- [x] Pruebas de funconamiento realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se implementa organigrama

Ya queda realizado organigrama, se carga cuando se le da al botón de "ORGANIGRAMAS"
![Image](https://github.com/user-attachments/assets/78c0e41c-c3e4-4b9d-b376-cfee3a5545f9)

Se observa con @diagutierrezro que existen múltiples nodos que no tienen padre ni hijos que afectan la visualización, no obstante se puede observar el árbol que nace de la dependencia "UNIVERSIDAD DISTRITAL" se esta graficando de manera adecuada.

**Problema**
![Image](https://github.com/user-attachments/assets/9ed25f9a-61ba-466f-9d94-1cb673bdaee3)

**Árbol Universidad**
![Image](https://github.com/user-attachments/assets/1b24b712-69ca-4094-8a76-882e670f28ee)

**Comment by xDa04vidx** [comment]
### Pull request
Se agrega el commit al pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)

![Image](https://github.com/user-attachments/assets/c0039d12-fba3-4127-9b8a-14b1837de0e8)
