### ISSUE TITLE
Revisar flujo de mapeo en X-Ray cuando se hacen peticiones de MID a MID

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#137]
Se requiere realizar la revisión de los mapeos cuando las peticiones se hacen de MID a MID teniendo en cuenta la imagen del mapeo que se encuentra en #134 donde el mapeo desde firma_electronica_mid hacia el gestor_documental_mid no se encuentra correcto.

**Sub Tareas**

- [x] Ajuste a mapeo de MID hacia MID realizado.
- [x] Probar que el mapeo se esté haciendo de manera correcta.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Después de trabajar en las apis gestor_documental_mid y firma_digital_mid, la cual hace petición a gestor_documental_mid y esta queda como remote, se ha configurado el sdk de las dos apis, ya que se esta trabajando en local con las dos, también se han modificado los http request y los encabezados de headers, pero no se ha logrado solucionar el error, ya que queda de la siguiente forma, creando subsegmentos y dejando en remoto a la api gestor_documental_mid.

La solución más cercana que se obtuvo para que la api no sea clasificada como remoto, fue que creo como un nuevo segmento pero no deja traza de las apis y aún crea un nodo de la api donde se ve como remoto, es decir que crea dos nodos, uno donde se ve como si un cliente le pidiera una petición y otro donde aparece como remote, se deja la traza de la petición http y la imagen de como aparece en aws:

            {
                "Id": "1-66d7b38f-df3e4447cfe9345fb5c5387e",
                "Duration": 3.597,
                "LimitExceeded": false,
                "Segments": [
                    {
                        "Id": "35265dfbd9097be3",
                        "Document": {
                            "id": "35265dfbd9097be3",
                            "name": "localhost:4000",
                            "start_time": 1725412239.1983695,
                            "trace_id": "1-66d7b38f-df3e4447cfe9345fb5c5387e",
                            "end_time": 1725412242.795699,
                            "in_progress": false,
                            "http": {
                                "request": {
                                    "url": "http://localhost:8034/v1/document/putUpdate",
                                    "method": "PUT"
                                },
                                "response": {
                                    "status": 200
                                }
                            },
                            "aws": {
                                "xray": {
                                    "sampling_rule_name": "Filtro-V1",
                                    "sdk_version": "2.14.0",
                                    "sdk": "X-Ray for Python"
                                }
                            },
                            "service": {
                                "runtime": "CPython",
                                "runtime_version": "3.10.12"
                            },
                            "subsegments": [
                                {
                                    "id": "ad9e5edbbcefba0f",
                                    "name": "localhost",
                                    "start_time": 1725412239.1989172,
                                    "end_time": 1725412242.7955396,
                                    "in_progress": false,
                                    "http": {
                                        "request": {
                                            "url": "http://localhost:8034/v1/document/putUpdate",
                                            "method": "put"
                                        },
                                        "response": {
                                            "status": 200
                                        }
                                    },
                                    "namespace": "remote"
                                }
                            ]
                        }
                    },
                    {
                        "Id": "12c07b292ccb33ac",
                        "Document": {
                            "id": "12c07b292ccb33ac",
                            "name": "localhost",
                            "start_time": 1725412239.1989172,
                            "trace_id": "1-66d7b38f-df3e4447cfe9345fb5c5387e",
                            "end_time": 1725412242.7955396,
                            "parent_id": "ad9e5edbbcefba0f",
                            "inferred": true,
                            "http": {
                                "request": {
                                    "url": "http://localhost:8034/v1/document/putUpdate",
                                    "method": "put"
                                },
                                "response": {
                                    "status": 200
                                }
                            }
                        }
                    }
                ]
            }

<img width="334" alt="image" src="https://github.com/user-attachments/assets/8bf9c933-98cb-493a-a6a7-1f91b4874e10">

SE SIGUE TRABAJANDO EN BUSCAR LA SOLUCIÓN.

**Comment by JulianAvella** [comment]
Se trata de evitar que las trazas entre las APIs gestor_documental_mid y firma_digital_mid queden registradas como subsegmentos en AWS X-Ray, además que cuando gestor_documental_mid retorne información a firma_digital_mid, la traza no quede clasificada como "remote" ni se registre como un subsegmento, además que las trazas en AWS X-Ray no queden duplicadas en una petición HTTP que se le haga a una API.

En un resumen de las soluciones intentadas:

+ Modificación directa de las funciones de solicitud HTTP: 

    * Se intentó controlar manualmente las trazas mediante las funciones personalizadas get_json, post_json y put_json en ambas APIs.
    * Se utilizó el manejo de segmentos y subsegmentos en estas funciones:
      - Al comenzar una solicitud, se verificaba si ya existía un segmento activo. Si no, se creaba un nuevo segmento.
      - Se añadieron metadatos y anotaciones para tratar de evitar la clasificación como "remote".

+ Uso de anotaciones y metadatos:

    * Se intentó utilizar las anotaciones namespace y skip_remote para indicar que la traza no debía clasificarse como remota ni generar subsegmentos.
    * Ejemplo de anotación: segment.put_annotation('namespace', request.host)

+ Configuración global del SDK en Flask:

    * Se implementó una configuración inicial del SDK de X-Ray, parchando todas las bibliotecas soportadas.
    * Se probaron etiquetas en la configuración del demonio.
    * Se probo con middleware.
    * Se probo utilizando before_request y after_request para gestionar los segmentos en todas las solicitudes.

+ Actualización del SDK de AWS X-Ray:

    * Se consideró actualizar la versión del SDK para Python, buscando una versión equivalente a la utilizada en el SDK de Go (1.8.1). La versión 2.6.0 del SDK para Python fue la equivalente .
    * Tras actualizar el SDK, el comportamiento de las trazas no cambió significativamente en cuanto a la creación de subsegmentos.

+ Configuración avanzada para controlar las trazas:

    * Se intentó implementar una configuración avanzada del SDK, replicando el comportamiento esperado en Go. Esto incluía:
        - Evitar la inferencia de trazas como "remote".
        - Controlar manualmente los segmentos sin generar subsegmentos.

+ Implementación casi igual del SDK de Go:

    * Se probo desarrollar un código similar del SDK de Go que esta en utils para el SDK de Python.

+ Desarrollo desde cero:

    * Se intento hacer el desarrollo y configuración del SDK de Python, de diferentes formas desde el inicio del código fuente.

Nota: Aunque se intentaron diversas configuraciones y ajustes en el código, no se ha logrado una solución definitiva que elimine por completo la clasificación como "remote" o la creación de subsegmentos en las trazas de AWS X-Ray.
