### ISSUE TITLE
Ajustar vista para creación de mapeo de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#138]
Se requiere realizar el ajuste en la vista que permita el nuevo registro del mapeo de dependencias, para esto tener en cuenta la modificación en los mockups que se realizará en #139.

**Sub Tareas**

- [x] Ajustar vista según ajustes en mockups.
- [x] Implementar endpoint de creación de nuevo mapeo de dependencias.
- [x] Probar correcto funcionamiento del registro del mapeo.

**Criterios de aceptación**

- [x] Ajuste de vista según mockups realizado.
- [x] Implementación de enpoint realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación realizadas.

**Dependencias**
Para poder dejar la vista funcional es necesario que el ingeniero Jhon cree los respectivos endpoint en JBPM que permita la creación de este mapeo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
@Skyrus1203 Recuerda la importancia de documentar las issues, nos tienes aconstumbrados a muy buenos comentarios!

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 04/09/24

Similar a lo informado para el avance de hoy en [el issue de edición de dependencias](https://github.com/udistrital/core_documentacion/issues/141) se realizó la parte visual de la ventana de creación de dependencias agregando los campos requeridos y las ventanas informativas, quedando pendientes los mismos puntos señalados en el avance de hoy del issue ya mencionado. Por lo que la ventana de creación de dependencia queda de esta manera:

![image](https://github.com/user-attachments/assets/fec532c8-9dbc-48bd-9189-ae4aa941f233)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 05/09/24

Se ajusta tamaño del botón:

![image](https://github.com/user-attachments/assets/df2b6214-e5b1-4faf-a63d-6acd7951a18f)

![image](https://github.com/user-attachments/assets/721eb01d-8d95-495b-b1b7-15292d2645ab)


 y en la lógica se dejan listos los Form Control para ser implementados al momento de capturar información para llamar al endpoint cuando esté listo:

![image](https://github.com/user-attachments/assets/6e3793eb-5cf3-4fc3-b9f4-c7900e64aca5)

![image](https://github.com/user-attachments/assets/36556f70-aa82-4c77-aaf6-a17eb171c0d8)

Por lo tanto se está a la espera de la finalización de los endpoints para poder continuar

**Comment by diagutierrezro** [comment]
Se ha generado una demora por parte del ingeniero Jhon para la creación de los endpoints en JBPM por lo que la tarea no se ha podido finalizar.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/09/24

Recibidos los endpoints se realizaron algunas pruebas para verificar su funcionamiento, sin embargo dichos endpoints arrojaban error de CORS:

![Captura de pantalla 2024-09-08 120400](https://github.com/user-attachments/assets/5932c607-a2bb-4e2b-8cc2-c82869aff387)

Por lo tanto se adelantan funcionalidades mientras se corrige el CORS y se pueden probar correctamente los Endpoints.

Se crea una lógica general para gestionar respuestas XML la cual se puede adaptar para recibir la respuesta de los endpoints suministrados y así poder capturar la información que se requiera:

![image](https://github.com/user-attachments/assets/3fbccf08-a49e-4c8d-96c8-5fe82490ed09)

Se crea método que genera un objeto que luego se enviará como json para el post y put respectivamente y se maneja lógica que adapta dicho objeto dependiendo de ello:

![image](https://github.com/user-attachments/assets/0c14d085-23da-4831-ac18-90f2828eacb0)

Para esto se modifica la interfaz de MapeoBusqueda:

![image](https://github.com/user-attachments/assets/69591e6c-e8d0-41db-b0f8-8f66271d3f81)


Se crea método para gestionar la creación de dependencias (el post) cargando el objeto creado anteriormente y manejando las alertas correctas:

![image](https://github.com/user-attachments/assets/152a9d40-2d18-48a3-9ecf-78804f9bdb3a)

Así mismo para que esto funcione se crea un service que mediará con los nuevos endpoints implementados:

![image](https://github.com/user-attachments/assets/dfed6a69-4d8b-47f9-b7f4-9fcbe6f62998)

Se programa también el botón de Editar/Crear para que ejecute la siguiente función:

![image](https://github.com/user-attachments/assets/8514a374-3de1-4c5d-a67a-ba9c465c7dd9)

La cual se encarga de definir qué función ejecutar en función si se quiere crear o editar una dependencia:

![image](https://github.com/user-attachments/assets/a3480163-d2bc-409f-9041-a6e3f65e47d8)

Por tanto queda pendiente la desactivación temporal del CORS para terminar de ajustar los métodos que apuntan a los endpoints y probar sus funcionalidades.

**Comment by diagutierrezro** [comment]
Se solicita al ingeniero Jhon la revisión de los endpoints, se finalizará la implementación en otra issue.
