### ISSUE TITLE
Actualizar mockup de mapeo para gestión de dependencias en OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#139]
Se requiere actualizar el mockup de mapeo para gestión de dependencias en OIKOS. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado el cambio de mockups colocando los nuevos campos de iris y argo



![Image](https://github.com/user-attachments/assets/0bd19832-1e24-4090-a521-3f8dc7e03c6f)
![Image](https://github.com/user-attachments/assets/62ca7c5f-d1ff-41f3-b965-c812b2aa97c8)

[Carpeta de los mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EgJLYlLpaVxNjKDtcv2uFecBXk1GNnbAANIEX0AGwnveyw?e=00mZC6)

**Comment by diagutierrezro** [comment]
Por favor actualizar tambien la vista de generar mapeo para que tambien se muestren los códigos de argo e iris

**Comment by mantnicot** [comment]
Se ha actaulizado las vistas 
[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EgJLYlLpaVxNjKDtcv2uFecBXk1GNnbAANIEX0AGwnveyw?e=qcXr6c)



![Image](https://github.com/user-attachments/assets/0462347b-0512-4b4e-99c7-f744c58bfa16)
![Image](https://github.com/user-attachments/assets/5924a751-9b13-480d-b0b6-b737dfb987cb)
![Image](https://github.com/user-attachments/assets/53a9836b-1b9c-4e45-bfc6-8a9efc2e13d6)

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot , revisaremos al detalle en el próximo review.

**Comment by jcmurilloa** [comment]
Mockup revisado y aprobado por el equipo.
