### ISSUE TITLE
Analisis de la lógica de firma electronica hacia la nueva API

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#14]
Se requiere realizar el analisis para la migración de la lógica de firma electronica que se encuentra actualmente en el API del gestor_documental_mid hacia la nueva API creada.

**Sub Tareas**
- [x] Realizar el analisis migración de la lógica relacionada con firma electronica hacia la nueva API creada en el issue #6 
- [x] Documentar en el issue el respectivo analisis realizado.

**Criterios de aceptación**
- [x] Logica migrada hacia la nueva API.
- [x] Pruebas funcionales realizadas.

**Requerimientos**

No aplica

**Dependencias**
Creación del repositorio por parte de @diagutierrezro 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
----- ACTUALIZACIÓN 07/05/2024 ----------
Por motivos de practicidad se referirá a gestor documental como GD y a la API nueva de firma electrónica como FE.
Después de un análisis del código de GD se llegó a la conclusión de que debían implementarse los siguientes cambios en FE:
1. Se identificó que en GD los dos métodos concernientes a la firma electrónica son dos: el primero que sube un documento a nuxeo y lo firma y el segundo que se encarga de verificar la firma electrónica en el documento:
![Captura de pantalla 2024-05-07 181721](https://github.com/udistrital/core_documentacion/assets/77305100/ee691bc8-85f1-4d0c-9a07-d2fc49f477d5)
![Captura de pantalla 2024-05-07 181702](https://github.com/udistrital/core_documentacion/assets/77305100/71d7476c-3ca2-4243-b4a2-211dcf11ca68)

2. Para la implementación de dichos métodos se identificó por el momento, que requieren las librerías  nuxeo, PyPDF2, pdfminer y Criptography para que los módulos de firma electrónica funcionen correctamente (En el futuro puede llegar a identificarse más librerías necesarias), las cuales se agregan al requeriments.txt de FE: 
![image](https://github.com/udistrital/core_documentacion/assets/77305100/4a225bde-ce49-44ca-8026-49bb169465d8)

3. Analizando el routers.py de GD nos damos cuenta que el único controlador (preliminarmente) que necesitamos es el llamado document.py el cual en FE tenemos como controllerPrueba, por lo que ya que realizamos los ensayos necesarios para verificar el funcionamiento del esqueleto de FE podemos cambiar el nombre a uno más pertinente (se coloca tentativamente controllerFirma.py):
![image](https://github.com/udistrital/core_documentacion/assets/77305100/73cd88ca-237b-4a2d-88b9-adbbc250376c)

4. Analizando los dos métodos de document.py en GD encargados de firmar y verificar (postFirmaElectronica y postVerify respectivamente) nos damos cuenta que requerimos no sólo estos métodos si no que también necesitamos crear dos modelos: firma_electronica.py y firma.py. Por tanto se procede a copiar dichos archivos a FE para su posterior adaptación y modificación de ser necesaria:
***Captura de imports de document.py (para no mostrar todo el código de los métodos):***
![image](https://github.com/udistrital/core_documentacion/assets/77305100/2f513514-1164-459d-9fb7-dff900c593b8)
***Captura de archivos modelo copiados a FE***
![image](https://github.com/udistrital/core_documentacion/assets/77305100/420a61b7-4379-42e2-af95-b580e5572438)

**Comment by Skyrus1203** [comment]
---------ACTUALIZACIÓN 09/05/2024 ------------

*** Inicio de construcción de métodos discriminados e identificación de dependencias***

Esta actualización tiene como propósito principal identificar las dependencias de variables a consultas hechas en gestor documental que deban considerarse ser trasladadas (y con esto ser duplicadas) o bien ser discriminadas. Se hizo un análisis de la función de firma electrónica en base a una reunión realizada con el líder del grupo en la cual se aclararon muchos aspectos respecto a la migración del módulo de firma electrónica, con base en ello se realizó este análisis para encontrar qué partes de la firma electrónica dependen de ciertos comandos de gestor documental para que estos deban ser trasladados a pesar de quedar duplicados en la API de FE:

**Análisis**

Se comienza con la migración de los métodos de firma electrónica desde GD a FE. Primero se identifica que a pesar de prescindir de ciertos métodos que se reiteran en el método POST de gestor documental en document.py (identificados gracias a una reunión realizada el día de hoy con el líder de equipo), se reconoce que los métodos concernientes a factura electrónica utilizan la misma variable llamada "data" que guarda el parámetro "body" que recibe el método el cual es un Json con la información del documento. Por tanto, por motivos de practicidad se traslada la variable a la nueva API FE con los mismos nombres:
En GD:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/38aa646c-9d28-4bb7-a3d7-03b17a1bd155)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/0738776b-399f-4d35-9446-d3a14c325903)
Tratamiento de datos replicado en post de gestor documental que usan la variable data:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/bc105b99-8db8-4811-925e-5fde89bbc57b)
Tratamiento de datos concerniente a firma electrónica que usan la variable data:

EN FE:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/cde31d2e-e2f8-4342-a117-6626c7ce77de)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f5672c38-b384-48bd-bd6a-7d60be29e3f8)

Ya que para la extracción de datos del post de gestor documental y para la extracción de firmantes de firma electrónica se utiliza la variable data sólo que discriminando diferentes campos no sería necesario replicar la extracción inicial mostrada arriba. Los datos que se extraen del siguiente fragmento se guardan en la variable *up_file* 
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f76a167a-d0c6-4cdf-a9db-046f4b03e8c4)
Y up_file sólo se vuelve a utilizar aquí:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/2ac0caee-259d-45be-a824-1903c328d3cf)

Siguiendo esta lógica se podría idear un modo de extraer las variables ya establecidas en el post de gestor documental para que no se tengan que replicar en FE. Esto con el propósito de tener en cuenta lo siguiente: 

En la reunión con el líder de grupo se identificó la creación de un objeto en el archivo de document.py el cual es el siguiente:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/fca66c84-790c-4ad4-ac18-f5aedecbfad9)

Este posteriormente se utiliza en el put a Documentos CRUD aquí:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/cceda5cc-d1bb-4bc6-a056-1e6456c5c0b4)

En la reunión se teorizó que la creación de este objeto no era necesaria ya que la información agregada de firmantes no aparecía en la base de datos de Documentos CRUD. Este objeto es creado con anterioridad más arriba aquí:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/e000d35a-aa54-4157-8d9f-3cb583a6bb1d)

Y este no es usado por la firma electrónica. Sin embargo es necesario aclarar correctamente si la segunda creación de dicho objeto es necesaria por lo siguiente:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/bccf7434-b27d-4713-9910-a890a3ee1b20)
Como vemos este objeto utiliza la variable "file" y la variable "res_json" las cuales se obtienen de la siguiente manera:

Para obtener res_json es necesario realizar la consulta siguiente a documentos crud (mediante un get) la cual se había descartado para implementar en FE:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/3c227585-120e-4585-89a0-7a85ea29676b)

Para file es necesario ejecutar el siguiente comando con nuxeo utilizando up_file que de caso de requerir dicho comando también necesitaríamos en este caso dicha variable de up_file:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/7f0fbc60-e920-47ed-ae0f-0281824745cb)

Por lo tanto de confirmar que la creación de el objeto DicPostDoc no es necesaria ensu segunda iteración (en la que se agrega la información de firmantes y representantes) se puede proceder sin necesidad de realizar consultas preliminares, simplemente rescatando de gestor documental responsePostDoc que utiliza DicPostDoc para el siguiente comando:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/0185c5db-f37c-4f0e-9cc1-b45b63901aab)

Y por último en la creación del objeto datos que tiene información de la firma electrónica se necesitaría el re_json el cual podría o bien plantearse ser rescatado de gestor documental (que sería lo más óptimo) o duplicar las consultas necesarias para obtener esta variable:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/c6b42829-cd9e-4a7b-85a4-94e1affc50c6)

El resto de funcionalidades pueden ser utilizadas autónomamente o bien accedidas de gestor documental, por lo tanto se procede a adelantar el avance en el traspaso de las partes que son independientes en lo que se termina de analizar lo expuesto en este informe.

**Comment by Skyrus1203** [comment]
------- ACTUALIZACIÓN 13/05/24 --------------

Se trasladan los comandos de Firma electrónica a la nueva API:

Se traslada desde la definición del Json de firmantes hasta la definición del Json DicPostDoc:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/00d7a89f-8909-43a5-8bb7-79f2fa809a0d)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/ce60e882-17f6-493e-a0cd-c4cbaef60a53)

Ahora bien se tienen dos puntos pendientes:
1. Para poder estampar la firma se requiere del objeto datos que requiere a res_json para su elaboración, variable que no está presente en la lógica de firma electrónica pero que si se obtiene en gestor documental, por lo que este dato dependiente se comentarea. Se propone como consideración recibir esta variable como parámetro desde gestor documental mid, en cuanto se tome una decisión al respecto la línea 70 de document.py queda comentareada
![image](https://github.com/udistrital/core_documentacion/assets/77305100/b57188c7-bf98-4e3b-bc43-dbc74bb60acc)

2. Algo similar sucede con la definición de DicPostDoc: Sin embargo esta definición se había puesto en veremos ya que la información que envía este documento hacia Documentos CRUD no es utilizada por completo, sin embargo se agrega en el caso de necesitarse. Esta definición requiere tanto la antes mencionada variable res_json como la variable file por lo que también se propone dejarla como parámetro que recibe desde gestor documental:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/a798d5a6-196f-442f-a90a-cd11b487ff30)

Queda pendiente para discutir estos dos puntos y la retroalimentación de la lógica trasplantada para definir si es necesario agregar algo más o se puede proceder con lo que se trasladó.

Se tomaron un par de apuntes importantes de la reunión de aclaración que tuvo el lider de grupo con la persona que aclaró algunas dudas del módulo de firma electrónica:

[Apuntes grabación aclaración.txt](https://github.com/udistrital/core_documentacion/files/15301475/Apuntes.grabacion.aclaracion.txt)

**Comment by diagutierrezro** [comment]
Muy buen trabajo @Skyrus1203 

Se crea el [repositorio](https://github.com/udistrital/firma_electronica) donde se almacenará el código del API firma_electronica.
