### ISSUE TITLE
Refinar requerimiento de ínea de acción de Auditoría

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#140]
Se requiere realizar el seguimiento, la investigación y documentación del requerimiento frente a la linea de acción de Auditoría

**Sub Tareas**

- [x] Generar seguimiento a los avances con los responsables
- [x] Establecer contacto con los encargados
- [x] Documentar los avances del refinamiento
- [ ] Generar proyección de costos

**Criterios de aceptación**

- [x] Contacto con responsables
- [x] Documento con lo adelantando en el seguimiento
- [x] Refinamiento y definición del alcance inicial de Auditoria

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Con base a charlado en la reunión con el equipo de segudirdad y aquitectura se concluye la siguiente linea de acción

[Documento de auditoria](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWHOKCIBBrZPqxZbniF1gXIBI7QhsE5LXM49-_o0vXlr5A?e=ENcKjO)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, repasaremos en el review, con base a este documento, la continuidad de la refinación de esta línea de acción para el proyecto.

**Comment by mantnicot** [comment]
Para poder suplir lo de proyección de costos , se define que so es responsabilidad de la persona encargada de AWS, se hará seguimiento de parte del equipo para el requerimiento
