### ISSUE TITLE
Ajustar vista para edición de mapeo de dependencias - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#141]
Se requiere realizar el ajuste en la vista que permita la edición del mapeo de dependencias, para esto tener en cuenta la modificación en los mockups que se realizará en #139.

**Sub Tareas**

- [x] Ajustar vista según ajustes en mockups.
- [x] Implementar endpoint de edición en el mapeo de dependencias.
- [x] Probar correcto funcionamiento de la edición del mapeo.

**Criterios de aceptación**

- [x] Ajuste de vista según mockups realizado.
- [x] Implementación de enpoint realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación realizadas.

**Dependencias**
Para poder dejar la vista funcional es necesario que el ingeniero Jhon cree los respectivos endpoint en JBPM que permita la edición de este mapeo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
@Skyrus1203 Recuerda la importancia de documentar las issues, nos tienes aconstumbrados a muy buenos comentarios!

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN DE 02 - 03 DEL 09 DE 24

Se tiene una reunión el día lunes con el desarrollador David para realizar una apropiación del sistema. El día de ayer se realizó la clonación de repositorios, sin embargo al tratar de ejecutar en simultaneo el oikos root, el core cliente, y las apis de mapeo de dependencias y gestión de dependencias (por medio de la opción "Debug" presente en el package.json de ambos el oikos root y el core cliente) la consola se quedaba congelada y no ejecutaban los servicios, y aún así el consumo de memoria ram era muy elevado

### ACTUALIZACIÓN 04/09/24

Se resolvió el problema presentado el día anterior, primero siguiendo las instrucciones presentes en el readme de los respectivos repositorios y segundo en el core_cliente se realizó pull de los cambios realizados en la rama en la que se están desarrollando las funcionalidades, en la que se agrega la url de pruebas del core_cliente alivianando la ejecución local.

Luego se procedió a ejecutar las apis de mapeo de dependencias y el mid de gestión de dependencias, siendo el primero ejecutado exitosamente y el segundo presentando un error:

![image](https://github.com/user-attachments/assets/b6e45f16-b46e-4baa-97fb-d8c963b9c0ce)

Primero se identificó que no se creaba el go.sum al hacer go mod init -> go mod tidy. En el repositorio del mid había un comando go get que al agregarse generó exitosamente el go.sum con lo siguiente:

![image](https://github.com/user-attachments/assets/54360f9a-589a-4001-a22b-9eec03a92929)

Sin embargo el error persiste y no permite ejecutar el mid. Se está trabajando en arreglar este inconveniente para poder completar las tareas lo antes posible. Este comentario también aplica para el otro issue asignado sobre la  [edición de dependencias](https://github.com/udistrital/core_documentacion/issues/138)


Adicional a esto me disculpo por no realizar la documentación respectiva los días anteriores, a mi juicio al no tener avances significativos en la tarea no consideré pertinente documentar los problemas de instalación y ejecución que he tenido estos días. Tendré en cuenta la observación de la importancia de la documentación, y procuraré documentar diario por más pequeños que sean los avances.

**Comment by Skyrus1203** [comment]
### ADJUNTO A AVANCE ACTUALIZACIÓN 04/09/24

En la ventana de edición de mapeo de dependencias se logró realizar el ajuste de front agregando los campos requeridos (Con la ayuda y guía del desarrollador David Arias) y también se logró añadir pestañas informativas para cada campo ajustando su despliegue para que pudiese ser visible:

![image](https://github.com/user-attachments/assets/1c66ab7d-f3ea-498b-a60e-530ab7453e50)

Se edita ligeramente el Css para que la pestaña informativa de la columna izquierda se muestre hacia la derecha con el propósito de que la viñeta no se corte:

![image](https://github.com/user-attachments/assets/4709225a-62f3-46c2-80fa-448f5fe1c465)

Quedando de la siguiente manera:

![image](https://github.com/user-attachments/assets/a2fe1678-8fa2-4002-abbd-47fcae6d8c83)

Queda pendiente ajustar el botón al ancho requerido en el mockup, agregar los place holders en los inputs en los que se muestren los datos de la dependencia a editar, ajustar pop ups y crear el endpoint correspondiente y probarlo

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 05/09/24

Los avances descritos para el día de hoy son los mismos puntualizados en el [Issue de generación de dependencias](https://github.com/udistrital/core_documentacion/issues/138)

**Comment by diagutierrezro** [comment]
Se ha generado una demora por parte del ingeniero Jhon para la creación de los endpoints en JBPM por lo que la tarea no se ha podido finalizar.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/09/24

Además de la actualización descrita en el issue [de creación de dependencias](https://github.com/udistrital/core_documentacion/issues/138) se agrega también el método de edición de dependencias, que también queda pendiente de ser probado:

![image](https://github.com/user-attachments/assets/126676e1-5cf1-4ff1-9cfc-74bce937dc91)

**Comment by diagutierrezro** [comment]
Se solicita al ingeniero Jhon la revisión de los endpoints, se finalizará la implementación en otra issue.
