### ISSUE TITLE
Ajustar lógica para crear estructura que permita traer el mapeo de organigramas academicos y administrativos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#143]
Se requiere realizar el ajuste de la lógica para la creación de la estructura para los organigramas academico y administrativo. La propuesta inicial es realizar la busqueda de las dependencias para encontrar la "RECTORIA", una vez se encuentre dependiendo si queremos guardar la estructura para el organigrama academico o administrativo, borrar los hijos que no se necesiten. Por ejemplo, si se quiere mostrar el organigrama académico, buscar en los hijos de rectoría y dejar unicamente el hijo de la dependencia academica.

**Sub Tareas**

- [x] Realizar ajuste de la lógica para definir los dos organigramas.
- [x] Probar funcionamiento de la lógica modificada.
- [x] Documentar issue con ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra obtener los arboles con solamente el árbol de la universidad distrital, tanto en Académico como en Administrativo

**Académico**
![Image](https://github.com/user-attachments/assets/1c77de6d-c8c9-4dfc-8371-bc757aab1708)

**Administrativo**
![Image](https://github.com/user-attachments/assets/7e533431-ce44-425b-bf01-003563efa2b8)

**Comment by xDa04vidx** [comment]
### Problema

Actualmente, se está trabajando en el organigrama académico. Por lo tanto, se está intentando dejar únicamente el nodo 'VICERRECTORÍA ACADÉMICA' como hijo de 'RECTORÍA', aunque los intentos realizados hasta ahora no han sido exitosos.

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra dejar en el organigrama académico que aparezca únicamente como hijo de "RECTORIA" la "VICERRECTORIA ACADEMICA"

![Image](https://github.com/user-attachments/assets/4e39859d-e668-4606-af77-ac573982c91b)

Mientras que en el organigrama administrativo se logra que aparezcan todos los hijos de "RECTORIA" excepto "VICERRECTORIA ACADEMICA"
![Image](https://github.com/user-attachments/assets/5f682caf-5b26-4c75-ac85-77c70b601b58)

**Comment by xDa04vidx** [comment]
### Problema

Se logra identificar un problema en la poda de los nodos huérfanos, dado que no solo esta borrando los nodos huérfanos, sino también las hojas de los arboles.

**Comment by xDa04vidx** [comment]
### Organigrama con hojas
Se logra solucionar el problema anterior, tanto en el organigrama académico como el administrativo, se deja sin los nodos huérfanos y se logran visualizar las  hojas

**académico**
![Image](https://github.com/user-attachments/assets/b1fd1b01-d7c4-4361-8dd8-2181f65caaca)

**administrativo**
![Image](https://github.com/user-attachments/assets/307f52df-54a4-4095-8272-4d21eefa600c)

**Comment by xDa04vidx** [comment]
### Pull Request
Se realiza pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)



![Image](https://github.com/user-attachments/assets/df910b52-fe77-4aad-bd4a-eff418f3db33)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David, gracias.
