### ISSUE TITLE
Ajustar cliente para mostrar orgranigramas academico y administrativo

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#145]
Se requiere realizar el ajuste al cliente para que mapee los organigramas academico y administrativo teniendo en cuenta el ajuste realizado en #143 

**Sub Tareas**

- [x] Ajuste al cliente realizado.
- [x] Documentación de funcionamiento correcto.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Pull Request 
Se realiza pull request en [oikos_root_mf](https://github.com/udistrital/oikos_root_mf)


![Image](https://github.com/user-attachments/assets/5d315dfb-0359-4640-8c68-34cfa7bf2154)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra ajustar la vista para la correcta visualización en el cliente
**Académico**

- Centro
   ![Image](https://github.com/user-attachments/assets/574f764b-1cc5-4966-a0ad-7776065b0491)
 
- Facultad
   ![Image](https://github.com/user-attachments/assets/4d568337-8568-4b9e-a229-1c611339dff3)

**Administrativo**
![Image](https://github.com/user-attachments/assets/f683ce1f-ef04-4d31-bb15-019e4f2263af)

**Comment by xDa04vidx** [comment]
### Pull request
Se agrega al pull request el commit en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)

![Image](https://github.com/user-attachments/assets/b5606a5d-9255-44b3-92d4-b7c458f52750)

**Comment by xDa04vidx** [comment]
### Cambio en el root
Se realiza un cambio en el root, para el microcliente de core, no apunte a local sino a pruebas 

![Image](https://github.com/user-attachments/assets/8a16a70a-ccf5-4e55-b968-d7d6389c4241)

Se comprueba funcionamiento:

Pagina de inicio:
![Image](https://github.com/user-attachments/assets/ceb52bae-0cea-4093-adfa-1db103dfb178)

Loggin funcional:
![Image](https://github.com/user-attachments/assets/e5924f8f-055e-4cbd-b9c0-e6fbe735a85a)

Acceso:
![Image](https://github.com/user-attachments/assets/609f3baa-3c5a-409c-80e1-faea76050b02)

**Comment by xDa04vidx** [comment]
### Pull request
Se agrega al pull request el commit en [oikos_root_mf](https://github.com/udistrital/oikos_root_mf)


![Image](https://github.com/user-attachments/assets/225cb120-9b38-4c41-a050-35568b0eed4c)

**Comment by diagutierrezro** [comment]
Despues se deben crear issues para pulir el cliente visualmente pero la parte funcional ya se encuentra correcta, gracias David.
