### ISSUE TITLE
Ajustar consulta de busqueda de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#146]
Se requiere realizar el ajuste al cliente de Oikos, donde se restrinja los filtros posibles, la idea es que solo se pueda seleccionar un "desplegable" al tiempo entre "tipo dependencia", "facultades" y "vicerrectorias" si selecciono uno los otros deben quedar vacios.

**Sub Tareas**

- [x] Realizar restricción para poder seleccionar un único desplegable.
- [x] Probar funcionamiento del funcionamiento correcto.
- [x] Documentar issue con pruebas realizadas.

**Criterios de aceptación**

- [x] Restricción de desplegables realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se realiza el cambio

**Vista inicial**
![Image](https://github.com/user-attachments/assets/45ad03a1-8cfd-4e0d-a4db-c15dd93d87f0)

**Selección de un tipo**
![Image](https://github.com/user-attachments/assets/b2ea5867-8efd-486a-81ed-2b7779acb51e)

**Selección de una vicerrectoría**
![Image](https://github.com/user-attachments/assets/4ab9a511-7af3-415c-9286-fe397e424a8e)

Se observa que se borra la selección del tipo.

**Selección de una facultad**
![Image](https://github.com/user-attachments/assets/ed4b5e08-01f4-4411-8025-750306af7b9a)

Se observa que se borra la selección de la vicerrectoría.

**Selección de otro tipo**
![Image](https://github.com/user-attachments/assets/7680d04a-0dcd-4a43-a998-53f7849064c6)

Se observa que se borro la selección de la facultad.

**Comment by xDa04vidx** [comment]
### Funcionamiento
Se comprueba que se puede hacer la busqueda por seleccion individual y combinada.

**Busqueda por tipo**
![Image](https://github.com/user-attachments/assets/d31ea479-e4f4-461a-b05d-2d22bd0f76af)

**Busqueda por tipo y nombre**
![Image](https://github.com/user-attachments/assets/66a5fffa-80ce-48b9-9f98-04097efe63c9)

**Busqueda por Vicerrectoria**
![Image](https://github.com/user-attachments/assets/86c11109-f91e-46ed-b400-e2d69186039a)

**Busqueda por Vicerrectoria y nombre**
![Image](https://github.com/user-attachments/assets/2651b4da-0a74-4aeb-9424-64d5824576ed)

**Busqueda por Facultad**
![Image](https://github.com/user-attachments/assets/ccd3be0b-070a-4bdd-aa88-01a54c51a3c8)

**Busqueda por Facultad y nombre**
![Image](https://github.com/user-attachments/assets/71739e63-285d-4a55-9c2c-e3b5fb03bf6c)

**Comment by diagutierrezro** [comment]
Buen trabajo David.
