### ISSUE TITLE
Generar documentación referente a X-Ray en python

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#147]
Se requiere realizar la documentación necesaria sobre como realizar la implementación de X-Ray en Apis de python y aparte una documentación detallada sobre el desarrollo realizado en la librería.

**Sub Tareas**

- [x] Realizar documentación sobre como implementar.
- [x] Realizar documentación sobre desarrollo realizado para la librería.
- [x] Documentar issue con documentos creados (cargar el link de one drive unicamente para lectura)

**Criterios de aceptación**

- [x] Documentación sobre como implementar realizada.
- [x] Documentación sobre desarrollo realizado, creada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se realiza la documentación sobre la implementación de X-Ray en Apis de python, el cual esta en el siguiente archivo:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jerodrigueza_udistrital_edu_co/EdBy-HjYS-xHjvtQpD0NR_oB-4R_UZyiYUmPiSQs_BjBOg?e=fBe3tS

Aparte el siguiente archivo detallada el código fuente de la librería con el SDK de X-Ray para python:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jerodrigueza_udistrital_edu_co/EcKnc0xmPrdNojLYW2ObiuABaWKbZqMEoZ0PA-8F8qYSVw?e=ae8vUJ

Nota: el archivo de la implementación lo termino el lunes en la mañana, debido a que me tomo un poco más de tiempo
