### ISSUE TITLE
Realizar ajustes visuales de paginación de tablas y visualización de organigramas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#148]
Se requiere realizar ajustes visuales en el cliente de Oikos, para esta issue el alcance será ajustar la paginación de las tablas y pulir la visualización de los organigramas.

**Sub Tareas**

- [x] Ajustar paginación de tablas, iniciar con la tabla de gestión de dependencias.
- [x] Pulir visualización de organigramas, revisar trazado de lineas y posibilidad de mapear hacia abajo las dependencias finales.
- [x] Documentar cambios realizados.

**Criterios de aceptación**

- [x] Paginación de tablas corregida.
- [x] Visualización de organigramas mejorada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Paginación 
Se han intentado diferentes métodos, sin logro alguno.

1. Se trata de que la tabla sea de tipo de angular material
![Image](https://github.com/user-attachments/assets/ed6a7036-174e-432d-abca-1ed289f114fc)

2. Se inicializa el paginator, y se establece como función de arranque del front el ngOnInit, ademas de que se inicializa el paginator en ngAfterViewInit
   ![Image](https://github.com/user-attachments/assets/442f647b-c7e5-461a-b4ae-d38999d5f7d3)
   Aun asi no se logra visualizar el cambio.

3. Actualización del paginar post cargar los datos de la tabla
   ![Image](https://github.com/user-attachments/assets/07dc0427-5797-4b4c-9feb-fd3dd788eafa)
   Se esta reasignando el paginador, sin éxito.

**Vista**
Se ve que no esta tomando ni la cantidad de elementos
![Image](https://github.com/user-attachments/assets/c399e099-096a-4304-8d80-da6eaa1547b4)

**Comment by xDa04vidx** [comment]
### Paginación
Con base en el cliente [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf), donde se utiliza el paginator, se encuentra el error, y es que se estaba actualizando el paginator de manera equivocada, se cambia a la manera correcta:
![Image](https://github.com/user-attachments/assets/4d950f03-3f3a-484d-b7b2-e5cd81549670)

Y se logra obtener una paginación correcta en el cliente
   **Para los primeros 5**
   ![Image](https://github.com/user-attachments/assets/21fd8744-c437-4f1c-8931-a9452a7b9e8f)

   **Para la pagina posterior**
   ![Image](https://github.com/user-attachments/assets/5ab6dcce-8f78-44d3-9674-7b5686cd76f0)

   **Para mostrar 10**
   ![Image](https://github.com/user-attachments/assets/96d09ae1-7b4f-4862-b309-492161ef239c)

**Comment by xDa04vidx** [comment]
### Organigrama

Se logra hacer que las lineas se muestren en el organigrama
![Image](https://github.com/user-attachments/assets/64eb0790-6dc5-4e79-83ba-1b6011f0baa5)

El cambio necesario para ello, se encuentra en los estilos del angular.json
![Image](https://github.com/user-attachments/assets/34137cce-ee32-4803-8421-d3bc210e4793)

**Problema**
Existen lineas de enlace (las verticales), que no se encuentran bien ajustadas, ademas de que se estan mostrando bordes de los nodos, que no se necesitan

**Comment by xDa04vidx** [comment]
### Se agrega la paginación en Mapeo

**Primera pagina**
![Image](https://github.com/user-attachments/assets/f7f1c5f1-7246-415c-8ae5-7007e90d5650)

**Segunda pagina**
![Image](https://github.com/user-attachments/assets/23d2b601-102c-47cc-8266-9648c04b3931)

**Con 10 resultados**
![Image](https://github.com/user-attachments/assets/57433ee9-b925-465d-866c-6b74eb6dbb33)

**Comment by diagutierrezro** [comment]
Muy bue trabajo David.
