### ISSUE TITLE
Revisar paleta de colores Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#149]
Se requiere realizar la revisión de la paleta de colores que se está manejando para el cliente de Oikos, esto teniendo en cuenta que actualmente se usa un rosado pero según los mockups y el requerimiento del cliente debe ser un vinotinto mas oscuro.

**Sub Tareas**

- [x] Ajustar paleta de colores en el cliente.
- [x] Documentar pruebas de cambios realizados.

**Criterios de aceptación**

- [x] Ajuste de paletas realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hace el cambio del color al vino tinto que ya tenian otras partes del proyecto:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/c99fb1a6-6e48-4b0b-8eca-2b00328ca7bc">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/50f61586-3352-4ce1-8da6-7d2badcf4e88">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/9f30e9ca-bd96-4256-a019-86d8893f0cc3">

No se colocan los estilos en el archivo general styles.css porque no reconoce los colores aun cuando se llama mediante la etiqueta html, nombre clase:

<img width="435" alt="image" src="https://github.com/user-attachments/assets/3f31efc1-2c65-400d-9fdd-ba6005bc0eb9">
<img width="950" alt="image" src="https://github.com/user-attachments/assets/d4913c0e-0361-4fb5-a1bc-7ac7ef30a516">

Entonces se cambian los colores desde los archivos especificos de cada componente.

**Comment by diagutierrezro** [comment]
Gran trabajo Julian, gracias.
