### ISSUE TITLE
Realizar la migración del código hacia el API de firma_electronica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#15]
Se requiere finalizar la migración de la lógica según lo analizado y adelantado en #14

**Sub Tareas**
- [x] Migración de la lógica de la firma electrónica. 
- [ ] Pruebas de funcionamiento realizadas de manera local.

**Criterios de aceptación**
- [x] Migración de lógica realizada.
- [ ] Documentación de pruebas realizadas en ambiente local.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
----- ACTUALIZACIÓN 15/05/24 --------

Con el líder de grupo se hizo un análisis de la situación respecto a las variables externas de gestor documental que eran necesarias en la nueva API para que esta pudiese funcionar. Se llegó a la conclusión que ciertas consultas y declaraciones que en un principio debían omitirse debían ser incluidas ya que de otra forma, no se encontró una manera de obtener dichas variables de forma externa. Por lo que se hace el traslado de esos fragmentos de código:

**Consulta GET inicial del ID y generación de variable res_json con la respuesta de dicha petición:**
![image](https://github.com/udistrital/core_documentacion/assets/77305100/9435d1ca-fe94-4274-ac90-0fff3034c761)

**Formateo en base 64 de archivo (No se contempla dentro de los requerimientos de las variables externas pero se llegó a la conclusión que debía ser agregado por cuestiones del flujo del proceso de firma electrónica):**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f8f44df1-113b-4b40-a6d7-81cfe1c7d70a)

**Creación inicial de DicPostDoc y Post inicial a Documentos CRUD y su respectiva respuesta (que luego es utilizada en firma electrónica)**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/bf8ac744-8b7b-4bcc-9318-d00ed21964c6)

Además la segunda definición de DicPostDoc se definió que debía reestructurarse para adaptarse a las necesidades de un nuevo método que se agregará a gestor documental, que permitirá realizar un put en la base de datos de documentos con lo la información que le envíe la API de firma electrónica. Este nuevo método fue autorizado en una reunión aclaratoria que tuvo el líder de grupo con la persona encargada de esto. 

Así pues queda pendiente definir los detalles de este nuevo método a implementar y la configuración del entorno de pruebas, a no ser que se encuentre algo adicional que agregar a la lógica de firma electrónica, el método quedaría de la siguiente manera:

`def postFirmaElectronica(body):
    try:
        data=body
        for i in range(len(data)):
            IdDocumento = data[i]['IdTipoDocumento']
            res = requests.get(str(os.environ['DOCUMENTOS_CRUD_URL'])+'/tipo_documento/'+str(IdDocumento))
            
            if res.status_code != 200:
                return Response(json.dumps({'Status':'404','Error': str("the id "+str(data[i]['IdTipoDocumento'])+" does not exist in documents_crud")}), status=404, mimetype='application/json')

            res_json = json.loads(res.content.decode('utf8').replace("'", '"'))

            blob = base64.b64decode(data[i]['file'])
            with open(os.path.expanduser('./documents/documentToSign.pdf'), 'wb') as fout:
                fout.write(blob)

            jsonFirmantes = {
                    "firmantes": data[i]["firmantes"],
                    "representantes": data[i]["representantes"],
            }

            DicPostDoc = {
                'Metadatos': all_metadata,
                'Nombre': data[i]['nombre'],
                "Descripcion": data[i]['descripcion'],
                'TipoDocumento':  res_json,
                'Activo': True
            }
            resPost = requests.post(str(os.environ['DOCUMENTOS_CRUD_URL'])+'/documento', json=DicPostDoc).content
            responsePostDoc = json.loads(resPost.decode('utf8').replace("'", '"'))

            firma_electronica = firmar(str(data[i]['file']))

            electronicSign = ElectronicSign()
            firma_completa = electronicSign.firmaCompleta(firma_electronica["llaves"]["firma"], responsePostDoc["Id"])
            objFirmaElectronica = {
                "Activo": True,
                "CodigoAutenticidad": firma_electronica["codigo_autenticidad"],
                "FirmaEncriptada": firma_completa,
                "Firmantes": json.dumps(jsonFirmantes),
                "Llaves": json.dumps(firma_electronica["llaves"]),
            }
            reqPostFirma = requests.post(str(os.environ['DOCUMENTOS_CRUD_URL'])+'/firma_electronica', json=objFirmaElectronica).content
            responsePostFirma = json.loads(reqPostFirma.decode('utf8').replace("'", '"'))
            datos = {
                "firma": responsePostFirma["Id"],
                "firmantes": data[i]["firmantes"],
                "representantes": data[i]["representantes"],
                "tipo_documento": res_json["Nombre"],
            }

            electronicSign.estamparFirmaElectronica(datos)
            jsonStringFirmantes = {
                "firmantes": json.dumps(data[i]["firmantes"]),
                "representantes": json.dumps(data[i]["representantes"])
            }

            all_metadata = str({** firma_electronica, ** data[i]['metadatos'],  ** jsonStringFirmantes}).replace("{'", '{\\"').replace("': '", '\\":\\"').replace("': ", '\\":').replace(", '", ',\\"').replace("',", '",').replace('",' , '\\",').replace("'}", '\\"}').replace('\\"', '\"').replace("[", "").replace("]", "").replace('"{', '{').replace('}"', '}').replace(": ", ":").replace(", ", ",").replace("[", "").replace("]", "").replace("},{", ",")

            DicPostDoc = {
                'Metadatos': all_metadata,
                "firmantes": data[i]["firmantes"],
                "representantes": data[i]["representantes"],
                'Nombre': data[i]['nombre'],
                "Descripcion": data[i]['descripcion'],
                'TipoDocumento' :  res_json,
                'Activo': True
            }
`

**Comment by Skyrus1203** [comment]
--- ACTUALIZACION 17/05/24 ---

Se sube al repositorio primer commit del API firma electrónica:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/9476bd08-e911-40f4-a31a-0d0d076aecce)

**Comment by Skyrus1203** [comment]
Las pruebas no se llevaron a cabo ya que, como parte de los requerimientos se especificó que la firma electrónica estuviese desacoplada de gestor documenta, a lo largo del análisis se llegó a la conclusión de que se debía crear un nuevo método en gestor documental para poder poner en funcionamiento la API nueva de firma electrónica, por lo tanto las pruebas se llevarán a cabo en cuanto se complete esta nueva funcionalidad

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 20/05/24 ###

Antes de crear las ramas y continuar con el desarrollo siguiendo los lineamientos de la oficina, se considera pertinente modificar la estructura del enrutamiento de la nueva API de firma electrónica para que esta se adapte y exista una uniformidad en cuanto a la estructura y lineamientos con los que gestor_documental_mid está construido. Por lo tanto, para ello se usan las bibliotecas flask_restx y flask_cors para modificar el enrutamiento de direcciones de la nueva API. En consecuencia se elimina el uso de Flask_swagger_ui y el swagger.json respectivo. **Cabe recalcar que todos los cambios mencionados aún se encuentran en local**.

Se crea un nuevo archivo en la carpeta "models" cuyo nombre es "model_params.py" el cual nos servirá para definir la estructura del json que enviaremos a la función de firma electrónica para realizar dicho proceso, dicho archivo contiene el siguiente código que se readaptó del model_params de gestor documental omitiendo el código innecesario para que pudiese ser utilizado con el único propósito de limitarse a la definición de modelos del método de firma electrónica:

![Image](https://github.com/udistrital/core_documentacion/assets/77305100/1533e525-a625-4c95-85c6-3f9fc8a3e028)

En "router.py" se agregó que la url de la API tuviese un "v1" para adaptarse a los lineamientos, además de ello se crearon nuevos controladores para el enrutamiento, con el propósito de que se pudiese construir el swagger a partir del código mismo sin tener que construirlo manualmente desde cero:

![Image](https://github.com/udistrital/core_documentacion/assets/77305100/4acff089-4563-4c8c-8570-3daf41b92954)

Se evidencia por tanto una reducción de esfuerzo y un aumento de escalabilidad en este aspecto.

Ahora bien, con estos nuevos controladores de enrutamiento, el archivo de model_params y el uso de CORS se procede a construir el nuevo enrutamiento al método de firma_electronica:

![Image](https://github.com/udistrital/core_documentacion/assets/77305100/8d99bf42-51e7-4352-a420-b0325d0db8a9)

Sin embargo se presentó un error al momento de levantar el servicio:

![Image](https://github.com/udistrital/core_documentacion/assets/77305100/b62f67b6-0b88-430f-b769-705385eb693d)

Queda pendiente la resolución de dicho error, para poder realizar el respectivo commit de los cambios y una vez estén dichas modificaciones en el repositorio, las cuales implementan mejor los lineamientos utilizados en gestor_documental y mejoran la actualización del swagger, se procederá a la creación de las diferentes ramas y a la construcción del nuevo método de gestor_documental.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 21/05/24 ###

Se corrige el error mencionado en el comentario anterior, completando así la reestructuración de la API dejándola lista para posteriores desarrollos y pruebas. Se subió a Master estos cambios como se muestra a continuación:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/121a2cd7-d48f-476a-8c9e-5ef671c55640)

Además de ello se creó la rama Develop y la rama Feature/Migracion_logica_firma_electronica_inicial
