### ISSUE TITLE
Ajustar vista para creación y edición de mapeo de dependencias - parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#150]
Se requiere realizar la continuación para ajustar las vistas de creación y edición de mapeos de dependencias que se inició en #138 y #141, para este issue se requiere la implementación del endpoint, se debe solicitar a Jhon la revisión del error CORS, una vez se haga esta implementación se finalizará la implementación de la logica y pruebas de funcionamiento.

**Dependencias**
Para la solución satisfactoria del issue se requiere que el error generado en los endpoints sea solucionado lo mas pronto posible

**Sub Tareas**

- [x] Implementar endpoints para registro y edición de mapeo de dependencias.
- [x] Realizar ajustes código realizado para garantizar el funcionamiento del desarrollo realizado.
- [x] Pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Implementación de endpoints realiazada.
- [x] Ajustes al código realizados.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realiazada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 10/09/24

Se especifican problemas de cors y se envía información de como se están implementando endpoints al ingeniero Jhon para que pueda revisar mejor el error que resulta al consultar cualquiera de los endpoints

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 11/09/24

Habiendo recibido notificación del Ingeniero Jhon para probar de nuevo los endpoints se realizaron pruebas nuevamente, sin embargo surgió otro error:

![Captura de pantalla 2024-09-11 194848](https://github.com/user-attachments/assets/75688bf7-bf7f-4732-8adc-070db99b40d7)

Al parecer la API no puede soportar respuestas con XML, siendo que las cabeceras de la petición son las siguientes:


![Captura de pantalla 2024-09-11 153514](https://github.com/user-attachments/assets/1595e301-f032-40af-b058-ecc47185f668)

Por lo tanto se intenta ajustar las caberas en el request manager de manera que la API sea forzada a responder con un JSON, cosa que primero se probó en postman y se logró forzar correctamente la respuesta como JSON:

![Captura de pantalla 2024-09-11 194237](https://github.com/user-attachments/assets/d4f2d3c5-70c5-425a-81f2-ba87dc908399)

![Captura de pantalla 2024-09-11 194925](https://github.com/user-attachments/assets/41c4b923-b037-4cd9-aec2-6a671ea95a9c)

Sin embargo al probarlo en la API se obtiene el mismo error. Pero se comprobó que las cabeceras eran afectadas exitosamente:

![Captura de pantalla 2024-09-11 165811](https://github.com/user-attachments/assets/fc680bc2-6564-433a-9860-909e5c5b1fa8)
![Captura de pantalla 2024-09-11 173630](https://github.com/user-attachments/assets/6f2cee63-098c-40d1-8d0e-d6e118617250)

Por lo que se intentó otra aproximación permitiendo que la API recibiese cualquier respuesta e internamente se manejaría una lógica que permitiera tramitar la respuesta dependiendo del tipo, si era JSON la retornaba directamente, si era un XML se pasaba a JSON y se devolvía:

![Captura de pantalla 2024-09-11 192516](https://github.com/user-attachments/assets/998bd355-4084-4b66-96e1-bad59d18b83e)
![Captura de pantalla 2024-09-11 192307](https://github.com/user-attachments/assets/e5134f98-235c-44ba-9d0d-80381b8a969d)
![Captura de pantalla 2024-09-11 192323](https://github.com/user-attachments/assets/2a6f4a6f-0d41-47d4-bb68-1fcd686da8f2)
![Captura de pantalla 2024-09-11 192501](https://github.com/user-attachments/assets/c0b1adc8-72e6-4c44-9d47-dfdb1d4984df)

Y ahora a pesar de no recibir el mismo error de formato inicial se sigue recibiendo un error:

![Captura de pantalla 2024-09-11 192040](https://github.com/user-attachments/assets/10c4f89b-2c56-4f5d-9d8e-e5bccc3f9921)

Finalmente realizando la documentación, se descubrió que el xml que retornaban los endpoints no incluía la información solicitada, sino uno en el que el contenido era un Hash:

![Captura de pantalla 2024-09-11 195010](https://github.com/user-attachments/assets/cbabfb30-6b25-4585-b1ee-ed6a31bda23e)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 12/09/24

EL líder de grupo logró corregir el error presentado el día de ayer por lo que se procedió a realizar los ajustes necesarios.

Primero se logró hacer funcionar el get para precargar los datos de las dependencias en el formulario de mapeo:

![image](https://github.com/user-attachments/assets/27b03fc1-f0b9-46f5-816d-bfb0bc28e5c5)
![image](https://github.com/user-attachments/assets/0690685d-f008-4143-8b9c-6a84e2f17130)

Luego se pasó a probar el post para generar el mapeo de dependencias y se detectó que enviaba un error 500. Al probar en postman se determinó que habían variables que no estaban en el formato correcto a pesar de seguir las indicaciones del ingeniero Jhon, por lo que se hicieron ajustes al JSON que se envía y mediante pruebas en postman se logró encontrar el formato correcto:

**Formato del ingeniero Jhon**(enviaba error):
![Captura de pantalla 2024-09-12 194731](https://github.com/user-attachments/assets/9faeb86f-44a3-44c1-b963-793f45cd7bc2)

**Formato Corregido**:

![Captura de pantalla 2024-09-12 194736](https://github.com/user-attachments/assets/e40ec95b-e9c3-4ade-9ab2-1a9a440405ff)


Realizando una prueba en post man resulta correcta (manda un error de llave primaria duplicada ya que se está tratando de crear un mapeo con un id ya existente):

![image](https://github.com/user-attachments/assets/6fdc3d35-c329-4fbd-a636-a89752020703)

Sin embargo al intentar con un id aparentemente nuevo, tanto en el navegador como en post man arrojan un error de tiem out luego de un tiempo en el que la solicitud se intenta procesar:

![Captura de pantalla 2024-09-12 195209](https://github.com/user-attachments/assets/4054fa60-3c65-425a-9235-05723be9bb86)

![Captura de pantalla 2024-09-12 195434](https://github.com/user-attachments/assets/fbc371b0-c2b2-4f32-a04a-60f0ce9bf8f5)


Por su parte el put, siguiendo con la estructura indicada por el ingeniero Jhon:

![image](https://github.com/user-attachments/assets/2a83488f-251d-4644-9d9f-4475d805ced5)

Se realizan pruebas para la edición de dependencias sin embargo esta vez el error es que al parecer el endpoint no está registrado:


![Captura de pantalla 2024-09-12 202831](https://github.com/user-attachments/assets/51dbaed4-2169-45c7-afaf-f71f9aebf6b0)
![Captura de pantalla 2024-09-12 202841](https://github.com/user-attachments/assets/871a6246-9a9e-4655-84ec-05b70fe3f922)

Por lo tanto queda pendiente la revisión de las posibles causas y su respectiva solución de estos detalles

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/09/24

Se informa al ingeniero Jhon de los problemas presentados el día anterior. Él realiza unas correcciones a los endpoints para ser probados y estos ya quedaron funcionales. Por lo tanto se termina de ajustar el módulo de mapeo de dependencias quedando funcionales la generación y edición de mapeo de dependencias.

Para esto se tuvo que realizar algunos cambios, primero sobre los objetos que se envían que cambiaron de nombre:

![image](https://github.com/user-attachments/assets/2f3f5293-bbd0-40ab-9409-2f6b14475f20)

Segundo se tuvo que cambiar la validación con la que se determinaba si la consulta había sido exitosa, ya que la respuesta de ambos endpoints es la siguiente (como ejemplo):

`{
  "mapeo_dependencias": {
    "id_master": "724"
  }
}`

En consecuencia la validación quedó de la siguiente manera:

![image](https://github.com/user-attachments/assets/a3c65adf-60b7-4bba-ba85-ffe8045ffac9)

Por lo tanto se procede a demostrar el correcto funcionamiento de ambos endpoints.

**Para la generación de dependencias:**

En primera instancia al hacer click en la generación de dependencias se muestra la ventana sin precargar datos salvo el nombre de la dependencia:

![image](https://github.com/user-attachments/assets/11734f31-77e0-47e6-a8a2-af3d9aa9f811)

Posteriormente se llena con estos datos:

![image](https://github.com/user-attachments/assets/5c75ae59-150e-4322-8531-283376a08778)


La operación es exitosa:

![image](https://github.com/user-attachments/assets/b7273129-cf86-4b95-90ac-2bed043e929e)


Para comprobarlo, por postman realizamos un get para verificar que el registro haya sido creado:

![image](https://github.com/user-attachments/assets/afa562f2-3e6b-46ac-a5bc-05b8d11fb377)

En caso de un error (en este caso tratar de crear una dependencia con un id ya usado) muestra el error:

![image](https://github.com/user-attachments/assets/19b308a4-1e75-43e1-bd72-0381f292d27f)


![image](https://github.com/user-attachments/assets/a432d8cf-1f72-4d26-a6e5-b30f0e621496)


**Para la Edición de dependencias:**

En primera instancia al hacer click en la ediciójn de dependencias se muestra la ventana precargando los datos que estén disponibles de la dependencia:

![image](https://github.com/user-attachments/assets/e03796c2-fda5-47e8-b4b1-68f4a876eecd)

Cambiando los valores de SNIES e Iris de la siguiente forma realizamos la prueba:

![image](https://github.com/user-attachments/assets/835b83b9-5670-49ff-95c9-0c65130b661b)

La operación es exitosa:

![image](https://github.com/user-attachments/assets/efcfa5bd-bad6-4a39-85f1-903f0e3464cd)

Comprobamos por postman:

![image](https://github.com/user-attachments/assets/a63d2ed9-e6a7-4d96-bfd4-0c3dd0b278b8)


Al ocurrir un error se muestra correctamente (en este caso tratando de editar una dependencia sin llenar los campos):

![image](https://github.com/user-attachments/assets/f62331ec-d834-457b-996c-ede2072e44e7)

Por lo tanto se deja el issue en in review
