### ISSUE TITLE
Concertar, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#151]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente OIKOS

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se espera a que el arquitecto termine un endpoint para poder terminar cosas del cliente  se espera que pronto se termine ese ajuste para realizar la reunión

**Comment by jcmurilloa** [comment]
Se traslada la issue al siguiente sprint, al reunir los elementos requeridos para concertar la reunión.

**Comment by mantnicot** [comment]
Se ha agendado la reunión con el cliente para el día 18/09/2024 a las 02:00 pm

[Link de reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODFjYjhhZmQtZjNhMC00MmY3LWJhZjktYjVjOTQ1MDIzMmE5%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha generado el acta de la reunión

[acta reunión sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EewXulFY5ahBm1zDLBM35uwBRFuKpxkhnEB3O0O1wcPH_Q?e=jLwHR9)

**Comment by jcmurilloa** [comment]
Muy buen trabajo, estarremos atentos a la recolección de firmas.

**Comment by mantnicot** [comment]
Se ah recolectado la firmas

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EcuZv6PV_QNAv4B3PhwstJ4B94mruvNrJ2gUjswiV1Wrrw?e=Dwluaw)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
