### ISSUE TITLE
Construir documentación para socialización e implementación de firma electrónica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#152]
Se requiere realizar la construcción de la documentación para socialización de firma electrónica dirigida al consejo académico y usuarios en general

**Sub Tareas**

- [x] Generar la investigación corresponiente, partiendo del documento https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQkXilD7tLRIvlANrDKuA3kBywPvUBzLkjKDm-w01rQMtw?e=RPOapc
- [x] Actualizar y complementar la documentación relacionada
- [x] Exponer el documento final al equipo SoS
- [x] Proyectar una presentación relacionada

**Criterios de aceptación**

- [x] Documentación aprobada equipo SoS
- [x] Presentación documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se agrega el documento de socialización de firma para planeación y comité.

[Documentos de base](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErQeMf_AHBxHrogLTf5RGgcBUs4MB_FArVCqAXxu_2l5rQ?e=l96FBo)

Se tomo en cuenta la información de implementación y la información previamente investigada y se intento resumir los procesos de firma para el fácil entendimiento del comité


[Documento para comité ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYHLqgzvWAFHraEFd9Iib_wBhaj_wGJYk-ouUrW8VnIHeQ?e=5ULw07)

**Comment by jcmurilloa** [comment]
Muy buen documento el estructurado @mantnicot, por favor articular con el responsable para recoger recomendaciones si es el caso.
