### ISSUE TITLE
Socializar cliente de oikos con el usuario

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#153]
Se requiere realizar la socialización del cliente de Oikos (Jhon Castellanos) para obtener retroalimentación en el desarrollo realizado.

**Sub Tareas**

- [x] Socialización con el usuario.

**Criterios de aceptación**

- [x] Reunión con el usuario realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Reunión
Con ayuda del analista @mantnicot , se logra pactar la reunión el día 18/09/2024 a las 2 pm
![Image](https://github.com/user-attachments/assets/5aa577ab-a19f-4fd5-a988-8580b17f4808)

**Comment by xDa04vidx** [comment]
### Grabación de la reunión
https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/Oikos%20-%20Muestra%20Avances%20Cliente-20240918_140308-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=E1RfUC&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D
