### ISSUE TITLE
Estabilizar entorno de desarrollo para cliente de Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#154]
Se requiere realizar la estabilización del entorno de desarrollo local para poder ejecutar el cliente de Oikos, para esto se solicita colaboración de @xDa04vidx para que haga de guía en esta tarea.

**Sub Tareas**

- [x] Estabilizar entorno de desarrollo

**Criterios de aceptación**

- [x] Estabilización realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Con la guía @xDa04vidx se logro la estabilización en mi entorno de desarrollo para el cliente de Oikos:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/45775505-31b8-4f46-bfd1-003693869544">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/5e5eef1a-15ad-4692-8f20-ea65558cbefc">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/66e53dcb-1c8a-422a-be11-a0a4f94ff0c1">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/13c70335-1148-487b-ac57-12f50ff91ea4">
