### ISSUE TITLE
Ajustar botones de activar y desactivar dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#155]
Se requiere realizar el ajuste de los botones para activar y desactivar dependencias en la vista de gestión dependencias ya que actualmente estos botones no cuentan con funcionalidad.

**Sub Tareas**

- [x] Funcionalidad de activar y desactivar desarrollada.
- [x] Pruebas de funcionamiento realizadas.

**Criterios de aceptación**

- [x] Funcionalidad desarrollada.
- [x] Pruebsa realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
No se logran terminar las pruebas, porque muestra un error cuando se actualiza la información, tanto del código fuente como mediante postman:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/a4685e98-99cb-4fc0-bbc3-8f2875b28523">

<img width="676" alt="image" src="https://github.com/user-attachments/assets/0f3b455a-8ef1-468d-a58f-863e2f614841">

**Comment by diagutierrezro** [comment]
El error puede deberse a los headers que se envian en la petición, pendiente para revisar

**Comment by JulianAvella** [comment]
Haciendo la petición en postman, con la información en formato json y colocando el token como bearer token, funciona y hace la actualización: 
<img width="676" alt="image" src="https://github.com/user-attachments/assets/84453ac9-9511-4294-aa0a-c2963547d098">
Pero haciendolo desde el código genera el error:
<img width="334" alt="image" src="https://github.com/user-attachments/assets/1597586b-94d7-43b5-b3ae-c3a7c2809beb">
Se busca como solucionar este error

**Comment by JulianAvella** [comment]
Se muestra que esta activa el registro:
<img width="956" alt="image" src="https://github.com/user-attachments/assets/58a8e6de-585d-4162-92b3-272d03cf5c2b">
Se da clic en la opción de desactivar el registro "en la equis":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/587c7707-6fe3-4c13-99a0-8bd1728b4ca9">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d1d5ef1a-607c-473a-a7d0-5431b525e40f">
En postman se verifica que se haya actualizado el registro en el campo "Activo" a "false" que sería "NO ACTIVA":
<img width="674" alt="image" src="https://github.com/user-attachments/assets/33a5d258-3e72-4dfc-a840-5c63b12c9e0c">
Ahora que esta desactivada, se da clic en la opción de activar el registro "en la chulo":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d8ff2411-fbe7-4667-aac2-cb8fa6696ff3">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/7eee6090-b3e6-46a2-8770-a2901af017de">
En postman se verifica que se haya actualizado el registro en el campo "Activo" a "true" que sería "ACTIVA":
<img width="673" alt="image" src="https://github.com/user-attachments/assets/18dd504c-fcf6-4318-8877-c8bb746f3d0e">

**Comment by JulianAvella** [comment]
Se hace el commit al repositorio en github, en la rama feature/color:
<img width="552" alt="image" src="https://github.com/user-attachments/assets/cc9c5cef-d73e-4bab-b8c4-64dc1f41dbb8">
