### ISSUE TITLE
Agregar loader en vista de organigramas y tabla de edición y mapeo de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#156]
Se requiere realizar el desarrollo para cargar un loader que se muestre hasta que se finalice la carga de la información de los organigramas de las dependencias ya que actualmente el usuario no tendría como saber que esta carga se está haciendo y se puede interpretar como un bloqueo del sistema. Tambien se debe mostrar el loader despues de actualizar una dependencia y que el pop up no se cierre automaticamente.

**Sub Tareas**

- [x] Desarrollar vista de loader hasta cargue de organigramas.
- [x] Desarrollar vista de loader en tabla de edición de dependencias.
- [x] Desarrollar vista de loader en tabla de mapeo de dependencias.
- [x] Configurar pop ups para que no se cierren automaticamente.
- [x] Prueba de funcionamiento correcto

**Criterios de aceptación**

- [x] Desarrollo de loader realizado.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se agrega loader en búsqueda 

**Gestión**

- Carga
  ![Image](https://github.com/user-attachments/assets/b3fba1fd-8d0b-4ef9-b800-01301df90550)

- Finalización con éxito 
   ![Image](https://github.com/user-attachments/assets/09a4ca94-945c-4042-a149-2a53270eded9)

- Finalización con error
   ![Image](https://github.com/user-attachments/assets/d693960e-2eac-4008-9afa-1b2aac49651d)

**Mapeo**

- Carga
  ![Image](https://github.com/user-attachments/assets/d1b25052-d9c8-49b1-b3e4-f95a52cf69ee)

- Finalización con éxito 
   ![Image](https://github.com/user-attachments/assets/51c347ff-c5e1-4eec-a79b-1a5a623a9da5)

- Finalización con error
   ![Image](https://github.com/user-attachments/assets/5db25ac5-2a58-4d6d-aef2-2220649f5e96)

**Comment by xDa04vidx** [comment]
**Organigrama**

- Carga
   ![Image](https://github.com/user-attachments/assets/9414c0bc-61ee-4bb1-84db-6ddba75a4b22)

- Finalización con exito
  ![Image](https://github.com/user-attachments/assets/8e589b22-cd86-4abe-b7d3-fb3546a21bdb)

- Finalizacion con error
  ![Image](https://github.com/user-attachments/assets/bccc40b6-c2e2-40af-a030-45cbb7d39864)

**Comment by xDa04vidx** [comment]
### Pull request
Se realizan dos pull request

1. En [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/4e2dae1b-bb2b-4b67-af09-349ab79e11fb)

2. En [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)
![Image](https://github.com/user-attachments/assets/1d83b76b-f4c9-4e9a-ad22-092a5278057b)
