### ISSUE TITLE
Realizar analisis de cambios a realizar en firma electrónica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#157]
Se requiere realizar un analisis tecnico de los cambios a realizar según lo acordado en la reunión para multiples firmantes. Se requiere agregar dos nuevos endpoints que realicen estampa de firma, una estampa unicamente registrará el firmante, representante (en caso de existir), fecha y hora de firma; el otro endpoint tambien realizará estampa de firma pero este si realizará la logica de la firma electrónica ya que será el último firmante de la lógica, revisar que no se vea afectado el endpoint de firma actual y revisar si se puede reutilizar código existente.

**Sub Tareas**

- [x] Realizar documento analizando los cambios a realizar.

**Criterios de aceptación**

- [x] Documento realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 12/09/24

Se realiza el documento técnico y se adjunta el enlace al drive para su revisión.

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/EVBgCPX1kEZFpGpPEdgkU5YB5buCUbdJpf5Ahvf1a-hfyA?e=KBp4Pz

Se coloca el issue en in review para que se verifique su contenido y en caso de que sea el correcto, se le dé el visto bueno

**Comment by diagutierrezro** [comment]
La implementación se iniciará en otros issues, buen trabajo Andres.
