### ISSUE TITLE
Crear endpoint para estampa de firma (sin firma electronica)

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#158]
Se requiere realizar el desarrollo para estampar la firma (sin realizar el proceso de firma electronica) donde se estampe en los documentos el firmante, representante junto con fecha y hora de la firma.

**Sub Tareas**

- [x] Desarrollar estampa de firma inicial o posteriores.
- [x] Probar funcionamiento del desarrollo realizado.

**Criterios de aceptación**

- [x] Desarrollo realizado.
- [x] Pruebas de funcionamiento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/09/24

Se inicia el proceso de implementación de los nuevos endpoints de firma electrónica:

Primero se agregan a Routers dos endpoints (uno de firma múltiple inicial y otro final), los cuales respectivamente se encargarán de estampar sólo los datos:

![image](https://github.com/user-attachments/assets/1ed56d40-7e44-4567-b69e-37de22441736)

![image](https://github.com/user-attachments/assets/2aaa3bb3-1d8f-4194-8010-bc869d95d6fc)

También se dejan esqueletos de nuevos métodos separados en controller firma:

![image](https://github.com/user-attachments/assets/ed5d0367-94cc-4936-8738-21ee034cf455)

![image](https://github.com/user-attachments/assets/709e5b15-6397-4f27-9656-88132b581433)

Además de dejar también esqueletos para los métodos de estampa:

![image](https://github.com/user-attachments/assets/db66954e-e15a-426f-8c02-50711f7ec7c2)


Sin embargo realizando los esqueletos y analizando mejor el flujo, se propone una alternativa que no implica creación de nuevos endpoints, si no que consiste de la inclusión de tres parámetros en el json que recibe firma electrónica, parámetros los cuales serán booleanos y se encargarán de indicarle al método en qué etapa de la firma se encuentra (Primera firma, firma intermedia o firma final) o bien si se trata de una firma única. Esto con el propósito de evitar la mayor cantidad de redundancia de código posible, facilitar la implementación en otros sistemas y manejar internamente por medio de condicionales el código que debe ejecutarse en determinada situación o no. Puede que de todas formas, por ejemplo para la parte de estampado se deban crear métodos a parte, sin embargo mi propuesta busca evitar la creación de endpoints o métodos que puedan llegar a ser innecesarios o bien para facilitar su futura implementación. A continuación se adjunta un diagrama de flujo explicando el funcionamiento que podría tener esto:

![Diagrama flujo nuevos firmantes](https://github.com/user-attachments/assets/fd79c44b-7cf8-492f-9c29-074052cf1771)

Por el momento se dejan los endpoints y esqueletos de nuevos métodos en el código, y se solicita a @diagutierrezro la revisión de la propuesta para verificar su viabilidad para que dé el visto bueno o de lo contrario continuar con la implementación que se tenía originalmente pensada

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 17/09/24

Debido a un análisis mejor sobre lo propuesto el día anterior se determinó realizar un híbrido entre lo originalmente planeado y la propuesta desarrollada el día de ayer: Se crearía un único endpoint adicional que se encargaría de manejar cada una de las etapas por medio de condicionales.

Así se readaptó el Router.py para manejar un único endpoint:

![image](https://github.com/user-attachments/assets/0e90d85f-726e-4c87-ace9-663e6046ebaa)

Para este propósito se creó un nuevo modelo en el cual se agrega la clave valor **etapa_firma**:

![image](https://github.com/user-attachments/assets/0d133f6d-391e-4ad4-9f35-c6eb9e236db7)

Así en el swagger se ve de la siguiente manera:

![image](https://github.com/user-attachments/assets/ed304098-f7a2-4805-9789-a1bc5bb2c3df)

Así mismo en controllerFirma se deja un único método para manejar el procedimiento de múltiples firmantes:

![image](https://github.com/user-attachments/assets/dd96a35a-d4b5-4889-af6a-a39a0ba66393)

Por el momento en este método se realiza todo el proceso hasta la estampa, es decir no se realiza el hash ni se sube a nuxeo.

Para la estampa se agrega al json que se envía el campo "tipo_firma" que permitirá que en el modelo de firma_electronica saber qué texto estampar:

![image](https://github.com/user-attachments/assets/38dd8028-b4b3-466a-baf4-3c2d7c8b4326)

En el modelo de firma electrónica se dejó un único signature alternativo:

![image](https://github.com/user-attachments/assets/e24f2b5a-415f-41af-b5bd-96510dc5055d)


Así en estamparFirmaElectronica se realizará una comprobación para determinar si se trata de una estampa común o una estampa dinámica:

![image](https://github.com/user-attachments/assets/820a544c-0048-4296-9c40-e576d734f107)

Dentro de la signature_alter por ahora sólo se diferenciará entre una firma inicial y una intermedia de modo que si es inicial imprimirá el título "**Firmado Digitalmente**":

![image](https://github.com/user-attachments/assets/1e1b91b5-0d8c-4d3d-a71c-8af5c4a30838)

Así se realizan pruebas en postman:

Primero se realizará una firma inicial, nótese que en la clave "**etapa_firma**" se coloca como valor "inicial":

![image](https://github.com/user-attachments/assets/6212e94a-4446-46c2-905d-9be0c73f5449)

Como resultado se tiene lo siguiente:

![image](https://github.com/user-attachments/assets/b7de81eb-a0ae-4f68-bdb9-d764ec18674c)

Posteriormente se realiza la prueba de una firma intermedia, nótese que en la clave "**etapa_firma**" se coloca como valor "intermedia":

![image](https://github.com/user-attachments/assets/c0a7b2a1-3fbe-46e6-aa84-4284b9c9a0f5)

Con el siguiente resultado:

![image](https://github.com/user-attachments/assets/fa123fcc-b122-449b-bf39-2f5e85d63723)

Aún no se ha ajustado totalmente ya que aún se tienen que pulir muchos aspectos, pero la funcionalidad básica se logró desarrollar y las pruebas salieron correctas.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/09/24

Se crea lógica para desarrollar la firma final (Aún no se sube a Nuxeo, sólamente se ha probado la estampa), siendo que por medio de un If se comprobará si la firma electrónica se encuentra en una etapa final para estampar el código de verificación el tipo de documento y el enlace de verificación:

![image](https://github.com/user-attachments/assets/b27074b8-3765-497d-a783-df68b87cbe6d)


Por lo tanto en postman se envía el documento en la etapa que se había dejado el día anterior con la clave etapa_firma con un valor de "final":

![image](https://github.com/user-attachments/assets/74575902-dd60-457d-9162-346b0ed2b471)


Como resultado el documento estampa correctamente la etapa final de la firma con el firmante enviado:

![image](https://github.com/user-attachments/assets/1f39d068-9e23-4d7e-bdf5-266875e460f6)

Siendo así, se pasan a desarrollar ajustes en el espaciado y distribución de las diferentes estampas en las etapas, además de que se debe puntualizar de que en cada etapa de firma el sistema verifica si hay espacio suficiente así que por el momento puede suceder que la firma si es muy larga se distribuya entre dos páginas distintas.

Además de ello queda pendiente la implementación de la lógica de subida a nuxeo para las diferentes etapas y la implementación de hash para la última etapa

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 19/09/24

Se ajusta modelo y lógica para que la clave valor que se encarga de identificar la etapa de la firma sea un entero en vez de una cadena:

![image](https://github.com/user-attachments/assets/725152f9-d616-4174-921b-5d500e0a2c23)

Así mismo se crean condicionales para gestionar la lógica posterior a la estampa, dejando todo lo concerniente al hash y la generación de registros en la tabla de firma electrónica para la última etapa de la firma múltiple:

![image](https://github.com/user-attachments/assets/2927c9eb-a6cb-4559-bcba-a79ae7ddcb23)
![image](https://github.com/user-attachments/assets/5837b485-f240-4065-a3b2-e0ab1aac0f20)

También se hicieron ajustes como la creación del arreglo de datos dependiendo de la etapa mostrada en anteriores capturas y la adición de la verificación dentro del estampado sobre la utilización de la variable de firma que ahora sólo será enviada a la estampa en la última etapa:

![image](https://github.com/user-attachments/assets/95916f95-d432-4557-8a72-777b50c0fa6e)

Así en todas las etapas se realizará la subida a nuxeo pero sólo en la última se realizará el hash y la creación de registros en la tabla de firma electrónica.

También se acordó con el lider que para mantener una consistencia en los registros que se ingresarán a la tabla firma electrónica en cuanto a firmantes y representantes, en la última etapa de la firma se enviará el firmante y representante a estampar común y corriente, y en los metadatos se enviarán todos los firmantes y representantes del proceso (incluyendo el que se envía actualmente) para ser guardado en la base de datos.

Por tanto queda pendiente corregir el espaciado de la estampa en lo cual ya se está trabajando, implementar la lógica de extracción de firmantes de los metadatos y realizar las pruebas de la funcionalidad completa del nuevo endpoint
