### ISSUE TITLE
Generar la investigación sobre roles en el sistema urano para generar alternativas de caducidad

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#159]
Se requiere realizar una investigación sobre roles en el sistema urano para generar alternativas de caducidad 

**Sub Tareas**

- [x] Realizar investigación en el sistema y sus respectivos roles
- [x] Documentar en el issue las opciones encontradas.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido generar un primer acercamiento a Milton la persona encargada de urano y comenta que varios roles del sistema se generan la caducidad con base a sus contratos y novedades de los mismos.


- Tambien cuenta que ya tiene un sistema de caudicad de roles el sistema , el cual se coloca la fecha limite para eso.
- Para las personas de planta se deben dar fin cuando termine el contrato
- los docente de catedra deben dar fin una vez que tengan dos semestres sin carga academica
- Los estudiantes tienen un cambio de rol cuando se graduan a "egresados" por lo cual el rol anterior pereze

por lo cual se comiensara a revisar en ese sistema como se gestionara los procesos para darle caducidad a los contrato de planta y docentes de catedra.

**Comment by jcmurilloa** [comment]
Es un buen comienzo de investigación, la información que se vaya recopilando por favor generar la respectiva documentación.

**Comment by jcmurilloa** [comment]
Pendiente construcción de documento y archivo.

**Comment by mantnicot** [comment]
Se establece el documento del nuevo requerimiento

[Documento caducidad URANO](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYqgXS0FdGNNijYQu4xjtFMBprUAE3pBlT7_nDyfp1awkA?e=TLG2Ll)

**Comment by jcmurilloa** [comment]
Investigación documentada @mantnicot, buen trabajo!
