### ISSUE TITLE
Terminar la instrumentalización de las APIs

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#16]
Se requiere realizar la continuación de la instrumentalización de APIs pendientes con XRAY, teniendo en cuenta lo registrado en el [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYHrM0PC9JtMlfe_H5zx6CYBFFLf-JfqULxErrmsDEODSg?e=1wQbaP) para la semana 1

**Sub Tareas**
- [x] Instrumentalización de APIS definidas
- [x] Documentación de instrumentalización realizada

**Criterios de aceptación**
- [x] Instumentalización realizada.
- [x] Documentación de instrumentalizaciones realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api eventos_crud:
<img width="958" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/a3546546-aaed-436e-bcf5-ff11600a6963">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api movilidad_academica_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/0fdd3c13-8d98-47aa-a31a-4073b90c710e">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api organizacion_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/500643de-2cec-4a7a-96fb-c4ba8c15d691">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api proyecto_academico_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/ae5014ff-d8f8-4a7a-8319-8640aa122d80">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api administrativa_crud_api:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/39f58e66-97de-4752-b0d2-f20532088e48">

**Comment by diagutierrezro** [comment]
Se define que se continuará con las instrumentalización de los CRUD ya que se tiene mas claro el proceso y se puede lograr un mayor avance y los MID que implican un mayor analisis para realizar la instrumentalización se dejarán para el final de la actividad.

**Comment by diagutierrezro** [comment]
Queda pendiente realizar las pruebas con AWS
