### ISSUE TITLE
Ajustar estilo de desplegable tipo de dependencia

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#160]
Se requiere realizar el ajuste del estilo del tipo de dependencia utilizado en el módulo de edición de dependencias para que quede similar a los otros desplegables.

**Sub Tareas**

- [x] Ajustar desplegable de tipo dependencia.
- [x] Pruebas de ajuste realizado.

**Criterios de aceptación**

- [x] Ajuste visual de desplegable realizado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Cambio
Se realiza el cambio estético, falta socializar el cambio con el líder @diagutierrezro, para determinar si el cambio es el esperado
![Image](https://github.com/user-attachments/assets/72cd2bd5-c726-4d2c-a4f9-f67563cc4cb7)

**Comment by xDa04vidx** [comment]
### Pull Request
Se realiza pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/d7ec2f50-41d9-4c6a-b6df-58975f198f18)
