### ISSUE TITLE
Modificar desplegable de tipo dependencia en registro de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#161]
Se requiere realizar la modificación del desplegable "tipo dependencia" para permitir que se puedan seleccionar multiples tipos de dependencia. Esto tambien requiere la modificación de la lógica para que al hacer el POST se guarden los tipos seleccionados.

**Sub Tareas**

- [x] Realizar modificación al desplegable para poder seleccionar multiples tipos.
- [x] Modificar lógica para permitir el registro de los diferentes tipos seleccionados.
- [x] Probar funcionamiento correcto del despelgable.

**Criterios de aceptación**

- [x] Modificación de desplegable realizada.
- [x] Modificación de lógica realizada.
- [x] Pruebas de funcionamiento realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra que el desplegable de tipo acepte múltiples opciones. 
![Image](https://github.com/user-attachments/assets/7932e445-ca68-421b-b14f-8d8a1cc3b8cf)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra configurar el json para la petición
![Image](https://github.com/user-attachments/assets/b2166dbb-f7be-484e-8963-79e48a74cd15)

**Comment by xDa04vidx** [comment]
### Adelanto back
Se logra realizar el registro de la dependencia con múltiples tipos
![Image](https://github.com/user-attachments/assets/fd5b66ed-cd4c-4872-8757-ac97f462efe1)

Se comprueba haciendo la petición hacia la dependencia creada
![Image](https://github.com/user-attachments/assets/491bd610-f86a-4137-90eb-7fec7362180e)
![Image](https://github.com/user-attachments/assets/132d16ba-a473-4f4f-821b-eb19c70b9183)

Se puede observar que los 3 tipos que se pasaron, se lograron registrar con éxito.

Además se comprueba que la dependencia padre, se creara de forma correcta
![Image](https://github.com/user-attachments/assets/a4160fe3-ae47-4d6d-9249-349cea03640f)

Por ultimo, se puede observar en la tabla de gestión, que la dependencia fue creada
![Image](https://github.com/user-attachments/assets/104f0d56-e57c-400d-a8c8-b747a469f921)

**Comment by xDa04vidx** [comment]
### Faltante
Hace falta realizar los rollback para regresar cambios, en los registros múltiples de los tipos.

**Comment by xDa04vidx** [comment]
### Se comprueba uso de rollback
Para corroborar el uso del rollback, se configura el endpoint para entre directamente a los rollback.
![Image](https://github.com/user-attachments/assets/41f8a07e-9198-4aae-a2e4-0c2a02fa96ec)

Luego, se realizo un cambio sobre el rollback de tipo de dependencia, para que itere sobre los ids de tipo creados
![Image](https://github.com/user-attachments/assets/9c4ea73b-8133-49d8-9a33-7238d0340a9e)

Por ultimo se prueba el endpoint 
![Image](https://github.com/user-attachments/assets/2d520290-e99f-43fc-9be5-c4b78820ff43)

Da exitosa y se comprueba la existencia de los registros de la dependencia
**Tipo dependencia**
![Image](https://github.com/user-attachments/assets/733e830c-b7bf-4526-a62a-d2b9bccc36df)
**Dependencia padre**
![Image](https://github.com/user-attachments/assets/3d6069f3-b968-4372-9475-3eb98dbf4972)
**Dependencia**
![Image](https://github.com/user-attachments/assets/80426e30-d208-4050-b823-fe9554cebd80)

Se verifica que se borraron los registros.

Por ultimo en el endpoint principal 
![Image](https://github.com/user-attachments/assets/5e6eade3-d7ed-45a5-97bb-b9f64ebf60ab)

Se están guardando los ids de los tipos creados, y si hay algún fallo se comprueba que al menos exista un tipo creado para que entre al rollback de los tipos, si no se ha creado ninguno, entra directo a borrar la dependencia.

**Comment by xDa04vidx** [comment]
### Pull Request
Se crea pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)
![Image](https://github.com/user-attachments/assets/58f10990-2a27-4571-b28a-0b7ae93342c6)

**Comment by xDa04vidx** [comment]
### Frontend
Se logra registrar la dependencia con varios tipos
![Image](https://github.com/user-attachments/assets/b0238f9e-34bb-4bb2-990b-7d3ac0f960af)

Se verifica la existencia
![Image](https://github.com/user-attachments/assets/2e9271af-a085-44e4-9c74-c6aced1ea323)

**Comment by xDa04vidx** [comment]
### Pull request
Se crea pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/2c5087a3-c69d-48db-9605-6f4b30f7cbca)

**Comment by xDa04vidx** [comment]
### Solución a error
En la prueba del frontend se detecto un error en el mid, este se soluciono, y se realiza el commit pertinente
![Image](https://github.com/user-attachments/assets/ae7ea16c-a887-4277-bd8b-d41542b57a19)
