### ISSUE TITLE
Agregar loader y recarga de tabla en gestión dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#162]
Se requiere realizar el ajuste en el modulo de gestión de dependencias para que al realizar la edición de alguna dependencia se muestre un loader mientras se realiza la operación (preguntar a David como realizarlo) y posteriormente recargar la tabla con la información actualizada.

**Sub Tareas**

- [x] Loader realizado.
- [x] Actualización de datos en la tabla.
- [x] Demostración de ajustes realizados.

**Criterios de aceptación**

- [x] Loader realizado.
- [x] Actualización de tabla realizada.
- [x] Demostración realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se espera poder ver avances y comentarios para poder dar seguimiento de trabajos , gracias

**Comment by JulianAvella** [comment]
Con la explicación que amablemente me dio mi compañero David para entender la funcionalidad del código existente y lo que debía de hacerse, se empezo el issue, el cual quedo de la siguiente forma:

Se aplican datos filtro para buscar una dependencia, la cual se muestra de primeras en la tabla: 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ddb50ca5-4579-41f7-969e-34f6ff23259a">

Se da clic en la parte de edición que se encuentra en la parte de acciones, así están los datos:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/732a2b4d-92ea-4701-bf5d-a11849829a28">

Los datos vamos a cambiarlos de esta forma:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/1a627ff9-8710-4821-8047-523b684cc423">

Después le damos clic en "Editar dependencia", la cual enviaría los datos para ser actualizados en la BD, y hay es cuando se muestra el loader, el tiempo que se muestra depende de la duración que toma la actualización de la data en la BD:
<img width="578" alt="image" src="https://github.com/user-attachments/assets/70aeb3c3-d18d-44e7-8536-1465bafac419">

Luego de que se actualiza los datos en la BD, se muestra una ventana pop up que dice "Operación exitosa", si los datos fueron actualizados correctamente:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/911646d8-28e4-4620-a95f-bc989b0d6939">

Después de darle clic en "Aceptar" a la ventana pop up, se recarga la tabla con los datos actualizados y los datos filtros siguen intactos :
<img width="959" alt="image" src="https://github.com/user-attachments/assets/6ba59c96-568f-4a8c-b0d0-bd66557962a2">

Se muestra que en la tabla que fue recargada, los datos que actualizamos quedaron correctamente:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/b9e3369e-efc4-4f4d-986a-7250473d8b99">
