### ISSUE TITLE
Corregir los errores de ortografía en el cliente de OIKOS

### ISSUE THREAD

**Issue by mantnicot** [udistrital/core_documentacion#163]
Se requiere realizar la corrección en el apartado visual del cliente, pues varios títulos en los formularios muestran palabras incompletas o mal escritas

Sub Tareas

- [x] Realizar ajustes para corregir el cliente.
- [x] Documentar pruebas realizadas y errores encontrados.

Criterios de aceptación

- [x] Revisión realizada.
- [x] Correcciones realizadas.
- [x] Documentación realizada.

Requerimientos

No aplica

Definition of Ready - DoR

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.
Definition of Done - DoD - Desarrollo

Desarrollo en local.

- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Vista Gestión
**Estado inicial**
![Image](https://github.com/user-attachments/assets/e37c688d-66c6-4dfa-9cbd-1bf90ac81a6a)

**Corrección**
![Image](https://github.com/user-attachments/assets/da31e6e6-4283-4c07-bc30-b70a703f076c)
Se encontraron errores en las palabras "Dependencia", "Vicerrectoría" y "Mayúscula", además se revisaron los mensajes de los pop up's de carga.

### Vista Organigrama
**Estado inicial**
![Image](https://github.com/user-attachments/assets/d2f91161-ab6a-4791-abce-4497d76235c1)

**Corrección**
![Image](https://github.com/user-attachments/assets/f16e4628-2c1f-4461-a2df-4722c5dbacaa)
Se encontraron errores en las palabras "Académico" y "éxito".

### Vista Editar Dependencia
**Estado inicial**
![Image](https://github.com/user-attachments/assets/1424c067-4152-4e0a-a010-0542e84cec07)

**Corrección**
![Image](https://github.com/user-attachments/assets/52becb44-b9ab-423f-9b0c-dcadbb25a4c9)
Se encontraron errores en las palabras "Dependencia", "Teléfono" y "Mayúscula", además se revisaron los mensajes de los pop up's de carga y se corrige error de acción, antes decía "dependencia creada", se cambia a "dependencia editada"

### Vista Registro
**Estado inicial**
![Image](https://github.com/user-attachments/assets/8865d730-4022-4476-84b4-db6a25140538)

**Corrección**
![Image](https://github.com/user-attachments/assets/e7de9ed0-4b0a-4c58-8135-0db7ebe0dc5d)
Se encontraron errores en las palabras "Dependencia", "Teléfono" y "Mayúscula", además se revisaron los mensajes de los pop up's de carga.

### Vista Mapeo
**Estado inicial**
![Image](https://github.com/user-attachments/assets/28e23ca5-afe3-457c-9196-9b41096982bc)

**Corrección**
![Image](https://github.com/user-attachments/assets/fee28f88-4daa-430a-8a9a-9b34cf0dee7c)
Se encontraron errores en las palabras "Dependencia", "Vicerrectoría" y "Mayúscula", además se revisaron los mensajes de los pop up's de carga.

### Vista Generar y Editar Mapeo
**Estado inicial**
![Image](https://github.com/user-attachments/assets/9fd5df21-b7da-4829-b446-24ecde49c3a3)

**Corrección**
![Image](https://github.com/user-attachments/assets/36199a5f-b784-4611-9ef6-1f2d01c6563b)
Se encontraron errores en las palabras "Dependencia", "Único", "Código", "Académico" e "Identificación".

**Comment by xDa04vidx** [comment]
### Pull request

1. En [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf), se agrega al pull request 
![Image](https://github.com/user-attachments/assets/d9b74931-8d6a-4b6f-844c-1f11cabecb2c)
 
2. En [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf), se agrega al pull request
![Image](https://github.com/user-attachments/assets/8b625a85-8b13-4ae2-9218-07ebc3d46654)
