### ISSUE TITLE
Iniciar revisión para realizar consulta con palabras clave en gestión dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#164]
Se requiere realizar el comienzo de la revisión para las tareas a realizar teniendo en cuenta que se solicitó por parte del usuario modificar el filtro para que este se pueda hacer mediante palabras clave. Para la issue se debe revisar el CRUD de Oikos para analizar cuales son las tareas que se deben realizar para realizar el filtro correcto en la consulta.

**Sub Tareas**

- [x] Revisar CRUD de oikos para analizar que cambios se deben realizar en el filtro.
- [x] Documentar en el issue los cambios a realizar para realizar el filtro.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
1. Se comenzó con la revisión del controlador dependencia_v2.go, que maneja las operaciones de consulta a la base de datos. Se revisó el método GetAll del controlador, que recibe los parámetros de consulta enviados al endpoint y los pasa al modelo, donde se ejecutan las consultas a la BD.

Se observó que el controlador permite la especificación de múltiples filtros mediante la URL, lo que facilita la combinación de varios criterios de búsqueda. El filtro actual realiza coincidencias exactas para todos los campos, incluido el campo Nombre, que se solicitó modificar para que permita la búsqueda de palabras clave.

2. Tras revisar el controlador, se investigó el archivo del modelo dependencia.go, donde se encuentra el método GetAllDependencia. Este método es responsable de ejecutar las consultas basadas en los parámetros de filtrado. En su estado actual, utiliza el método Filter de Beego ORM para filtrar los resultados de la base de datos. Este método realiza una coincidencia exacta de los datos.

Una posible solución investigada fue modificar este método para que, cuando el campo Nombre sea uno de los criterios de búsqueda, se utilice la cláusula icontains de Beego ORM, que internamente genera una consulta LIKE en la BD. Esta modificación permitiría que las consultas sobre el campo Nombre no requieran una coincidencia exacta, sino que puedan encontrar coincidencias parciales, que tiene la misma función de la palabra reservada LIKE.

3. Se exploraron diversas alternativas para implementar la funcionalidad de filtrado basado en palabras clave en el nombre de la dependencia:

* Uso de icontains en Beego ORM: Esta opción permite modificar el filtro para que utilice búsquedas con coincidencias parciales. Se investigó cómo aplicar esta funcionalidad solo al campo Nombre, mientras que los demás campos continúan utilizando coincidencias exactas.
* Combinación de varios filtros: Se analizó la posibilidad de realizar una combinación de Filter y icontains en el mismo conjunto de filtros, dependiendo de los campos a consultar.
* Impacto en el rendimiento: Se consideró cómo las búsquedas con LIKE afectan el rendimiento, especialmente en bases de datos con grandes volúmenes de datos. La implementación debe hacerse de manera eficiente para evitar cargas innecesarias en el servidor de la BD.

4. Se concluyó que la solución más adecuada es modificar el modelo para que, al buscar por el campo Nombre, se utilice la opción icontains del ORM de Beego. Esta implementación permitirá que las búsquedas se realicen con coincidencias parciales, mejorando la flexibilidad de filtrado sin afectar el funcionamiento de los otros filtros existentes en el CRUD de Oikos.
