### ISSUE TITLE
Realizar desarrollo para estampa final con firma electrónica - Parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#165]
Se requiere realizar el desarrollo de la estampa final junto con el proceso de firma electrónica que hace referencia a la etapa final de los procesos que requieren multiples firmantes, en esta ultima estampa debe ir adicionalmente el código de verificación y el texto indicando donde se debe verificar el documento.

**Sub Tareas**

- [x] Realizar desarrollo para agregar estampa final.
- [x] Realizar desarrollo para aplicar firma electrónica al documento.
- [x] Probar funcionamiento correcto de los desarrollos realizados.

**Criterios de aceptación**

- [x] Desarrollo para estampa final realizado.
- [x] Desarrollo para firma electrónica realizado.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/09/24

Se crea lógica para desarrollar la firma final (Aún no se sube a Nuxeo, sólamente se ha probado la estampa), siendo que por medio de un If se comprobará si la firma electrónica se encuentra en una etapa final para estampar el código de verificación el tipo de documento y el enlace de verificación:

![image](https://github.com/user-attachments/assets/a8fbe053-10a0-4db0-b09f-b6ece9c16e0d)

Por lo tanto en postman se envía el documento en la etapa que se había dejado el día anterior con la clave etapa_firma con un valor de "final":

![image](https://github.com/user-attachments/assets/2fa2ac78-5833-400d-bcc2-d025ed786493)

Como resultado el documento estampa correctamente la etapa final de la firma con el firmante enviado:

![image](https://github.com/user-attachments/assets/69631c18-8fdb-4ebf-b739-0d54440a8dc6)

Siendo así, se pasan a desarrollar ajustes en el espaciado y distribución de las diferentes estampas en las etapas, además de que se debe puntualizar de que en cada etapa de firma el sistema verifica si hay espacio suficiente así que por el momento puede suceder que la firma si es muy larga se distribuya entre dos páginas distintas.

Además de ello queda pendiente la implementación de la lógica de subida a nuxeo para las diferentes etapas y la implementación de hash para la última etapa

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 19/08/24

Se ajusta modelo y lógica para que la clave valor que se encarga de identificar la etapa de la firma sea un entero en vez de una cadena:

![image](https://github.com/user-attachments/assets/4d73db88-b773-4983-9a08-397a845619ec)

Así mismo se crean condicionales para gestionar la lógica posterior a la estampa, dejando todo lo concerniente al hash y la generación de registros en la tabla de firma electrónica para la última etapa de la firma múltiple:

![image](https://github.com/user-attachments/assets/cabe21a0-0004-4e9f-8eaf-31764a80d559)
![image](https://github.com/user-attachments/assets/49577c3f-c2bf-4403-85e8-e414bdba6467)

También se hicieron ajustes como la creación del arreglo de datos dependiendo de la etapa mostrada en anteriores capturas y la adición de la verificación dentro del estampado sobre la utilización de la variable de firma que ahora sólo será enviada a la estampa en la última etapa:

![image](https://github.com/user-attachments/assets/bed6dd0c-f0a3-48fe-baa5-bf39063cb43a)

Así en todas las etapas se realizará la subida a nuxeo pero sólo en la última se realizará el hash y la creación de registros en la tabla de firma electrónica.

También se acordó con el lider que para mantener una consistencia en los registros que se ingresarán a la tabla firma electrónica en cuanto a firmantes y representantes, en la última etapa de la firma se enviará el firmante y representante a estampar común y corriente, y en los metadatos se enviarán todos los firmantes y representantes del proceso (incluyendo el que se envía actualmente) para ser guardado en la base de datos.

Por tanto queda pendiente corregir el espaciado de la estampa en lo cual ya se está trabajando, implementar la lógica de extracción de firmantes de los metadatos y realizar las pruebas de la funcionalidad completa del nuevo endpoint
