### ISSUE TITLE
Finalizar detalles de multiples firmantes.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#166]
Se requiere realizar la finalización de los últimos detalles de multiples firmantes en firma electrónica, estos detalles son mas que todo visuales, por ejemplo que las diferentes firmas no queden tan separadas entre si, realizar pruebas de estampas, especialmente al final de las hojas para comprobar el correcto funcionamiento de estas (probar diferentes escenarios).

**Sub Tareas**

- [x] Finalizar detalles de multiples firmantes.
- [x] Realizar diferentes pruebas de funcionamiento para multiples firmantes.
- [x] Documentar pruebas realizadsa.

**Criterios de aceptación**

- [x] Detalles de multiples firmantes finalizados.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 23/09/24

Se ajusta el espaciado de la firma múltiple y se prueba la correcta subida a Nuxeo de los documentos quedando de la siguiente manera:

**Primera etapa:**

![Captura de pantalla 2024-09-23 174310](https://github.com/user-attachments/assets/a30a9b34-1ea7-422c-972a-20759464ca96)

**Segunda etapa:**

![Captura de pantalla 2024-09-23 175856](https://github.com/user-attachments/assets/c9cded9a-8f4e-4c03-8e30-3e8b4e9a375c)

**Etapa final:**

![Captura de pantalla 2024-09-23 182426](https://github.com/user-attachments/assets/a2ae61e9-7419-43e4-ac2b-1f42af965e0e)


También se realizó una prueba en el caso de que la firma completa no cupiese en una sola hoja, en ese caso queda dividida de esta manera:

![Captura de pantalla 2024-09-23 200328](https://github.com/user-attachments/assets/289ac887-ddc4-4a9d-8142-660e776ca317)

También se corrigieron algunas validaciónes y errores que se detectaron al momento de probar cambiando de nuevo el sistema de etapas siendo que antes se tenía que era 0 para la etapa inicial, 1 para la etapa intermedia y 2 para la etapa final, sin embargo en las validaciones esto generaba conflicto así que se cambió para que fuese de 1 a 3. También se cambió la comprobación de cual estampa usar en el modelo de firma electrónica, ya que al hacer una firma normal generaba conflico, por tanto se agregó un .get al diccionario "datos" para verificar la existencia de la clave valor que indica la etapa de la firma:

![image](https://github.com/user-attachments/assets/621a6287-077c-471c-ac7c-ca7ccc70678f)

Queda pendiente ajustar la lógica para la correcta persistencia de toda la información del proceso en la base de datos

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/09/24

Se plantea una solución para el tema de la persistencia de los múltiples firmantes en la base de datos.

Como se acordó con el líder se enviarán en el json de la petición los registros de los firmantes y/o representantes de la etapa final y las anteriores etapas en los metadatos al momento de hacer la última estampa (es decir la etapa final en sí), de la siguiente manera:

![Captura de pantalla 2024-09-24 214155](https://github.com/user-attachments/assets/5e38d4e8-05ea-46c2-b2c7-4bfc22a14dc0)

Así se podrá guardar en la base de datos, en la tabla de firma electrónica, todos los firmantes y representantes involucrados en el proceso. Cabe recalcar que de todas maneras se debe enviar común y corriente los firmantes y representantes de la estampa de la última firma a pesar de ser incluidos en los metadatos.

Así pues se tiene el siguiente fragmento de código que crea un Json con esta información rescatada de los metadatos, y los envía en el objeto en el que luego se realizará la consulta a la tabla de firma electrónica.

![Captura de pantalla 2024-09-24 214215](https://github.com/user-attachments/assets/1280df1a-d3e1-4544-b68d-bc038b131897)

Así se realiza una firma con los datos de prueba mostrados en la primera captura de pantalla, dando como resultado un proceso exitoso:

![Captura de pantalla 2024-09-24 214137](https://github.com/user-attachments/assets/d77fc234-a7de-4381-86da-ed494904c655)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/09/24

Se realizaron pruebas de funcionamiento para verificar la correcta operación del nuevo endpoint cuando la firma no quepa en una sola página. Para este propósito se realizó una firma mútiple con 4 estampas; una inicial dos intermedias y una final agregando de una vez los representantes para probar el estampado con esta información:

**Primera etapa:**

![image](https://github.com/user-attachments/assets/8c97da4f-7c71-4b04-a483-8f34ecfb8ad8)

**Segunda etapa:**

![image](https://github.com/user-attachments/assets/607e2784-f7e1-4b96-a8c7-e205bbb9ba5e)

**Segunda etapa parte dos:**

![image](https://github.com/user-attachments/assets/51bd2999-c102-4008-931b-ce385f32fc93)

**Tercera etapa:**

![image](https://github.com/user-attachments/assets/930dfe5b-3500-4b33-95b4-ba2be9f5b5c1)

Con esto se termina de hacer las pruebas y se coloca la tarea en in review

**Comment by diagutierrezro** [comment]
Se finaliza satisfactoriamente le desarrollo y se presenta a funcionamiento. Gran trabajo Andres.
