### ISSUE TITLE
Presentar a funcionamiento nueva metodología de multiples firmantes.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#167]
Se requiere realizar la presentación al equipo de funcionamiento sobre la nueva metodología desarrollada para multiples firmantes.

**Sub Tareas**

- [x] Realizar presentación.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 27/09/24

Se realiza la presentación a funcionamiento del nuevo endpoint y su funcionalidad de forma satisfactoria, se resuelven dudas y no surgieron imprevistos, se coloca en in review

**Comment by diagutierrezro** [comment]
Muy buena presentación Andres, gracias.
