### ISSUE TITLE
Actualizar documento de implementación de firma electrónica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#168]
Actualizar documento creado en #114 en el cual se indica como realizar la implementación, especialmente en la sección de multiples firmantes.

**Sub Tareas**

- [x] Actualizar documento sobre como implementar firma electrónica.

**Criterios de aceptación**

- [x] Documento actualizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 27/09/24

Se actualiza el documento con las funcionalidades, especificaciones y modelos del nuevo endpoint de firma múltiple, así como la adición del base 64 del archivo firmado a la respuesta del endpoint de firma única. Se adjunta el enlace al documento para su revisión:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/EduV40kCqS5GvE0uGyWcSQIBYHavlpo4j6kLzxghZJKfdA?e=WqR5ES

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres, gracias.
