### ISSUE TITLE
Implementación de multiples firmantes nuevo en cumplidos CPS - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#169]
Se requiere realizar la implementación de la nueva metodología de multiples firmantes en cumplidos CPS, para esto se requiere apoyo de Juan Camilo Martinez (lider encargado de este sistema) con el cual es importante tener una comunucación constante sobre las tareas a realizar.

Para esta implementación se debe actualizar lo desarrollado anteriormente y adaptarlo al nuevo flujo de firma que se desarrolló. Iniicalmente se debe implementar la primera estampa la cual se realiza una vez el contratista envía el cumplido para su revisión.

**Sub Tareas**
- [x] Iniciar implementación de estampa inicial cuando el contratista sube el cumplido.
- [x] Documentar avances realizados.

**Criterios de aceptación**

- [x] Implementación inicial realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 30/09/24

Se tuvo una reunión con Juan Camilo para definir los aspectos más importantes de la implementación tales como el número de etapas necesarias en el flujo, de las cuales se concluyó que sólo se necesitaría la inicial para el contratista y la final para el supervisor, y en ese mismo orden de ideas se acordó los puntos en el código en los que se debería realizar dicha implementación.

Para más detalles se adjunta enlace a la grabación de la reunión.

[Grabación de la definición de detalles de implementación de firma múltiple en cumplidas](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/davagomezr_udistrital_edu_co/ES0WuEE-9ypKvpCZw_Oh3isBi_sijuEy2VPSQzJXB8Li8g?e=7AN4MK&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 01/10/24

Se inicia con la implementación de la nueva funcionalidad de firma múltiple, en específico a la implementación de la primera etapa al momento en que el Contratista sube el certificado de cumplimiento:

Para ello primero se agrega al service de firma electrónica el debido método que llamará al nuevo endpoint de la API de firma:

![Captura de pantalla 2024-10-01 194758](https://github.com/user-attachments/assets/cab79e25-c8d8-47a2-bd7a-24d21c6a8b47)

Luego en el archivo **informe_gestion_y_certificado_cumplimiento.js** se agrega en la definición del módulo la inclusión del servicio de firma electrónica:

![Captura de pantalla 2024-10-01 195728](https://github.com/user-attachments/assets/ab996f9c-6798-49b1-899f-f45c7679a45d)

Posteriormente en la función **subirInforme** se modifica el arreglo que se tenía antes, ya que anteriormente el arreglo que se construía carecía de gran parte de la información que se envía a firma ya que se usaba gestor documental para subir directamente a Nuxeo, para ello entonces se agregan los campos faltantes y se reorganiza el diccionario para mejor comprensión y se reemplaza la petición a gestor documental por la petición a firma:

![image](https://github.com/user-attachments/assets/5ff07252-a492-4810-a9fe-f9fc4bcf9077)

Con esto implementado se procede a probar, subiendo un certificado de cumplimiento de prueba resultando exitosamente:

**Vista desde el visor de pdf de cumpldios donde el contratista puede ver su certificado ya subido listo para enviar al supervisor: **

![Captura de pantalla 2024-10-01 210111](https://github.com/user-attachments/assets/2c3fce13-019c-4d31-8cb6-c72df289d1de)


**Vista desde Nuxeo:**

![Captura de pantalla 2024-10-01 211814](https://github.com/user-attachments/assets/da1c95ad-75cc-4d78-9b8c-b4cf59bf0ec6)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 02/10/24

Se comienza con la implementación de la etapa final de la firma múltiple al momento en que el supervisor aprueba el documento subido por el contratista:

Primero en aprobacion_supervisor.js se modifica el diccionario que se enviará a firma, colocando en los metadatos los firmantes tanto te la etapa actual como de la anterior y agregando la clave-valor etapa_firma con el valor 3 para indicar la etapa final:

![image](https://github.com/user-attachments/assets/cab192de-c861-42c3-9100-29902f941c53)

Posterior a ello se cambia el endpoint al cual se apuntaba originalmente en el flujo:

![image](https://github.com/user-attachments/assets/da2c09d6-974f-4e53-b14f-7dcf181cf5df)

A continuación se genera un documento por parte del contratista con la primera etapa de la firma:

![Captura de pantalla 2024-10-02 223959](https://github.com/user-attachments/assets/370f8be2-7655-4801-925f-9555748f76e1)

Luego como supervisor se intenta aprobar, sin embargo ocurre un error:

![Captura de pantalla 2024-10-02 224347](https://github.com/user-attachments/assets/0c00321c-d33b-4e06-b152-b1e0d1dc3394)

Revisando las peticiones se identifica el causante del error:

![image](https://github.com/user-attachments/assets/1f04b350-913b-418b-aa24-de1e2263256e)

Al parecer hay un problema rescatando el archivo desde nuxeo por medio de gestor documental, ya que al parecer el UID no corresponde con un archivo o bien no encuentra el documento asociado.

Se está trabajando en encontrar el error.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 03/10/24

Se tuvo una reunión con Juan Camilo para abordar el tema de los rechazos en el proceso de firma electrónica, se acordó realizar cambios en el crud y mid de cumplidos adicionales a los necesarios en el cliente, además de acordar con los DBA's la modificación de los registros de los soportes para que se pueda utilizar con fiabilidad los campos de "activo". Para mayor detalle se adjunta la grabación de la reunión:

 [Reunión revisión de rechazo en flujo de firma de cumplidos](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/davagomezr_udistrital_edu_co/ESSEpN_JZvRGkcq4S2eFjXcBJXSGLzNoIqSz64Il3kL7TA?e=GGM4R7&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

Además se revisó el error presentado el día anterior y se llegó al origen del problema.

Cuando gestor documental consulta un documento en nuxeo para extraer su base 64, el hace la búsqueda asegurando como condicional del query, que el documento esté activo:

![Captura de pantalla 2024-10-03 212331](https://github.com/user-attachments/assets/9df048d8-0c31-4c14-97f2-f4cf9c9947d7)

Consultando el documento que se trató de firmar el día anterior por medio de la última etapa se encontró que dicho campo estaba en false:

![Captura de pantalla 2024-10-03 205711](https://github.com/user-attachments/assets/d635f020-832c-4611-9a86-d8760ca7cfae)

Comprobando los flujos de firma electrónica y firma múltiple se confirmó que dicho campo se estaba mandando como true siempre, por lo que se pasó a realizar una prueba adicional para identificar el punto en el que este valor cambiaba de true a false:

Se creó una primera estampa:

![image](https://github.com/user-attachments/assets/b3ba7469-7ab8-4897-8c22-dda4d7c6434b)

El valor seguía en verdadero. Al enviarlo al supervisor seguía en verdadero. Y sorpresivamente al momento de aprobar, el flujo completo funcionó y la consulta de gestor documental que generaba fallo funcionó correctamente:

Registro en BD:

![Captura de pantalla 2024-10-03 204054](https://github.com/user-attachments/assets/f7f32c5c-e603-4ded-8b44-ba6bdc144d64)
![Captura de pantalla 2024-10-03 204047](https://github.com/user-attachments/assets/8b2a09eb-bab5-4f40-b00f-d19b4bd46a5a)

Consulta y resultado:


![Captura de pantalla 2024-10-03 204105](https://github.com/user-attachments/assets/da24c200-5f32-4677-9916-f21650995131)

Nuxeo:

![Captura de pantalla 2024-10-03 204209](https://github.com/user-attachments/assets/a870efd9-7408-48bf-9a50-768ae625de65)

Para confirmar el correcto funcionamiento se hizo una segunda prueba documentada en video:

https://github.com/user-attachments/assets/644ea0dc-a183-4513-8d69-3d938c204370

El documento en nuxeo resultado de dicha prueba es este:

![image](https://github.com/user-attachments/assets/a5299a2a-cf2c-4793-bfa0-7b09e63a6c7e)


Por lo tanto el error presentado el día anterior fué resultado de algún evento aislado no identificado, ya que como se evidencia el flujo funciona correctamente.

Así pues se inician los ajustes respectivos al rechazo en el flujo de cumplidos
