### ISSUE TITLE
Realizar cambio de versión en SGA y ARKA

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#17]
Se requiere realizar el cambio de versionado de Oikos en el cliente de arka y sga para posteriormente realizar las respectivas pruebas para comprobar que los sistema sigue funcionando correctamente.

**Sub Tareas**
- [x] Realizar el cambio de versión de Oikos en el cliente de arka.
- [ ] Realizar el cambio de versión de Oikos en el cliente de sga.
- [ ] Realizar prueba de los sistemas modificados para comprobar que funcionan correctamente.

**Criterios de aceptación**
- [ ] Cambios de versión de Oikos realizado en los dos clientes.
- [ ] Pruebas realizadas documentadas.

**Requerimientos**
No aplica

**Dependencias**
Por desconocimiento del funcionamiento del cliente de novedades se solicitará reunión con el último desarrollador que trabajó con este cliente para que nos colabore con la realización de las pruebas, por lo que la finalización de este issue está sujeta a disponibilidad de el.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Se clono el repositorio de Arka cliente**


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/6859f0f7-64a5-4786-a7f7-cb1357099588)

**Comment by xDa04vidx** [comment]
**Se identificó que se está utilizando la v2 en OIKOS**
Al realizar la clonación, se identificó que ya se está utilizando la versión 2 de OIKOS.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/eafe76c8-3a26-4ca9-ab11-818fef079449)

**Comment by xDa04vidx** [comment]
**Se logra correr el cliente**

De igual manera se espera la reunión con la persona encargada, para ver el funcionamiento de la v2, y el porque se esta revisando esta API, si ya estaba usando la v2 de OIKOS.

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/4eb0fa12-26ee-4df4-8524-aeddd8317534)

**Comment by xDa04vidx** [comment]
**arka cliente**

Para este cliente no fue necesario realizar pruebas, ya que ya contaba con la versión 2 de OIKOS, por lo tanto, se procedió a cerrar la tarea.

**Comment by xDa04vidx** [comment]
**SGA cliente**

Cuando se correo el cliente se identificaron las siguientes APIs que tenian errores:

- https://autenticacion.portaloas.udistrital.edu.co/apioas/core_crud/v2 
- https://autenticacion.portaloas.udistrital.edu.co/apioas/proyecto_academico_crud/v1
- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1
-  https://autenticacion.portaloas.udistrital.edu.co/apioas/planes_estudios_crud/v1

Se notificaron estos errores a @diagutierrezro 

Además, en el MID de SGA, había endpoints que tampoco estaban funcionando correctamente. Estos fueron:

- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1/notas/InfoDocenteAsignatura/
- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1/notas/InfoEstudianteNotas/94
- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1/plan_trabajo_docente/asignaciones_docente/94/56
- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1/plan_trabajo_docente/preasignaciones_docente/94/55
- https://autenticacion.portaloas.udistrital.edu.co/apioas/sga_mid/v1/admision/getlistaaspirantespor?id_periodo=56&id_proyecto=29&tipo_lista=3

Sin embargo, se procedió a realizar las pruebas específicas de los endpoints que apuntan a la base de datos de OIKOS.

**Comment by xDa04vidx** [comment]
**Análisis peticiones en el cliente de sga**
El documento que contiene el análisis de las peticiones hacia Oikos, localizado en el cliente de SGA, aún está en construcción.

OneDrive:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/EZdxJ9BGsL1MlzR_PWWiMG0BRCSfKd8NsDRNZxL7Qbbcyw?e=rDLE3c

**Comment by xDa04vidx** [comment]
**Análisis peticiones en el cliente de SGA**
Se finaliza el documento de análisis sobre las peticiones hacia Oikos desde el cliente de SGA.

OneDrive:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/EZdxJ9BGsL1MlzR_PWWiMG0BRCSfKd8NsDRNZxL7Qbbcyw?e=rDLE3c

PDF:

[sga_cliente.pdf](https://github.com/udistrital/core_documentacion/files/15448190/sga_cliente.pdf)

Se concluye que no se puede realizar el cambio de versiones aún, dado que existen peticiones que generan error al utilizar la versión 1. Se evaluarán los resultados del análisis junto al líder @diagutierrezro.

**Comment by diagutierrezro** [comment]
Según los errores encontrados hacia V1 se define que no se hará nada ya que el error es apuntando hacia la V1 de oikos, este error viene de antes y al hacer la modificación hacia la V2 el API ya responde de manera correcta. 

Buen trabajo David.
