### ISSUE TITLE
Mover textos para que sean usados desde un diccionario

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#171]
Se requiere realizar la migración de textos para que estos sean usados desde un diccionario, normalmente se encuentra en la carpeta assets - i18n donde se ponen los textos en español y en ingles, una vez se realice esta migración de textos se deben ajustar las partes de código donde se "quemen" los textos anteriores y modificarlos para que se consulten desde el diccionario.

**Sub Tareas**

- [x] Crear diccionario de textos con los textos necesarios para los diferentes microclientes.
- [x] Moficiar y consumir textos desde el diccionario anteriormente creado.
- [x] Documentar issue con cambios realizados.

**Criterios de aceptación**

- [x] Diccionarios en microclientes creados.
- [x] Textos modificiados y consumidos desde el diccionario.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra implementar el cambio en la vista de gestión
**Código**
![Image](https://github.com/user-attachments/assets/e57ecf4a-8f8c-47b3-88da-28c36cb2223c)

**Vista**
![Image](https://github.com/user-attachments/assets/347839c6-7bda-416e-bc24-7012589eadf5)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra implementar el cambio en la vista de editar dependencia

**Código**
![Image](https://github.com/user-attachments/assets/6200d5eb-2560-42ed-bcf2-8de582646514)


**Vista**
![Image](https://github.com/user-attachments/assets/fae845c4-52e6-4a6e-91b4-660eea7c450b)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra implementar el cambio en la vista de registro de dependencia

**Código**
![Image](https://github.com/user-attachments/assets/406de3c6-3d36-4538-a75e-598463e1ae54)

**Vista**
![Image](https://github.com/user-attachments/assets/a951958c-4603-45ae-8513-2be6b1c156e9)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra implementar el cambio en la vista de mapeo de dependencia

**Código**
![Image](https://github.com/user-attachments/assets/000083ed-51fc-4146-8959-12e8e1e09984)

**Vista**
![Image](https://github.com/user-attachments/assets/81261b5e-634c-4dc6-8dfa-6d105833e8cd)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra implementar el cambio en la vista de editar-generar mapeo

**Código**
![Image](https://github.com/user-attachments/assets/ec1dce27-716f-48cb-83b5-af5af66d11b1)

**Vista**
![Image](https://github.com/user-attachments/assets/6080b754-3b8a-4f4a-97c6-0c553d614d34)

**Comment by xDa04vidx** [comment]
### Pull request

Se crean pull request en

1. [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/1d3cedda-727a-40c8-88c8-4e2b95678709)

2. [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)
![Image](https://github.com/user-attachments/assets/db1224d0-9fd5-4296-9e1b-33d758115eff)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David.
