### ISSUE TITLE
Concertar, desarrollar y levantar sesión de refinamiento múltiples firmantes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#174]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente para múltiples firmantes

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión apra el día  27/09/2024 a las 10:00 am 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NTQzMGJmMDAtZThhNy00YTUyLTg4MDktYzgwNjM3NmRhMjhl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha generado el acta de reunión

[acta reunión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ERpcCc2LxfxIklg7OzLdAHgB8_Mb9_rjAd_EcGkRj2eo6A?e=mBafDk)

**Comment by jcmurilloa** [comment]
Buen trabajo y excelente resultado de la reunión, tenemos nuevos compromisos en Core. A recoger firmas por favor

**Comment by mantnicot** [comment]
Se recolecto la firmas

[acta con firmas](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EWzv9etiHPNPi0h-TorOhzgBHFOsgatgNmffHJxNbFjhDg?e=OetbgD)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
