### ISSUE TITLE
Crear documentación para difusión de firma electronica en sabana de notas con comunicaciones

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#175]
Se requiere realizar la construcción de la documentación informativa soporte para difusión de firma electronica en sabana de notas con comunicaciones

**Sub Tareas**

- [x] Proyectar documento a modo de soporte para difusión de firma electronica en sabana de notas con comunicaciones
- [x] Enviar documentos revisados por SoS a interesados

**Criterios de aceptación**

- [x] Documento soporte para difusión de firma
- [x] Documentación cargada a carpeta

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha creado el documento y enviado a Viviana para su distribución, a espera de dar fecha de publicaicón


[Documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW2vxz2V9J5KrjokPNjsssoB1JtERgeqZ-oL6c623rWGjw?e=gqsJl0)

**Comment by jcmurilloa** [comment]
Recuerda revisar al detalle las subtareas @mantnicot, me hubiera gustado revisar el documento antes del envío a Viviana, como lo señala la descripción de la issue. Como observación principal recomiendo mostrar la estampa con un solo firmante, pues esta es la que se reflejará en la sábana de notas, y no la demúltiples firmantes, y la mostraría implementada en un documento.

**Comment by jcmurilloa** [comment]
Se queda atento a la implementación de firma en sábana de notas para compartir la documentación.
