### ISSUE TITLE
Concertar sesión para el levantamiento de de segundo alcance oikos con respecto a espacios fisicos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#176]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos con el cliente oikos con respecto a segundo alcance de espacios físicos

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Todavía no se ha dado repsuesta de parte del cliente para ello , se espera poder gestionar pronto

![Image](https://github.com/user-attachments/assets/a678e8b3-cd8d-45c1-9779-34339b32fa40)

**Comment by jcmurilloa** [comment]
Se hace necesario insistir @mantnicot, toda vez que esta en juego la hoja de ruta de Oikos para el nuevo alcance.

**Comment by mantnicot** [comment]
Ya se a podido agendar la reunión para 25/09/2024 a las 10:30 am

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzNkYmQ1ZjAtZDAyYy00YzliLTljMWUtODM4ZTU2YzYxODk4%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha generado el acta para la reunión

[acta renión sin firmas ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVOKlHK8Kr1Jm2v0dDi1kwEBBu-60GM4WyA_GwceYci_cw?e=ZkSDCY)

**Comment by jcmurilloa** [comment]
Acta revisada y lista para recoger firmas. Cobramos según esto con mucha más claridad para el nuevo alcance de Oikos. Excelente @mantnicot!

**Comment by mantnicot** [comment]
Se ha recolectado la firma 

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EWmTIq-x3EJLuFpdcmJaYQoBAFicIbMssPT-bt09rBNxDw?e=gifo6L)
