### ISSUE TITLE
Modificar funcionalidad de firma electrónica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#177]
Se requiere realizar la modificación al endpoint de firma electrónica para que en el JSON de respuesta se retorne el documento firmado en base64, esto surge debido a una solicitud desde funcionamiento ya que consultar este documento desde el gestor_documental_mid requiere mas trabajo debido a que está fuera de la arquitectura de los sitemas.
**Sub Tareas**

- [x] Modificar firma electrónica para que retorne el documento en base64, importante no afectar la lógica para no dañar otras implementaciones.
- [x] Documentar issue con pruebas de funcionamiento esperado.

**Criterios de aceptación**

- [x] Endpoint modificado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/09/24

Se realiza la modificación del endpoint de acuerdo a lo solicitado:

![image](https://github.com/user-attachments/assets/43fb209e-1fde-4625-8454-c907049ada48)

Se crea una variable que almacenará el base 64 del archivo que se envía a gestor para subir a Nuxeo y se agrega al diccionario que se envía como respuesta luego del proceso mencionado de Nuxeo. La clave se llamará **file**. Se realiza la prueba y funciona exitosamente sin afectar ningún flujo y agregando el archivo en base 64:

![image](https://github.com/user-attachments/assets/1bf1fa81-2725-462d-882b-f3397d3cbe02)

Se descarga el archivo de Nuxeo y se pasa a base 64 y se realiza un pequeño script para comprobar si el base 64 en Nuxeo es el mismo que el que se retorna en la respuesta:

![image](https://github.com/user-attachments/assets/06b355c2-8ec8-4724-977d-a116baca2888)

Como resultado se tiene un caso de éxito:

![image](https://github.com/user-attachments/assets/293db863-8b55-4b65-aded-6952f7c98b0f)

Por tanto se envía a in review y se realizará el pull request respectivo
