### ISSUE TITLE
Modificar colores de tabla en mapeo de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#178]
Se requiere realizar la modificaciones de colores a la tabla de mapeo de dependencias para que coincidan con la paleta de colores del cliente.

**Sub Tareas**

- [x] Modificación de colores realizados.
- [x] Documentar issue con cambios realizados.

**Criterios de aceptación**

- [x] Modificación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hizo la modificación de color para que coincida con el color vino tinto:
![image](https://github.com/user-attachments/assets/8f56c794-56b6-4a36-8a90-0274fba3797c)

**Comment by diagutierrezro** [comment]
Gracias Julian, buen trabajo.
