### ISSUE TITLE
Probar funcionamiento de consulta de dependencias con palabras clave

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#179]
Se requiere realizar la prueba de consultas de las dependencias con palabras clave según lo realizado en #172, se debe probar en el cliente que esta consulta funcione como se espera.

**Sub Tareas**

- [x] Realizar pruebas para comprobar el funcionamiento esperado.
- [x] Documentar issue con pruebas realizadas.

**Criterios de aceptación**

- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Al hacer la busqueda desde el cliente de oikos, y al buscar por una palabra como "FACULTAD" que es una palabra que la pueden tener varios nombres de dependencias, me muestra todos los nombres de las dependencias con ese palabra asociada:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/9f6bbc07-d819-4147-96df-a6e9107b43fe">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/df9f89d2-0a54-4e04-9866-89d3835a2fd4">

Genera un error con la palabra "ARTES" aun cuando hay un nombre de dependencia que tiene esa palabra:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/852d8af4-8d42-42aa-98c3-e12dda4fedaa">
Pero haciendo la prueba al crud que consulta en la BD, el crud responde bien con la información solicitada, que fue donde se hizo el cambio para que buscara por la palabra clave, entonces el error debe de estar en el mid  al que apunta el cliente de Oikos al momento de hacer la petición:
<img width="674" alt="image" src="https://github.com/user-attachments/assets/5cd5e0cc-4dbd-4d6f-8978-fd7ffad096d9">

Genera otro error al buscar por nombre de dependencia cuando la palabra esta en minúscula:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/1b857313-a199-4290-9f53-b1ea5b9135fd">

Se esta buscando la solución a este error

**Comment by diagutierrezro** [comment]
Se manejará una issue para solucionar los errores. Gracias Julian.
