### ISSUE TITLE
Creación de nueva funcionalidad en gestor_documental para uso con firma_electronica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#18]
Se requiere realizar la nueva implementación en el API del gestor_documental la cual consiste en cargar un documento en nuxeo y **actualizar** un registro en la DB de documentos el cual será creado previamente con el API de la firma_electronica

**Sub Tareas**
- [x] Creación de la  nueva funcionalidad en el API de gestor_documental.
- [x] Realizar pruebas de manera local, se puede crear un registro en la tabla documentos y posterior comprobar que la funcionalidad carga el documento en nuxeo y actualiza ese registro.
- [x] Actualizar swagger.

**Criterios de aceptación**
- [x] Nueva funcionalidad desarrollada.
- [x] Pruebas realizadas en ambiente local.
- [x] Swagger actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
###ACTUALIZACIÓN 22/05/2024 ###

Se comienza la creación de la nueva funcionalidad en gestor documental. Primero se genera la ruta en routes.py la cual dirigirá al método que se creará en document.py:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/5d5ba976-ee11-4c5f-8567-746866685663)

Posteriormente en document.py se crea la función putUpdate que utilizará en principio como base el método Upload, ya que su funcionalidad tendrá similitudes con la diferencia de que en el nuevo método se va a actualizar un registro previamente hecho por API firma electrónica, por tanto salvo la eliminación de partes como los comandos de firma electrónica, una redundancia en la asignación del json que recibe el router y el momentaneo comentareo del último fragmento del try - except (y eventualmente la operación que se realizará a documentos CRUD siendo ahora un put y no un post), por el momento queda la misma estructura en la nueva funcionalidad que en Upload. En las siguientes actualizaciónes se realizarán modificaciónes y cambios pertinentes para adaptar este nuevo método a las necesidades requeridas.

El fragmento comentareado es el siguiente:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/eb72b358-1c30-4c9c-921e-0ef011fafea7)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/05/24 ### 

**1. Actualización del Swagger**
Se realiza la actualización del Swagger con la adición de un nuevo modelo a "model_params.py" el cual es similar a "upload_model" con la diferencia de que los metadatos serán Strings:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/63ae3339-6932-47a1-85f1-b35af125fbf6)

Esto debido a que rescatarán los metadatos construidos en la nueva API para poder realizar el JSON que será usado en el PUT de la nueva funcionalidad, y este ya viene como un string desde firma electrónica.

Por tanto se utilizará este modelo para mostrar en el swagger del nuevo método el cual quedó de la siguiente forma:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3c0b62cb-de65-4be1-9916-6bc0fd2ee711)

**2. Agregación de parámetros: all_metadata y idDocUp**

Para poder llevar a cabo la actualización del nuevo método de Gestor Documental es necesario tener dos parámetros que permitirán el correcto cumplimiento de la función del nuevo método:

- **all_metadata**: En estos metadatos irán la información de los firmantes y la firma electrónica, los cuales están formateados a String desde la API firma electrónica.
- **idDocUp:** En la nueva funcionalidad, el Id que se está consultando con el Get corresponde a la tabla tipo_documento de DocumentosCrud, sin embargo estamos necesitando usar el Id del documento guardado en documentos crud para poder actualizarlo, por lo tanto, se rescata otra variable de la API de firma electrónica. En firma electrónica al hacer el post inicial del documento sin el enlace de nuxeo se guarda en la variable "responsePostDoc" la información de la respuesta del documento subido, la cual incluye el id del documento:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/3d3162f4-7aae-44f9-aba2-c87826783843)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/0adc5f75-45a9-4100-a9b9-12f9f574b492)

Dicho id, también se mandará como parámetro desde la API firma electrónica a la nueva funcionalidad de gestor documental, el cual se convertirá en la variable idDocUp en este contexto, el cual será utilizado en el post para indicar a qué documento se quiere acceder para realizar la modificación. Por tanto el inicio del método queda de esta manera:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/7c619f85-35c1-4b11-b627-746bfd7ef73c)

**4. Utilización de variables:**

Con lo anterior explicado, all_metadata será utilizado en la creación del json DicPostDoc de la nueva funcionalidad:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/d00d5ff0-597e-4128-b1be-af8c0795991d)

Así, este json junto con la variable idDocUp serán utilizados en el put el cual actualizará el registro del documento:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/cd35431d-682b-4c11-bb4a-c47066819aaa)

**6. Acceso a Bd:**

Ya se logró concertar la reunión con la persona encargada de ingresar las credenciales de acceso a las bases de datos de los necesarias para realizar las pruebas pertinentes. Por lo que salvo surja alguna novedad en un análisis de los cambios y funcionalidades implementadas, se estaría listo para probar la nueva funcionalidad de gestor documental

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/05/2024 ###

Se dieron inicio a las pruebas en entorno local de la nueva funcionalidad del gestor documental. 

Sin embargo antes de proceder con ellas primero se realizaron un par de ajustes en la API Firma electrónica y la nueva funcionalidad de gestor documental, las cuales son las siguientes:

***Cambio de parámetros que recibe nuevo método***

Para optimizar y simplificar los procesos de comunicación de la API firma electrónica y el método putUpdate de gestor documental, se tomó la decisión de que en vez de que putUpdate recibiese de firma electrónica los metadatos y el Id del documento en BD, esta información viniese en un JSON en el cual viene toda la información que originalmente el JSON data que maneja firma electrónica tiene, agregando/modificando estos dos datos, siendo así que sólo es necesario enviar un único JSON con la información necesaria. En firma electrónica el JSON se construye así:

  
![image](https://github.com/udistrital/core_documentacion/assets/77305100/4992f243-c70a-4e86-984b-664e3272e765)

En gestor documental por lo tanto los parámetros de entrada quedan así: 

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2fd13f37-99fc-4e37-b77b-96c86eee69c5)

Por lo tanto en gestor documental se corrigen las referencias a estos parámetros:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2d9b04c8-3c97-421e-9632-d52f8cf352e2)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/d46de1af-e2e9-4751-8cb9-64214edb87f9)

Por último se actualiza el Swagger para mostrar tanto el modelo corregido como la función PUT corregida:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/754bcd64-136d-44ef-b68d-c672dc1755ed)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/80c0804a-2b22-4a99-9da7-d5d31b03f932)

Además se corrige el nombre de una Variable para evitar confusiones a posibles nuevos desarrolladores que deban trabajar con el módulo, ya que como se ha presentado en otros métodos, la variable idDocumento contenía el id del **tipo de documento NO del documento en sí** por lo que se realiza la corrección de la declaración de la variable y su uso cambiando su nombre por  **idTipoDocumento**:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f9b0b395-16be-4e2f-b0cc-7727c71b110b)

Hechas estas correcciones se proceden a las pruebas en local:

###Pruebas en local###

Primero se realiza la prueba del método put, en el cual la idea es que sin conectarse a nuxeo, el método pueda actualizar un registro de prueba ya existente en la base de datos el cual ya es cargado con anterioridad a la misma con el siguiente query:

`INSERT INTO documento.documento(
	nombre, descripcion, enlace, tipo_documento, metadatos, activo, fecha_creacion, fecha_modificacion)
	VALUES ('PruebaGestor1', 'Prueba de nueva funcionalidad', '', 2, '{"NombreArchivo":"cumplidos profesor hernan.pdf","FechaCreacion":"19_Feb_2018_09:22:54","Tipo":"Archivo","IdNuxeo":"fb69f49f-2b26-47d7-bfe9-1304f7cbdb3c","Observaciones":"Listas de Asistencia Fisica Newtoniana Prof. Dr. Hernan Garrido Vertel"}', true, '2021-03-13 09:10:18.568868', '2021-03-13 09:10:18.568868');`

El cual en la base de datos se ve de la siguiente manera:

![Captura de pantalla 2024-05-27 215515](https://github.com/udistrital/core_documentacion/assets/77305100/1c2c38a9-88f8-4fee-9948-8a94f0a34abc)

Como se mencionó antes, no se conectaría a Nuxeo en esta prueba, por lo que todo el fragmento concerniente a ello se comentarea y se coloca un uid ficticio para realizar el testeo:

**Fragmento comentareado:**

![Captura de pantalla 2024-05-27 220502](https://github.com/udistrital/core_documentacion/assets/77305100/b0a02703-dd72-4b6a-87e4-2c08aae9d03b)

**UID ficticio y JSON DicPostDoc de prueba a mandar en put:**

![Captura de pantalla 2024-05-27 220511](https://github.com/udistrital/core_documentacion/assets/77305100/64f20b81-d5e7-4e14-b20b-daa7deb2c73b)

Ya finalmente para realizar la prueba se envió por medio de Swagger el siguiente JSON:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3352f707-1b23-4f73-8d4c-ca008b084bba)

### Prueba 1

En la primera prueba se recibió la siguiente respuesta:

![Captura de pantalla 2024-05-27 221131](https://github.com/udistrital/core_documentacion/assets/77305100/35681a70-91ce-4122-b73a-0a56163bd849)

Luego de analizar el código se encontró que la ruta del PUT estaba mal definida, careciendo de una barra inclinada en la URL que apuntaba a la base de datos antes de especificar el id del documento a modificar, cambiando este parámetro la sentencia queda de la siguiente manera:

![Captura de pantalla 2024-05-27 221405](https://github.com/udistrital/core_documentacion/assets/77305100/e99fc0d4-4a58-4af0-9491-906d73fe9edc)

### Prueba 2

Realizada de nuevo la prueba se logra la modificación del registro de manera exitosa:

![Captura de pantalla 2024-05-27 221612](https://github.com/udistrital/core_documentacion/assets/77305100/3225cbfb-262a-4275-9897-8fdb4b2a741a)

![Captura de pantalla 2024-05-27 221733](https://github.com/udistrital/core_documentacion/assets/77305100/56a6a81c-d96d-4de6-ba25-0593b87bccc7)

Como se puede evidenciar, el enlace y los metadatos fueron modificados, definiendo así el correcto funcionamiento del comando PUT.

Queda pendiente para el día siguiente probar con la conexión a nuxeo y usando documentos en base64.

Al finalizar las pruebas se eliminarán los registros de testeo que se hayan creado para tal propósito

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 28/05/24

Se realizaron las pruebas con archivos pdf de prueba y con conexión a Nuxeo.

Se anexa a este Issue el Excel en el que se registraron todas las pruebas de la nueva funcionalidad de Gestor documental, para más detalles de las mismas, consultar dicho documento.

**PRUEBA 1**

La prueba fué realizada enviando un JSON con los mismos datos usados en las pruebas del día anterior con la diferencia de que en el campo "file" del JSON se ingresó el documento de prueba (el cual también se anexará en formato pdf) en base 64. El resultado de la prueba dió un código 500 el cual decía que "el archivo no se encontraba en el directorio" lo cual ocasionó que en Nuxeo se creara el registro del archivo, mas no el archivo en sí, apareciendo este registro vacío. Después de un análisis se llegó a la conclusión de que además del archivo en base 64, también es necesario el original en pdf en una carpeta llamada "documents" la cual debe estar ubicada en la raiz del proyecto, y dicha carpeta está incluida en el **gitignore** y es por esta razón que no se tenía constancia de su existencia, al crear dicha carpeta, y realizar unos cambios en las rutas de acceso del script se procedió a realizar la prueba 2:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b180c845-ec1f-46bf-8d6c-f1a846390ff0)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/fc04ef5c-7e89-490e-8ec4-983dc73fa038)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/57ef18c0-cd64-45cd-9be3-5bc84571d180)

**PRUEBA 2**

Luego de realizar los siguientes cambios que se mencionaron anteriormente:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/0afba7cd-8254-4b88-b585-7e0cefa56602)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/5f4f2048-c94b-4d6c-9f43-816f37ff3c11)

Se procedió a la segunda prueba resultando en un caso de éxito, en el cual se recibió un código 200, la verificación de que en nuxeo se creó el registro y se subió el archivo y en la base de datos se actualizó el campo de enlace:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/10825e10-9519-4c07-9bcd-fcf23363bf99)

**PRUEBA 3**

Para que el método putUpdate soporte cualquier nombre de archivo, sin tener que cambiar el código se hicieron modificaciones al script para este propósito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0f864ce4-52b9-4a59-8753-f1b36579182a)

En donde se contemplan casos en el que el nombre del archivo que se recibe por JSON esté sin extensión o con extensión, para ello en la prueba 3 se prueba este script con un nombre sin extensión, resultando en un caso de éxito, validando respectivamente que en todos los sistemas (swagger, BD y nuxeo) la información esté correcta:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/432ec2f2-1372-4495-a35d-603780d55759)


**PRUEBA 4**

La prueba 4 consistió en la misma dinámica anterior pero con archivos con extensión, consiguiendo también un caso de éxito:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/90ff361d-5e0a-46c0-9f8e-4b89b0cf5e31)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/cf5a8312-957f-4a16-a9f1-ac40232094a4)



Finalmente se anexa documento en excel para revisión y se pasa a Review el Issue
[Pruebas locales nuevo método gestor documental.xlsx](https://github.com/udistrital/core_documentacion/files/15475963/Pruebas.locales.nuevo.metodo.gestor.documental.xlsx)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres.
