### ISSUE TITLE
Crear rollbacks en el MID

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#180]
Se requiere realizar los rollback de las transacciones que se realizan en el [mid](https://github.com/udistrital/gestion_dependencias_mid) de Oikos, tener en cuenta que los rollback se hacen desde la última acción realizada hacia atras para evitar errores con llaves foraneas que puedan surgir en los post o put que se van realizando, se puede usar como guía los rollback creado en las transacciones en el mid de Pólux.

**Sub Tareas**

- [x] Crear rollbacks para transacciones utilizadas en el mid de Oikos.
- [x] Hacer que el sistema falle en ciertos puntos (puede ser modificando rutas) para que los rollback se ejecuten y comprobar funcionamiento.
- [x] Documentar pruebas de funcionamiento.

**Criterios de aceptación**

- [x] Rollbacks creados.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto Issue

La Issue, se centra en crear los rollbacks faltantes en la edición de dependencias, para ello se crearon 3 tipos de rollbacks:

- Rollback para devolver cambio sobre la dependencia
- Rollback para eliminar nuevos tipos de dependencia asociados a una dependencia
- Rollback para devolver cambio de los tipos existentes de las dependencias

![Image](https://github.com/user-attachments/assets/3844f514-41bf-4eac-a132-56aefbc03091)

Para crear estos rollbacks fue necesario crear una copia de la dependencia original, un listado con los tipos de dependencia nuevos y una lista con los tipos de dependencias con su estado original.

estos rollbacks se pusieron en el momento donde se realizan "PUT" o "POST"

![Image](https://github.com/user-attachments/assets/65b623c3-68c7-42f1-b4d9-8375b0793ca8)

Además se tiene que después de que se realiza un rollback se llama al anterior.

No obstante se encuentran puntos en donde se hace un "GETJSON" y en estos no están los rollback, hace falta evaluar si allí también es necesario poner los rollbacks

**Comment by mantnicot** [comment]
Se revisa la issue y se solicita la terminación de la misma pues ya se encuentra dos springs atrasados , recordar que cargar con issues afecta la proyección de los nuevos. Gracias

**Comment by xDa04vidx** [comment]
### Pruebas de funcionamiento

Se realizan ajustes en el código, dado que no se estaban guardando los ids en las iteraciones.

Se realizaran las pruebas con la dependencia con Id 305, esta tiene 3 tipos activos correspondientes a los ids 1, 2 y 3, y dependencia asociada el id 22.

**Datos de la dependencia**
Generales:
  ![Image](https://github.com/user-attachments/assets/f4b081cb-c9aa-47ed-8d13-fb7f2135cc81)

Dependencia padre:
  ![Image](https://github.com/user-attachments/assets/8ec9c76e-e035-4826-a74a-1ca92e0a35e9)
  

A continuación se muestran los fallos en los puntos críticos.

**Cuando entra un nuevo tipo de dependencia**
En este error existen dos puntos, el primero cuando se llama el get del nuevo tipo, y el segundo cuando se intenta crear.

1. Cuando se llama el nuevo tipo
    Punto del error:
        ![Image](https://github.com/user-attachments/assets/b4df432e-7daf-4e2f-a7a2-47f751c6f1db)

    Solicitud:
        ![Image](https://github.com/user-attachments/assets/86c5dbcc-cea7-4a33-97a6-3fd7011b9d11)
    Se agrega un nuevo tipo, el de id 4

    Fallo:
        ![Image](https://github.com/user-attachments/assets/963b7800-23a8-417f-b193-6a0070390a8f)
    
    Rollback:
    Se garantiza que no haya registro del nuevo tipo y que no haya cambiado ningún dato general
        ![Image](https://github.com/user-attachments/assets/e8ede6d1-2092-41e4-af26-7621677aa46a)
        
2. Cuando se intenta crear
    Punto del error:
        ![Image](https://github.com/user-attachments/assets/6d75fb49-2376-4ff0-ad42-19a3132e03de)

    Solicitud:
        ![Image](https://github.com/user-attachments/assets/6672e8c7-6e1e-44be-b948-70c8e4ec2bb6)

    Se agrega un nuevo tipo, el de id 4

    Fallo:
        ![Image](https://github.com/user-attachments/assets/963b7800-23a8-417f-b193-6a0070390a8f)
    
    Rollback:
    Se garantiza que no haya registro del nuevo tipo y que no haya cambiado ningún dato general
        ![Image](https://github.com/user-attachments/assets/ced7ad55-b3bc-4973-b9bd-ae154a6c106b)

**Cuando se modifica algún tipo de dependencia**
En este error existen dos puntos, el primero cuando se llama el get del tipo existente, y el segundo cuando se intenta modificar.

1. Cuando se llama el tipo
    Punto del error:
        ![Image](https://github.com/user-attachments/assets/bdd5624b-2cee-4abb-a45c-757a2bf81492)

    Solicitud:
        ![Image](https://github.com/user-attachments/assets/7ed02272-aa7b-4eb5-a3af-c4bcc219187d)

    Se agrega un nuevo tipo, el de id 4, y se quita el existente en 3, este debería pasar como false

    Fallo:
        ![Image](https://github.com/user-attachments/assets/a1749df1-dc23-4ccc-ab37-bf998b37a421)
    
    Rollback:
    Se garantiza que no haya registro del nuevo tipo, que el tipo 3 siga en true y que no haya cambiado ningún dato general
        ![Image](https://github.com/user-attachments/assets/099b1844-e508-44a2-9fa5-99e87abf7552)

2. Cuando se modifica el tipo
    Punto del error:
        ![Image](https://github.com/user-attachments/assets/157eebd1-d93e-4911-abfa-bdc4959df105)

    Solicitud:
        ![Image](https://github.com/user-attachments/assets/7ed02272-aa7b-4eb5-a3af-c4bcc219187d)

    Se agrega un nuevo tipo, el de id 4, y se quita el existente en 3, este debería pasar como false

    Fallo:
        ![Image](https://github.com/user-attachments/assets/83f73e57-49a0-4cab-b6e8-43840333b726)
    
    Rollback:
    Se garantiza que no haya registro del nuevo tipo, que el tipo 3 siga en true y que no haya cambiado ningún dato general
        ![Image](https://github.com/user-attachments/assets/7510419b-18bc-41d4-b815-1962297120a9)

**Cuando se modifica la dependencia asociada**
En este error existen un único punto de posible error, que es cuando se modifica la dependencia asociada.

1. Cuando se modifica la dependencia asociada
    Punto del error:
        ![Image](https://github.com/user-attachments/assets/9bdfeb9b-fede-4b3c-8d3a-6bc137cda02b)

    Solicitud:
        ![Image](https://github.com/user-attachments/assets/29822324-cd1f-4b02-aa68-11daf8015f2e)

    Se mantienen los cambios anteriores, para corroborar que los cambios se realizan pero al encontrar el error vuelven al estado inicial

    Fallo:
        ![Image](https://github.com/user-attachments/assets/1dcd2066-f0ec-417c-b752-569f499c4427)

    
    Rollback:
    Se garantiza que no haya registro del nuevo tipo, que el tipo 3 siga en true, que no haya cambiado ningún dato general y que la dependencia asociada se mantenga en la 22
    Datos generales:
        ![Image](https://github.com/user-attachments/assets/7672b70c-c1ce-4de6-b729-72a7beaec564)
    Dependencia asociada:
        ![Image](https://github.com/user-attachments/assets/e6b9a9c1-4a75-4957-8074-fc51e7b04c9e)

### Funcionamiento correcto
Se realiza la prueba sin errores, para corroborar que el funcionamiento sigue siendo correcto:

Solicitud:
![Image](https://github.com/user-attachments/assets/a49c71b2-558c-4798-8ad4-ad06ca0afbe8)

Respuesta:
![Image](https://github.com/user-attachments/assets/fa10f9ad-fe6a-4ed6-aecd-8e2d751923d7)

Datos generales:
![Image](https://github.com/user-attachments/assets/2b444b43-e9f3-479e-95b8-5e12f352c4c5)
    ![Image](https://github.com/user-attachments/assets/12d633cf-939c-4278-8ab5-d93ddab5373e)

Dependencia asociada:
![Image](https://github.com/user-attachments/assets/a4fd2ed0-776a-45ce-a96d-d91dc1d04455)

**Comment by xDa04vidx** [comment]
### Pull request

Se crea pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)
![Image](https://github.com/user-attachments/assets/11974282-96dc-47b3-a44b-f4939d508048)
