### ISSUE TITLE
Agregar loaders en registros de dependencia y ajustar diccionario.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#181]
Se requiere realizar la creación de loaders al momento de registrar una dependencia, editar un mapeo de depenedencias, agregando tambien los avisos de que todo se haya realizado correctamente o si se encontraron errores, adicional a esto completar el uso del diccionario de textos para el modulo de registro de dependencias.

**Sub Tareas**

- [x] Crear loaders y avisos en registro de dependencias.
- [x] Crear loaders y avisos en edición de mapeo de dependecias.
- [x] Ajustar diccionario de datos en registor de dependencias.

**Criterios de aceptación**

- [x] Loaders y avisos creados.
- [x] Diccionario completado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Registro y Gestión

Se logra realizar la lógica para que se muestren los loaders de cada transacción que integra este microcliente.

1. Editar
    ![Image](https://github.com/user-attachments/assets/915665d3-7b63-4ed5-8404-27d7974b3a00)

2. Búsqueda de dependencias
    ![Image](https://github.com/user-attachments/assets/614f658f-d41c-436b-a130-481d9362b000)

3. Activar dependencia
    ![Image](https://github.com/user-attachments/assets/ab939ea9-9904-4668-b174-2e405af22300)

4. Desactivar dependencia 
    ![Image](https://github.com/user-attachments/assets/8bd8b866-b650-4e87-b64e-5613995aa8ff)

5. Organigrama
    ![Image](https://github.com/user-attachments/assets/6bf8d974-a730-4a4f-9418-87ba48536ce4)

6. Editar dependencia
    ![Image](https://github.com/user-attachments/assets/2289ef89-bc35-4f3f-9efe-59e9b3fb6f24)

**Nota**
Dado que las transacciones se realizan en cuestión de segundos, no se logra capturar el momento del loader, sin embargo, esta apareciendo y con el mensaje correcto.

**Comment by xDa04vidx** [comment]
### Pull request 

Se realiza pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/fc0b38ac-6e40-4c72-b41a-4fbac8b73204)

**Comment by xDa04vidx** [comment]
### Mapeo
Se logra realizar la lógica para que se muestren los loaders de cada transacción que integra este microcliente.

1. Buscar dependencias
    ![Image](https://github.com/user-attachments/assets/ab2eb50b-57d0-4684-8bfc-353addf3dd60)

2. Generar Mapeo
    ![Image](https://github.com/user-attachments/assets/7db47a33-f09e-4315-9be3-d8515e11bd02)

3. Editar Mapeo
    ![Image](https://github.com/user-attachments/assets/bbc904b6-bfad-4d48-a053-b5114aace844)

### Nota
Dado que las transacciones se realizan en cuestión de segundos, no se logra capturar el momento del loader, sin embargo, esta apareciendo y con el mensaje correcto.

**Comment by xDa04vidx** [comment]
### Pull request

Se realiza pull request en [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)

![Image](https://github.com/user-attachments/assets/1ed31000-28e4-49fb-83e2-c89e95dbf6a7)

**Comment by diagutierrezro** [comment]
Se comprueba funcionamiento correcto, gracias David.
