### ISSUE TITLE
Agregar indicativos a botones de las tablas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#182]
Se requiere realizar el desarrollo para que en las tablas de gestión de dependencias y mapeo de dependencias se le indique al usuario el funcionamiento de los diferentes botones cuando pongan el cursos encima de estos (activar dependencias, editar dependencia, etc.)

**Sub Tareas**

- [x] Desarrollar avisos en botones en las diferentes tablas.
- [x] Documentar pruebas realizadas con funcionamiento correcto.

**Criterios de aceptación**

- [x] Avisos realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Finalización Tarea

Se realizan los cambios, para ello fue necesario mejorar la lógica de los tooltip, para que esta se encuentre centralizada en los estilos globales.

1. Gestión

    - Tooltip Editar
       ![Image](https://github.com/user-attachments/assets/f341d7cd-8dac-4c71-9c47-ca50a686db62)

    - Tooltip Activar
       ![Image](https://github.com/user-attachments/assets/c5debccf-5911-41be-94c7-6c5fe952798d)

    - Tooltip Desactivar
       ![Image](https://github.com/user-attachments/assets/aafc37e8-529b-45e8-914a-d5121c11e320)


2. Mapeo
   
    - Tooltip Editar
       ![Image](https://github.com/user-attachments/assets/eb9f03b8-802f-4031-ab91-e06069018184)

    - Tooltip Generar
       ![Image](https://github.com/user-attachments/assets/bc46a7af-0b0e-4c8e-b1fb-d080ac4a0b20)

**Comment by xDa04vidx** [comment]
### Pull Request

Se generan dos pull request

1. En [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
    ![Image](https://github.com/user-attachments/assets/42510b20-de82-4874-803b-88cbb5fd1b30)

2. En [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)
    ![Image](https://github.com/user-attachments/assets/9db0bff6-36b8-4bee-b8f1-55e25f1e4f20)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David.
