### ISSUE TITLE
Corregir botones mostrados en edición de dependencias y corrección de tooltip.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#183]
Se requiere realizar el ajuste en la tabla de gestión de dependencias de tal manera que cuando una dependencia está activa unicamente me muestre el botón para desactivar o si está inactiva me muestre el botón de activar una dependencia.

Posteriormente corregir el tooltip de la vista de edición de dependencias ya que queda cortado y no se puede leer completo. En la vista de mapeo de dependencias agregar tooltip para el código de argo y corregir textos de los otros codigos, queda pendiente por parte de @diagutierrezro definir que textos irán ahi.

**Sub Tareas**

- [x] Modificar tabla para mostrar unicamente botón de activar o desactivar según sea el caso.
- [x] Corregir tooltip para que se muestre completo.
- [x] Completar y corregir tooltips de mapeos de dependencia.
- [x] Documentar issue con pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Tabla modificada.
- [x] Tooltip corregido.
- [x] Tooltips de mapeo de dependencias completos y corregidos.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Botones para edición de dependencias
Se han implementado condicionales para mostrar el botón de desactivar cuando la dependencia está activa, y el botón de activar cuando la dependencia no está activa.
![Image](https://github.com/user-attachments/assets/d3655dfa-8b6a-41e7-97e3-d917c4bdd56c)

**Comment by xDa04vidx** [comment]
### Tooltip de edición
Se soluciona el error y ya ningún tooltip, se corta con el borde de la ventana de editar Dependencia
![Image](https://github.com/user-attachments/assets/c677272e-d809-49c6-9f36-1879f72f85ee)

**Comment by xDa04vidx** [comment]
### Vista Mapeo

Se logra poner boton de ayuda en "IDENTIFICACIÓN ARGO" y se corrigen los textos de los tooltip de "CÓDIGO IRIS"

**ARGO**
![Image](https://github.com/user-attachments/assets/70aa89ed-7f44-4c6c-9d24-c9570a470fbc)

**IRIS**
![Image](https://github.com/user-attachments/assets/ebc1c07a-1019-42c1-a1f0-64bcfa894fa0)

**Comment by xDa04vidx** [comment]
### Pull Request
Se generan dos pull request

1. En [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
    ![Image](https://github.com/user-attachments/assets/aa473e8c-bfb4-4aeb-8ea6-68ef0123fecd)

2. En [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)
    ![Image](https://github.com/user-attachments/assets/3d648b39-fde2-4808-b5d6-746c91749c03)
