### ISSUE TITLE
Corregir error al filtrar por palabras clave

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#184]
Se requiere realizar la corrección del error encontrado en #178 donde se muestra un error al consultar dependencias por ciertos nombres. Revisar desde postman la posibilidad de que se hayan creado dependencias que no tengan la información completa lo que podría estar generando errores.

**Sub Tareas**

- [x] Revisar peticiones hacia el crud para verificar que puede estar generando error.
- [x] Borrar datos que no estén completos (en caso de ser necesario).
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Revisión de peticiones realizada.
- [x] Borrado de datos realizado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
En el análisis, se encontro que la data no es consistente en todos sus registro, los registros en su gran mayoria tienen la siguiente estructura:

{
        "Id": 35,
        "Nombre": "FACULTAD DE ARTES -  ASAB",
        "TelefonoDependencia": "3239300 Decanatura: 6616 | Secretaría Académica: 6606 - 6607 | Asesoría Jurídica: 6619 | Comunicaciones: 6620 | Bienestar Institucional (Enfermería): 6604 | Arte Danzario: 6630 - 6614 | Artes Escénicas: 6609 | Artes Musicales: 6612 - 6613 | Artes Plásticas",
        "CorreoElectronico": "decanatura_artes@udistrital.edu.co",
        "Activo": true,
        "FechaCreacion": "2022-07-06T19:45:10.995513Z",
        "FechaModificacion": "2024-09-24T16:49:00.294387Z",
        "DependenciaTipoDependencia": [
            {
                "Id": 29,
                "TipoDependenciaId": {
                    "Id": 2,
                    "Nombre": "FACULTAD",
                    "Descripcion": "",
                    "CodigoAbreviacion": "",
                    "Activo": true,
                    "FechaCreacion": "2022-07-06T19:43:19.205677Z",
                    "FechaModificacion": "2022-07-06T19:43:19.205677Z"
                },
                "DependenciaId": {
                    "Id": 35,
                    "Nombre": "FACULTAD DE ARTES -  ASAB",
                    "TelefonoDependencia": "3239300 Decanatura: 6616 | Secretaría Académica: 6606 - 6607 | Asesoría Jurídica: 6619 | Comunicaciones: 6620 | Bienestar Institucional (Enfermería): 6604 | Arte Danzario: 6630 - 6614 | Artes Escénicas: 6609 | Artes Musicales: 6612 - 6613 | Artes Plásticas",
                    "CorreoElectronico": "decanatura_artes@udistrital.edu.co",
                    "Activo": true,
                    "FechaCreacion": "2022-07-06T19:45:10.995513Z",
                    "FechaModificacion": "2024-09-24T16:49:00.294387Z",
                    "DependenciaTipoDependencia": null
                },
                "Activo": true,
                "FechaCreacion": "2022-07-06T19:48:47.28491Z",
                "FechaModificacion": "2022-07-06T19:48:47.28491Z"
            }
        ]
    }

Entonces hay datos que no tienen toda la estructura anterior, como los siguientes registros:

    {
        "Id": 225,
        "Nombre": "UNIDAD DE INVESTIGACIONES - FACULTAD DE ARTES - ASAB",
        "TelefonoDependencia": "3239300",
        "CorreoElectronico": "facartes-uinv@udistrital.edu.co",
        "Activo": true,
        "FechaCreacion": "2022-07-06T19:45:10.995513Z",
        "FechaModificacion": "2022-07-06T19:45:10.995513Z",
        "DependenciaTipoDependencia": []
    },
    {
        "Id": 248,
        "Nombre": "CENTRO DE DOCUMENTACIÓN DE LAS ARTES",
        "TelefonoDependencia": "3239300",
        "CorreoElectronico": "",
        "Activo": true,
        "FechaCreacion": "2023-02-03T16:44:13.609373Z",
        "FechaModificacion": "2023-02-03T16:44:13.609373Z",
        "DependenciaTipoDependencia": []
    },
    {
        "Id": 250,
        "Nombre": "COMITE DE ESPACIOS - FACULTAD DE ARTES - ASAB",
        "TelefonoDependencia": "3239300",
        "CorreoElectronico": "",
        "Activo": true,
        "FechaCreacion": "2023-02-03T16:44:13.609373Z",
        "FechaModificacion": "2023-02-03T16:44:13.609373Z",
        "DependenciaTipoDependencia": []
    }

Debido a esta inconsistencia en los datos, se presento el error, porque el código fuente del cliente de Oikos fue desarrollado para que necesitara toda la data para completar la tabla, entonces se modificó para que si no tiene la información de "DependenciaTipoDependencia" se muestre en la tabla la frase "NO REGISTRA" para evitar errores en el código y para que el usuario pueda ver que no tiene esa información asociada a la dependencia que busca, como se muestra en las siguientes imágenes:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/bacbb790-96ab-4d2f-9f71-63751c435dc8">

<img width="959" alt="image" src="https://github.com/user-attachments/assets/633cb839-9adb-4dcd-ac24-8a8c984e59ea">

**Comment by JulianAvella** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/9a6bb3b5-ef3d-4697-a8ae-6399bcb883df">
