### ISSUE TITLE
Restringir creación y edición de dependencias para volver campos obligatorios.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#185]
Se requiere realizar la restricción en el formulario de la creación y edición de las dependencias para que sean obligatorios todos los campos de este, revisar el uso del "required" en los formularios de angular el cual se encarga de manejar estos requerimientos.

Adicional a esto debe aparecer un aviso en los campos vacios que le indiquen al usuario que son campos obligatorios.![Image](https://github.com/user-attachments/assets/e895613a-7809-4896-ac22-41679494e505)

**Sub Tareas**

- [x] Restringir envío de formulario de registro de dependencias hasta que todos los campos estén llenos.
- [x] Indicar al usuario cuando le falte llenar algun campo con un aviso de "campo requerido".
- [x] Realizar las mismas dos tareas anteriores para la edición de dependecias.
- [x] Documentar correcto funcionamiento del sistema.

**Criterios de aceptación**

- [x] Formulario de registro restringido.
- [x] Indicaciones al usuario realizadas.
- [x] Ajustes a la edición de dependencias realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* Módulo de REGISTRO:

Se modifico un poco y asi es como se ve el formulario de registro de dependencias:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ff6eed34-4b1f-4643-9f41-c7dffef0b7aa">

El boton va a estar deshabilitado y si pasa el cursor va a aparecer un circulo de prohibido y se va a habilitar hasta que complete todos los campos.

Si toca un campo y no escribe nada y luego toca en otro lado, va aparecer el mensaje "* Campo obligatorio" en rojo justo debajo del campo, el mensaje se mostraría sin hacer perder la forma visual del formulario, se vería así:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/a0a2e240-766a-434f-b215-72eedef953e1">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3f61fc52-f4e8-47ce-966f-c9889664d28e">

Si completa los campos así se veria el botón habilitado:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ea8c2cdc-022f-4955-aed4-464012e2fad7">

Y si se crea la dependencia, mostraria su mensaje de "éxito":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/c1ee3e32-ae7a-4b19-adae-86089b2f4b0b">

**Comment by JulianAvella** [comment]
* Módulo de EDITAR DEPENDENCIA:

Se modifico un poco y asi es como se ve el formulario de editar la dependencia:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/28be92c9-2f86-4887-8f8c-0c9b4e3a21ef">

El botón estando deshabilitado y con unos campos vacios que muestran el mensaje "* Campo obligatorio" en rojo justo debajo del campo, el mensaje se mostraría sin hacer perder la forma visual del formulario, se vería así:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/4ffddfdb-85cd-4a7d-a659-2ef0c2a2965f">

Si completa los campos se veria el botón habilitado como se muestra en la primera imagen de este comentario.

Y si se edita la dependencia, mostraria su mensaje de "éxito":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/710c706d-7cf3-41e0-9714-d25be1587362">

**Comment by JulianAvella** [comment]
* Módulo de EDITAR MAPEO:

Asi es como se ve el formulario de editar el mapeo:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ff0a84a5-4646-4405-9ee7-b45ed1ad740f">

El botón estando deshabilitado y con el único campo requerido vacio "número de identificación interno" que muestra el mensaje "* Campo obligatorio" en rojo justo debajo del campo, se vería así:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/75b45f06-cb32-45c3-ba85-142c08f8a6fb">

Si completa el único campo requerido "número de identificación interno" se veria el botón habilitado, como se muestra en la primera imagen de este comentario.

Si se edita el mapeo, mostraria su mensaje de "éxito":
<img width="959" alt="image" src="https://github.com/user-attachments/assets/aef53f96-cffc-4c7d-a916-e1a8af204e39">

**Comment by JulianAvella** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/04502916-7a9f-42e9-b09b-f8b3d4cd9e24">
