### ISSUE TITLE
Crear formato historia de usuario para OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#186]
Se requiere realizar la Creación de formatos de historias de usuario para OIKOS

**Sub Tareas**

- [x] Creación del formato historias de usuario 
- [x] Socialización del formatos historias de usuario 
- [x] Aprobación del formato de historias de usuario

**Criterios de aceptación**

- [x] Formatos historias de usuario aprobados
- [x] Documentación de formatos historias de usuario para módulo reportes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado las historias de usuario
[Historias de usuario espacios fisicos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYiEOHH27yJMjBOCVoWVvNEBB-LRIaYMAUxWrOoz7nx5tA?e=e1s5Jb)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, ahora busquemos la aprobación por parte del usuario por favor.

**Comment by mantnicot** [comment]
Se ha dado aprobación de parte del cliente

![Image](https://github.com/user-attachments/assets/3e897101-3223-4683-b5f8-2d51e28e1437)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
