### ISSUE TITLE
Diseñar Mockup para segundo alcance cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#187]
Se requiere realizar el diseño del Mockup para el nuevo alcance del cliente OIKOS.

*Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han generado los mockups del segundo alcance
[carpeta mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpQmMdTw2gtPsSqPlMY7yxIBe0VcbTfKGTZQTPkP66f9wA?e=A6kp6S)

![Image](https://github.com/user-attachments/assets/a80dfdbc-ac32-4c64-8661-ab29508547c2)
![Image](https://github.com/user-attachments/assets/856a50ae-2db2-45be-abb1-02666a33c36e)
![Image](https://github.com/user-attachments/assets/f8d7d4a3-10ce-4d2f-beed-9f0591f06de3)
![Image](https://github.com/user-attachments/assets/ce300ac6-d0c8-417a-a497-5b0e4917cdc4)
![Image](https://github.com/user-attachments/assets/b4189a6c-e60d-4845-a9db-597e9bae6d7c)
![Image](https://github.com/user-attachments/assets/ac974e28-b77e-4eec-b8f2-be571a6489f7)
![Image](https://github.com/user-attachments/assets/a493e7cb-34b1-4db5-b1c0-e6c13a2f7dc0)
![Image](https://github.com/user-attachments/assets/7a307b33-7b7a-4642-8771-a952d912895d)

**Comment by jcmurilloa** [comment]
Que buen diseño @mantnicot, tendremos las respectivas observaciones en el próximo Review, con el fin de aprobarlo y buscar la muestra al cliente.

**Comment by mantnicot** [comment]
se ha realizado la revisión del líder técnico y se harán los cambios respectivos

**Comment by jcmurilloa** [comment]
Estaremos atentos a los cambios recomendados en el review, con el fin de dar por cerrada la issue.

**Comment by mantnicot** [comment]
Se ha dado aprobación de aprte del cliente

![Image](https://github.com/user-attachments/assets/3e897101-3223-4683-b5f8-2d51e28e1437)

**Comment by jcmurilloa** [comment]
Muy buen trabajo, aprobado para desarrollo @mantnicot!
