### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#188]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente OIKO

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido agendar la reunión el día 04/10/2024 a las 11 am

[Reunión enlace](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NmQwNjUyMGQtNWQ4Ni00N2Q3LTk2ZmEtY2M3NjEzOGZkNDY0%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se adjunta el acta de la sesión

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfYMr1MkJl5Og7HIQOCApp0Bd9qSmQQC4QHuOtwpq_Zeig?e=KSCZf3)

**Comment by jcmurilloa** [comment]
Que bien nos fue en la sesión con el cliente, recojamos las firmas del acta para continuar avanzando en oikos!

**Comment by mantnicot** [comment]
Se ha obtenido las firmas correspondiente

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXvc8omlJllIj-cgKhbOa30BohsqnSHcXVdLgp3J8gvW2A?e=Qb8nNO)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
