### ISSUE TITLE
Comenzar implementación caducidad de roles URANO

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#189]
Se requiere generar la respectiva gestión para iniciar la implementación de la caducidad de roles en URANO.

**Sub Tareas**

- [x] Contactar con el responsable para iniciar implementación.
- [x] Verificar y generar el seguimiento al proceso de implementación.

**Criterios de aceptación**

- [x] Implementación de caducidad realizada.
- [x] Anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha comunicado con John y se plantea una reunión con Milton pues Urano No usa wso2 por lo cual toca ver el job para construir en que bases de daatos

Se espera poder agendar reunión

**Comment by mantnicot** [comment]
Se ha agendado una reunión 3/10/2024 a las 3:00 pm con el arquitecto y el encargado de URANO 
[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDAxODM2NTMtM2EzNC00OWViLWExYjQtM2E3MmY1M2EwMmIx%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
No se presentaron ni el arquitecto o el encargado de urano , se intento contacta con cada uno pero ninguno respondio

![Image](https://github.com/user-attachments/assets/0b77a8a9-3b3a-4a05-a295-c0d4da16b5c9)

Se espera poder reagendar la reunión para darle ruta a caducidad

**Comment by mantnicot** [comment]
a las 3:36 se hizo la reunión y se deifnio lo siguiente : 

Hay un job que se ejecuta cada 6 horas el cual revisa si esta activo el usuario y como el rol de contratista no esta en la bd , se hace manual por un modulo , pero ya esta la solución en urano de caducidad de roles.


Se dará prioridad al siguiente sistema para caducidad

**Comment by jcmurilloa** [comment]
De esta manera podemos concluir que la implementación de caducidad de roles se realizó?

**Comment by mantnicot** [comment]
Si , pues ya el sistema cuenta con una implementación de caducidad por lo cual se dirige al siguiente sistema para generar la caducidad de roles.
