### ISSUE TITLE
Implementar funcionalidad nueva del gestor_documental en API de firma_electronica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#19]
Se requiere realizar la implementación de la nueva funcionalidad desarrollada en #18 para realizar el cargue del documento hacia nuxeo y actualizar el registro creado desde la firma electronica.

**Sub Tareas**
- [x] Realizar la implementación de la funcionalidad nueva del gestor documental.
- [x] Documentar la implementación realizada.

**Criterios de aceptación**
- [x] Implementación de la funcionalidad realizada.
- [x] Documentación de la implementación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/05/24

Se inicia con la integración del nuevo método de gestor documental. Comenzando por la creación de un script al final del método de postFirmaElectrónica de la nueva API:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3a7f68bf-2fc7-444e-9dcd-755c7d8fe191)

La variable de entorno GESTOR_DOCUMENTAL_URL se creó en el archivo .env:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f55221aa-a9c2-4c91-bdb8-ef1e205d690f)

Además se agregó una definición de la variable all_metadata inicial para crear el primer DicPostDoc que se había pasado por alto al desarrollar la nueva API:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/c4980d0c-aa3f-4b9e-abb7-888ab8e4516a)

**Adicional a ello se logró deducir que para la firma y el cargue del archivo a nuxeo no es necesario tener el archivo en local, sólo es necesario tener creado el directorio en la raiz del proyecto, y tener el base64 del archivo, el pdf lo crea el script a partir de ese base 64.**

Sin embargo se detectó que el base64 que debía enviarse a gestor documental no era el mismo que la API de firma electrónica recibía en el json como parámetro, si no que debía ser un base 64 del archivo firmado con la firma estampada ya lista para subir. Por lo tanto se creó el script que convertía dicho documento firmado en base 64 en el archivo **firma_electronica.py** y la respectiva corrección en la construcción del JSON que se envía a gestor documental:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/13e729b7-aff8-49ea-af1a-8e711c9c7ae3)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f53629d4-4e7e-4cef-9703-d12c025834fc)

Empezando a realizar pequeñas pruebas de funcionamiento se detectó que el swagger original de gestor documental para firma electrónica estaba desactualizado y por tanto el swagger de la nueva API así como sus parámetros de entrada, ya que revisando bien el código y la documentación, se descubrió que también debían llegar en ese json los firmantes y representantes. Por lo tanto se actualizó el Swagger de la nueva API de firma electrónica de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/1db9b740-952d-4e5d-a37b-00bdf2a30435)


Se continuaron con pruebas de funcionamiento en la integración y se detectó el siguiente error:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2f96671e-eb4b-447f-a307-015ca3805d07)

Realizando Debugging se detectó que el problema ocurría al momento de hacer el post a la tabla firma electrónica de la base de datos de Documentos:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/6c4c0811-25e9-49c5-bd13-c466d21de35a)

Más específicamente en el encode en utf 8 de la respuesta del post. Al imprimir el post devuelve un HTML con un título de Beego application error:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/48e08cff-7bd0-46ee-82ce-29a588575c3c)

Aún no se ha descubierto la causa, queda pendiente entonces por resolver este error

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 30/05/24

Se logró arreglar el error del día anterior además de otros errores con el apoyo del líder de grupo y se logró poner en funcionamiento las dos APIS integradas en local.

Primero se logró identificar comparando con versiones de gestor documental en pruebas se determinó que los campos que le llegaban a firma electrónica eran insuficientes por lo que se modificó ese aspecto en el código agregando el campo de documentoId.

![image](https://github.com/udistrital/core_documentacion/assets/77305100/64981996-45bd-4beb-83d6-39532e87231a)

Se agregó también como parámetro un Self a la función creada en el archivo firma_electronica.py para que dicha función operase correctamente ya que generaba un error al momento de llamarla:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/1beadbae-1821-4b44-93ed-15d3c4126314)

Se corrigieron las rutas en las que se direccionaba a otras APIS quitando las barras inclinadas para que no hubiesen dobles (siendo que en las variables de entorno la ruta termina en una barra inclinada). Sin embargo el cambio más relevante en cuanto a rutas se dió para apuntar a gestor documental, agregando un "document/putUpdate":

![image](https://github.com/udistrital/core_documentacion/assets/77305100/12eced82-1ab2-4d1e-9d87-5309eea3258d)

Se hicieron otras correcciones menores que surgieron de otros errores de funcionamiento. Por último, el JSON que se enviaba a gestor documental se estaba enviando incorrectamente, haciendo que Gestor tomase dicho arreglo como uno por cada campo del JSON enviado, se corrigió agregando paréntesis cuadrados a la creación de dicho JSON:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0c8086eb-b17d-49e8-8302-fc89ac43c36a)

Finalmente se probó y la integración funcionó:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/77f021af-6b73-4716-8194-9763897fd85f)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/04dacf90-4ded-4767-b10a-4c5e084a007b)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0032fc78-e14d-44a9-bc22-798cc7a9aa3f)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/ba94fb99-43aa-4397-8e08-080f4927e055)

Ahora bien, como se puede evidenciar en la última captura, a pesar de que la integración funciona correctamente, en algún punto del proceso de la firma electrónica ocurre una eventualidad que ocasiona que la firma se realice en un punto del documento que no debería, queda pendiente por tanto la revisión de esta situación

**Comment by diagutierrezro** [comment]
Buen trabajo Andres, queda pendiente ajustar la posición de la firma, se trabajará en otra issue.
