### ISSUE TITLE
Mostrar a funcionamiento cliente de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#191]
Se requiere realizar la presentación del cliente de Oikos a funcionamiento con el fin de obtener una retroalimentación del sistema.

**Sub Tareas**

- [x] Realizar presentación a funcionamiento.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Reunión
Se logra tener la reunión con funcionamiento el dia 4/10/2024 a las 11 am

link grabación: 
https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n%20de%20OIKOS%20-%20Primer%20avance%20a%20funcionamiento-20241004_110454.mp4?csf=1&web=1&e=BjyDr3&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by diagutierrezro** [comment]
La presentación se realiza de manera satisfactoria, queda pendiente realizar ultimos ajustes y se iniciará proceso de despliegue

**Comment by diagutierrezro** [comment]
El acta de la respectiva reunión se encuentra en #188
