### ISSUE TITLE
Corregir error al filtrar por palabras clave en tabla de mapeo dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#192]
Se requiere realizar la corrección del error al filtrar por palabras clave, la corrección es la misma a la realizada en #184 

**Sub Tareas**

- [x] Corregir filtro realizado a la tabla.
- [x] Documentar funcionamiento correcto.

**Criterios de aceptación**

- [x] Corrección realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
El error de debe a lo mismo del issue 184, es por una falta de datos completos en los registros de la BD.

En el campo de "Dependencias asociadas" se coloco que si no trae registro, se coloque "NO REGISTRA", para evitar errores en el código y para que el usuario pueda ver que no tiene esa información asociada a la dependencia que busca, como se muestra en las siguientes imágenes:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/62ad61e2-3b64-4e7b-9b4d-c4cba3d43674">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/42f6c77b-5b67-4977-b4dc-55daa8d46c31">

**Comment by JulianAvella** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/732d8ce8-653d-452b-babe-889f7ae5cd30">

**Comment by diagutierrezro** [comment]
Muy buen trabajo Julian.
