### ISSUE TITLE
Limpiar código en cargue de tablas en cliente.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#193]
Se requiere realizar la limpieza del código en el uso de tablas para la gestión de dependencias ya que despues de uan revisión se encontró que tanto para el cargue inicial de la tabla como para la actualización de la tabla se encuentra código duplicado, por esta razón se plantea la opción de transladar la lógica del cargue de la información de la tabla a una nueva función y realizar un llamado de esta función tanto en el cargue inicial como en la actualización de la tabla. Adicional a esto se debe reviar la paginación de tablas al editar los dependencias y recargar la tabla.

Finalmente, agregar el desarrollo para que se recargue la tabla al activar o desactivar una dependencia.

**Sub Tareas**

- [x] Transladar lógica del cargue de la tabla a una nueva función.
- [x] Realizar llamado de la función creada.
- [x] Actualizar tabla al activar o desactivar una dependencia.
- [x] Probar funcionamiento del desarrollo corregido.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Logica transladada.
- [x] Llamado a nueva función realizada.
- [x] Actualización al activar o desactivar desarrollada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* Esta es la función que queda con la lógica del cargue inicial y actualización de la información de la tabla: 

busqueda(busqueda: any = {}): Promise<any[]>{
    this.popUpManager.showLoaderAlert(this.translate.instant('CARGA.BUSQUEDA'));

    return this.oikosMidService.post("gestion_dependencias_mid/BuscarDependencia", busqueda).pipe(
      map((res: any) => {
        if (res && res.Data) {
          return res.Data.map((item: any) => ({
            id: item.Dependencia.Id,
            nombre: item.Dependencia.Nombre,
            telefono: item.Dependencia.TelefonoDependencia,
            correo: item.Dependencia.CorreoElectronico,
            dependenciasAsociadas: item.DependenciaAsociada ? {
              id: item.DependenciaAsociada.Id,
              nombre: item.DependenciaAsociada.Nombre
            }: null,
            tipoDependencia: item.TipoDependencia.map((tipo: any) => ({
              id: tipo.Id,
              nombre: tipo.Nombre
            })),
            estado: item.Estado ? 'ACTIVA' : 'NO ACTIVA',
          }));
        } else {
          return [];
        }
      }),
      catchError((error) => {
        Swal.close();
        this.popUpManager.showErrorAlert(this.translate.instant('ERROR.BUSQUEDA.BUSQUEDA') + (error.message || this.translate.instant('ERROR.DESCONOCIDO')));
        return []
      })
    ).toPromise() as Promise<any[]>;
  }

* Para la función de edición de las dependencias con el recargue de la tabla después de finalizar la edición y con su correcto funcionamiento en la paginación:

<img width="568" alt="image" src="https://github.com/user-attachments/assets/19781155-9c4e-4953-a757-74e661b87b93">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/635bbd94-7044-420d-9ca2-5eb034f97389">
<img width="568" alt="image" src="https://github.com/user-attachments/assets/dcc4938b-24f3-45f8-a2c7-b7cbb509de35">
<img width="571" alt="image" src="https://github.com/user-attachments/assets/cc0f9786-d0e5-4f50-9a3a-3663a8881acc">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/ada4f3a4-db5c-49b2-bba0-263854f84929">
<img width="568" alt="image" src="https://github.com/user-attachments/assets/19d4dd5e-604c-4fb6-b04b-ee3acd0dacdb">

* Para la función de desactivar una dependencia con el recargue de la tabla y funcionamiento en la paginación:

<img width="566" alt="image" src="https://github.com/user-attachments/assets/aabcfc9c-94fb-4465-8efe-f3293772ca58">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/dde25eb7-d743-4731-a075-8a1fd17e3180">
<img width="570" alt="image" src="https://github.com/user-attachments/assets/59972566-f414-4eab-b6f3-ad0c0fd36c1d">
<img width="567" alt="image" src="https://github.com/user-attachments/assets/f5fbd177-3885-455c-9995-ff221b6416f9">
<img width="570" alt="image" src="https://github.com/user-attachments/assets/ed854f14-5379-4fbe-9451-e7e422d5fc6d">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/4fbb536e-c3ec-4d35-b8be-318d1e00478a">

* Para la función de activar una dependencia con el recargue de la tabla y funcionamiento en la paginación:

<img width="568" alt="image" src="https://github.com/user-attachments/assets/8435251c-3ae6-47e9-87f2-d642babb3831">
<img width="569" alt="image" src="https://github.com/user-attachments/assets/f7d636bc-377c-47f7-8616-67a8c48eaecc">
<img width="563" alt="image" src="https://github.com/user-attachments/assets/f9626e52-e738-4d49-9fc9-4a19cb49dc5b">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/c686494b-dd03-42cf-bd37-2f88ec0977e6">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/80aaaa94-4f58-4390-84b6-177c9e1b4f9b">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/519c4f6b-24d4-4bf7-ab88-a1c346d6b9e0">

**Comment by JulianAvella** [comment]
* Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/e5348e61-a45e-45ff-9470-9a967c5d151d">

**Comment by diagutierrezro** [comment]
Se valida el desarrollo realizado, gracias Julian.
