### ISSUE TITLE
Agregar pop up para confirmación de acción de los usuarios

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#194]
Se requiere realizar el desarrollo de pop ups cuando el usuario editar una dependencia o un mapeo dependencias de tal manera que cuando se presione el botón de editar se despliegue dicho pop up donde el usuario tenga que confirmar su decisión, si presiona si se realiza la edición y si presiona se cierra el pop up sin realizar nada. Realizar lo mismo al activar o desactivar una dependencia.

**Sub Tareas**

- [x] Agregar confirmación para edición de dependencias.
- [x] Agregar confirmación para edición de mapeo de dependencias.
- [x] Agregar confirmación para activar o desactivar una dependencia.
- [x] Probar funcionamiento.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Desarrollos de pop ups de confirmación realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Pop up para confirmación en vista de Gestión

Se crean mensajes de confirmación en las tres transacciones de la vista de Gestión:

1. Editar
    Se crea el pop up:
    ![Image](https://github.com/user-attachments/assets/a50268ee-a827-4e26-807f-8dc0c76cd2e8)

    Se comprueba funcionamiento:

    - Editar
       ![Image](https://github.com/user-attachments/assets/e749064a-d8a1-45ad-936d-3d53356160a5)

    - No editar
        ![Image](https://github.com/user-attachments/assets/5076de1c-27f6-47f5-a1d6-da1355d3ee0e)

    - Cancelar
       ![Image](https://github.com/user-attachments/assets/0c54691f-7868-4e69-bbee-d0b5134e2a99)
       En cancelar no se realiza ninguna acción, solo se cierra el pop up.

2. Activar
    Se crea el pop up:
   ![Image](https://github.com/user-attachments/assets/f6035314-3486-4c6d-b725-11ff2aaaef4b)

    Se comprueba funcionamiento:

    - Activar
       ![Image](https://github.com/user-attachments/assets/17be7821-5e06-426c-b072-b15cd283a34b)

    - No activar
        ![Image](https://github.com/user-attachments/assets/83ad91ad-e7e6-46a2-bece-7102a57b76dd)

    - Cancelar
       ![Image](https://github.com/user-attachments/assets/5b662c90-df05-42f2-9237-db5a62c420f1)
       En cancelar no se realiza ninguna acción, solo se cierra el pop up.
 
3. Desactivar
    Se crea el pop up:
   ![Image](https://github.com/user-attachments/assets/cf114691-0c36-43e2-96ef-6c249abc77f5)

    Se comprueba funcionamiento:

    - Desactivar
       ![Image](https://github.com/user-attachments/assets/fe4974ce-163f-4c2e-9b48-dff108b79af7)

    - No desactivar
        ![Image](https://github.com/user-attachments/assets/f18dc0f9-2ade-40cf-b895-443d13ec6e34)

    - Cancelar
       ![Image](https://github.com/user-attachments/assets/9f857b1e-0f05-437f-b463-518fa8bd8baa)
       En cancelar no se realiza ninguna acción, solo se cierra el pop up.

**Comment by xDa04vidx** [comment]
### Pull Request

Se crea pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/0ffe3e25-d747-4d7b-b55d-087e8549e323)

**Comment by xDa04vidx** [comment]
### Pop up para confirmación en vista de Mapeo

Se crean mensajes de confirmación en las tres transacciones de la vista de Mapeo:

1. Editar mapeo
    Se crea el pop up:
    ![Image](https://github.com/user-attachments/assets/59a3eb68-a779-4b82-b585-f0c68c2ea204)

    Se comprueba funcionamiento:

    - Editar
       ![Image](https://github.com/user-attachments/assets/f0f7c9e1-28e5-49b4-9ac6-95eb9bd3b9c1)

    - No editar
        ![Image](https://github.com/user-attachments/assets/b5bac751-5dde-4f01-aa83-35d814469c86)

    - Cancelar
       ![Image](https://github.com/user-attachments/assets/c513452b-28fd-4b35-b756-062fac795e8b)
       En cancelar no se realiza ninguna acción, solo se cierra el pop up.

2. Generar mapeo
    Se crea el pop up:
   ![Image](https://github.com/user-attachments/assets/044baa6f-3384-4274-8dee-9cd45181b70f)

    Se comprueba funcionamiento:

    - Generar mapeo
       ![Image](https://github.com/user-attachments/assets/8c623e76-b703-48f7-b157-532273218628)

    - No generar mapeo
        ![Image](https://github.com/user-attachments/assets/ecb24e4e-a5e7-4a80-a761-69a33b389806)

    - Cancelar
       ![Image](https://github.com/user-attachments/assets/a65c2b6f-740d-4091-b881-8ef8f07b508b)
       En cancelar no se realiza ninguna acción, solo se cierra el pop up.

**Comment by xDa04vidx** [comment]
### Pull Request

Se realiza pull request en [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)

![Image](https://github.com/user-attachments/assets/a41c0d03-a0b0-43b8-ac77-df34ae6f7a25)

**Comment by diagutierrezro** [comment]
Se plantea cambiar los colores utilizados para hacerlo más acorde al cliente. Muy buen trabajo David
