### ISSUE TITLE
Fijar códigos de identificación interna en mapeos de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#195]
Se requiere realizar el desarollo para que tanto en la vista de creación como edición de dependencias se fije el número de identificación interno que corresponde al ID de la dependencia en la tabla dependencia, este campo no puede ser modificado por lo que se requiere que este campo del formulario no sea editable.

**Sub Tareas**

- [x] Precargar número de identificación interno para que se muestre el id de la dependencia al momento de registrar un nuevo mapeo y deshabilitar el campo del formulario para que no se pueda editar.
- [x] Probar funcionamiento.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Número de identificación interno precargado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se logra fijar el código de identificación

Se logra fijar el código en 

1. Generar mapeo
    - Vista    
       ![Image](https://github.com/user-attachments/assets/a90eaed5-b5fa-4b10-8aa8-eceaeed486f5)
    - Funcionamiento
       ![Image](https://github.com/user-attachments/assets/4becdf3b-a784-4ece-97a9-81389585db18)

2. Editar mapeo
    - Vista    
       ![Image](https://github.com/user-attachments/assets/6c1a7426-9e79-434a-abba-0d229d9dc68a)

    - Funcionamiento
       ![Image](https://github.com/user-attachments/assets/57ff721e-47c4-446b-a928-d271a142d403)

**Comment by xDa04vidx** [comment]
### Pull Request

Se agrega el commit al pull request en [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)

![Image](https://github.com/user-attachments/assets/570a2fdb-67b0-49f3-a6eb-e1659ecc0968)

**Comment by diagutierrezro** [comment]
Gracias David
