### ISSUE TITLE
Ajustar menú según rol definido en Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#196]
Se requiere realizar la actualización de los menús según los roles que se definan que tienen acceso al sistema.

**Dependencia**
Consultar con @mantnicot el rol que tendrá acceso al sistema una vez se despliegue.

**Sub Tareas**

- [x] Ajustar menú según el rol definido.

**Criterios de aceptación**

- [x] Menú ajustado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Ajuste de menús según el rol definido

Se ajustan los dos roles

1. SOPORTE_OAS
    ![Image](https://github.com/user-attachments/assets/d50951ba-8d73-4370-b2d1-91db9b3e37b1)

2. GESTOR_DEPENDENCIAS
    ![Image](https://github.com/user-attachments/assets/5a74fec3-164d-4b12-bf9d-e3270c430714)
