### ISSUE TITLE
Implementación de multiples firmantes nuevo en cumplidos CPS - parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#197]
Se requiere realizar la implementación de multiples fimantes en cumplidos CPS, como alcance para esta issue se requiere ajustar el flujo cuando el ordenador del gasto rechace algún cumplido, según lo acordado con Juan Camilo (lider de cumplidos CPS) una vez se rechace se deben modificar los campos activo para volver al paso inicial del flujo sin tener que agregar nueva información en la base de datos. Para esto se requieren realizar cambios en las Apis y posteriormente en el cliente.

**Sub Tareas**

- [x] Modificar la eliminación de los documentos que se habian subido, en su lugar se debe modificar el campo activo.
- [x] Implementar rechazo con el ordenador del gasto.
- [x] Realizar pruebas de funcionamiento

**Criterios de aceptación**

- [x] Modificación realizada.
- [x] Rechazo implementado.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 07/10/24

Según lo acordado con Juan Camilo la semana anterior, una vez completados los cambios necesarios en el mid y el crud de cumplidos se procede a ajustar entonces los flujos de rechazo.

Sin embargo antes se debe ajustar el flujo de eliminación de documentos ya que ahora con los cambios ha de utilizarse el campo de activo de la tabla de soporte_pago_mensual del esquema de cumplidos en udistrital_administrativo, con el fin de manejar una trazabilidad de los documentos subidos pero permitiendo diferenciar cuáles son los documentos en uso y cuales no. Para ello en el cliente, en el archivo cargar_documentos_contratista.js hay una función que se llama borrar_doc la cual es la siguiente:

![image](https://github.com/user-attachments/assets/549191bd-e546-47dc-ba80-74c19132f5f3)

Actualmente está usando gestor documental para solamente alterar el estado del registro del documento en la tabla de documentos y borrar el registro en Nuxeo. Se busca reemplazar esto por un put a soporte_pago_mensual que se describió con anterioridad. Para ello se encontró la estructura que debía llevar dicho put el cual se utilizará como base para crear la petición:

![image](https://github.com/user-attachments/assets/27574e84-9780-4119-9f6b-2b99fcf5259f)

Respecto a la información que se debe tener para poder completar el objeto en su totalidad satisfactoriamente se está explorando la forma de hacerlo, ya sea utilizando un Get o bien reutilizando posibles variables que se estén usando en el archivo, por ejemplo rescatando estas variables que se usan en un método distinto, que pueden servir para realizar las consultas necesarias para completar la información y realizar la petición:

![image](https://github.com/user-attachments/assets/314662a7-9e21-4a2b-abc7-e0dad83cb993)

Por lo tanto hecho este análisis se empezará a desarrollar la implementación de esta funcionalidad. También queda pendiente definir si dichas consultas se realizan por medio del mid o si se hacen directamente al crud

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/10/24

Se realiza la implementación de la modificación del estado del documento en la base de datos al "borrar" un documento subido, persistiendo este en Nuxeo ahora.

Ahora la función modificada tiene la siguiente lógica:

![image](https://github.com/user-attachments/assets/021d316b-f71c-4044-b80b-801b43352978)
![image](https://github.com/user-attachments/assets/02ed488b-99a4-4be9-b697-99b925cc700e)

Siendo que ahora se realiza un get a soporte_pago_mensual en base el id del documento en documentos crud, para luego construir el objeto que se usará en el put y así asignar en falso el valor de estado "activo".

Con esto se realiza una prueba de funcionamiento:

Se inicia subiendo un documento:

![Captura de pantalla 2024-10-08 202256](https://github.com/user-attachments/assets/e2182601-7a42-4bb6-824a-5942774ab96e)

Luego se procede a pulsar el botón de borrar, llamando la función modificada resultando en un caso de éxito:

![Captura de pantalla 2024-10-08 202306](https://github.com/user-attachments/assets/2b0acc34-3fe6-4e69-b531-3f3074deb761)

Confirmando en la herramienta de inspección en el apartado de Network vemos que todas las peticiones incluida el put salieron bien:

![Captura de pantalla 2024-10-08 202312](https://github.com/user-attachments/assets/c3d298d4-a87c-4d28-9f4d-f369df14c149)

En la base de datos el registro fué modificado correctamente:

![Captura de pantalla 2024-10-08 202336](https://github.com/user-attachments/assets/cca96a84-22b3-4c3b-a644-d5d76ee50969)

Y el archivo ya no se carga en la pestaña de documentos subidos:

![Captura de pantalla 2024-10-08 202321](https://github.com/user-attachments/assets/2027a81c-3bd4-4169-9b31-b90f8ee67dd8)

Por lo tanto se concertó una reunión con Juan Camilo para mañana 9 de octubre a las 10 am para concertar el flujo de rechazo del ordenador y así finiquitar la implementación de la firma múltiple en cumplidos.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 09/10/24

Se realiza la reunión con Juan Camilo, y para el flujo del rechazo de ordenador se pidió una demostración a tiempo real del flujo implementado hasta ahora, sin embargo el error de la segunda etapa ocasional que se presentó en el [la parte uno de la implementación](https://github.com/udistrital/core_documentacion/issues/169) se presentó de nuevo y se tuvo que posponer la reunión y por tanto el avance de la implementación hasta la oportuna corrección del error. Por tanto hasta que esto ocurra, remitirse al [issue destinado a la corrección de este inconveniente](https://github.com/udistrital/core_documentacion/issues/201) para el correcto seguimiento de los avances en este aspecto. En cuanto dicho problema se resuelva se comentarán los avances de la última parte de la implementación de cumplidos por medio de este issue

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/10/24

Debido al cambio solicitado por el profesor Daza en la primera etapa de la firma señalada en la actualización del 11/10/24 en el [issue de corrección del error de la segunda firma](https://github.com/udistrital/core_documentacion/issues/201), se procede a adelantar dicha funcionalidad. Primero se reestablece la función de subir el informe de gestión en el archivo **informe_gestion_y_certificado_cumplimiento.js** para que ya no se realice la firma allí:

![image](https://github.com/user-attachments/assets/3d106b29-fc06-4604-9b59-3b5db87a3b80)

Y se comienza a implementar dicho proceso en el archivo **carga_documentos_contratista.js**. Hasta el momento se logró recolectar satisfactoriamente toda la información necesaria para realizar la petición:

![image](https://github.com/user-attachments/assets/253043e2-8763-42b3-b16e-4baade190797)

Y la parte de la petición para firmar y lo que se hace luego por el momento está comentareada:

![image](https://github.com/user-attachments/assets/754bfa66-20c1-4e3a-835a-99d8879a5186)

La razón de esto es que no basta con firmar el documento si no que tiene que ir este anexo con los otros documentos y que sea cargado junto con ellos en la ventana de contratista, y para ello se tiene como base el proceso que se realiza en **informe_gestion_y_certificado_cumplimiento.js** para adjuntar el informe recién generado como soporte de pago. Sin embargo esto implica algunos métodos de los cuales no se está seguro si sea necesario o si se pueda obtener la información necesaria correctamente, además como en un principio se busca implementar la propuesta para el rechazo referida en la entrada del viernes en el [issue de corrección del error de la segunda firma](https://github.com/udistrital/core_documentacion/issues/201), es necesario que el informe sin firma esté en estado activo true por lo que de lado del supervisor y el ordenador podría aparecer tanto el soporte sin firma como el soporte con firma, por lo tanto se consultará con Juan Camilo el proceder para concertar la vía más óptima de implementar esta primera firma al momento de enviar al supervisor los soportes para revisión
