### ISSUE TITLE
Agregar restricción para correos y filtro de inactivos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#198]
Se requiere realizar el desarrollo para que en la sección de registrar o editar el correo sea obligatorio que el correo tenga formato "@udistrital.edu.co". Posterior a esto se debe corregir el filtro de busqueda de dependencias ya que actualmente si no se pone ningun filtro busca unicamente los inactivos. Al no poner nada en los filtros se deben traer todas las dependencias (activas e inactivas)

**Sub Tareas**

- [x] Ajustar campo de correo para obligar que el correo tenga el formato deseado.
- [x] Ajustar filtro en busqueda de dependencias.
- [x] Probar funcionamiento de desarrollos realizados.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Restricción de correo realizada.
- [x] Filtro de busqueda ajustado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Corrección búsqueda en Gestión

Se logra corregir el error de la búsqueda, ahora se crea una función con la cual se devuelve el resultado de la búsqueda de las dependencias, se muestra a continuación como es el funcionamiento:

**Búsqueda por nombre**
![Image](https://github.com/user-attachments/assets/84b0b675-4b33-43a6-97fc-85c296be7b46)

**Búsqueda por tipo**
![Image](https://github.com/user-attachments/assets/8ff77b26-92ae-462a-b3b1-450c0c382d64)

**Búsqueda por Facultad**
![Image](https://github.com/user-attachments/assets/96502396-ba00-4957-8783-6bf4cce725c8)

**Búsqueda por vicerrectoría**
![Image](https://github.com/user-attachments/assets/2c64bbdd-9ac8-4e0f-80de-d7ca657b3d44)

**Búsqueda por estado activo**
![Image](https://github.com/user-attachments/assets/91bfbdbe-3bfd-46dc-ae71-dfe9d221bd2b)

**Búsqueda por estado inactivo**
![Image](https://github.com/user-attachments/assets/087793eb-3fa1-4a10-8f5c-78182f88ba31)

**Búsqueda total**
![Image](https://github.com/user-attachments/assets/22bc891c-5018-4eb5-8f92-d78367f13e83)

**Comment by xDa04vidx** [comment]
### Pull Request

Se agrega el commit en el pull request de [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/babba1c6-a7ef-42ee-ac0e-e338a6aa8560)

**Comment by xDa04vidx** [comment]
### Se realiza la restricción para correo

Se realiza restricción en:

1. Registro

    - Correo diferente
       ![Image](https://github.com/user-attachments/assets/7859202f-14c1-425d-a600-356cae2c11be)

    - Correo '@udistrital.edu.co'
       ![Image](https://github.com/user-attachments/assets/9dc032ce-8045-45c3-b883-8868ff8d63c0)

2. Editar

    - Correo diferente
       ![Image](https://github.com/user-attachments/assets/ad016be0-30e0-46d5-bbfe-6960d8c22a13)

    - Correo '@udistrital.edu.co'
       ![Image](https://github.com/user-attachments/assets/954bed57-92b8-4101-b9b6-eb932f069597)

**Nota**
    Además se cambia para estos formularios que el texto para el nombre de las dependencias sea siempre en mayúscula, pues es la especificación que aparece en el tooltip.
![Image](https://github.com/user-attachments/assets/d871b31e-9883-4eb1-9314-9637b8556f7b)

Se comprueba el funcionamiento correcto

**Comment by xDa04vidx** [comment]
### Pull Request

Se realiza pull request en [gestion_registro_dependencias_mf](https://github.com/udistrital/gestion_registro_dependencias_mf)
![Image](https://github.com/user-attachments/assets/53a8f5dd-9670-49dc-bddc-10fb9c9a3078)

**Comment by xDa04vidx** [comment]
### Corrección búsqueda en Mapeo

Se logra corregir el error de la búsqueda, ahora se crea una función con la cual se devuelve el resultado de la búsqueda de las dependencias, se muestra a continuación como es el funcionamiento:

**Búsqueda por nombre**
![Image](https://github.com/user-attachments/assets/47866111-792d-4fb3-86ed-5ef78d41da41)

**Búsqueda por tipo**
![Image](https://github.com/user-attachments/assets/cbe167e3-7e4b-45d5-a72b-bddfef23a6a4)

**Búsqueda por Facultad**
![Image](https://github.com/user-attachments/assets/bc76e4e4-de5b-4959-874b-824d055bc3ac)

**Búsqueda por vicerrectoría**
![Image](https://github.com/user-attachments/assets/3530312a-b2f9-4c9f-b93b-8b552cc94d74)

**Búsqueda por estado activo**
![Image](https://github.com/user-attachments/assets/61b2df35-3bb6-44eb-91aa-7ba54e4e2362)

**Búsqueda por estado inactivo**
![Image](https://github.com/user-attachments/assets/e3b3fd98-35d4-460e-b855-4fb89cdb8c9a)

**Búsqueda total**
![Image](https://github.com/user-attachments/assets/d7a50502-8fe2-4718-a99f-83a345aea53e)

**Comment by xDa04vidx** [comment]
### Pull Request

Se realiza pull request en [mapeo_dependencias_mf](https://github.com/udistrital/mapeo_dependencias_mf)
![Image](https://github.com/user-attachments/assets/c64165b3-1895-4b40-a3d7-da96277c158d)

**Comment by diagutierrezro** [comment]
Gran trabajo, se valida el funcionamiento correctamente.
