### ISSUE TITLE
Concertar reunión con requerimiento de plantillas

### ISSUE THREAD

**Issue by mantnicot** [udistrital/core_documentacion#199]
Concertar y levantar los requerimientos del modulo de plantillas

**Comment by mantnicot** [comment]
Se ha podido realizar la reunión con el equipo de Norbey [Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWFkNjgxYWMtOTZiZS00NTdkLTg4NjItMmFkYjJkY2JlNjU4%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%220682e8de-4c08-41cb-8451-60d5505efa7b%22%7d)


Se hablo con Fabian y Carlos y se comento que ellos en algun momento estaban trabajando formularios dinamicos y que estos estaban enfocados para ser un microcliente para uso de los sistemas , pero no necesariamente son plantillas. 

Fabian comento que lo mejor es hablar con Eduar Granados y con Brayan Sierra pues ellos deben tener más claro eso

**Comment by jcmurilloa** [comment]
Pendiente entonces continuar esta definición con el cliente interno del área de funcionamiento, así como con @edwargl7 a partir del desarrollo de formularios dinámicos.
