### ISSUE TITLE
Apropiación del sistema de firma electronia

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#2]
Se requiere realizar la apropiación del sistema de firma electronica para comprender el funcionamiento del sistema.

**Sub Tareas**

- [x] Revisión de la [documentación ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElfPf25nNRFBqVVdA5CjgOMB442xygeWyhpSFFM9dqpLxA) existente de firma electronica.
- [x] Identificar y apropiarse del funcionamiento de la firma electronica. 
- [x] Clonar el [repositorio ](https://github.com/udistrital/gestor_documental_mid) en el que se encuentra actualmente el modulo de firma electronica.
- [x] Ajustar entorno de desarrollo según los requerimientos mencionados en la documentación. Ejemplo: Instalar python.

**Criterios de aceptación**

- [x] Revisión de documentación realizada.
- [x] Repositorio clonado.
- [x] AJuste de entorno de desarrollo. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
![image](https://github.com/udistrital/core_documentacion/assets/77305100/c70cff16-f162-4b25-a4cf-89c56d065c97)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/851e99c0-91d0-433b-bea2-d3606ad051c9)
Repositorio clonado

**Comment by Skyrus1203** [comment]
[Apuntes Firma Electrónica.txt](https://github.com/udistrital/core_documentacion/files/15182084/Apuntes.Firma.Electronica.txt)

**Comment by Skyrus1203** [comment]
![Captura de pantalla 2024-05-02 180927](https://github.com/udistrital/core_documentacion/assets/77305100/093a1c14-a6da-4113-a63a-61dca15e13c7)
![Captura de pantalla 2024-05-02 181558](https://github.com/udistrital/core_documentacion/assets/77305100/fae3b5a6-b17d-4ba5-a7ab-6c511df2a693)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/01f97b94-e370-4941-9d11-e7c2e7c6c1cd)
