### ISSUE TITLE
Continuar instrumentalización de APIs con XRay

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#20]
Se requiere continuar con las instrumentalización de APIs  según lo que se encuentra en el [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYHrM0PC9JtMlfe_H5zx6CYBFFLf-JfqULxErrmsDEODSg) definido para la semana 2.

**Sub Tareas**
- [x] Instrumentalizar APIs definidas para la semana 2.
- [x] Realizar la documentación del progreso a lo largo de todo el sprint.
- [x] Realizar las pruebas junto con el lider @diagutierrezro de el correcto funcionamiento con XRay.

**Criterios de aceptación**
- [x] Instrumentalización de APIs definidas.
- [x] Documentación de APIs instrumentalizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
NO se implementa x-ray en la api entradas_crud, porque aparece que esta archivada:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/516cc9b1-44c8-4449-bb82-faaed7796b90">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api minutas_argo_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/a19794f5-ad48-4154-95e1-e3e8443a7705">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api titan_api_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/e41a9da5-4242-46ae-9896-dc29f8a67c44">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api seguridad_social_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/41feafb4-eca0-470a-8289-a0c0a41041c2">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api novedades_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/d0defce1-0134-4900-bae9-b9c80390001e">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api descuento_academico_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/b7051caa-3482-4aeb-b74d-8108415eedc6">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api documentos_campus_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/76e19b33-f5a4-466f-8864-c9485632e701">

**Comment by JulianAvella** [comment]
Se corrige la rama de salida a dev para hacer el merge de la implementación de  x-ray en la api seguridad_social_crud
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/21aa4b48-92ac-4661-8217-6b3a3c93dbdc">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api evaluacion_inscripcion_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/be9f1f9e-c476-48c0-a0d2-132130114896">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api experiencia_laboral_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/56266c26-4051-4669-b314-e9b0e666eacc">

**Comment by JulianAvella** [comment]
Se implementa x-ray en la api formacion_academica_crud:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/84ca87bc-a464-4e97-a403-61acc27afd6e">

**Comment by JulianAvella** [comment]
No se logra implementar x-ray en la api documento_programa_crud, porque genera un error 403 en el push, aún cuando se tiene los permisos para hacerlo:
<img width="732" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/0d5c7da3-d466-44b0-8acb-9ff1c1b1e63a">

**Comment by diagutierrezro** [comment]
Queda pendiente por definir el manejo que se le dará al API documento_programa_crud por lo mencionado anteriormente.

Tambien queda pendiente despliegue a pruebas por parte de @diagutierrezro , a medida que se vayan realizando los despliegues se irá actualizando el documento relacionado.

Buen trabajo Julian.
