### ISSUE TITLE
concertar , levantar requerimientos auditoria

### ISSUE THREAD

**Issue by mantnicot** [udistrital/core_documentacion#200]
Concertar y levantar los requerimientos de auditoria con el cliente

**Comment by mantnicot** [comment]
Se ha agendado al reunión con el cliente de auditoria 

[enlace de reunión ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGYxMThhNzUtZTk3Ny00MDUxLWIzYzgtODJjMzJjM2YwNzJk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by jcmurilloa** [comment]
Pendiente generar la respectiva documentación asociada al requerimiento.

**Comment by mantnicot** [comment]
Se ha realizado la documentación de auditoria
[docuemntacin auditoria](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWHOKCIBBrZPqxZbniF1gXIBI7QhsE5LXM49-_o0vXlr5A?e=pwfw71)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, insumos importante para el desarrollo y cierre de la vigencia del proyecto Core.
