### ISSUE TITLE
Agregar sonar a los diferentes microclientes y mid de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#203]
Se requiere realizar la adición de archivos de sonarQube a los diferentes microclientes y al mid de Oikos con el fin de que se realice el respectivo análisis de código y posteriormente realizar los ajustes que surjan.

**Sub Tareas**

- [x] Agregar archivos de sonar a los microclientes.
- [x] Agregar archivos de sonar al mid.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Archivos en microclientes agregados.
- [x] Archivos en mid agregados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Oikos root
Se agrega el comando de sonar en el drone y se crea el nuevo archivo de propiedades

![Image](https://github.com/user-attachments/assets/71d605b3-5888-47ad-9770-47b36423fe33)

**Comment by xDa04vidx** [comment]
### Gestión y registro
Solo se crea el nuevo archivo de propiedades, dado que el comando del sonar ya estaba presente
![Image](https://github.com/user-attachments/assets/7d8e3126-9bd1-4c78-b1dc-3196f4e801dd)

**Comment by xDa04vidx** [comment]
### Mapeo
Solo se crea el nuevo archivo de propiedades, dado que el comando del sonar ya estaba presente
![Image](https://github.com/user-attachments/assets/30bdfbac-8d4d-4d81-a8d8-62c4323f73c4)

**Comment by xDa04vidx** [comment]
### gestion_dependencias_mid
Ya se encontraban creados y ajustados los archivos necesarios para el sonarQube
![Image](https://github.com/user-attachments/assets/b7e3f794-f716-4b81-a728-e7d011e12c1d)

**Comment by xDa04vidx** [comment]
### Pull request

Se realiza pull request en los micro clientes.

- Root
   ![Image](https://github.com/user-attachments/assets/67a22830-5d5a-496a-90b5-dbf69c28b293)

- Gestión y registro
   ![Image](https://github.com/user-attachments/assets/cef7c302-2add-41fd-b1c4-61589446290a)

- Mapeo
   ![Image](https://github.com/user-attachments/assets/a48a33cc-143b-4127-92e5-1fff0ab8c179)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David.
