### ISSUE TITLE
Concertar, desarrollar y levantar acta sesión de requerimiento cliente plantillas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#205]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos con el cliente módulo de plantillas

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [ ] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado un acercamiento con la Heiner el otro lider para entender el requerimiento desde el equipo y se quedo en una reunión para agendar 18/10/2024 a las 5:30 pm

**Comment by mantnicot** [comment]
Por cuestiones técnicas de parte de Heiner no se pudo realizar la Reunión , pero el envió una reunión de empalme sobre plantillas con Brayan en la cual se confirma que ya hay desarrollos del modulo y que se basa en los formularios dinámicos 

[reunión de empalme](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EfeqkMWtO9tNoeSRT9p9whABKZIrD7xeWpiKM7N9pb3XXw?e=cKBeHO&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Comment by jcmurilloa** [comment]
Con este documento es posible establecer la línea base de desarrollo para este requerimiento?

**Comment by mantnicot** [comment]
Análisis del Sistema Actual de Plantillas y Estado en el Ambiente de Pruebas

Descripción del Sistema de Plantillas

El sistema actual de plantillas cuenta con cuatro servicios principales, entregados en su estructura actual por el equipo liderado por Brayan. Estos servicios están organizados de la siguiente manera:

Microcliente: Este servicio está diseñado para la creación y gestión de plantillas. Su enfoque principal es permitir que el equipo de operaciones pueda administrar eficazmente las plantillas requeridas para distintas funcionalidades.

Microservicio Serveless CRUD: Este componente permite las operaciones CRUD sobre las plantillas, aunque actualmente falta implementar las funciones de actualización de plantillas y el versionamiento.

Plantillas MID: Este servicio intermedio se encarga de los procesos de creación y recepción de plantillas, gestionando las operaciones necesarias para integrar plantillas dentro de flujos más amplios.

Servicio de Renderizado: Este componente procesa las plantillas, transformándolas en formatos utilizables para los usuarios finales.

En el entorno de pruebas, actualmente se encuentran disponibles los siguientes componentes:

Servicio Serveless (CRUD para plantillas): Este servicio permite la creación y obtención de plantillas, funcionando en su capacidad básica.

MID: Aunque el servicio MID está en el entorno de pruebas, es necesario actualizarlo con la versión más reciente, en desarrollo por el equipo liderado por Heiner, que incorporará mejoras en la funcionalidad del servicio.

Renderizado: Este servicio ya cuenta con la funcionalidad de convertir las plantillas en formato HTML y generar archivos PDF, proporcionando los elementos de salida requeridos para la funcionalidad final del sistema.

Se propone que el equipo de Core tome a su cargo el microcliente, dado que este es el servicio principal para la gestión y operación de las plantillas y es clave para el funcionamiento del sistema de plantillas.

**Comment by jcmurilloa** [comment]
Podemos por favor esta información documentarla como lo realizado con la integración de Pólux con biblioteca @mantnicot.

**Comment by mantnicot** [comment]
Se adjunta el documento 

[documento de plantillas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ee29KRClGIhIgy6RRHm6zisBtUe4qfrvlbMznNhCTwubvw?e=6mKHcw)
