### ISSUE TITLE
Modificar proceso de firma.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#206]
Se requiere realizar la modificación del proceso de firma electrónica en el flujo de cumplidos CPS, para esto es necesario almacenar el documento original (sin ninguna firma) el cual es el que se mostrará al contratista cuando no se ha enviado a revisión, una vez el contratista envía los documentos para revisión es que se realiza la primera estampa de la firma. Importante tener en cuenta que una vez se realice el rechazo se retorna al documento original sin firmas ya que una vez se vuelva a enviar los documentos se debe realizar una nueva estampa.

Importante hablar con Juan Camilo para obtener la ruta a seguir en estos ajustes.

**Sub Tareas**

- [x] Modificar proceso de firma en el flujo inicial.
- [x] Analizar rechazo realizado para que retorne al documento sin firmas.
- [x] Documentar avances realizados.

**Criterios de aceptación**

- [x] Flujo de firma inicial modificada.
- [x] Ajustes de rechazo realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 15/10/24

Se tiene una reunión con Juan Camilo para resolver ciertas dudas generadas en la implementación del cambio solicitado por el profesor Daza para la primera firma. Gracias a el se pudo completar la implementación ya que siguiendo lo planeado en la propuesta expuesta en [el issua de corrección de errores](https://github.com/udistrital/core_documentacion/issues/201) se debían realizar unos cambios en el mid, los cuales se describen a continuación:

Ya que la idea es dejar todos los documentos de un proceso (sin firma, firma contratista, firma de supervisor) en activo hasta que el ordenador los apruebe (si no son rechazados) era necesario cambiar el mid de cumplidos para uqe sólo trajera el certificado de cumplimiento activo más reciente, para ello con ayuda y guía de Juan Camilo se implementó el siguiente cambio enla función **TraerEnlacesDocumentosAsociadosPagoMensual** en el helper de **contratista.go**:

![image](https://github.com/user-attachments/assets/4257c6ae-a5a6-42c1-9463-c12645ceb6ea)

Así pues, con algunos apuntes de como terminar de enviar el archivo firmado se realizó la prueba:

Se genera el informe, como se ve ya no tiene la firma al ser generado:

![image](https://github.com/user-attachments/assets/af4b5805-253f-4d7d-b955-bbab1014b8e0)

Se envía al supervisor:

![image](https://github.com/user-attachments/assets/e021b314-3106-497b-85bf-24a428f5a40d)

Y desde la vista del supervisor:

![image](https://github.com/user-attachments/assets/1b5e6f5e-e541-4764-8be1-2a6bf3688948)

De esta forma queda completado el cambio en la primera firma. Por lo tanto queda pendiente la corrección del error  en la segunda etapa y la implementación del flujo de rechazo

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/10/24

Se corrige el problema presente en la segunda etapa de la firma, es decir cuando el supervisor aprueba y firma los soportes del contratista.

Luego de analizar el flujo, se encontró el punto en el que se podría estar generando la discrepancia de archivos ocasionalmente al momento de firmar, resultando en esta función:

![image](https://github.com/user-attachments/assets/9db0cd3b-4405-42c7-a255-960d506746dd)

La cual al abrirla nos encontramos con eso:

![Captura de pantalla 2024-10-16 164529](https://github.com/user-attachments/assets/09498c60-dd66-48cf-aebb-8459c11a7025)

Como se ve se realiza una petición a soporte_pago_mensual la cual devuelve un json que tiene dentro el UID del archivo que se va a firmar. Sin embargo la respuesta de dicha petición estaba trayendo la información mal ordenada ocasionando los problemas descritos en anteriores issues, además de una nueva problemática que se descubrió con la prueba hecha a continuación:

Se generó un certificado desde la ventana de contratista:

![Captura de pantalla 2024-10-16 165312](https://github.com/user-attachments/assets/49da4fec-b315-4999-819a-39435f8c68e1)

Se recibe por parte del ordenador ya firmado:

![Captura de pantalla 2024-10-16 165347](https://github.com/user-attachments/assets/c0115d64-139b-48b5-8b5e-72616e90ec07)

El proceso de firma funciona:

![Captura de pantalla 2024-10-16 165408](https://github.com/user-attachments/assets/5e91c539-ed11-4e4e-97b3-86e4379812da)

Sin embargo al momento de verificar en Nuxeo nos damos cuenta que está tomando el documento sin firma para aplicar la estampa del supervisor:

![Captura de pantalla 2024-10-16 174305](https://github.com/user-attachments/assets/456da7c7-1a5b-4935-9fc7-2c8f8126f261)

Esto es causado por lo descrito anteriormente. Se intentó arreglar esta consulta por medio de postman pero no se logró el resultado esperado por lo que se convocó a Juan Camilo, y con su ayuda se estableció que la consulta estaba mal construida, y es que en el crud, se tiene que el **orderby** hace referencia al orden en el que se rescatan los datos y el **sortby** se tiene como la columna por la cual se ordena, caso contrario a como se tenía en la consulta de la función de traer informe ya que ahí se usaba orderby para señalar la columna para ordenar sin el sort.

Por tanto se corrigió esto agregando a la consulta el sortby, cambiando el orderby por el order y agregando el desc, además de agregar un nuevo filtro para que sólo traiga los archivos con campo activo = true, de modo que la consulta quedó de la siguiente manera:

![Captura de pantalla 2024-10-16 180150](https://github.com/user-attachments/assets/d1f12b0c-1dc5-41fb-8aaf-4251fbe3a6cc)

Así se inicia una nueva prueba y se obtiene el resultado esperado:

![Captura de pantalla 2024-10-16 180224](https://github.com/user-attachments/assets/33835a6f-abdf-43ff-9fd3-f94a2f5df4f7)

Sin embargo para descartar se realiza una prueba más:

Se crea el informe

![Captura de pantalla 2024-10-16 181129](https://github.com/user-attachments/assets/e6fe9ecb-712f-4491-8fcb-66608d6bebfe)

Se envía:

![Captura de pantalla 2024-10-16 181150](https://github.com/user-attachments/assets/67e98d75-0606-4963-bba7-a0584626bbd5)

Desde el lado del supervisor vemos que el documento fué firmado correctamente por el contratista:

![Captura de pantalla 2024-10-16 181444](https://github.com/user-attachments/assets/eeb6fb4b-20cd-4f48-85f2-26214242f09c)

Se aprueba desde el supervisor:

![Captura de pantalla 2024-10-16 181504](https://github.com/user-attachments/assets/00d8abc6-f1ad-47ec-a81d-a23b4271f6d7)

Y se verifica en Nuxeo:

![Captura de pantalla 2024-10-16 181536](https://github.com/user-attachments/assets/cd9aab2c-104c-4b9c-8f23-020249087bb4)

Así bien, queda por finalizada la corrección del error, quedando pendiente únicamente el flujo de rechazo

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 17/10/24

Se inicia con el flujo de rechazo comenzando con el rechazo por parte del supervisor:

Para este punto del flujo se realiza un barrido por todos los soportes de pago activos anexos al pago mensual en cuestion, rescatando sólo los que sean certificados de cumplimiento, para luego desactivarlos todos menos el original sin firma como se hace en este código:

![image](https://github.com/user-attachments/assets/f9cfb5ff-2a55-4073-b6b7-9e88b4e6d4c3)

Así se inicia con la prueba:

Se tiene el siguiente conjunto de soportes:

![Captura de pantalla 2024-10-17 204254](https://github.com/user-attachments/assets/6d1e0606-4308-485c-a45a-2f49b6602d8e)

Se envía al supervisor:

![Captura de pantalla 2024-10-17 204442](https://github.com/user-attachments/assets/f5f28b4f-4aa2-41f7-bef3-2234cd071023)

Como se puede verificar ahora mismo hay dos certificados de cumplimiento activos, el original sin firma y el que se acaba de firmar:

![Captura de pantalla 2024-10-17 204447](https://github.com/user-attachments/assets/0784a92f-dca9-4459-a94d-608e295ddf1e)

Se recibe desde el supervisor:

![Captura de pantalla 2024-10-17 204509](https://github.com/user-attachments/assets/7beb8cbb-833c-4b78-ab49-452b06feb752)

![Captura de pantalla 2024-10-17 204516](https://github.com/user-attachments/assets/5ded1324-a6d0-4adf-a7fb-5a15e389c7df)

Se realiza el rechazo:

![Captura de pantalla 2024-10-17 204537](https://github.com/user-attachments/assets/528a6471-cf46-47c2-889f-a34662cf3e21)

Y ahora sólo está activo el original sin firmar:

![Captura de pantalla 2024-10-17 204554](https://github.com/user-attachments/assets/800d2ec9-23c4-4451-8726-6bb1548ad5a7)
![Captura de pantalla 2024-10-17 204610](https://github.com/user-attachments/assets/77cae304-8bdd-4737-b258-5f9e4f49ba34)

Ahora bien adicional a esto, tanto en caso de que este proceso de rechazo falle tanto para supervisor como para ordenador, se crea un script al momento de enviar a revisión por parte del contratista se desactiven los posibles documentos que hayan quedado activos:

![image](https://github.com/user-attachments/assets/9f3afd79-2d69-4dbd-a355-c45d855ecc52)

La cual es llamada aquí:

![image](https://github.com/user-attachments/assets/368ca0ae-5f1f-4683-9ded-e34dcd2b3e74)


Ahora para el ordenador, el script es casi idéntico al supervisor:

![image](https://github.com/user-attachments/assets/00de99e5-2c9f-4a4b-bcdd-185be41d7249)

Se realizó la prueba a continuación:

Se envía la solicitud al supervisor:

![Captura de pantalla 2024-10-17 204625](https://github.com/user-attachments/assets/ca93dae2-6321-4fb2-9998-65f6e7cdb0f4)

Se aprueba desde el ordenador:

![Captura de pantalla 2024-10-17 204644](https://github.com/user-attachments/assets/9f23e77b-0bf1-43c6-a900-75bc84236d3c)

Como se aprecia a continuación, tenemos activos dos documentos: El original sin firmar y el firmado por el contratista y por el supervisor:

![Captura de pantalla 2024-10-17 221311](https://github.com/user-attachments/assets/2f5cc362-8464-418e-9ad5-a0a810df4bc4)

Desde la vista del ordenador:

![Captura de pantalla 2024-10-17 221249](https://github.com/user-attachments/assets/24a85138-6427-470e-bf30-4ee5ba1252d8)

Se rechaza y se evidencia que sólo esta activo ahora el original sin firmar:

![Captura de pantalla 2024-10-17 221338](https://github.com/user-attachments/assets/b49ac4bc-f114-4c46-8340-cc27c75778e4)

![Captura de pantalla 2024-10-17 221345](https://github.com/user-attachments/assets/b2869d9c-4aac-459b-bd75-8309a16c00e4)


Por tanto los flujos de rechazo quedan correctamente desarrollados y probados. Lo único pendiente es que al aprobar, todos los documentos se desactiven menos el último, es decir, el que ya ha sido firmado por contratista y supervisor.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/10/24

Se finaliza con la implementación de la desactivación de los documentos antiguos al aprobar el ordenador:

La aprobación del supervisor tiene dos funciones, una para aprobar individualmente solicitudes, y otra para aprobar solicitudes en masa, por lo que se tuvo que implementar en ambas:

**Aprobación única:**

Aquí no se tuvo que modificar la función que se venía utilizando para el proceso salvo por el cambio de que ahora sólo dejase activo el documento más reciente del proceso, es decir el firmado por contratista y supervisor.

![image](https://github.com/user-attachments/assets/9ba2e95d-55b9-4c5c-86b1-59f6f4634feb)

Así se realiza la prueba de funcionamiento:

Desde el usuario de contratista se cargan estos documentos y se envían:

![Captura de pantalla 2024-10-18 174729](https://github.com/user-attachments/assets/34013ab4-2269-4e44-ae86-f78e479f4c75)

![Captura de pantalla 2024-10-18 174758](https://github.com/user-attachments/assets/5031bbfe-eada-4f5e-9c58-6a900abea0a5)

Desde el supervisor se reciben y se aprueban para la revisión del supervisor:

![Captura de pantalla 2024-10-18 174824](https://github.com/user-attachments/assets/df81a067-ffb9-45f0-b7d4-d250d78e9220)

![Captura de pantalla 2024-10-18 174850](https://github.com/user-attachments/assets/cd9895ac-658f-4147-b297-9ed4c79f6998)

Como se puede ver en postman, actualmente existen el documento original y el firmado por supervisor y contratista:

![Captura de pantalla 2024-10-18 174911](https://github.com/user-attachments/assets/5b9fb36c-16e4-4a7c-ad97-74d350a2f280)

Ahora desde la vista del ordenador dicho pago se aprueba y si se verifica en postman, se identifica que el documento más reciente fué el que quedó activo:

![Captura de pantalla 2024-10-18 175015](https://github.com/user-attachments/assets/89c17ead-a05c-48f0-802f-e53cd9633af8)

![Captura de pantalla 2024-10-18 175023](https://github.com/user-attachments/assets/cc93b001-b592-4435-9feb-dace502b320b)

**Aprobación Múltiple: **

Para la aprobación múltiple se aprovechó el objeto previamente creado llamado **arreglo_aux** para extraer de ahí los pagos mensuales mediante un proceso de iteración y así aplicar el algoritmo de desactivación a cada uno de los soportes seleccionados. Se tuvo que implementar en dos partes del flujo ya que hay dos casos en los que se aprueban los soportes:

![Captura de pantalla 2024-10-18 193726](https://github.com/user-attachments/assets/56bd05a4-b80c-442a-9f24-17708b0246fa)

![Captura de pantalla 2024-10-18 193748](https://github.com/user-attachments/assets/2139c97c-f65a-4beb-bf5b-7db9bd40641c)

Así bien se comienzan con las pruebas:

Desde el contratista se crean 3 soportes descritos a continuación:

![Captura de pantalla 2024-10-18 182700](https://github.com/user-attachments/assets/f889af40-3577-4179-87c4-c2891f1a44b9)

![Captura de pantalla 2024-10-18 182758](https://github.com/user-attachments/assets/cb6b2b84-53b5-4dc8-8da5-36ac77c5b038)

![Captura de pantalla 2024-10-18 182920](https://github.com/user-attachments/assets/8e9a280d-e2e5-411f-8abd-339d179574d5)

Los cuales son enviados al supervisor, desde el cual se pueden visualizar:

![Captura de pantalla 2024-10-18 183013](https://github.com/user-attachments/assets/643e0ba0-30b4-46c6-993d-c90efda161c2)

A continuación se presenta en postman el estado de los documentos estando firmados por el contratista y el documento original respectivamente (por descuido no se tomó captura cuando se envió al supervisor):

![Captura de pantalla 2024-10-18 183237](https://github.com/user-attachments/assets/77116099-550f-4a90-9a30-e8e47960f8e9)
![Captura de pantalla 2024-10-18 183244](https://github.com/user-attachments/assets/fb90beb1-0c4e-4c81-8157-c30a4d270bc4)
![Captura de pantalla 2024-10-18 183248](https://github.com/user-attachments/assets/876216b7-5efc-4ea3-b9f7-0af5aadc3e5c)

Sin embargo consultando la base de datos se encuentra el consecutivo de estos documentos al ser firmados por el supervisor:

![Captura de pantalla 2024-10-18 185406](https://github.com/user-attachments/assets/fb25b5df-5b49-4c18-9077-ce7495ea99e5)

Ahora desde la vista de ordenador se visualizan los documentos debidamente firmados:

![Captura de pantalla 2024-10-18 183413](https://github.com/user-attachments/assets/9d4ddb17-aeb1-4354-8420-4e82b268f509)
![Captura de pantalla 2024-10-18 184550](https://github.com/user-attachments/assets/656181c6-9f6e-425e-ae53-251fa4c2121e)
![Captura de pantalla 2024-10-18 184628](https://github.com/user-attachments/assets/dd8ae11d-62df-4464-adb3-92e6863f5c35)

Los tres son aprobados y si se contrasta con los registros de la base de datos, se notará que los registros restantes son los más recientes firmados por supervisor y contratista:

![Captura de pantalla 2024-10-18 184657](https://github.com/user-attachments/assets/9cdbd296-13f7-4bfb-bd78-240f83258fdf)
![Captura de pantalla 2024-10-18 184741](https://github.com/user-attachments/assets/af7af76a-6bcf-4632-b326-8d8ba73a031c)
![Captura de pantalla 2024-10-18 184805](https://github.com/user-attachments/assets/e2674fb7-0c40-45c6-b610-80b12d61aa63)
![Captura de pantalla 2024-10-18 184930](https://github.com/user-attachments/assets/5cd3e4af-dc61-4a23-951c-507cf687c1c0)


Siendo así se concluye con la implementación de firma múltiple en cumplidos, se pasa el issue a in review
