### ISSUE TITLE
Realizar ajustes que surjan del uso de sonarQube - Parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#207]
Se requiere realizar el ajuste al código según los hallazgos que se hayan realizado en el sonar implementado en #203, estos reportes se pueden encontrar encontrar en [sonar](https://sonarqube.portaloas.udistrital.edu.co/projects?sort=-analysis_date), los ajustes pueden ser problemas de seguridad, code smells, etc. Es importante tener en cuenta que los ajustes que se realicen no deben afectar el funcionamiento actual del sistema, por lo que puede que no todos los errores del sonar se puedan corregir

**Sub Tareas**

- [x] Realizar ajustes a los microclientes de Oikos (los que no afecten el funcionamiento del sistema).
- [x] Documentar todos los ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
No se realizó avance alguno en esta issue @JulianAvella? no se generó ningún commit frente a desarrollo de estas subtareas!

**Comment by JulianAvella** [comment]
Se corrigen los errores que indica sonarqube;

* Micro frontend **gestion_registro_dependencias_mf**, tiene 28 errores:

<img width="713" alt="image" src="https://github.com/user-attachments/assets/e2e2efa5-d8a2-408d-b496-96c27cbbf153">
<img width="708" alt="image" src="https://github.com/user-attachments/assets/f31dd647-8d1f-4264-90bc-7221d46dd1db">
<img width="714" alt="image" src="https://github.com/user-attachments/assets/36cc3755-cf33-4e3a-989e-42b300186c64">
<img width="706" alt="image" src="https://github.com/user-attachments/assets/37ce6730-50b5-4a29-9d06-7ee333dae6a1">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/d049ad8e-a4e3-4cd0-afa1-ee6d53dae548">

Al hacer el primer push a la rama creada sonarqube, muestra dos errores:

<img width="713" alt="image" src="https://github.com/user-attachments/assets/75443016-12cc-458d-8700-bfd0e75dcb71">

Luego se corrigen de otra manera y ahora si queda sin ningún error reportado:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/03c51a31-6872-4ca9-86a4-08b8e2cfd19c">

Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/dc21d66e-b954-44f9-a17a-0b53e2025fd1">

**Comment by JulianAvella** [comment]
Micro frontend **mapeo_dependencias_mf**, tiene 18 errores:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/ffab38a6-27b8-46ee-be93-350d4cf4b2b9">
<img width="724" alt="image" src="https://github.com/user-attachments/assets/b58f2c9e-6195-488b-9ec1-d86533d5aac1">
<img width="720" alt="image" src="https://github.com/user-attachments/assets/d7c84767-3914-4a5e-bff9-57a182932b86">
<img width="727" alt="image" src="https://github.com/user-attachments/assets/2adaa75c-b7a4-4513-b654-6cc28478bf63">

Al hacer el primer push a la rama creada sonarqube, muestra dos errores:

<img width="713" alt="image" src="https://github.com/user-attachments/assets/b4e05062-bb70-4f41-b4b2-cbbda06d795b">

Luego se corrigen de otra manera y ahora si queda sin ningún error reportado:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/489bbefe-66c8-43f9-b18a-4213c1e01c70">

Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/161a1361-b28f-4df3-b328-ba07e375be09">

**Comment by JulianAvella** [comment]
Micro frontend **oikos_root_mf**, tiene 1 error:

<img width="727" alt="image" src="https://github.com/user-attachments/assets/f26e1f5b-1312-4bfd-bc88-88bcbf714cae">

Se corrigio quitando un comentario.

Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/567bdbfb-a876-4ad6-9a10-9d4c6d76c1a5">
