### ISSUE TITLE
Diseñar el mockup para el módulo Auditoría

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#208]
Se requiere realizar el diseño del mockup para el módulo Auditoría, teniendo como cliente al responsable de funcionamiento

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han creado los mockups 

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eu4BvNtN6sNDhTaS6GsqLUABuDOz7LVlFmnZxRId3ascwA?e=uo8HCG)

![Image](https://github.com/user-attachments/assets/e8610fd3-20b9-4b29-86b2-2ae3e7b89ccd)
![Image](https://github.com/user-attachments/assets/d202e314-1786-4b44-8794-ac404b2718cc)
![Image](https://github.com/user-attachments/assets/44f5557e-afd7-46cc-af89-c5aab335c2b2)
![Image](https://github.com/user-attachments/assets/e7603ef4-3cee-4836-96a1-a664ba0679dc)

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot, revisaremos en el próximo review wl detalle.

**Comment by jcmurilloa** [comment]
Revisado por equipo SoS para muestra al cliente, y definición de tecnología.

**Comment by mantnicot** [comment]
Se ha realizado una v2 de los mocukps por petición del cliente , pero ya fuero aprobados 
Se adjunta la carpeta de la versión 2

[mockups audtioria v2](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EiPoTvkJXeVHgFwS2IpIURIBrDN1iVeudxcryZvNUXTYeg?e=NtDi3t)

![Image](https://github.com/user-attachments/assets/0068516e-c020-4c92-9b34-e6ff1c190751)

**Comment by jcmurilloa** [comment]
@mantnicot excelente diseño!
