### ISSUE TITLE
Actualizar la hoja de ruta y requerimientos (lineamientos) para despliegue a producción de un sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#209]
Se requiere realizar la actualización de la hoja de ruta y requerimientos para el despliegue a producción de un sistema, teniendo en cuenta los lineamientos de la OATI y las actividades de difusión  hacía los usuarios de la Universidad. Se comparten los siguientes documentos para tener una base para su desarrollo:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU6xVqCteLtMgMZWGApXvAUBPBcaY6oAAptK_iXr4X42bA?e=oyQHZw

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYoa200KQKdAl7aAKilus80BTPpOktmXFvqFI_J3BTjkMg?e=DJAbO7

**Sub Tareas**

- [x] Proyectar documento a modo de checklist, con su respectivo flujo, responsable y producto asociado. 
- [x] Exponer documento a equipo SoS.
- [x] Refinar documento según observeciones equipos SoS.

**Criterios de aceptación**

- [x] Documento soporte aprobado equipo SoS.
- [x] Documentación cargada a carpeta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha creado un documento base para poder determinar rutas y despliegue de un sistema
[Documento de ruta](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/caescorciab_udistrital_edu_co/EfBkjBClTWdArYJD1hJZdUcB9P5HOw1cdqXe9dFMCjv5yg?e=oDTybQ)

**Comment by jcmurilloa** [comment]
Buen documento base para la ruta y seguimiento de análisis, desarrollo y despliegue de nuestros proyectos.
