### ISSUE TITLE
Realizar implementación de la actualización del modelo de datos para Oikos_api

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#21]
Se requiere realizar la actualización del modelo de Oikos junto con el CRUD según lo analizado en el issue #22 para dar respuesta a la necesidad presentada desde el sistema de cumplidos CPS.

**Sub Tareas**
- [x] Creación del script de migración con la creación de la nueva tabla y los respectivos contraints para las llaves foraneas y llaves primarias.
- [x] Actualización del CRUD de Oikos_api para aplicar el nuevo modelo de datos.
- [x] Realizar pruebas de manera local.
- [x] Actualizar el swagger.

**Criterios de aceptación**
- [x] Creación del scipt de actualización.
- [x] Actualización del CRUD de Oikos_api
- [x] Actualización del swagger.
- [x] Realización de pruebas.

**Requerimientos**

No aplica

**Dependencias**
- El lider @diagutierrezro debe crear un backup de la base de datos actual para poder realizar las pruebas de manera local ya que no se tiene acceso directo a las bases de datos por API.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Base de datos**

- Se creo un modelo con ayuda de pgModeler, en este se simulo la propuesta realizada de la nueva tabla, se genero la siguiente imagen:

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/afc4fea7-f3c9-4e2b-ad79-0eb88d0ce3d3)

- Con el modelo, la herramienta suministro el siguiente script para la creación de las tablas realizadas. Sin embargo, se tuvo una equivocación y se crearon con un schema llamado public, el cual se procedió a corregirlo.

**Comment by xDa04vidx** [comment]
**Base de datos**

Con ayuda de @diagutierrezro, se obtuvo un backup de la base de datos de OIKOS, para realizar las pruebas. Con este archivo se logró clonar la base de datos en local, para poder realizar las respectivas pruebas de funcionamiento.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/ea34e674-dd26-4a8b-baab-6b3d7f520fc6)

Además, se logró resolver el problema previo relacionado con el nombre del esquema en el SQL generado con pgModeler. Se determinó que el esquema correcto a utilizar es "oikos".

**Comment by xDa04vidx** [comment]
**Base de datos**

El script corregido para la creacion de la nueva tabla es el siguiente:


CREATE TABLE public.cambio_dependencia (
	id integer NOT NULL,
	id_dependencia_nueva integer NOT NULL,
	id_dependencia_antigua integer NOT NULL,
	activo boolean NOT NULL,
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	resolucion varchar(400),
	CONSTRAINT cambio_dependencia_pk PRIMARY KEY (id)
);

ALTER TABLE oikos.cambio_dependencia OWNER TO postgres;

ALTER TABLE oikos.cambio_dependencia ADD CONSTRAINT fk_dependencia_nueva FOREIGN KEY (id_dependencia_nueva)
REFERENCES oikos.dependencia (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE oikos.cambio_dependencia ADD CONSTRAINT fk_dependencia_antigua FOREIGN KEY (id)
REFERENCES oikos.dependencia (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;


**Hace falta una reunión con @diagutierrezro para dar el visto bueno o corregir este script**

**Comment by xDa04vidx** [comment]
**Implementación en el API**

Se creo una nueva rama del repositorio y se creo un primer commit.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/cabbc7ed-6fdc-45cb-b489-8a7d43185b59)

**Comment by xDa04vidx** [comment]
**Base de datos**

Se corrigió el script sql, para la agregación de la nueva tabla en la base de datos.


CREATE TABLE oikos.cambio_dependencia (
id integer NOT NULL,
id_dependencia_nueva integer NOT NULL,
id_dependencia_antigua integer NOT NULL,
activo boolean DEFAULT true NOT NULL,
fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
fecha_modificacion timestamp without time zone DEFAULT now() NOT NULL,
resolucion varchar(400)
);


COMMENT ON TABLE oikos.cambio_dependencia IS 'Tabla que contiene las relaciones entre las dependencias que existen en la Universidad Distrital';

COMMENT ON COLUMN oikos.cambio_dependencia.id IS 'Identificador de la relacion entre dependencias.';

COMMENT ON COLUMN oikos.cambio_dependencia.id_dependencia_nueva IS 'El identificador de la nueva dependencia';

COMMENT ON COLUMN oikos.cambio_dependencia.id_dependencia_antigua IS 'El identificador de la antigua dependencia';

COMMENT ON COLUMN oikos.cambio_dependencia.activo IS 'Valor booleano para indicar si el registro esta activo o inactivo.';

COMMENT ON COLUMN oikos.cambio_dependencia.fecha_creacion IS 'Fecha y hora de la creación del registro en la BD.';

COMMENT ON COLUMN oikos.cambio_dependencia.fecha_modificacion IS 'Fecha y hora de la ultima modificación del registro en la BD.';

COMMENT ON COLUMN oikos.cambio_dependencia.resolucion IS 'La resolucion del cambio de la dependencia';

CREATE SEQUENCE oikos.cambio_dependencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE oikos.cambio_dependencia_id_seq OWNED BY oikos.cambio_dependencia.id;

ALTER TABLE ONLY oikos.cambio_dependencia ALTER COLUMN id SET DEFAULT nextval('oikos.cambio_dependencia_id_seq'::regclass);

ALTER TABLE ONLY oikos.cambio_dependencia
    ADD CONSTRAINT pk_cambio_dependencia PRIMARY KEY (id);

COMMENT ON CONSTRAINT pk_cambio_dependencia ON oikos.cambio_dependencia IS 'Llave primaria de la tabla cambio_dependencia';

ALTER TABLE ONLY oikos.cambio_dependencia
    ADD CONSTRAINT fk_dependencia_dependencia_nueva FOREIGN KEY (id_dependencia_nueva) REFERENCES oikos.dependencia(id);

ALTER TABLE ONLY oikos.cambio_dependencia
    ADD CONSTRAINT fk_dependencia_dependencia_antigua FOREIGN KEY (id_dependencia_antigua) REFERENCES oikos.dependencia(id);

**Comment by xDa04vidx** [comment]
**Pruebas de funcinonamiento**

- **Get All**:
En la base de datos:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/387a6a0b-0bd9-49a4-9b61-e996cc7a4617)

En el swagger:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/76d92cde-c2bb-4578-a3c3-f278070ee54d)

- **Post**:
En el swagger:
    - Petición:  
![image](https://github.com/udistrital/core_documentacion/assets/168471458/64f4b434-e448-4077-8ff5-ee7525905652)

   - Respuesta:
   
![image](https://github.com/udistrital/core_documentacion/assets/168471458/8eda551a-6697-4aa2-8748-5f5e59a10bb4)

Para caso de ingresar una dependencia que no existe:

     - Petición:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/dd82c949-f0ce-4d44-9828-4378dda0be8c)

     - Respuesta:
 ![image](https://github.com/udistrital/core_documentacion/assets/168471458/807c5d4f-c4e4-4945-9971-6903ad5ebcb5)

- **Get by Id**:
En la base de datos:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/5e775406-34d4-4d79-982e-fcecbc5193f3)

En el swagger:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/5569bd9d-8e6b-4499-8ebc-c093b3817e4c)

- **Put**:
Se modificara el registro con Id = 5, se cambiara la depencia nueva a 21 y se cambia la resolucion:
En el swagger:
   - Petición:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/0178758d-aa32-495c-8ade-1ff24852bdae)

   - Respuesta:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/c75b1950-5989-457f-a6c2-11dfbd72954f)

En la base de datos:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/a47d724e-5374-42e2-8284-c732d9a7fc4d)

- **Delete**:
En la base de datos (inicial):
![image](https://github.com/udistrital/core_documentacion/assets/168471458/7c3aa232-ad63-41e7-8353-8903d6f1bed7)

En el swagger:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/d7a8105e-084f-42a0-8da1-ccfd80831804)

Base de datos:
![image](https://github.com/udistrital/core_documentacion/assets/168471458/95fc5298-3137-4b2b-a34c-7a1afe230ab8)

**Comment by xDa04vidx** [comment]
**Cambio en el swagger**
Para poder probar la nueva implementación, se modifico las ruta raiz del swagger, para que se estableciera en la v2.

- ![image](https://github.com/udistrital/core_documentacion/assets/168471458/5bc25c9a-428b-41c7-8d3d-3fb0a01dd922)

- ![image](https://github.com/udistrital/core_documentacion/assets/168471458/0989d883-41e4-4d68-9122-34e4821010e5)

**Comment by diagutierrezro** [comment]
El cambio quedó desplegado en ambiente de pruebas y se notificó para que se realicen las respectivas pruebas.
