### ISSUE TITLE
Gestión para la creación de manuales de usuario del sistema OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#210]
Se requiere realizar la gestión para la creación de los manuales de usuario para el sistema OIKOS.

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión para el día 17/10/2024 a las 11am 
[Link Reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGJmZTc3NmItZjgyZS00NzAxLWE5MzItOGNmODgyZmZlNTNk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha realizado la reunión y se ha definido que se hará entrega el 22/10/2024

**Comment by jcmurilloa** [comment]
Muy buen trabajo, estaremos atentos a la revisión del producto final.

**Comment by mantnicot** [comment]
Se ha dado la entrega del manual

[Carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdX0hSUPGjNKrt1OZDAz78QBMYOwQnXRuUfSPQK0ofbH9Q?e=UdiKSa)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, pendiente añadir comentario frente a gestión de roles en el instructivo, o disponer de un nuevo manual para el rol pertinente.
