### ISSUE TITLE
Realizar ajustes visuales al cliente de Oikos para los módulos de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#214]
Se requiere realizar los ajustes visuales que se soliciten por parte del usuario para que se cumplan los lineamientos y requerimientos realizados al proyecto, estos ajustes pueden requerir cambios de colores en diferentes puntos del flujo, cambios de vistas en general pero son cambios que no afectarán el funcionamiento general del aplicativo.

**Sub Tareas**

- [x] Modificar colores de tablas y alertas mostradas para que coincidan con las solicitadas por funcionamiento.
- [x] Documentar cambios realizados.

**Criterios de aceptación**

- [x] Modificaciones realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 21/10/24

Se tuvo ciertos inconvenientes al ejecutar el cliente de mapeo y el root por lo que se borraron y se volvieron a clonar. Sin embargo al probarlos ya funcionando, resulta que la parte de mapeo no funciona;

![Captura de pantalla 2024-10-21 204939](https://github.com/user-attachments/assets/6245565f-98ff-481a-a5ff-eb5dcd1cacd8)

A pesar de que ambos componentes, el Root y el cliente de mapeo se ejecutan perfecto al parecer el cliente de mapeo no reconoce las variables de entorno correctamente ya que como se evidencia está ejecutandose en el puerto 4200, cuando en las variables de entorno se está configurado para que se ejecute en el 4203:

![Captura de pantalla 2024-10-21 205009](https://github.com/user-attachments/assets/51c7a5e2-d1d3-4678-8596-bb4f50bf845e)

![Captura de pantalla 2024-10-21 205015](https://github.com/user-attachments/assets/1ea678a3-aa83-4ba2-8655-3509bf667286)

Y como se ve el root también se ejecuta en el 4200:

![image](https://github.com/user-attachments/assets/7b472aa1-acb4-4ff5-bb38-36dc87dd5b2b)

Se está buscando una solución

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 22/10/24

Se realizan los ajustes visuales solicitados:

**Mapeo de dependencias:**

El color de la tabla es del color rojo de la paleta de colores, así como también el color del botón de "buscar":

![image](https://github.com/user-attachments/assets/e72dc8dd-1570-4551-947d-adf7a97f2118)

También se ajusta el color de los pop ups informativos:

![Captura de pantalla 2024-10-22 154206](https://github.com/user-attachments/assets/d7c79e6c-c340-48e1-ac6b-410dd7ad4974)

También los botones de edición y mapeo de dependencias al abrir los dialog utilizando los botones de la tabla fueron debidamente modificados:

![image](https://github.com/user-attachments/assets/9ca5d611-daeb-4a65-aaf1-fe212e47e474)
![image](https://github.com/user-attachments/assets/27db8dea-7865-4b99-a38e-19205b9c8dec)

También los pop ups confirmativos fueron ajustados cambiando los botones de confirmación a verde:

![image](https://github.com/user-attachments/assets/e93267b2-fc52-4b83-8c69-f79d32d61c05)
![image](https://github.com/user-attachments/assets/54f9aa6c-a82c-4990-b0cf-b76f9f67cc1f)

Y el pop up de error también fué ajustado:

![image](https://github.com/user-attachments/assets/b6abbf51-c813-4930-b0c8-3374c4570109)

**Gestión de dependencias:**

El botón de buscar dependencias fué ajustado debidamente:

![image](https://github.com/user-attachments/assets/2b038bc0-edbf-46fa-b8bb-b7e29904979e)

También el pop up informativo:

![image](https://github.com/user-attachments/assets/98eb7b11-3a34-469d-871a-1ffcf71a4280)

Los pop ups confirmativos también fueron ajustados:

![image](https://github.com/user-attachments/assets/d30ab0c8-81e8-4d27-ba9d-96d75ae018f2)

![image](https://github.com/user-attachments/assets/5a7550e9-8ae1-4153-9204-8e767dddd1c3)

También el botón de edición de dependencia:

![image](https://github.com/user-attachments/assets/b84c9578-98d7-4eee-9b28-9e4e98a062fe)

**Registro de dependencias:**

Tanto el botón como el pop up informativo fueron modificados de forma satisfactoria:

![image](https://github.com/user-attachments/assets/976512e0-dda9-4dc5-bb41-65e1cf3d00a2)

Por tanto se procede a pasar este issue a in review

**Comment by diagutierrezro** [comment]
Gran trabajo Andres, muchas gracias.
