### ISSUE TITLE
Realizar presentación de ajustes realizados al proceso de firma electrónica en cumplidos CPS.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#215]
Se requiere realizar la presentación a funcionamiento donde se les socialice los cambios realizados al cliente de cumplidos CPS, importante que en dicha reunión se especifique los proceso de firma y los procesos a nivel tecnico que se realizan tanto para la firma como para los rechazos en diferentes puntos del flujo.

**Sub Tareas**

- [x] Realizar presentación a funcionamiento.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/10/24

Se tuvo la reunión con funcionamiento para mostrar la implementación de firma múltiple en cumplidos. La reunión salió bien, surgiendo sólo un par de ajustes siendo estos cambiar un texto en el pop up de confirmación de envío a revisión a contratista, y una documentación de la implementación de firma en cumplidos.
