### ISSUE TITLE
Ajustar diagrama de bases de datos para DB de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#217]
Se requiere realizar el ajuste del diagrama de bases de datos para el esquema de Oikos ya que es un requerimiento para la actualización de esta base de datos en ambiente de producción.

**Sub Tareas**

- [x] Realizar diagrama ER actualizado de la base de datos de Oikos.
- [x] Documentar issue con digrama realizado.

**Criterios de aceptación**

- [x] Diagrama realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
Con ayuda del programa PgModeler, se logra realizar el diagrama actualizado de la base de datos, se muestra a continuación:
![image](https://github.com/user-attachments/assets/62c84f12-2b8f-4c91-9f8e-78a450a31b72)

Sin embargo, el archivo XML que genera la herramienta no se pudo obtener dada la lincencia del programa que se maneja. No obstante se obtiene el archivo .sql

**Comment by diagutierrezro** [comment]
Muy buen trabajo David.
