### ISSUE TITLE
Analizar manejo de guards para implementación en microclientes de Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#219]
Se requiere realizar el análisis para realizar la implementación de guards en el cliente de Oikos, el objetivo de los guards es restringir el acceso a ciertas vistas si el usuario logueado no cuenta con los permisos necesarios, un ejemplo del uso de estos guards se puede encontra en [resoluciones_v2](https://github.com/udistrital/resoluciones_cliente_v2/blob/develop/src/app/pages/pages-routing.module.ts) sin embargo hay que analizar si el uso en una arquitectura de microclientes es el mismo.

**Sub Tareas**

- [x] Realizar análisis de uso de guards en el cliente de Oikos.
- [x] Crear documento (no debe ser formal) donde se muestre un primer acercamiento a los cambios a realizar para la implementación de guards.
- [x] Documentar issue con el documento realizado.

**Criterios de aceptación**

- [x] Análisis realizado.
- [x] Documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 23/10/24

Se realiza una investigación preliminar del uso de los Wards en angular.

Se apropia del proceso de creación por medio del comando `ng generate guard nombre_guard` permitiendo escoger entre diferentes interfaces:

- **CanActivate:** Carga el contenido y confiere acceso sólo cuando el usuario retorne la condición de autorización que se indique
- **CanActivateChild:** Similar al anterior pero enfocado en las rutas hijas de la ruta en la que se especifique el Guard
- **CanDeactivate:** Permite validar solicitudes de salida de la ruta especifica
- **CanLoad:**  útil para sistemas con Lazy load, tiene un uso similar al CanActivate
- **CanMatch:** Se usa en rutas que tienen nombre similar para evitar que el router del sistema haga la cancelación de la navegación y así buscar otra coincidencia de rutas

Ahora bien por el momento se identifica más óptimo para OIKOS el CanActivate y probablemente si se quiere verificar la completitud de formularios puede usarse el CanDeactivate.

Para aplicar cualquiera de los wards se debe agregar a la ruta requerida una clave valor indicando una de las interfaces anteriormente descritas, y cualquier lógica que se ejecute que tenga que ver con estos guards debe desarrollarse en los archivos .guard.ts que se generan.

Ahora para el uso en micro clientes casi no se encontró información salvo en la documentación oficial de Single SPA, enlace el cual adjunto para mayor contexto: [Documentación Single SPA guards](https://single-spa.js.org/docs/api/#canceling-navigation)

Sin embargo, aún no se tiene certeza del correcto uso e implementación de este último apartado a pesar de haber apropiado el concepto y generación de los guards.

Por lo tanto queda pendiente una mejor apropiación de este apartado en aras de elaborar el documento técnico solicitado

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/10/24

Se realiza el documento técnico solicitado, gracias a que el lider de equipo suministró un repositorio en el que se estaban utilizando guards en micro clientes, llegando a la conclusión de que dicha implementación no difiere en el uso de los mismos en sistemas normales de Angular. Por lo tanto se adjunta el enlace del documento:

[Documento técnico para la implementación de guards en oikos](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/ERJRkIg1wnNMqCx8L9KS0RwBP5WcGwDqzTqAEFGF1gwOhQ?e=i6JoWu)
