### ISSUE TITLE
Analizar tareas a realizar para realizar la implementación de modificación en modelo de datos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#22]
Se requiere realizar el analisis de las tareas a realizar para llevar a cabo la implementación del cambio solicitado hacia oikos_api en el siguiente [issue](https://github.com/udistrital/oikos_api/issues/60), este analisis debe incluir desde la realización del script SQL a ejecutar en la base de datos hasta la modificación del API.

**Sub Tareas**
- [x] Realizar el analisis de las tareas a realizar.

**Criterios de aceptación**
- [x] Analisis realizado y documentado en el issue con las tareas a realizar.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Preliminar**
Antes de comenzar con la tarea, se tuvo una reunión con @diagutierrezro, quien me proporcionó información sobre el origen de esta tarea. La razón fundamental es apoyar la petición de la creación de una nueva tabla, explicada en la siguiente imagen:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/5163bc7c-8a03-4d94-8724-a670904218c4)

Como conclusión, se determinó que es necesario realizar todo el análisis previo para implementar esta nueva tabla en el API de oikos_api.

**Comment by xDa04vidx** [comment]
**Análisis**
Se realizo un análisis sobre las tareas necesarias para realizar la implementación de la nueva tabla en el API de oikos_api.

PDF:

[Analisis implementacion de nueva tabla.pdf](https://github.com/udistrital/core_documentacion/files/15375453/Analisis.implementacion.de.nueva.tabla.pdf)

ONEDRIVE:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/EcO-s49VEv1HjeyebR0WtJABPRHvOMtWCTfAaDhZFOXcCg?e=qbVxlY

**Comment by diagutierrezro** [comment]
Documento revisado, buen trabajo David
