### ISSUE TITLE
Iniciar implementación de guards en microclientes de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#220]
Se requiere realizar la implementación inicial de los guards en los microclientes de Oikos, para esto se requiere que se implementen los guards en los diferentes microclientes (gestión y mapeo de dependencias) para que no se tenga acceso a rutas a las cuales el usuario no tiene permisos.

**Sub Tareas**

- [x] Implementar guards en microclientes de Oikos.
- [x] Realizar pruebas de funcionamiento de los guards, para esto es necesario ingresar al sistema con un usuario sin permisos y realizar pruebas para asegurarse que efectivamente no tiene acceso.
- [x] Documentar issue con cambios y pruebas realizadas.

**Criterios de aceptación**

- [x] Guards implementados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/10/24

Se realiza una implementación funcional de los guards salvo por un detalle que se puntualizará más adelante:

Se implementó en los microclientes de **gestion_registro_dependencias_mf** y en **mapeo_dependencias_mf** los respectivos guards, siendo que el proceso es casi idéntico:

En ambos se crearon los archivos respectivos de los guards de forma idéntica quedando de esta manera:

![image](https://github.com/user-attachments/assets/b2fd7dc0-357c-42b4-afd4-af309e8f939f)

En el **app-routing.module.ts** se agregó la clave valor de la interfaz del guard en las rutas pertinentes:

**En gestion_registro_dependencias_mf:**

![image](https://github.com/user-attachments/assets/656e1d73-a569-4d09-8568-3a9a89a2354c)

**En mapeo_dependencias_mf:**

![image](https://github.com/user-attachments/assets/df1d394f-d3d3-4f01-9088-b856b7439136)

Ahora bien en el archivo **auth.guard.ts** de ambos microclientes el código es idéntico, basándose en el código implementado en el microcliente de SGA con ciertas modificaciones se logró implementar los guards funcionales:

![image](https://github.com/user-attachments/assets/d8b1cc45-1a14-485d-826b-acce0e8c3c48)

Así se empieza probando con un usuario con permisos:

![image](https://github.com/user-attachments/assets/4059a14b-8a68-4d6c-9f71-da425005fb39)

Como se ve, en el menú tiene acceso a dependencias y espacios físicos. Por lo tanto debería poder entrar en los microclientes antes mencionados:

**Entra a gestión y registro de dependencias:**

![image](https://github.com/user-attachments/assets/4f04012a-acce-4c40-8dc7-e4ae44c99841)

![image](https://github.com/user-attachments/assets/0a34bec6-c195-462f-9a96-09dd0fa4db57)

**Entra en mapeo de dependencias:**

![image](https://github.com/user-attachments/assets/c8784183-43d0-480f-8e37-1e3fe583f426)

Ahora intentando con un usuario sin permisos:

![image](https://github.com/user-attachments/assets/ebe4c7ed-88a0-422d-90cb-f0bc23114628)

Como se ve no tiene ninguna opción habilitada en el menú por lo tanto no debería poder entrar en los microclientes:

**No puede entrar a gestión y registro de dependencias:**

![image](https://github.com/user-attachments/assets/887db669-8d8a-453b-ab92-fb1dad592f2b)
![image](https://github.com/user-attachments/assets/6de7cd87-d4f1-43a6-a9a6-fa751f0d4d2e)
![image](https://github.com/user-attachments/assets/2576c446-0cfd-450d-9ea8-042e09eb8c67)
![image](https://github.com/user-attachments/assets/7103a2f7-0141-4281-b5e8-0e7b9e3dc856)

**No puede entrar a mapeo de dependencias:**

![image](https://github.com/user-attachments/assets/9cfff044-ff6e-4c40-8919-9b43cbf3def6)
![image](https://github.com/user-attachments/assets/a34dea88-e0b2-4e52-b8ff-44aefa58f733)


Por lo tanto el bloqueo de navegación a usuarios no autenticados queda funcional, sin embargo como se evidencian en las capturas de pantalla, el pop up responsable de notificar el error de permisos no funciona correctamente, lo cual queda pendiente por arreglar. Este error es mostrado en consola:

![image](https://github.com/user-attachments/assets/29df22ad-7697-4e07-9eb5-b5af2c6920c7)

**Comment by diagutierrezro** [comment]
Gran trabajo Andres, gracias.
