### ISSUE TITLE
Realizar ajustes que surjan del uso de sonarQube - Parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#221]
Se requiere realizar la finalización de los ajustes de sonar en el MID de Oikos con el fin de terminar los errores encontrados en los reportes de SonarQube.

**Sub Tareas**

- [x] Finalizar ajustes de errores encontrados en reporte de Sonar en el Mid de Oikos.
- [x] Documentar cambios realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se corrigen los errores que indica sonarqube;

API **gestion_dependencias_mid**, tiene 64 errores:

<img width="716" alt="image" src="https://github.com/user-attachments/assets/e2eeb72b-e75d-4a50-8765-b53ceb3e4275">
<img width="715" alt="image" src="https://github.com/user-attachments/assets/88a0c442-c146-424d-b239-f3e614c2011c">
<img width="713" alt="image" src="https://github.com/user-attachments/assets/62209824-a76b-4d41-9517-1ff094666f19">
<img width="713" alt="image" src="https://github.com/user-attachments/assets/19b30a17-15ca-42df-aafa-721af764c49f">
<img width="719" alt="image" src="https://github.com/user-attachments/assets/9eb57062-2193-4f36-9116-d037d3880ef2">
<img width="727" alt="image" src="https://github.com/user-attachments/assets/548e3f9d-1747-402a-b35b-eed2a4e30eba">
<img width="728" alt="image" src="https://github.com/user-attachments/assets/19b4d0ce-4aae-47d2-aeb8-461ded4ab58d">
<img width="725" alt="image" src="https://github.com/user-attachments/assets/194a5c62-932a-40fa-b6e9-4eb375fbd354">
<img width="734" alt="image" src="https://github.com/user-attachments/assets/23bed6d3-3aeb-4c6f-93f1-291e90e8714c">
<img width="722" alt="image" src="https://github.com/user-attachments/assets/85beafcb-c0cb-4b00-889b-cc74c5379fe6">
<img width="724" alt="image" src="https://github.com/user-attachments/assets/7e097a46-3052-4136-bf94-d2c4038ce042">

**Comment by JulianAvella** [comment]
Al hacer el primer push a la rama creada sonarqube, muestra 17 mejoras a realizar, pero estas no se van hacer debido a que esto no mejoraria el funcionamiento o rendimiento del sistema, y lo que haría es desarrollar más código porque las mejoras que indica sonarqube es para subdivir una función en más funciones, esto haría más complejo el código de entender para el desarrollador:

<img width="722" alt="image" src="https://github.com/user-attachments/assets/e19ac002-b0fb-4f79-a331-56828681fa81">
<img width="722" alt="image" src="https://github.com/user-attachments/assets/e6a91743-fbbc-42bf-ac6d-898ccf60e8ba">
<img width="722" alt="image" src="https://github.com/user-attachments/assets/ccccc41f-3167-489b-8f77-ac1cf8ade78b">

**Comment by JulianAvella** [comment]
Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/3b2c9f0d-39f8-435c-8a43-c784fc7d15c1">
