### ISSUE TITLE
Realizar pruebas funcionales del sistema de Oikos en ambiente de pruebas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#222]
Se requiere realizar las pruebas funcionales de Oikos, todas las pruebas que se realicen deben quedar documentadas tal como se hizo en el issue #39 en un excel, tanto las exitodas como las erroneas.

**Sub Tareas**

- [x] Realizar y documentar pruebas funcionales.
- [x] Documentar issue con link de pruebas realizadas.

**Criterios de aceptación**

- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 31/10/24

Se inicia con la documentación de las pruebas funcionales, siendo que se realizaron seis pruebas de Guards (3 de las cuales no se pudieron completar por que olvidé realizar los pull request para incluir esta funcionalidad en el ambiente de pruebas) y se realizaron 4 pruebas al módulo de registro de dependencias probando cada una de sus funcionalidades y gestión de formularios, se adjuntan capturas demostrativas de las 10 pruebas realizadas hasta ahora:

![image](https://github.com/user-attachments/assets/2fb0d697-abd1-4f81-a46f-6217a79ea311)
![image](https://github.com/user-attachments/assets/aebdf6f5-1e73-430e-9327-1314c87b3cf6)

Las tres pruebas en amarillo son las de los guards que no se pudieron completar.

![image](https://github.com/user-attachments/assets/8ec68b5f-d4a1-4e38-8902-7e26e4eaf1aa)
![image](https://github.com/user-attachments/assets/50f15d5b-7711-4300-8cc5-231c3db0466c)

Queda pendiente probar los módulos de gestión de dependencias y mapeo, además de terminar las pruebas de los guards

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 02/11/24

Se finalizan las pruebas en ambiente de pruebas de OIKOS, surgiendo 3 pruebas fallidas y una por comprobar. Las tres fallidas corresponden a que por alguna razón los guards no funcionan correctamente en ambiente de pruebas, y la prueba a comprobar corresponde a la generación de mapeo de dependencias que al momento de generar un mapeo de una dependencia que ya está mapeada envía una ventana de error que no es clara y puede prestarse para confusiones, así que es necesario corroborar que dicho comportamiento de muestra de la ventana de error es el debido.

El resto de pruebas salieron exitosas, para más información remitirse al archivo en el cual se documentaron todas las pruebas, el cual se adjunta a continuación:

[Documentación de pruebas funcionales en ambiente de pruebas de OIKOS](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/davagomezr_udistrital_edu_co/ERBpewzSo0ROuLSVdrDBKhgB6PJY9JHV6VSU_VBEpfHpVA?e=zyhKdO)
