### ISSUE TITLE
Iniciar implementación de lógica en vista de registro de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#223]
Se requiere realizar la implementación de la lógica en el módulo del registro de espacios fisicos. Se debe analizar si al realizar registros nuevos se deben afectar multiples tablas, en caso de que sí, estas se deben realizar a modo de transacción como se realizó en el primer alcance en el que se realicen los diferentes POST y sus respectivos rollback en caso de que algo falle.

**Sub Tareas**

- [x] Implementar lógica en módulo de registro de espacios fisicos.
- [x] Realizar transacción en mid de espacios fisicos (se debe crear nuevo repositorio).
- [x] Documentar issue con ajustes realizados.

**Criterios de aceptación**

- [x] Implementación de lógica realizada.
- [x] Creación de transacción realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto

Se han realizado diferentes progresos en la tarea.

1. En el mid
    Se creo el mid, con una estructura similar a la creada en el mid de dependencias:
    ![Image](https://github.com/user-attachments/assets/8d08819c-440f-4a76-8423-e3d0478ffbbe)
    Además ya se tiene la lógica para poder crear, espacios físicos, crear un registro en la tabla que relaciona dependencias y espacios físicos (asignacion_espacio_fisico_dependencia), crear un registro en la tabla que relaciona espacios físicos con su tipo de uso (tipo_uso_espacio_fisico) y para crear campos.
   No obstante, hace falta crear los registros en la tabla que relaciona campos con espacios físicos. 
   En la lógica que se esta implementando se esta tratando de implementar funciones.
   ![Image](https://github.com/user-attachments/assets/f456ad1a-1a5e-45bf-a460-cc4296c4e062)

2. En el cliente
    En el cliente ya se tiene la creación del json que se envía al backend, en este se toman los valores que se obtienen del formulario de registro.
    Además se realizo la implementación de la comprobación para realizar el registro:
    ![Image](https://github.com/user-attachments/assets/551398af-1af8-48a4-ad05-4797c38d8e6d)
   También ya se esta conectando el cliente con el backend y se mapeo las respuestas positivas y negativas, según sea el caso.

   - Error
     ![Image](https://github.com/user-attachments/assets/db40c4d7-ab58-4a60-b8e1-1b2ecc83f806)

   - Éxito   
     ![Image](https://github.com/user-attachments/assets/b3585612-a5f5-45d7-a499-cf458000ecd1)

3. Correcciones de la BD
    Se encontraron algunos errores en el momento de crear registros, pues existían errores de la secuencias de los id's, con ayuda del líder @diagutierrezro se logro solucionar estos errores.


### Faltantes

- Hace falta crear los registros de la tabla que relaciona los campos y los espacios físicos.
- Realizar los rollbacks

**Comment by xDa04vidx** [comment]
### Creación de los registros

Se evidencia que al enviar el POST con el json que contiene la información para la creación, funciona de manera correcta y crea cada registro
![Image](https://github.com/user-attachments/assets/25622fc2-eb4c-42e3-b197-9da4e56abf13)

Ahora se mostrará cada registro para asegurar su correcto funcionamiento (por el manejo de fechas se evidencia que están recién creados esos registros).
**Espacio físico**
![Image](https://github.com/user-attachments/assets/90e26c13-9fe3-408b-a266-807189cb69d1)

**Asignación espacio físico dependencia**
![Image](https://github.com/user-attachments/assets/c58c1bf9-6cf0-4f25-92f2-b282dfe0f680)

**Tipo uso espacio físico**
![Image](https://github.com/user-attachments/assets/022f09a5-354b-4c91-b2a0-a09d9d555d56)

**Campos**
![Image](https://github.com/user-attachments/assets/114d1978-f9d7-45d2-b123-987b3f8266ba)
![Image](https://github.com/user-attachments/assets/f81ea94c-2f6e-4deb-a0f2-e9b322f9c45a)

**Espacio físico campo**
![Image](https://github.com/user-attachments/assets/191bda0a-2ae0-4745-98d1-2db2e4537601)
![Image](https://github.com/user-attachments/assets/9eaac0b7-464c-4f95-a843-c0555dc9a67d)

**Comment by xDa04vidx** [comment]
### Rollbacks
Para el uso y comprobación de los rollbacks, se realizaran errores intencionales en las transacciones POST, y así simular los fallos.

**Fallo en creación del espacio físico**
![Image](https://github.com/user-attachments/assets/b0a55627-2ab1-4fcd-a442-b92dcb9a9e14)
En este punto, no existe ningún rollback, dado que es la primera transacción y si no se crea no hay ningún problema con otros registros.

**Fallo en asignación espacio físico dependencia**
![Image](https://github.com/user-attachments/assets/2ba6a225-3774-499a-bda9-43e2b77a32df)
Con la flecha roja se muestra el punto del error y con la flecha verde el id del espacio físico creado, luego al buscar este id del espacio físico, se comprueba que se elimino satisfactoriamente este registro.
![Image](https://github.com/user-attachments/assets/421b7333-796a-45b6-b3ce-772dce42cc14)

**Fallo en tipo uso**
![Image](https://github.com/user-attachments/assets/37dffa68-62cc-4b41-8b2c-a8d8375f7b08)
Con la flecha roja se muestra el punto del error y con la flecha verde el id del espacio físico creado y el de asignación espacio físico dependencia, luego se buscan estos id´s y se comprueba que se eliminaron satisfactoriamente estos registro.
![Image](https://github.com/user-attachments/assets/988360d9-2d29-414f-982b-08854ed2daae)
![Image](https://github.com/user-attachments/assets/3953baac-874f-494a-b63e-cd91fde2ca63)

**Fallo en creación de campo**
En este punto existen dos posibles errores, el primero que cuando se esta creando el primer registro de campo falle, y el segundo cuando ya se ha creado un campo, en el primer caso se debe entrar al rollback de tipo uso y en el segundo en el mismo de campo.

- Primer caso
   ![Image](https://github.com/user-attachments/assets/6c3fc0dd-f736-4165-857e-fd8786e994bd)
   ![Image](https://github.com/user-attachments/assets/f136bb91-c748-43e0-ac7a-5d8a38527df1)
   Con la flecha roja se muestra el punto del error y con la flecha verde los id's de los registros creados, luego se buscan estos id´s y se comprueba que se eliminaron satisfactoriamente estos registro.
   ![Image](https://github.com/user-attachments/assets/04e3b6c1-acf5-411a-ac4d-36b5eedbaa23)
   ![Image](https://github.com/user-attachments/assets/f155d630-a786-4f1b-a68d-490e487979b1)
   ![Image](https://github.com/user-attachments/assets/b33aab24-d409-455a-85d1-d755ddf2de42)

- Segundo caso
   ![Image](https://github.com/user-attachments/assets/74598afc-e8b1-42d1-99d8-ccf6dffbe8ac)
   Con la flecha roja se muestra el punto del error y con la flecha verde los id's de los registros creados, luego se buscan estos id´s y se comprueba que se eliminaron satisfactoriamente estos registro.
   ![Image](https://github.com/user-attachments/assets/7d88b42a-aebe-4801-ae6f-c93861bfb4fd)
   ![Image](https://github.com/user-attachments/assets/b5292d71-1eb9-4acb-b0d5-7dff0bcd59b0)
   ![Image](https://github.com/user-attachments/assets/8063d695-1fa4-4b38-93a8-2a6568793905)
   ![Image](https://github.com/user-attachments/assets/ef1891cc-ef94-4a09-8e39-eef15815cc15)

**Fallo en creación de campo espacio físico**   
En este punto existen dos posibles errores, el primero que cuando se esta creando el primer registro de campo espacio físico falle, y el segundo cuando ya se ha creado un campo espacio físico, en el primer caso se debe entrar al rollback de campo y en el segundo en el mismo de campo espacio fisico.

- Primer caso
   ![Image](https://github.com/user-attachments/assets/378c31a6-b20a-4fc5-be05-afff1657b7ff)
   Con la flecha roja se muestra el punto del error y con la flecha verde los id's de los registros creados, luego se buscan estos id´s y se comprueba que se eliminaron satisfactoriamente estos registro.
   ![Image](https://github.com/user-attachments/assets/f8f26d61-3676-4ea6-955e-4812c3d99f5d)
   ![Image](https://github.com/user-attachments/assets/eb519220-0590-4b47-b109-9d99ab5b08a6)
   ![Image](https://github.com/user-attachments/assets/fd661237-3893-4f99-a931-a70c21c8a86c)
   ![Image](https://github.com/user-attachments/assets/2913aab3-4a52-4040-aead-ed4f8c42ef83)
   ![Image](https://github.com/user-attachments/assets/b6a2c84f-a386-4ac9-bda9-1f33f4936647)

- Segundo caso
   ![Image](https://github.com/user-attachments/assets/b71e3721-6758-4913-9bbe-2659f7493fc9)
   ![Image](https://github.com/user-attachments/assets/5f5c4315-1b43-40ae-87fa-f82b918e1c6a)
   Con la flecha roja se muestra el punto del error y con la flecha verde los id's de los registros creados, luego se buscan estos id´s y se comprueba que se eliminaron satisfactoriamente estos registro.
   ![Image](https://github.com/user-attachments/assets/c8792597-b40e-4ea2-930f-1376c010a836)
   ![Image](https://github.com/user-attachments/assets/095329b9-f66b-4fb9-b274-54fd167e5181)
   ![Image](https://github.com/user-attachments/assets/67ca5025-f03c-4af8-9691-18d4ea04ff66)
   ![Image](https://github.com/user-attachments/assets/1e1bd0d1-f045-44e5-9cba-42b83788b69a)
   ![Image](https://github.com/user-attachments/assets/2ac4108e-afdb-40a8-8f22-faec2bac2328)
   ![Image](https://github.com/user-attachments/assets/68944c8c-35a0-43fc-a331-fe0ff651be43)

**Comment by xDa04vidx** [comment]
### Pull request

Se crea pull request en [gestion_espacios_fisicos_mid](https://github.com/udistrital/gestion_espacios_fisicos_mid)
![Image](https://github.com/user-attachments/assets/62e38841-bb80-445a-bd31-bee527f13fc4)

**Comment by xDa04vidx** [comment]
### Pull request

Se agregan los cambios del frontend en el pull request de [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)
![Image](https://github.com/user-attachments/assets/447a0d4f-aad4-41d9-9051-3280a6939baf)
