### ISSUE TITLE
Actualizar con caducidad de roles y plantillas la hoja de ruta y requerimientos (lineamientos) del proyecto CORE

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#225]
Se requiere realizar la actualización de la hoja de ruta y requerimientos del proyecto CORE  para caducidad de roles y plantillas, teniendo en cuenta los lineamientos de la OATI y las actividades de difusión hacía los usuarios de la Universidad. Se comparte el enlace donde se viene consolidando la ifnromación:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ea4iWNAw-a1Em86ihVSUP-0B54wAyxycFDpYfpAqjmc4Sw?e=yeRBNO

**Sub Tareas**

- [x] Proyectar documento a modo de checklist, con su respectivo flujo, responsable y producto asociado. 
- [x] Exponer documento a equipo SoS.
- [x] Refinar documento según observeciones equipos SoS.

**Criterios de aceptación**

- [x] Documento soporte aprobado equipo SoS.
- [x] Documentación cargada a carpeta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha actualizado el documento con caducidad , ya solo falta lo de plantillas 

[Documento de ruta](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/caescorciab_udistrital_edu_co/EfBkjBClTWdArYJD1hJZdUcB9P5HOw1cdqXe9dFMCjv5yg?e=bzMltY)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, pendiente culminación con módulo de plantillas.

**Comment by mantnicot** [comment]
Se ha actualizado el documento de ruta con el modulo de plantillas

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, continuaremos de esta manera alimentado este instrumento en cada etapa del proyecto.
