### ISSUE TITLE
Realizar la gestión para actualización del formato de sábana de notas relacionado con el nombre del secretario académico

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#226]
Se requiere realizar la gestión para actualización del formato de sábana de notas relacionado con el nombre del secretario académico.

**Sub Tareas**

- [x] Adelantar contacto para desarrollo de aprobación del formato de sábana de notas.
- [x] Solicitar requerimiento para generar la respectiva modificación.

**Criterios de aceptación**

- [x] Aprobación por secretaria académica del formato.
- [x] Requerimiento a funcionamiento solicitado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.

**Comment by mantnicot** [comment]
Se ha hablado con secretaria academica pero no se ha dado respuesta aun
![Image](https://github.com/user-attachments/assets/f4aab383-ab22-4ed4-9c0e-d92a4c553939)

**Comment by mantnicot** [comment]
Se ha hablado con la persona encargada de secretaria y esta nos ha dicho que esa gestión se tiene que hacer por medio de la aprobación de los secretarios académicos y posterior a eso con vice académica , ys e recomienda que lo hagamos con el ingeniero Milton.

![image](https://github.com/user-attachments/assets/cde25ba8-98a5-4bf4-89f9-abbb8890d62f)

Posterior a esto se comunica con el ingeniero y nos cuenta que desde un principio se buscaba la reunión o socilización de la sabana de notas con la nueva firma 

![image](https://github.com/user-attachments/assets/884b8ef4-dda1-4fe7-a695-011fe439299a)


por lo cual la gestión sería que reuniera a los 6 secreatirrios en pro de obtener el aval y posterior a eso a viceacademica

**Comment by jcmurilloa** [comment]
@mantnicot el siguiente paso sería esta gestión? O solo elevaríamos la conclusión y solicitud a funcionamiento para que continúe el procedimiento?

**Comment by mantnicot** [comment]
se realizara un correo informativo para funcionamiento ( computo ) , Eduar y Milton , donde se expondrá lo realizado

**Comment by mantnicot** [comment]
Gracias a la comunicación via whatsapp se informo al Eduar sobre el tema y se espera decisión de equipo para saber como gestionamos el avance

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot
