### ISSUE TITLE
Iniciar creación de estructura en microcliente de auditoría.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#227]
Se requiere realizar el la estrucutra basica del módulo de auditoría el cual se realizará con microclientes, los mockups se encuentran en #208, se debe iniciar creando el microcliente desde cero realizando las configuraciones necesarias de Single SPA para que se pueda realizar la respectiva conexión con el root. Se propone usar como prueba inicialmente el root de Oikos.

Una vez se realice la configuración y conexión inicial se deben crear los menus (inicialmente en OIKOS, el cual usaremos como prueba) para poder redirigir hacia el microcliente creado y una vez realizado esto se puede iniciar con el desarrollo de la estructura básica.

**Sub Tareas**

- [x] Crear microcliente de auditoría realizando al configuración y conexiones iniciales.
- [x] Crear menú en Oikos para redireccionar al microcliente.
- [x] Iniciar creación de estructuras en el microcliente de Oikos teniendo en cuenta los Mockups V2

**Criterios de aceptación**

- [x] Microcliente creado y configurado.
- [x] Menú creado.
- [x] Estructuras de microcliente desarrolladas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Esta es la forma como esta quedando los filtros de busqueda con la tabla de Auditoria:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5964734d-83a2-49ad-bcf4-df1aa05174b8">

Pero se tiene un error cuando se le da clic en la acción de "ver detalle log", porque no muestra un error en la consola, ni en las terminales además que hace que se oculte los filtros y la tabla, entonces es como un bug y se esta probrando diferentes formas para quitar ese error.

**Comment by JulianAvella** [comment]
* Con la ayuda de @xDa04vidx "David", se realizo la configuración inicial con el single spa de angular, además de conectarlo con el micro frontend de oikos_root_mf, con el fin de poder ver la parte visual de como estaría quedando la estructura de auditoria; se solicito la ayuda ya que él ha realizado varios microclientes y tiene el conocimiento para agilizar este proceso y evitar que se genere una demora por un error en la configuración, y aprendi como se debe realizar.

Asi quedo la estructura de archivos del microcliente: 

<img width="187" alt="image" src="https://github.com/user-attachments/assets/90461ce0-5ff9-4df5-9372-401a832d7e85">
