### ISSUE TITLE
Generar el despliegue en producción de sistema OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#228]
Se requiere realizar el despliegue en producción de sistema OIKOS

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [ ] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2
- [ ] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [ ] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [ ] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [ ] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [ ] Revisión de estado de bases de datos (ETL)
- [ ] Revisión de actualización de APIs consumidas (terceros, transversales)
- [ ] Definición y/o actualización de manual de usuario/videotutoriales
- [ ] Documento técnico

**Nota:** Este sistema tiene creado un ambiente de producción para las APIs MID y CRUD y para el Cliente, por lo que se requiere tener mucho cuidado con el incremento para no afectar data en producción.

**Comment by diagutierrezro** [comment]
Se realizan las solicitudes para despliegue a producción 
MID https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=66638
ROOT https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=66639
MF1 https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=66640 
MF2 https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=66641

**Comment by diagutierrezro** [comment]
Las pruebas funcionales se inician en el issue #222

**Comment by diagutierrezro** [comment]
Se solicita la realización de pruebas de carga y seguridad https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=66342

**Comment by diagutierrezro** [comment]
Se realizan pruebas unitarias en #202 #216
