### ISSUE TITLE
Construir acta de entregable para sistema OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#229]
Se requiere realizar la proyección del acta de entregables para el sistema OIKOS

Subtareas**

- [x] Recopilar la información técnica de cada modalidad
- [x] Construir el acta de entregables del sistema
- [ ] Exponer acta de entregables a funcionamiento

**Criterios de aceptación**

- [x] Acta de entregables documentada
- [ ] Acta de entregables aprobada por funcionamiento

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Por motivos de salud no finalicé el issue, se finalizará para el siguiente issue.

**Comment by diagutierrezro** [comment]
Se crea [acta de entregables](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Ec_GZ88YGvJKvaYJsswjzm4BeLPUts3102uqUfHZI7-ssA?e=YFGu7t) para el cliente de Oikos

**Comment by jcmurilloa** [comment]
De esta manera se inicia con la respectiva recolección de firmas.
