### ISSUE TITLE
Creación de documentación técnica sistema OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#230]
Se requiere realizar la construcción de la documentación técnica del sistema OIKOS respecto a requerimientos de funcionamiento, teniendo en cuenta la del sistema pólux: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ

**Sub Tareas**

- [x] Recopilar la información necesaria para proyección de documento
- [x] Construir la documentación técnica
- [ ] Exponer documentación a equipo SoS y funcinamiento

**Criterios de aceptación**

- [ ] Documentación técnica almacenada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Por motivos de salud no finalicé el issue, se finalizará para el siguiente issue.

**Comment by diagutierrezro** [comment]
Se crea el [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EaEue48QVg9OlAc0nwqs1MgB_lO2_1K1nZrM1fsrvXjTtA?e=eCdIv5) con la descripción técnica de Oikos

**Comment by diagutierrezro** [comment]
Queda pendiente los diagramas modular y de proceso general. Se recibirá apoyo de @mantnicot y desarrollo
