### ISSUE TITLE
Corregir error de popups para guards en Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#231]
Se requiere realizar la corrección de los errores en los popups de Oikos para obtener los textos desde el diccionario de textos. Se debe revisar por que no está alcanzando el archivo donde se encuentran los textos y realizar los ajustes necesarios para que el texto se obtenga de allí.

**Sub Tareas**

- [x] Realizar ajustes necesarios para poder obtener los textos desde el diccionario de datos.
- [x] Realizar pruebas del funcionamiento correcto.
- [x] Documentar en el issue ajustes y pruebas realizadas. 

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 28/10/24

Se corrige problema de pop ups, realizando un proceso idéntico en ambos micro clientes. 

Se agrega al diccionario de traducciones (es.json) una clave valor de ROL con su respectivo mensaje equivalente:

![image](https://github.com/user-attachments/assets/6d826739-10f3-46a0-8d08-99080496af88)

De igual forma en el guard se agrega el comando para establecer el diccionario de traducciones a utilizar:

![image](https://github.com/user-attachments/assets/29a37f5c-00df-4b3c-98bd-03a62c23c6ff)

También, al ejecutarse los guards antes de cualquier servicio, incluidas las traducciones, se realiza una promesa en la cual se espera a que carguen dichas traducciones para acto seguido ahí si mostrar el pop up:

![image](https://github.com/user-attachments/assets/2d80b774-1a25-4fe2-bc6a-9fe39c208491)

Así se realiza la prueba y el pop up se muestra correctamente:

![image](https://github.com/user-attachments/assets/a96b5edd-4abe-4443-b59f-d2fd5bd82434)
