### ISSUE TITLE
Realizar ajustes solicitados por funcionamiento.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#232]
Se requiere realizar ajustes solicitados por funcionamiento posterior a la presentación realizada en #215, se requiere actualizar el popup que se muestra cuando el contratista va a enviar los documentos a revisión, en este pop up ahora se debe indicar que el documento quedará firmado electronicamente.

Una vez realizados los popups se requiere realizar un documento en el que se explique de manera tecnica el proceso de implementación de firma especificamente en el sistema de cumplidos CPS

**Sub Tareas**

- [x] Corregir textos de popups existentes para indicar que el documento quedará firmado electrónicamente.
- [x] Realizar documento donde se indique las tareas realizadas en la implementación de firma electróncia en cumplidos CPS.

**Criterios de aceptación**

- [x] Corrección de popups realizados.
- [x] Documento de implementación realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 30/10/24

De acuerdo con la reunión realizada con funcionamiento, se ajustó el pop up que se le muestra al contratista al momento de querer enviar y firmar los soportes de pago, quedando de la siguiente manera:

![Captura de pantalla 2024-10-30 163134](https://github.com/user-attachments/assets/1dc24adb-bd10-4cac-8363-c93f8e2ce966)

Adicional a ello se realizó una documentación detallada de la implementación de firma múltiple en el cliente de cumplidos en la cual se explica tanto el flujo y el algoritmo de firma electrónica y rechazo utilizado, como los cambios requeridos en el código, a continuación se deja el enlace para su revisión:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/EcvJw4yGeVNHqZi-594b2uoBIYM3-mq0CTKrnj7d6OwtKQ?e=ZnS0SL
