### ISSUE TITLE
Iniciar implementación de lógica en gestión dependencias - Parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#233]
Se requiere realizar la implementación de la lógica en gestión dependencias iniciando por los ajustes en el microcliente.

**Sub Tareas**

- [x] Realizar ajustes en el microcliente para iniciar adaptación hacia la lógica a realizar en el mid.
- [x] Documentar issue con ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Frontend
Se logra realizar el json para enviar al mid, ademas se usa el servicio de OIKOS para obtener los tipos de uso y los tipos de espacios.
![Image](https://github.com/user-attachments/assets/544e3d0d-9424-4e7d-9cdc-98c14650bd40)

**Comment by xDa04vidx** [comment]
### Adelanto visual
Se logra realizar los ajustes visuales en la vista de gestión.

**Loader de búsqueda**
![Image](https://github.com/user-attachments/assets/018c9f20-34ed-4bac-84cb-bdecab44227b)

**Resultado de búsqueda**
![Image](https://github.com/user-attachments/assets/359597b7-8174-4855-941d-2d27e55108ce)

**Tabla resultante del mid**
![Image](https://github.com/user-attachments/assets/0e3b74d0-a0e5-4995-aa28-5843abf7f4f3)

En caso de que no se tiene un tipo de uso no se pone ningún contenido, además se verifica que la paginación funciona.
![Image](https://github.com/user-attachments/assets/7c29207e-6d82-4d29-aa28-00aa40528d0f)

**Detalles**
En esta sección hace falta faltar el endpoint que obtiene toda la información faltante del espacio físico, por el momento se obtiene la información que viene de la tabla
![Image](https://github.com/user-attachments/assets/4d074ae4-b890-47ea-b9bf-606e27fbe575)

**Editar**
En esta sección hace falta faltar el endpoint que obtiene toda la información faltante del espacio físico, por el momento se obtiene la información que viene de la tabla
![Image](https://github.com/user-attachments/assets/604b14d9-5a72-4e50-95e3-f55a447565b1)

**Comment by xDa04vidx** [comment]
### Pull request
Se agrega al pull request existente en [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)
![Image](https://github.com/user-attachments/assets/5792326b-c429-4e54-a0bf-3d8013611f44)
