### ISSUE TITLE
Levantar información necesaria para requerimientos varios del CORE

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#234]
Se requiere realizar el levantamiento de información con el ingeniero Milton con el fin de definir multiples necesidades de las que no se tiene claridad:

- Aclarar dudas sobre los campos en bases de datos de Oikos como son el campo de fecha_inicio, fecha_fin en tabla asignacion_espacio_fisico_dependencia, campo valor en tabla espacio_fisico_campo.
- Definir aprobación con los diferentes secretarios académicos para validar el cambio de firma en las sabanas de notas.

**Sub Tareas**

- [ ] Levantar información sobre multiples necesiades.

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha intetnado levantar la información con Jhon pero por el desconocimiento se pregunto a milton quien tampoco pudo dar información , pero nos comento que Ludwing nos puede ayudar , a quien se pregunto sobre el tema y se espera respuesta

**Comment by mantnicot** [comment]
revisar si se peude duplicar nombre de dependencias

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/17da44e0-45f6-45d4-b24b-f96dc77bf15f)

se ha intentado comunicar pero no se ha dado respuesta

**Comment by mantnicot** [comment]
Se ha dado respuesta de la primera parte

![Image](https://github.com/user-attachments/assets/96ccf3f6-2932-47b5-a64a-4a37fcc49fc0)

**Comment by mantnicot** [comment]
Con respecto al valor se da la siguiente respuesta

![Image](https://github.com/user-attachments/assets/c69869df-95ad-401c-b611-2faba2c44ac9)
