### ISSUE TITLE
Iniciar implementación de lógica en gestión de espacios fisicos - Parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#235]
Se requiere continuar con la implementación de la lógica para la gestión de espacios fisicos, se requiere realizar el filtro de espacios fisicos donde los filtros son independientes (queda pendiente por definir si la busqueda se realizaría teniendo en cuenta los filtros seleccionados en conjunto o por separado), se debe crear una transacción en el mid para concretas los cambios que realice el usuario en los diferentes espacios fisicos.

**Sub Tareas**

- [ ] Crear lógica para busqueda de espacios fisicos según los diferentes criterios de busqueda.
- [ ] Precargar información de espacio fisico seleccionado.
- [ ] Iniciar transacción para edición de espacios fisicos.

**Criterios de aceptación**

- [ ] Lógica para busqueda de espacios fisicos creada.
- [ ] Información de espacios fisicos precargada.
- [ ] Transacción para edición iniciada.
- [ ] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se adelanta el mid

Se lograron avances significativos en la búsqueda de espacios físicos, a pesar de la complejidad del desarrollo. Esto se debe a la necesidad de considerar todos los campos enviados al mid, combinando las peticiones para mostrar únicamente los espacios académicos que coincidan con los criterios recibidos.

En primer lugar, se lograron realizar las combinaciones mediante comparaciones de los ID de los espacios físicos, enviando todos los objetos necesarios tanto para la edición como para los detalles. Sin embargo, al enviar toda esta información y al comparar solo los índices sin guardar el objeto completo, algunas consultas en este endpoint resultaban lentas, alcanzando tiempos de respuesta de hasta 1 minuto.

Tras un análisis con el líder @diagutierrezro, se logró capturar el objeto completo del espacio físico en la primera búsqueda y enviar solo los datos necesarios para construir la tabla. Este cambio en la lógica optimiza los tiempos de respuesta (aunque en algunos casos persiste cierta lentitud debido a la cantidad de información). También implica la creación de un nuevo endpoint para cargar la información faltante al ver detalles y editar el espacio físico.

**Pendiente**
Queda pendiente desarrollar el endpoint que, al recibir un ID, devuelva la información de la dependencia asociada y los campos relacionados con el espacio físico. Esta información es la que falta para completar las vistas de detalles y edición.

**Comment by xDa04vidx** [comment]
### Funcionamiento de lo realizado
Se mostrará el funcionamiento por medio del frontend, donde se facilita la utilización del endpoint, en primera medida se mostrará la búsqueda por campo individual y luego si por combinadas.

**Búsqueda por tipo de espacio físico**
![Image](https://github.com/user-attachments/assets/373d43d4-7a36-4e2e-8a7f-2738a1f4d2a4)

**Búsqueda por nombre**
![Image](https://github.com/user-attachments/assets/231461d0-af9b-41f1-8223-3323412cde35)

**Búsqueda por tipo de uso**
![Image](https://github.com/user-attachments/assets/08540822-946a-4ced-949a-82e907fdb47e)

**Búsqueda por dependencia**
![Image](https://github.com/user-attachments/assets/8cd69218-6782-4e75-9a9e-59d3f0f158de)

**Búsqueda por nombre y tipo espacio**
![Image](https://github.com/user-attachments/assets/5d8f7eb3-f8c3-4110-9098-8ab2f8c9d657)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/b34cb3ed-8d74-4419-8521-8cb8aa3764a2)

**Búsqueda por nombre y tipo de uso**
![Image](https://github.com/user-attachments/assets/d393cde9-4ef5-46d2-8065-05edbe354daf)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/aaadb88b-1237-4095-bd4f-ad84744f2070)

**Búsqueda por nombre y dependencia**
![Image](https://github.com/user-attachments/assets/338c43a4-6f36-477c-94b1-f5b2aaccd814)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/1e207329-5442-4e08-aa5c-f32e2b94e4ff)

**Búsqueda por tipo de espacio y tipo de uso**
![Image](https://github.com/user-attachments/assets/1c1ee0fe-2f16-4246-bcef-befbd94bc3d8)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/c4da3e1d-4180-45b4-94b6-27f2b50ac43c)

**Búsqueda por tipo de espacio y dependencia**
![Image](https://github.com/user-attachments/assets/015ef236-cbd5-4900-8c7c-f5137ed1a8a4)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/8559d3f8-3352-4cf5-8475-c1fb38bfa0a2)

**Búsqueda por tipo de uso y dependencia**
![Image](https://github.com/user-attachments/assets/c1908ecf-8f06-4473-8f76-5e4c6fbab924)

En caso de que no exista coincidencia, no muestra nada.
![Image](https://github.com/user-attachments/assets/b809cc0e-455b-41a1-a36b-7bc7ab20c90b)
