### ISSUE TITLE
Continuar creación de estructura básica para microcliente de Auditoría.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#236]
Se requiere finalizar la creación de la estructura básica del microcliente de auditoría, para este issue el objetivo es solucionar el error que no permite la visualización del modal para ver los logs y finalizar el desarrollo de dicha vista.

**Sub Tareas**

- [x] Finalizar creación de estructura básica de microcliente.
- [x] Documentar issue con estructura creada.

**Criterios de aceptación**

- [x] Estructura básica del mf finalizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
El error que no se mostraba en la consola del navegador, la pantalla de este ni el la terminal del entorno de desarrollo es porque faltaba unas importaciones de paquetes en el app.module, esto es un error muy silencioso ya que no muestra error.

Asi quedo la forma principal del microcliente:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f54fa09a-d708-4641-952d-06eb5f496cfe">

En los campos de fecha y hora quedaron de forma desplegable.

La ventana emergente que se muestra con la única acción de la tabla quedo de la siguiente forma:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/fe3382e5-bf1f-45cd-b08a-5ca719412151">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3b138553-e2ef-470c-a6ef-bcef34e090b0">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/1f3a297a-42ae-4597-bd76-c8ae824155e9">

Los cuadros quedaron como text-area para que el texto se pueda mostrar de manera interlineada similar a un parrafo.

**Comment by JulianAvella** [comment]
Se crea la rama llamada "estructura-inicial" con el código de la parte visual del microcliente:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/2a312998-cbc8-4c92-8b6b-ec12cac1b53f">

No se crea un pull request, ya que todavía no hay una rama develop
