### ISSUE TITLE
Realizar análisis sobre como se puede enviar información entre microclientes para implementarse en módulo de auditoría.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#237]
Se requiere realizar una investigación donde el objetivo es encontrar maneras en las que se pueda enviar información (inicialmente se planea desde el root) hacia el microcliente de auditoría, esto con el fin de que el mf de auditoría detecte desde cual sistema está siendo implementado con la finalidad de mas adelante poder saber a que Apis se podrian consultar.

**Sub Tareas**

- [x] Realizar diferentes busquedas sobre como se podría implementar el envío de información desde el root hacia el mf.
- [x] Documentar issue con diferentes posibles soluciones encontradas.

**Criterios de aceptación**

- [x] Busqueda e investigación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 05/11/24

Se inicia la investigación acerca de métodos para traspasar información entre micro clientes.

## PRIMERA FUENTE

Una de las fuentes más interesantes encontradas corresponde a una discusión en github en la que se enumera los posibles métodos para realizar lo que se está buscando en un contexto similar al que tendremos en nuestra implementación, y sus respectivas desventajas. Las respuestas a esa discusión tienen enlaces que también pueden ser de utilidad. En resúmen, la persona que inicia la discusión enumera tres formas de hacer esto:

1. Crear módulos de utilidad para obtener y establecer el contexto que se requiera compartir.
2. Módulo de utilidad para establecer el contexto, pero pasar el contexto como Custom-Props
3. Usar el localstorage

Para más contexto se adjunta el enlace de la discusión: [Discusión sobre métodos para compartir información entre micro clientes](https://github.com/single-spa/single-spa/discussions/863)

## SEGUNDA FUENTE

Ahora bien uno de los enlaces que colocan en las respuestas de la discusión es el siguiente:

[Preguntas frecuentes: Cómo puedo compartir el estado de mi aplicación entre aplicaciones](https://single-spa.js.org/docs/faq/#how-can-i-share-application-state-between-applications)

En el se enlistan varios métodos con sus respectivos enlaces de consulta los cuales enumeraré resumidamente:

1. Crear un microfrontend de utilidad de API compartido que almacene en caché las solicitudes fetch/XHR y sus respuestas. Todos los microfrontends llaman al microfrontend API cuando realizan una petición, de modo que el microfrontend puede controlar si se recuperan los datos o no.
2. Cree un microfrontend de utilidad Auth compartido que exponga una función userCanAccess para que otros microfrontends la utilicen cuando comprueben los permisos. El módulo auth también puede incluir otras exportaciones como el objeto usuario conectado, tokens auth, etc.
3. Exporte el estado compartido desde la interfaz pública de su microportal para que las bibliotecas puedan importarlo. Para los valores que cambian con el tiempo, Observables (RxJS docs) puede ser útil. Crea un ReplaySubject para que puedas enviar nuevos valores a todos los suscriptores en cualquier momento.
4. Utiliza eventos personalizados del navegador para comunicarte. Dispararlos en la ventana en un microfrontend, y escuchar el evento en un microfrontend diferente.
5. Utilice cookies, almacenamiento local/sesión u otros métodos similares para almacenar y leer ese estado. Estos métodos funcionan mejor con cosas que no cambian a menudo, por ejemplo, la información del usuario conectado.

## TERCERA FUENTE

En un issue del github de Single SPA titulado [intercomunicación entre dos aplicaciones angular](https://github.com/single-spa/single-spa/issues/552), uno de los usuarios responde con un enlace en el que se listan métodos para realizar este proceso, y realiza una breve explicación muy generalizada de cómo sería el proceso: 

[Comentario destacado del Issue](https://github.com/single-spa/single-spa/issues/552#issuecomment-628697900)


El enlace que el coloca redirecciona al siguiente portal web de single SPA con documentación:

[Comunicación entre apps con Single SPA](https://single-spa.js.org/docs/recommended-setup/#inter-app-communication)

Ahí se listan distintas consideraciones a tener en cuenta para este proceso. en ese mismo portal hay también documentación de los utility modules mencionados en **La segunda fuente**, el cual adjunto a continuación: [Utility modules](https://single-spa.js.org/docs/recommended-setup/#utility-modules-styleguide-api-etc)


## Conclusión del avance

Hasta ahora esta es la información encontrada al respecto de lo que se quiere realizar. Como hasta ahora es una primera aproximación, no se tiene total comprensión de la forma de implementar cualquiera de todas estas opciones referidas y enumeradas, por lo que se requiere un análisis más riguroso.
