### ISSUE TITLE
Levantar la documentación que se agrega con respecto a los espacios fisicos en OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#238]
Se requiere realizar la consulta y definición de la documentación que se agrega con respecto a los espacios fisicos en OIKOS

**Sub Tareas**

- [x] Contactar con responsable de la Universidad.
- [x] Adelantar la investigación relacionada con la documentación que se agrega con respecto a los espacios fisicos.
- [x] Proyectar documento derivado de la investigación.

**Criterios de aceptación**

- [x] Documento producto investigación.
- [x] Documento almacenado y compartido con desarrollo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/f7ae8914-43b4-46d3-bd08-ec2437418677)
 se ha intentado obtener la información con Cristian Laguna pero no se sabe a lo cual se comenta a Eduard , el cual nos cuenta qeu conseguira a una persona de infraesctructuraa para ellos , no se ha dado respuesta

**Comment by mantnicot** [comment]
Se ha podido Hablar con Santiago una personas encargada de infraestuctura y se cuenta que el unico documento que se adjunta es el siguiente formato :

[GIF-PR-014-FR-010 (3).docx](https://github.com/user-attachments/files/17739213/GIF-PR-014-FR-010.3.docx)

El cual tiene de base circulares como esta : 

[Circular 12 asignación, intervención, incorporación (2).pdf](https://github.com/user-attachments/files/17739217/Circular.12.asignacion.intervencion.incorporacion.2.pdf)


Pero para el registro solo se usa el primer formato

**Comment by jcmurilloa** [comment]
Muy buen trabajo, pendiente añadir este espacio para cargue de documento en un siguiente alcance.
