### ISSUE TITLE
Realizar el levantamiento respecto a la caducidad de roles en Argo y Arka

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#239]
Se requiere realizar la consulta y definición de la caducidad de roles en Argo y Arka.

**Sub Tareas**

- [x] Contactar con responsable de la Universidad.
- [x] Adelantar la investigación relacionada con la caducidad de roles en Argo y Arka.
- [x] Proyectar documento derivado de la investigación.

**Criterios de aceptación**

- [x] Documento producto investigación.
- [x] Documento almacenado y compartido con desarrollo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido levantar la información con Cristian Alape con respecto a Argo 

![Image](https://github.com/user-attachments/assets/b3b519c5-4820-4f77-a0dd-c58108ba6f32)


La conclusión sería que se puede plantear es generar un job de igual manera que esta en el sistema de novedades o cumplidos , con fin de contratos y las novedades de los mismos, sin reglas adicionales

**Comment by jcmurilloa** [comment]
Pendiente documentación relacionada.

**Comment by mantnicot** [comment]
Se ha plantado el siguiente documento donde se evidencia el job
[Documento caducidad de roles novedades y ARGO](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ETm9Z7qGGQNBgKjOPtEhUO8BrYsAn8LXeBjQhTMkg7sAbA?e=bsYqr7)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, de esta manera se documenta la investigación solicitada.
