### ISSUE TITLE
Construir el flujo actual del cliente (Mapeo cliente OIKOS)

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#24]
Se requiere realizar la construcción del flujo actual del cliente (Mapeo cliente OIKOS)

**Sub Tareas**

- [ ] Repasar el flujo actual del sistema con el cliente
- [ ] Construir diagrama de flujo

**Criterios de aceptación**

- [ ] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
SE ha realizado el flujo entendido en la reunión con Jhon , se queda a espera del otros mapeos con Milton y Francisco

![Flujo mapeo oikos Jhon drawio](https://github.com/udistrital/core_documentacion/assets/85162258/aee86e15-c8d8-4c1c-bf69-4a316e2ba582)

[Diagrama de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuZ7rg5hhTVCnX5YfsyclQkByvuIeJcRkNoGO3nL6YZQ6g?e=zlDGrd)

**Comment by mantnicot** [comment]
Se adjunta el nuevo diagrama obtenido con base ala reunión del día 22/05/2024

![Flujo mapeo oikos completo  drawio](https://github.com/udistrital/core_documentacion/assets/85162258/1d28f345-fa5e-47bc-9ed7-b1460b113e3f)



Se adjunta el link de los flujos


[LINK flujos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuZ7rg5hhTVCnX5YfsyclQkByvuIeJcRkNoGO3nL6YZQ6g?e=ZU3ftc)

**Comment by jcmurilloa** [comment]
Tener en cuenta las observaciones realizadas en el review.
