### ISSUE TITLE
Iniciar creación de mid que realizará consultas hacia AWS.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#240]
Se requiere realizar la creación de mid el cual será el encargado de realizar las consultas pertinentes hacia AWS desde donde se obtendran los logs

**Dependencias**
Importante que @diagutierrezro facilite la grabación realizada por funcionamiento donde se explica como se realizaría dicha conexión hacia AWS

**Sub Tareas**

- [x] Realizar revisión de grabación.
- [x] Crear api MID en el lenguaje python con configuración inicial, se puede usar como guia el [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid) o [firma_electronica_mid](https://github.com/udistrital/firma_electronica_mid).
- [x] Documentar avances realizados.

**Criterios de aceptación**

- [x] Revisión de grabación realizada.
- [x] Api MID con configuración inicial creada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* Se creo la estructura inicial del api mid en el lenguaje Python con la siguiente relación de archivos:

![Image](https://github.com/user-attachments/assets/ea65e92a-6234-465a-b338-46686d409e8a)

La api corriendo con la configuración inicial:

![Image](https://github.com/user-attachments/assets/924c4e63-9fff-4245-9985-1c2eb1ec1f87)
