### ISSUE TITLE
Apropiar librería de auditoría.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#241]
Se requiere realizar la apropiación de la librería de auditoría que se encuentra en [utils_oas](https://github.com/udistrital/utils_oas/tree/master/auditoria), el objetivo únicamente es entender el funcionamiento de dicha librería, si se considera que se necesita acceso a AWS por favor notificar a @diagutierrezro para solictar el usuario

**Sub Tareas**

- [x] Apropiarse de la librería de Auditoría.
- [x] Generar un documento donde se especifique lo entendido sobre el funcionamiento de esta librería.
- [x] Documentar el issue con el documento realizado.

**Criterios de aceptación**

- [x] Apropiación realizada.
- [x] Documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 07/11/24

Se realiza la revisión del repositorio de la librería de auditoría, y se realiza un informe detallando el funcionamiento de los archivos más relevantes de la misma, con tal de dejar una claridad del rol que desempeña cada uno y qué información se maneja así como los flujos de cada una de las funciones. Se adjunta el archivo a continuación:

[Informe de apropiación de librería de auditoria](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davagomezr_udistrital_edu_co/ESOt5ra8Z9BLsMEE-QsPL5IB1mTlwNi4vp1otQeCqTngTg?e=OhyR0Z)
