### ISSUE TITLE
Desarrollar lógica para edición de espacios fisicos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#242]
Se requiere realizar el desarrollo para implementar la edición de espacios fisicos, tener en cuenta que se debe traer la información de la dependencia y campos únicamente del espacio fisico seleccionado, se debe precargar la información y posterior a esto realizar la transacción para modificar los diferentes campos, recordar que dicha transacción se realice en diferentes funciones cuando sea posible y que se deben realizar rollbacks.

**Sub Tareas**

- [x] Obtener información especifica del espacio fisico.
- [x] Precargar información del espacio fisico.
- [x] Crear lógica en el MID para asegurarse de que se modifican los campos necesarios cuando se va a editar un espacio fisico, esto se realiza mediante transacción y se deben tener rollbacks.

**Criterios de aceptación**

- [x] Información de espacios fisicos concretos obtenida.
- [x] Información de espacio fisico precargada.
- [x] Lógica de transacción y rollbacks desarrollada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Avances gráficos
Se logra precargar la información del espacio físico para las vistas de edición y detalles
**Detalles**
![Image](https://github.com/user-attachments/assets/e31a8227-b6ef-4965-8dee-d5f7d329bfc3)

**Edición**
![Image](https://github.com/user-attachments/assets/490975d5-0042-4e85-975f-18b188e9d4ae)
Se observa que en caso de que un espacio físico no tiene todos los registros, no esta habilitado el botón de editar

Además en la vista de editar, se esta poniendo la lista de dependencias, de tipos de uso y tipos de espacio.
![Image](https://github.com/user-attachments/assets/bc20f021-0049-432d-a09a-37aa68009ca9)
![Image](https://github.com/user-attachments/assets/2d1fca71-4ac9-4598-a423-2a37bb4f38f2)
![Image](https://github.com/user-attachments/assets/4959a7cc-e9c7-4b7d-8f02-a4e3eff73a74)
Este ajuste se logra obteniendo el id de cada tabla que se obtiene de la vista de la tabla de registro, por ahora solo se esta buscando la información de la dependencia, mas adelante se buscaran los campos del espacio

**Comment by xDa04vidx** [comment]
### Mid
Se desarrolló la lógica en el MID para la edición de espacios físicos. Este trabajo se centró en la modificación de los datos propios del espacio físico (nombre, descripción y código de abreviación), así como en las tablas de relación correspondientes al tipo de uso y la asignación de dependencia. A continuación, se presentan los casos de uso relacionados.

**Espacio original**
Se trabajará sobre el espacio fisico con Id: 1825, este espacio tiene los siguientes datos basicos:
![Image](https://github.com/user-attachments/assets/475bc53a-10f6-4d22-a85f-e4dbf7b211fe)
Además este espacio físico tiene el tipo de uso activo numero 3
![Image](https://github.com/user-attachments/assets/6fd83f77-34b7-47c4-ba3f-5dfebcbb455e)
y la dependencia numero 22
![Image](https://github.com/user-attachments/assets/2ef4e0ab-a586-463d-83bf-00d99c08ced7)

**Casos**
- Edición de datos básicos junto con tipo de espacio
  - Respuesta MID
    ![Image](https://github.com/user-attachments/assets/bd7ef9d5-a1ed-49f9-b815-7d29859c230d)
  - Cambio
    ![Image](https://github.com/user-attachments/assets/370105ed-cad8-45c1-aefd-a28e0c7f060e)

- Agregar un nuevo tipo de uso
  - Respuesta MID
    ![Image](https://github.com/user-attachments/assets/186b48c0-95f9-4ba2-9f3d-bbf9a031ee6c)
  - Cambio
    ![Image](https://github.com/user-attachments/assets/5159c7a8-abc2-4ea1-b097-f1b1e4b5543c)

- Activar un tipo de uso existente
  - Respuesta MID
    ![Image](https://github.com/user-attachments/assets/efa84224-85a2-4bfd-b5b2-f707312edca1)
  - Cambio
    ![Image](https://github.com/user-attachments/assets/9847b0ef-49a1-4c24-90c6-a3094fdcb9a5)

- Agregar una nueva dependencia al espacio
  - Respuesta MID
    ![Image](https://github.com/user-attachments/assets/208f119e-e1ab-4751-b63d-32582b15c6dd)
  - Cambio
    ![Image](https://github.com/user-attachments/assets/235d22d3-2059-446f-ba36-e98f7ebe82f2)

- Activar una dependencia existente
  - Respuesta MID
    ![Image](https://github.com/user-attachments/assets/1b709ea3-1f9c-43d5-b7c7-ac8a330cb014)
  - Cambio
    ![Image](https://github.com/user-attachments/assets/d9d28823-ac7a-4a89-aec4-cc71eef358ca)

**Comment by xDa04vidx** [comment]
### Frontend
Se mostrará la edición del espacio físico desde el frontend, para ello se manejará el mismo espacio
![Image](https://github.com/user-attachments/assets/2792e018-2b09-46cc-8a17-d5f88bcaeaa8)

Se editarán todos los campos, y se mostraran los cambios con ayuda de postman y pgAdmin
**Cambios**
![Image](https://github.com/user-attachments/assets/2a293f51-3030-4aaf-9c95-e2512c8926aa)

**Prueba de los cambios**
![Image](https://github.com/user-attachments/assets/edfa72b6-6320-4560-af27-d89f10fca651)

**Comment by xDa04vidx** [comment]
### Pull request

Se agregan los cambios al pull request existente en [gestion_espacios_fisicos_mid](https://github.com/udistrital/gestion_espacios_fisicos_mid)
![Image](https://github.com/user-attachments/assets/07ddc59e-6ea5-42b5-acb5-254f66ab381e)

Se crea pull request en [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)
![Image](https://github.com/user-attachments/assets/c74a0747-a043-4db7-a8a2-c268704a97d9)
