### ISSUE TITLE
Realizar pruebas de concepto para comunicación entre root y mf

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#243]
Se requiere realizar diferentes pruebas de concepto donde se prueben las diferentes opciones según lo investigado en #237, la idea general es que se envíe información (por ahora no se sabe en concreto que información ni la forma en la que se envíe) desde el root y el mf la pueda detectar, puede ser información como nombre del sistema, un json con un posible listado de Apis, etc.

Importante ir documentando en el issue las pruebas realizadas y los resultados obtenidos aún si la prueba no fue exitosa.

**Sub Tareas**

- [x] Pruebas de concepto realizadas.
- [x] Documentar issue con pruebas de concepto realizadas.

**Criterios de aceptación**

- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 12/11/24

Se inicia con las pruebas del método que involucra custom props de single SPA, el cual consiste en definir estos en el root config (obviamente del root) y enviar estos props a la ruta del microcliente que se desee. Este método asegura que sólo se envíe esta información al micro cliente deseado y no a todos los microclientes del mismo dominio. así para realizar este proceso son necesarios los siguientes cambios:

En el root config establecer en la variable de data un arreglo de props en el que se incluyen las previamente ya establecidas variables de entorno y nuestra información personalizada:

![image](https://github.com/user-attachments/assets/95e0f599-4b27-41d1-8806-c9a2f6ef19fe)

Y en el microfrontend-layout.html se reemplaza en props el "environment" previo por "props" que es el nombre del arreglo definido en data:

 
![image](https://github.com/user-attachments/assets/9b0054c8-c137-44ba-8bd1-ae14f82d65ca)

Como se ve sólo se realiza este cambio en el micro cliente de auditoria que es al cual queremos enviarle la información.

Y desde el microfont end de auditoria esta información se puede rescatar desde el app.component.ts (por el momento) de la siguiente manera:

![image](https://github.com/user-attachments/assets/7bef743a-6145-4895-a380-0f1c07bdd9ea)

Sin embargo al momento de realizar la prueba la consola del navegador arroja el siguiente error:

![image](https://github.com/user-attachments/assets/d47c1fc7-0085-4e49-8288-06a009af5141)

Se está buscando el modo de resolver este error

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/11/24

Se realizaron las pruebas de dos métodos:

## Local Storage:

La implementación es sencilla y es accesible desde cualquier parte del micro cliente de auditoria, sin embargo la información que se guarde aquí  es accesible desde cualquier micro cliente del mismo dominio.

Primero se realiza el guardado de la información en el local storage desde el Root de Oikos en el **root config**:

![Captura de pantalla 2024-11-13 143207](https://github.com/user-attachments/assets/442dc064-a20d-404d-85c7-7a38390140da)

Luego desde el componente de auditoría en el ngInit se rescata la información y se imprime en consola:

![Captura de pantalla 2024-11-13 143219](https://github.com/user-attachments/assets/505ec2e2-6f4f-4c9c-b996-ba03e1435528)

![Captura de pantalla 2024-11-13 143228](https://github.com/user-attachments/assets/7dc80ea0-e55f-4817-9f24-df141ed844b4)

## Custom Events:

En esta aproximación se tiene más control del acceso a la información, ya que del modo en que se implementó se buscó que sólo el microcliente de auditoría tuviese acceso a la información que se quería enviar. Para lograr esto se hizo lo siguiente:

1. En el ngInit del componente de auditoría se creó un evento personalizado llamado **appMounted** con una carga de información indicando el nombre del microcliente:

![Captura de pantalla 2024-11-13 160027](https://github.com/user-attachments/assets/31bf523b-ec63-47e9-b960-f4bf366ee28b)

2.  En el root de Oikos, dentro del **root-config** se crea un evento personalizado que espere a que se active el evento appMounted y a partir de ahí compare el contenido, y si este coincide con el nombre del microcliente entonces envía la información que se desea compartir:

![Captura de pantalla 2024-11-13 160402](https://github.com/user-attachments/assets/fbecf699-0379-4a9d-a250-abda3c8e3014)

3. Luego en el componente de auditoría se crea un event listener que escuche al evento del root y en este caso imprima en consola la información que se envía desde allá:

![Captura de pantalla 2024-11-13 160408](https://github.com/user-attachments/assets/76682608-3990-4449-807c-9aff474619e5)

![Captura de pantalla 2024-11-13 160422](https://github.com/user-attachments/assets/5544f650-12f3-47fc-b2aa-cbc4ba2c6e34)

## Custom props

En cuanto el uso de los Custom props no se ha podido encontrar la forma de hacerlo funcionar aún, ya que o bien al no enviar en los props el environment el mf de auditoría se rompe, o si se envía el environment en el prop como si fuese un diccionario (para poder agregar los custom props) no carga todo correctamente, por ejemplo la imagen de oikos.

Se está tratando de enviar la información dentro del mismo environment y rescatarla de algún modo desde el mf de auditoría pero aún no se ha tenido éxito

**Comment by JulianAvella** [comment]
* Custom props:

Se probo configurando el proyecto oikos_root_mf, se modifico el archivo udistrital-root-config.ts: 

import { registerApplication, start } from "single-spa";
import {
  constructApplications,
  constructRoutes,
  constructLayoutEngine,
} from "single-spa-layout";
import microfrontendLayout from "./microfrontend-layout.html";
import "./assets/styles/index.css";

let environment;

declare var isProd: boolean | undefined;
declare var isDev: boolean | undefined;
if (isProd) {
  environment = require("./environments/environment.production");
} else if (isDev) {
  environment = require("./environments/environment.development");
} else {
  environment = require("./environments/environment");
}

const sharedState = {
  data: null,
  sendData: (targetApp: string, message: any) => {
    if (targetApp === "@udistrital/mapeo-dependencias-mf" && window.mapeoNotify) {
      window.mapeoNotify(message);  
    } else if (targetApp === "@udistrital/auditoria-mf" && window.auditoriaNotify) {
      window.auditoriaNotify(message);  
    } else {
      console.warn(`No handler defined for app: ${targetApp}`);
    }
  },
};

const data = {
  props: environment,
  loaders: {},
};

const routes = constructRoutes(microfrontendLayout, data);
const applications = constructApplications({
  routes,
  loadApp({ name }) {
    return System.import(name);
  },
});
const layoutEngine = constructLayoutEngine({ routes, applications });

applications.forEach((app) => {
  registerApplication({
    ...app,
    customProps: (name) => ({
      ...data.props,
      notify: (message: any) => {
        sharedState.sendData(name, message);
      },
    }),
  });
});

applications.forEach(registerApplication);
layoutEngine.activate();

registerApplication({
  name: "@udistrital/auditoria-mf",
  app: () => System.import("@udistrital/auditoria-mf") as any,  
  activeWhen: ["/auditoria"],
  customProps: {
    sendData: sharedState.sendData, 
  },
});

registerApplication({
  name: "@udistrital/mapeo-dependencias-mf",
  app: () => System.import("@udistrital/mapeo-dependencias-mf") as any, 
  activeWhen: ["/mapeo"],
  customProps: {
    sendData: sharedState.sendData,  
  },
});

start();

El codigo anterior lo que hace es que registra los dos microclientes para que se puedan comunicar y enviarse información, y se creo una interfaz para recibir el mensaje, en el proyecto principal de oikos y en sus dos microclientes: 

export {};

declare global {
  interface Window {
    mapeoNotify?: (message: any) => void;
    auditoriaNotify?: (message: any) => void;
  }
}

En los microclientes se configuro el single-spa para que pueda recibir los proms, en el archivo main.single-spa.ts, se agrego esta sentencia "(window as any).singleSpaProps = singleSpaProps;": import { enableProdMode, NgZone } from '@angular/core';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Router, NavigationStart } from '@angular/router';

import { singleSpaAngular, getSingleSpaExtraProviders } from 'single-spa-angular';


import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { singleSpaPropsSubject } from './single-spa/single-spa-props';

if (environment.production) {
  enableProdMode();
}

const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    singleSpaPropsSubject.next(singleSpaProps);
    (window as any).singleSpaProps = singleSpaProps;
    return platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);
  },
  template: '<app-root />',
  Router,
  NavigationStart,
  NgZone,
});

export const bootstrap = lifecycles.bootstrap;
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;

Además que el componente del microcliente de auditoria, se coloco el codigo para recibir el mensaje, la misma manera se coloco en el cliente de mapeo:   

ngOnInit(): void {
    this.dataSource = new MatTableDataSource(this.logData);
    //this.dataSource.paginator = this.paginator;
    window.auditoriaNotify = (message: any) => {
      console.log('Mensaje recibido en Auditoría:', message);
    };
  }

  ngOnDestroy() {
    delete window.auditoriaNotify;
  }

NOTA IMPORTARTE: No se logro hacer la comunición entre los microclientes porque cuando se ejecutan, en el navegador desde el proyecto de oikos_root_mf muestra el siguiente error: 

<img width="959" alt="image" src="https://github.com/user-attachments/assets/61fcb6f5-812a-4476-90ba-bb823d62c739">
<img width="846" alt="image" src="https://github.com/user-attachments/assets/d4652f05-32c0-4b11-b5e8-9fb36c0bbb8a">
