### ISSUE TITLE
Ajustar conexión hacia AWS en el mid de auditoría

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#244]
Se requiere realizar la conexión del mid hacia AWS para esto se requiere que @diagutierrezro solicite la creación del usuario y brinde las credenciales, una vez realizado esto realizar la conexión teniendo en cuenta la grabación suministrada el sprint anterior.

**Sub Tareas**

- [x] Realizar conexión del api Mid creada hacia AWS para consulta de logs.
- [x] Realizar prueba donde se muestren los logs de algún api definiendole ciertos filtros como la fecha y el api a consultar.

**Criterios de aceptación**

- [x] Conexión entre Api mid y AWS establecida.
- [x] Prueba de obtención de logs realizada.
- [x] Documentación de issue realizada.

**Dependencias**
Por parte de @diagutierrezro  se debe solicitar el Key y Access Key a infraestructura

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se realiza la estructura para que cuando llegue una petición a la api mid, esta la dirija al router, este la direccione al controlador y este a su vez llama al servicio donde esta la lógica con un método getAll para traer los logs que se tienen en aws.

Las credenciales del usuario están como variables de entorno en el archivo ".env" y en el archivo ".gitignore" se coloca el archivo de las variables para evitar que se suba al repositorio en github, donde se subio el proyecto en la rama llamada "estructura inicial".

- Estructura de archivos: 

![Image](https://github.com/user-attachments/assets/f3df905d-f2a5-4411-b07a-481bc6069d7c)
![Image](https://github.com/user-attachments/assets/92834e31-1e05-408b-87fa-825b56feaae2)

- Api ejecutandose sin errores:

![Image](https://github.com/user-attachments/assets/b0735533-0b3b-47c7-83c8-221b1f0b7833)

- Petición de prueba desde postman:

![Image](https://github.com/user-attachments/assets/42c8ff21-e642-455e-9c43-5270d3272cdc)

- Código subido al repositorio auditoria_mid en github, en la rama "estructura-inicial":

![Image](https://github.com/user-attachments/assets/86e448b1-ebb1-41ff-a776-7b92249a6478)
