### ISSUE TITLE
Construir diagrama modular y de procesos del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#245]
Se requiere realizar la construcción de los diagramas modulares y de procesos del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/b9b7b0c8-c943-4e24-a308-b58a4927f00c)


Se realizo el diagrama modular de OIKOS 

[Enlace de la carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqS5W2seiLhDt6RZczEp42QB4VkjwyUUcYyColYu61H0SQ?e=387Jyp)

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/821abab7-180d-42eb-9e4f-d5fa2534a041)
Se agrega el diagrama de procesos

[carpeta de diagramaa](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Esf3UJ-5wxlIhT540iF6VM0Bj6nxtHAJ85FSoBvqeUftug?e=VsS5Jf)

**Comment by jcmurilloa** [comment]
Presentaremos de esta manera estos diagramas a funcionamiento para su respectiva revisión. Buen trabajo @mantnicot!
