### ISSUE TITLE
Levantar información sobre consulta de APIS

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#246]
Se requiere realizar el levantamiento de información con Maria Fernanda donde se debe averiguar como se espera que un microcliente sepa que Apis puede consultar, por ejemplo, el sistema de Oikos puede consultar unicamente el crud y el mid de Oikos? o puede consultar otras Apis y como se obtendría dicho listado o si por el contrario desde los diferentes microclientes se puede consultar cualquier Api.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido charlar con Maria Fernando y posterior a eso conn Jhon Castellanos sobre el tema a lo cual él respondió lo siguiente: 

![Image](https://github.com/user-attachments/assets/1ecd4ab6-5f46-4a03-8b3a-56ae4014d22f)

Se le comento al líder técnico y se va a generar una solicitud de su parte para hacer petición del servicio

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot
