### ISSUE TITLE
Realizar ajustes por pruebas de carga y seguridad.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#247]
Se requiere realizar los ajustes solicitados posterior al reporte de las pruebas de carga y seguridad.

**Sub Tareas**

- [x] Revisar TO DO en sonar.
- [x] Borrar go.mod go.sum y agregar dichos pasos al drone.
- [x] Eliminar console.log de los microclientes y del root.
- [x] Revisar códigos de respuesta si no se generan registros, es decir quitar 201 si no es necesario.

**Criterios de aceptación**

- [x] Ajustes TO DO realizados.
- [x] Archivos borrados y drone ajustado.
- [x] Console.log elimiados.
- [x] Revisión de código de respuesta en mid realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 14/11/24

Se inicia con los ajustes de carga y seguridad.

## TO DO de SonarQube en CRUD de OIKOS

Se revisan los distintos comentarios de To Do y se eliminan:

![Captura de pantalla 2024-11-14 165950](https://github.com/user-attachments/assets/35882c99-f3bb-4b4c-94b0-c0d4fd3cd63b)

Para este se realizó un análisis y ya que la función del comando propuesto no podía analizarse correctamente se optó por dejar la funcionalidad actual y eliminar los comentarios incluyendo la propuesta que reducía el proceso enlistado a una linea sin la seguridad de que funcionase correctamente:

![Captura de pantalla 2024-11-14 165956](https://github.com/user-attachments/assets/9404adf5-1d3f-40dc-8aaa-6330977cd6c5)

Ahora bien se tiene el siguiente comentario:

![Captura de pantalla 2024-11-14 170005](https://github.com/user-attachments/assets/c26c876c-45a4-4390-b106-3f1d9211b6a1)

Al no haber ninguna propuesta y al estar funcionando el CRUD con este código implementado, se deja tal cual y se elimina la etiqueta TO DO:

![Captura de pantalla 2024-11-14 170013](https://github.com/user-attachments/assets/e21e2f5d-5554-4419-a334-4a72ca1081a1)

Ahora bien similar al primer TO DO, se trata de revisar el método que en teoría reemplazaría las instrucciones listadas pero no se encuentra el modo de analizarla por lo que se dejan los comandos como están:

![Captura de pantalla 2024-11-14 170024](https://github.com/user-attachments/assets/d921c37e-d105-4624-b87d-28db1c0dffa2)

![Captura de pantalla 2024-11-14 170035](https://github.com/user-attachments/assets/c8b0a5a8-d590-497a-a068-c4c97d8c2daf)

Finalizando así esta sección, evidenciando que al subir la rama en la que se hicieron estos cambios ya no aparecen TODO's para corregir en SonarQube:

![Captura de pantalla 2024-11-14 170235](https://github.com/user-attachments/assets/848334e8-a62e-4216-a7ef-af58ede74d12)

## Borrar go mod y go sum y editar drone.yml

Se realiza la inclusión en el git ignore de los archivos go mod y go sum:

![Captura de pantalla 2024-11-14 171759](https://github.com/user-attachments/assets/e31edaba-a08e-434e-8d64-7b20dc225bd8)

Además de agregar en el go build del drone.yml el go mod init:

![Captura de pantalla 2024-11-14 171809](https://github.com/user-attachments/assets/a91946de-3448-425e-b946-d35db7aea2ba)

Y se reubica el go run test debajo del go build:

![Captura de pantalla 2024-11-14 171823](https://github.com/user-attachments/assets/4cdad25c-bd30-4439-874f-814d7f857e6a)

Y se evidencian los cambios:

![Captura de pantalla 2024-11-14 171832](https://github.com/user-attachments/assets/900a5edd-b068-47a6-8ed6-65a574d0355e)

## Eliminación de console.logs:

En gestión registro dependencias mf se realiza la limpieza de console logs solamente dejando los necesarios:

![image](https://github.com/user-attachments/assets/e25f42cb-131c-496a-8b7a-3834ffcec1fa)

Igualmente en mapeo de dependencias:

![image](https://github.com/user-attachments/assets/127497f7-c10d-4dd8-8023-3b6fb5a85ecf)

## Pendientes:

Queda pendiente la revisión de las respuestas de las peticiones en el mid de OIKOS

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/11/24

Se realizó la corrección de los códigos de respuesta de búsqueda y edición de dependencias cambiando dichos códigos en los controladores:

![Captura de pantalla 2024-11-16 145655](https://github.com/user-attachments/assets/c9993df5-d0ca-4f41-bbb2-74adf5eca427)

![Captura de pantalla 2024-11-16 145707](https://github.com/user-attachments/assets/d9409e95-d64f-446f-8a12-17f0efa47d86)

Siendo que ambos tenían como respuestas lo siguiente:

![Captura de pantalla 2024-11-16 144047](https://github.com/user-attachments/assets/764d436d-1115-46ec-a7c4-11515c99a4ec)

Ahora con este ajuste tenemos estas respuestas:

![Captura de pantalla 2024-11-16 144711](https://github.com/user-attachments/assets/9835f327-10d2-44d0-8518-b1fcf717a389)

![Captura de pantalla 2024-11-16 144835](https://github.com/user-attachments/assets/8487d99d-7700-4d6a-8f29-086b4178d701)
