### ISSUE TITLE
Finalizar ajustes solicitados en pruebas de carga y seguridad.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#248]
Se requiere finalizar los ajustes en pruebas de carga y seguridad, los cambios que se deben realizar son:
- Redireccionar al usuario despues de crear una dependencia.
- En el listado de dependencias en mapeo de dependencias traer solo dependencias activos (revisar).
- Realizar verficiaciones al generar o editar un mapeo

**Sub Tareas**

- [x] Redireccionar al usuario despues de crear una dependencia.
- [x] En el listado de dependencias en mapeo de dependencias traer solo dependencias activos.
- [x] Realizar verficiaciones al generar o editar un mapeo.

**Criterios de aceptación**

- [x] Redirección realizada.
- [x] Ajuste en consulta de dependencias realizado.
- [x] Verificaciones realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/11/24

Se realizó la redirección desde registro a gestión de dependencias al registrar una dependencia nueva. Se utilizó el router para este propósito:

![Captura de pantalla 2024-11-18 182502](https://github.com/user-attachments/assets/c70cb61b-f4ca-4792-8aac-0b0f1db57ea3)

![Captura de pantalla 2024-11-18 182449](https://github.com/user-attachments/assets/21b91f54-053a-4ecd-8530-f8dd37885528)

Y en el siguiente video se evidencia la prueba de su funcionamiento:

https://github.com/user-attachments/assets/900c435f-173f-40c3-aeb0-d148a5f05dba

En este momento se está adelantando la verificación de mapeo de dependencias por lo que queda este punto pendiente además del filtro de activos al traer dependencias

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 19/11/24

## Verificación de mapeo

Se realiza la verificación de edición y generación de mapeo:

Se importan los servicios de dependencia en **mapeo.component.ts**:

![Captura de pantalla 2024-11-19 133932](https://github.com/user-attachments/assets/42c94192-8883-4d10-b2e4-5219f7318f4e)

Luego en **es.json** se agregaron un par de traducciones para los mensajes de error:

![Captura de pantalla 2024-11-19 133932](https://github.com/user-attachments/assets/4f742930-3577-4041-9793-a16f3760f8bb)

Luego en la función **abrirDialogGenerarEditarMapeo** en **mapeo.component.ts** se agrega la siguiente lógica:

![Captura de pantalla 2024-11-19 133905](https://github.com/user-attachments/assets/064cb415-c8e7-4b39-b5d8-99fe17831720)

Así el funcionamiento queda de la siguiente manera:

https://github.com/user-attachments/assets/a21123b8-4aac-4bed-9b1c-f224162f8606

## Traer dependencias activas únicamente

El líder de equipo consultó lo respectivo a este apartado y se le informó que este punto ya no era necesario por lo que la issue quedó completada y se pasa a in review
