### ISSUE TITLE
Realizar gestión para implementar caducidad de roles en Pólux

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#249]
Se requiere realizar la gestión para implementar caducidad de roles en el sistema de POLUX 

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha levantado y se ha dado la implementacion a Jhon para ejecutar el script.

Se realizaron soguientes preguntas para definir cirterios y así definir cuales sería la caducidad del sistemas.

¿Algun usuaario deberia poder ingresar una vez concluya el contrato o matricula? .. no , los docentes no deberian , los estudiantes una vez concluyen ya no necesitan el sistema y los asistentes necesita. La informacion de la nota o el trabajo , pero mientras esten activos

¿Hay información sensible o que pueda ocurrir en un riesgo si se deja más tiempo? 

Si , el sistema posee la informacion del trabajo de grado del.estudiante

¿En caso de que el.estudiante pierda el documento del trabajo de grado?

Debera por ahora subirse al RIUD y por ende , si se necesita una copia debera estar allá.



Por lo cual con estas bases se puede definir que no es necesario colocar reglas más haya de que se termina el rol.una vez termine el contrato o las novedades del mismo.


Los roles que se irian son : Docentes, evaluador, coordinador(asistente) , oficina de pasantia y estudiante ( depende si esta activo)

**Comment by jcmurilloa** [comment]
Teniendo en cuenta estis requerimientos, se hace necesario la relaización de la gestión para su respectiva implementación en Pólux.

**Comment by mantnicot** [comment]
Se adjunta el documento de caducidad de roles 
[documentod e caducidad de polux](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EceZhbVTPFpCuzJNQ8bcinUBzqk4lTG00RTEVRGFs07GOQ?e=kV66FZ)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot
