### ISSUE TITLE
Gestionar la creación de nuevo usuario en AWS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#25]
Se requiere realizar el 

**Sub Tareas**

- [x] Crear el KANBAN con la solicitud
- [x] Enviar la solicitud a Infraestructura
- [x] Generar seguimiento a respuesta

**Criterios de aceptación**

- [x] Nuevo usuario creado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por Líder proyecto.

**Comment by diagutierrezro** [comment]
Se crea el usuario en AWS de manera exitosa, el desarrollador ya pudo acceder y ver la informacion de XRay

**Comment by jcmurilloa** [comment]
Muy buen trabajo Diego!
