### ISSUE TITLE
Generar documentación sobre depreciación de DB de Oikos en udistrital_core_db

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#250]
Se requiere realizar la evidencia de la sesión sobre la depreciación de DB de OIKOS 

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se genera el documento de analisis de la bajada de sistema
[Documento bajada](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW4y0oHW6ZZDodQVdSnMerIBbcyHlA5XVGjbDbBnEsZPZA?e=jnPLzS)

**Comment by jcmurilloa** [comment]
Muy buen trabajo, en la documentación se refleja claramente el procedimiento y su resultado final @mantnicot
