### ISSUE TITLE
Investigar como realizar filtros hacia AWS para no traer logs basura.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#252]
Se requiere realizar una investigación sobre como realizar filtros en las consultas de AWS con el fin de que no se muestren todos los logs de basura de chequeo de status que se registran en AWS.

**Sub Tareas**

- [x] Realizar investigación para implementación de filtros en busqueda de logs.
- [x] Realizar un documento con posibles filtros a realizar.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Documento realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/11/24

Se solicita a Jaime Leonardo Acosta el usuario de consulta de logs de AWS para poder iniciar con la tarea. Está pendiente recibir su respuesta

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 22/11/24

Debido a un retraso en la obtención de credenciales no se pudo documentar los días anteriores, sin embargo al día de ayer se logró acceder a los Logs de AWS. Así se inicia y termina con la investigación:

Primero que todo se encontró que el mismo AWS tiene documentación al respecto sobre filtros personalizados, que pueden hacerse de dos formas principalmente:

1. Usarlos directamente en la barra de búsqueda de logs de AWS
2. Crear una métrica personalizada

## PRIMER ENLACE: MÉTRICAS PARA GRUPO DE REGISTROS

Ya que lo primero va ligado con lo segundo, se investigó sobre las métricas y posibles filtros a realizar, encontrando en primera instancia un instructivo de AWS para realizar métricas de filtro personalizadas, documentación la cual se puede encontrar en el siguiente enlace:

[Crear un filtro de métricas para un grupo de registros](https://docs.aws.amazon.com/es_es/AmazonCloudWatch/latest/logs/CreateMetricFilterProcedure.html)

En él se listan una serie de pasos para que desde la interfaz de Cloud Watch se puedan crear las métricas deseadas con base en unas pautas, las cuales son lo más relevante ya que la documentación tiene un enlace que redirecciona a la definición de estas pautas, o para más claridad, las distintas formas en las que se pueden filtrar los registros en CloudWatch, enlace que se deja a continuación:

## SEGUNDO ENLACE: SINTAXIS DE FILTROS

[Filtro de sintaxis de patrones para filtros de métricas, filtros de suscripción, eventos de registro de filtros y Live Tail](https://docs.aws.amazon.com/es_es/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html)

En este enlace se listan distintas formas de filtrar:

## Expresiones regulares:

Para las expresiones regulares es importante destacar que para que estas sean reconocidas deben estar entre **%**, es decir:

`%REGEX%`

Así en ese apartado indican una serie de pautas y estándares que se deben seguir para que las expresiones regulares sean reconocidas correctamente. 

Lo importante de esto es que al usar expresiones regulares, el filtro no sólo busca en los encabezados de los registros si no en el contenido de los mismos como muestro en este ejemplo:

**Sin etiquetas de REGEX:**

![Captura de pantalla 2024-11-22 123716](https://github.com/user-attachments/assets/c652d6fb-fd18-4c84-8a68-82c6d95b11f9)

**Con etiquetas de REGEX:**

![Captura de pantalla 2024-11-22 123743](https://github.com/user-attachments/assets/7a57a603-1df7-4cbf-9ad8-f7dfa65ed2c9)

## Usar patrones sin estructura para hacer coincidir con eventos:

Este apartado plantea la utilización de palabras clave para el filtrado de eventos. Pudiendo utilizar desde palabras clave sin más, por ejemplo:

`ERROR`

Lo cual en la búsqueda arroja lo siguiente:

`[ERROR 400] BAD REQUEST`

`[ERROR 401] UNAUTHORIZED REQUEST`

`[ERROR 419] MISSING ARGUMENTS`

`[ERROR 420] INVALID ARGUMENTS`

Por ejemplo también se pueden usar signos de interrogación entre palabras clave para realizar búsquedas más amplias que contengan ambos términos sin importar los argumentos que estén entre ambos, por ejemplo:

`? ERROR ? ARGUMENTS`

Lo que arroja:

```
[ERROR 419] MISSING ARGUMENTS

[ERROR 420] INVALID ARGUMENTS
```

## Filtrado para registros JSON:

Se pueden también filtrar por patrones que contengan registros en formato JSON, con una sintaxis que puede ser simple o compuesta. Un ejemplo de sintaxis puede ser este:
                          
`{ ($.user.id = 1) && ($.users[0].email = "John.Doe@example.com") }`

Este patrón de filtro contiene una expresión compuesta que encuentra una coincidencia de "id" en "user" con un valor numérico de 1 y "email" en "users" con la cadena "John.Doe@example.com".

Nota: Se intentó probar este filtro con los datos de ejemplo de la documentación en la pestaña de prueba de creación de métricas pero al no dar resultado no se coloca una prueba realizada.

## Filtrado de eventos delimitados por espacios:

En este apartado se hace referencia a este tipo de eventos:
                            
`127.0.0.1 Prod frank [10/Oct/2000:13:25:15 -0700] "GET /index.html HTTP/1.0" 404 1534`

Para los cuales, por ejemplo, si se requiere encontrar un registro similar, se tendría el siguiente filtro:

`[ip=%127\.0\.0\.[1-9]%, user, username, timestamp, request =*.html*, status_code = 4*, bytes]`

Esto concluye con un repaso superficial de los métodos que proporciona AWS para la creación de filtros.

## OTROS EJEMPLOS DE FILTROS

El siguiente enlace proporciona otros ejemplos para realizar filtros:

[Creación de filtros de métricas](https://docs.aws.amazon.com/es_es/AmazonCloudWatch/latest/logs/MonitoringPolicyExamples.html)

## FILTROS CON MÉTRICAS

Como complemento a los filtros antes mencionados, se le pueden añadir parámetros de métricas las cuales son especificadas en el siguiente enlace:

[Sintaxis del patrón de filtro para filtros métricos](https://docs.aws.amazon.com/es_es/AmazonCloudWatch/latest/logs/FilterAndPatternSyntaxForMetricFilters.html)

Finalmente se intentó crear una métrica de filtro para poder documentar sin embargo la cuenta no tiene permisos para realizarlos así que se deja como planteamiento teórico:

![Captura de pantalla 2024-11-22 121055](https://github.com/user-attachments/assets/384ead63-5c72-4b52-93ca-e7b8de6da1a7)


Con esto se deja el issue en in review
