### ISSUE TITLE
Ajustes en edición de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#253]
Se requiere realizar ajustes en la edición de espacios fisicos, para esta issue se requiere realizar el precargue de los campos teniendo presente el nuevo alcance en el que se pueden agregar campos ya existentes (revisar posibles opciones), agregar esta lógica al MID donde se tenga presente los campos existentes para inactivar los que ya no existan o crear registros nuevos en caso de ser necesarios.

Finalmente iniciar la creación de rollbacks en caso de que falle la lógica en algún punto de la transacción.

**Sub Tareas**

- [x] Precargar información de campos.
- [x] Implementar la opción de agregar campos existentes.
- [x] Modificar lógica en MID para agregar edición de campos teniendo en cuenta los campos anteriores.
- [x] Iniciar creación de rollbacks.

**Criterios de aceptación**

- [x] Información de campos precargada.
- [x] Campos existentes agregados.
- [x] Lógica de mid modificada.
- [x] Rollbacks creados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Precarga de los campos
Se logra precargar los campos existentes en el espacio físico seleccionado

**Detalles**
![Image](https://github.com/user-attachments/assets/154e6467-14da-4369-bca6-3f8c29ca81fb)

**Editar**
![Image](https://github.com/user-attachments/assets/fd2febc1-e4ea-4f66-af21-f33068dde764)

**En caso de que el espacio no tenga campos, no genera error**

**Detalles**
![Image](https://github.com/user-attachments/assets/4c3476f7-b7d1-4e09-a447-65dc90e4d568)

**Editar**
![Image](https://github.com/user-attachments/assets/97e7b5ff-044f-4b2b-a253-6a46bb5ba58f)

**Comment by xDa04vidx** [comment]
### Adelanto seleccionar campo existente
Se decide manejar una ventana modal para agregar campos existentes, por el momento se tiene algunos inconvenientes en la informacion que se desplega, pero se logra ubicar la informacion de la descripcion, ademas esta informacion tiene deshabilitada la opcion de editar

**Ventana modal**
![Image](https://github.com/user-attachments/assets/ed95ca10-2b7b-4b7d-a820-7c18b60ffadd)

**Resultado despues de seleccionar**
![Image](https://github.com/user-attachments/assets/99133764-eaa9-4f41-b76e-613d35d78b1a)

**Comment by xDa04vidx** [comment]
### Adelanto visual
Se completó la actualización visual para incorporar campos existentes. Esta lógica se implementó tanto en la sección de edición de espacios físicos como en el registro de nuevos espacios físicos. A continuación, se detalla cómo se aplica en ambos casos: registro y edición.

**Registro**
Se agrega el nuevo botón.
![Image](https://github.com/user-attachments/assets/eeb3d71f-f074-426a-a3de-9c38d0fbd4a1)

Ventana modal para la seleccion del campo.
![Image](https://github.com/user-attachments/assets/66ab08c4-8d96-4b5a-968d-180ed6772f60)
![Image](https://github.com/user-attachments/assets/e7906778-e2df-43f7-8a58-b439f432a591)

En el formulario resultante, se añadió la nueva opción "valor", ya que en la base de datos los campos asociados a un espacio físico incluyen información en esa columna.
![Image](https://github.com/user-attachments/assets/0a265b1e-d45a-4ea9-b760-6537df4060e7)
![Image](https://github.com/user-attachments/assets/cbc84ee6-7cfb-4937-88c5-14fdf479d679)


En caso de que se quiera poner un campo que ya ha sido agregado, se muestra una alerta.
![Image](https://github.com/user-attachments/assets/241620d9-88da-4015-9c14-ed53ff059d5f)

**Editar**
En esta sección se aplico una lógica similar con la de registro, con la diferencia de que aquí se precargan los campos que contiene el espacio físico.
![Image](https://github.com/user-attachments/assets/d0054b0f-1a87-49ef-8c2b-dfb77cabaf70)
Se observa que los campos "nombre", "descripcion" y "codigo" estan en gris claro, esto se debe a que estos campos no se pueden editar, y el único campo editable es el de "valor".

Para agregar un nuevo campo existente, aparece la misma ventana modal anterior.
![Image](https://github.com/user-attachments/assets/c698ca94-4183-477e-b3e9-a92226ebfe7c)

Se comprueba que los formularios que se agregan, están vinculados con el original, dado que cuando se agrega un nuevo campo, se inhabilita el botón de editar.
![Image](https://github.com/user-attachments/assets/4d6d6b48-eb29-4bf5-b867-ccfe8ee92df6)

En el envió de información, se creo un json el cual para los campos existentes envía el id de la tabla que relaciona los campos con el espacio físico, mientras que para los nuevos campos que se agregan se envía el id de la tabla del campo y el valor que se decidió agregar, en este caso se modifico un valor de un campo y se agrego un nuevo campo al espacio físico.
![Image](https://github.com/user-attachments/assets/f10538b9-7bcf-4a7f-a396-2d43bbddb380)

Se muestra el json del envio.
![Image](https://github.com/user-attachments/assets/8e2ca934-6abf-4070-bf62-cffd5e7d1194)
