### ISSUE TITLE
Realizar ajustes de visualización en tabla de auditoría

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#254]
Se requiere realizar el desarrollo para generar la visualización de los logs a modo de tabla en el microcliente de auditoría según los logs obtenidos desde el mid, se necesita revisar patrones que se repitan en los diferentes logs para saber que tipo de información mostrar y dependiendo tambien del log, por ejemplo si es un log del middleware o si es simplemente un log de petición http que se muestra directamente desde el API.

Iniciar avances para visualización detallada de cada log, se puede iniciar llenando información basica de la sección detalles del log.

**Sub Tareas**

- [x] Iniciar ajustes de visualización de logs en la tabla de filtro según el tipo de log.
- [x] Iniciar implementación de información del log en el modal creado para esto.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Ajustes de visualización en tabla realizado.
- [x] Implementaciónm de visualización especifica de logs.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* Prueba:

Se hace la petición con filtros por fechas

<img width="959" alt="image" src="https://github.com/user-attachments/assets/64a8e965-9e9d-4cd2-aa42-d1586adee6c9">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3acd8e37-bf1c-4d45-adb0-0dc9e239c9cb">

Se le da clic en la acción de ver "ojo", donde desplega información más detallada

<img width="959" alt="image" src="https://github.com/user-attachments/assets/fa048bd9-eef6-4ab8-afa9-ef13a8bfc916">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/5466f6f8-6c52-4d76-8100-1f90b1f45e57">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/46703f64-a0ee-4797-8cfb-d175c7c6bb3e">

**Comment by JulianAvella** [comment]
Se hicieron ajustes y se desarollo nuevas funcionalidades en el Mid y en el microcliente, donde en el MID se buscan los datos del Log mediante expresiones regulares, solo se logran identificar unos patrones y de estos se extraen unos datos, además que retorna los datos mediante un modelo de respuesta, este modelo lo procesa el microcliente y los va asignando a la tabla con una promesa para que se logren cargar todos los datos que retorna el MID, todos los datos no se muestran en la tabla principal por eso unos datos estan ocultos, para luego se mostrados si el usuario da clic en la acción de "ver - ojo" donde se deja ver la información que falta por mostrar y es más específica

**Comment by JulianAvella** [comment]
Se sube el código del MID al repositorio auditoria_mid en la rama feature/Patrones-logs:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/6b2284bf-e478-4fb6-85cf-32313c958686">

Se sube el código del microciente al repositorio auditoria_mf en la rama feature/Insercion-datos-tabla y se crea su respectivo pull-request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/1732d06e-e834-4b77-a999-1af4fad817b9">
