### ISSUE TITLE
Ajustes en lógica del mid para edición de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#255]
Se requiere realizar la modificación en el MID para implementación de la modificación de espacios fisicos, espcialmente de los campos teniendo presente los nuevos ajustes realizados. Adicional a esto agregar los respectivos rollbacks a la lógica en los casos en que la lógica pueda fallar para que se reviertan los cambios realizados.

**Sub Tareas**

- [x] Modificar lógica en el mid para finalizar edición de espacios fisicos especificamente campos.
- [x] Agregar rollbacks a transacción en el mid.
- [x] Realizar pruebas de funcionamiento.
- [x] Documentar issue con modificaciones y pruebas realizadas.

**Criterios de aceptación**

- [ ] Logica en el mid para edición de campos agregada.
- [ ] Rollbacks agregados.
- [ ] Pruebas realizads.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Se logra realizar la edición de campos


Para esta edición, se utilizaron dos listas provenientes del frontend: una para los campos existentes y otra para los nuevos campos que se deseen agregar.

Manejo de campos existentes:

- Actualización de campos activos:

  Los campos de la lista de existentes se actualizan en los siguientes aspectos:
   Valor: Se asigna el nuevo valor proporcionado.
   Estado activo: Se establece como true sin importar su estado previo.
   Fecha de modificación: Se actualiza con la fecha actual.
  Los objetos modificados se agrupan en una lista denominada camposExistentesActivos.
   
- Actualización de campos no activos:

   Para los campos existentes que no fueron incluidos en la lista inicial, pero que aún están registrados, se realizó una búsqueda general cuyos resultados se almacenaron en la lista camposExistentesEspacio.
   Posteriormente, se compararon ambas listas para identificar los campos restantes, generando una nueva lista llamada camposExistentesNoActivos.
Estos campos se actualizaron configurando su estado Activo como false y actualizando la fecha de modificación.

Manejo de nuevos campos:

- Se iteró la lista de nuevos campos enviada al backend:

   Si el campo ya existe en el espacio físico, se actualiza su estado Activo a true y se asigna el nuevo valor.
   Si el campo no existe, se crea un nuevo objeto para registrar este campo en la base de datos.


Para los casos que se pueden presentar se utilizo el espacio físico con id:1810, a continuación se muestra el estado inicial del espacio físico:
![Image](https://github.com/user-attachments/assets/4f99567e-7de5-44f3-8324-9282d8c3caf3)

Casos:

- Solo se modifican los existentes:
  Respuesta MID:
  ![Image](https://github.com/user-attachments/assets/a07a4792-1a7a-4939-a2c3-26ea87a762bf)
  Cambio:
  ![Image](https://github.com/user-attachments/assets/e946de50-3d45-4695-a548-dd2895f5a4e6)

- No se envía un campo ya existente:
  Respuesta MID:
  ![Image](https://github.com/user-attachments/assets/4d8ad487-c9a3-484d-bdf9-7937a89d36d7)
  Cambio:
  ![Image](https://github.com/user-attachments/assets/3412f1a2-c3c6-4cf7-bdc6-279d6e55d542)

- Se envía un nuevo campo:
  Respuesta MID:
  ![Image](https://github.com/user-attachments/assets/2dde432e-a256-44c9-af59-f1a02ccb6c35)
  Cambio:
  ![Image](https://github.com/user-attachments/assets/79c51ad2-755b-4b00-81dd-59aa7f7caaf8)


- Se envia un nuevo campo que existio con anterioridad:
  Respuesta MID:
  ![Image](https://github.com/user-attachments/assets/4955615b-c139-4441-9838-de1f2c9b1375)
  Cambio:
  ![Image](https://github.com/user-attachments/assets/7f6a9bf6-9d48-40fa-ac96-3b42b07c9b1d)
