### ISSUE TITLE
Iniciar implementación de lógica en historico de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#256]
Se requiere iniciar la implementación de la lógica necesaria para el historico de espacios fisicos. Para esto se debe iniciar los ajustes en el microcliente para obtener la información de las Apis.

**Sub Tareas**

- [x] Iniciar implementación de lógica para historico de espacios fisicos.
- [x] Documentar avances realizados.

**Criterios de aceptación**

- [x] Implementación iniciada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se hace revisión de la Issue y se nota que no hay documentación , se recomienda tener en cuenta la importancia que se le debe dar a la misma .


Favor comentar con tiempo

**Comment by xDa04vidx** [comment]
### Finalización tarea
Se implementó la funcionalidad para buscar espacios físicos por año. Además, se reutilizó la vista de detalles de la sección de edición para permitir la visualización de los detalles del espacio físico deseado. Se realizaron pruebas exhaustivas en la vista de edición para asegurar que los cambios realizados no afectaran su funcionalidad.

A continuación se muestra la implementación de esta vista.

- **Búsqueda por un año**
  ![Image](https://github.com/user-attachments/assets/2c7dd699-822a-4496-8c3a-16255979e0e3)

- **Búsqueda por varios años**
   ![Image](https://github.com/user-attachments/assets/b76f0128-7562-4f1f-96a4-3e6a07c0cd28)
   se visualiza que se suman los resultados.

- **Muestra de detalles de varios espacios físicos**
   - ![Image](https://github.com/user-attachments/assets/65c7175f-f100-4ee6-933e-32184d0cfa75)

   - ![Image](https://github.com/user-attachments/assets/0421b66c-f09a-400c-b907-1dd5613f3cc2)


- **Funcionamiento vista editar (Detalles)**
   ![Image](https://github.com/user-attachments/assets/856f911b-fae7-4778-aa05-f873a5444cf3)

- **Funcionamiento vista editar (Editar)**
  ![Image](https://github.com/user-attachments/assets/423ec48c-0f17-417e-96dd-414ee401803c)

**Comment by xDa04vidx** [comment]
### Pull request
Se agregan los cambios al pull request existente en  [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)
![Image](https://github.com/user-attachments/assets/baef3397-d557-4951-b501-478f4484c959)
