### ISSUE TITLE
Revisar advertencias de seguridad en repositorios de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#257]
Se requiere realizar una revisión de advertencias de seguridad que genera github los cuales en su mayoría son por dependencias por lo que se requiere realizar ajustes de dependencias en los casos que sea posible siempre y cuando no afecten el funcionamiento normal del sistema.

**Sub Tareas**

- [x] Revisar alertas de seguridad en repositorios de Oikos, esto incluye microclientes y APIs (Mid y Crud).
- [x] Realizar ajustes en los casos que se pueda y no afecte la funcionalidad del sistema.
- [x] Documentar cambios realizados.

**Criterios de aceptación**

- [x] Revisión de alertas realizada.
- [x] Ajustes a repositorios realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/11/24

Se intentó realizar la depuración de las incidencias del dependabot en oikos root mf, sin embargo al tratar de modificar las dependencias aparece el siguiente error:

![image](https://github.com/user-attachments/assets/eaf8bc7a-68fb-4c15-ad1b-ed3274c9fb25)

Se están intentando distintos métodos para resolver esto (en una de las documentaciones de npm dice que esto no pasa cuando se tienen nvm pero a pesar de tener este gestor de versiones de node el problema persiste). Por lo que queda pendiente arreglar el inconveniente

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/11/24

Se realizan las correcciones de dependabot para oikos root, gestion y registro de dependencias y mapeo de dependencias, ya que oikos api y dependencias mid no requieren de estos ajustes.

## OIKOS ROOT

En el dependabot se registran los siguientes ajustes a realizar para oikos root:

![Captura de pantalla 2024-11-25 182830](https://github.com/user-attachments/assets/071789a9-ef40-4ed3-a65c-31aef04ccd07)

Para ello se realiza la agregación de los siguientes parámetros en el package.json:

![Captura de pantalla 2024-11-26 122159](https://github.com/user-attachments/assets/a89ef761-48ce-4a3d-8f31-93bc0d1ba7b6)
![Captura de pantalla 2024-11-26 122145](https://github.com/user-attachments/assets/e6bf0168-0521-45f2-b880-2b472181bc3b)

Al hacer npm install, y luego npm list se registra que se hicieron los cambios de versión solicitados por el dependabot:

![Captura de pantalla 2024-11-26 122434](https://github.com/user-attachments/assets/e5178a8f-42dc-49b0-be3f-5076ed9c1d5d)
![Captura de pantalla 2024-11-26 122526](https://github.com/user-attachments/assets/4b6bfbf8-d5aa-4fc9-a5c2-144969ad4e43)
![Captura de pantalla 2024-11-26 122619](https://github.com/user-attachments/assets/782e8cce-0bf9-4f7e-9b97-974e0ea6be51)

Al ejecutar el oikos root funciona normalmente:

![Captura de pantalla 2024-11-26 122124](https://github.com/user-attachments/assets/c6c525d6-318e-4e21-ab8e-4d066a733227)

## MAPEO DE DEPENDENCIAS

Para mapeo de dependencias, el dependabot mostró lo siguiente:

![Captura de pantalla 2024-11-26 124238](https://github.com/user-attachments/assets/f9e10538-509f-461b-9758-be4dd648e0d9)

Para ello se agregó en el package.json los siguientes parámetros para corregir las versiones de las dependencias:

![Captura de pantalla 2024-11-26 133147](https://github.com/user-attachments/assets/e34ca15a-169e-4ac8-872b-6480fd27bc68)
![Captura de pantalla 2024-11-26 133159](https://github.com/user-attachments/assets/a7c001aa-73b5-4ee2-87d9-436fa5924524)

Haciendo npm list para verificar luego del npm install tenemos:

![Captura de pantalla 2024-11-26 131351](https://github.com/user-attachments/assets/80e0660d-0e01-4114-b139-4084f69c39e2)


Y ejecutando mapeo verificamos que funciona correctamente:

![Captura de pantalla 2024-11-26 131918](https://github.com/user-attachments/assets/028a50d8-707d-448c-9659-6b78417cf9c7)

## GESTION Y REGISTRO DE DEPENDENCIAS:

El dependabot en este caso muestra lo siguiente:

![Captura de pantalla 2024-11-26 133715](https://github.com/user-attachments/assets/70181bd9-6d60-4ffc-b26f-1bff9f4f3515)

Para ello se agregan los siguientes parámetros al package json:

![Captura de pantalla 2024-11-26 143543](https://github.com/user-attachments/assets/bcbf3444-6d6d-4ee9-bc5a-60744f419c0c)
![Captura de pantalla 2024-11-26 143551](https://github.com/user-attachments/assets/14cc48c8-06eb-4ed8-ba38-9dd703928cd3)

Luego de hacer npm install, si hacemos npm list confirmamos que las versiones son las deseadas:

![Captura de pantalla 2024-11-26 144007](https://github.com/user-attachments/assets/235f8e83-b366-4fbf-a529-40542918acdc)

Y como podemos comprobar, funciona perfecto tanto gestion como registro de dependencias:


![Captura de pantalla 2024-11-26 144408](https://github.com/user-attachments/assets/7358142a-83af-4b09-b8e9-8fb4ca4dc07a)
![Captura de pantalla 2024-11-26 144500](https://github.com/user-attachments/assets/3c8fe986-b920-4cd3-a827-d1fe3baf4a32)


Por lo tanto se coloca el issue en in review
