### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de requerimiento con el cliente relacionado con los campos espacios físicos en OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#258]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos con el cliente relacionado con los campos que se usaran en los espacio físicos

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/5953079a-9af9-4ffe-9c8d-57cfee2d3d51)

Se ha dado la aprobación de parte del usuario

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, se deja constancia de aprobación del cliente sin necesidad de levantamiento del acta.
