### ISSUE TITLE
Diseñar Mockup relacionado con campos de espacios físicos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#259]
Se requiere realizar el diseño del mockup para el módulo de campos de espacios físicos, teniendo en cuenta requerimientos del cliente

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/303c69c2-d24c-4c73-b6a1-415a1be59fb9)
![Image](https://github.com/user-attachments/assets/04d6cedd-7b81-41b2-a062-4120ad5fe714)


Se han creado los mockups 

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Egyy4mt8L_9PjZ1dVXiZi4ABlbShss80AeLpm529ThpMTw?e=y4Y6qX)

**Comment by mantnicot** [comment]
Después de la revisión con el equipo se define que se cambiara el titulo del sub menú 
" gestión campos "por "Administración de campos"

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/9892fad8-dd9e-420a-aa6d-7eb2e4e5a462)
Se realizo el cambio

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Egyy4mt8L_9PjZ1dVXiZi4ABlbShss80AeLpm529ThpMTw?e=y4Y6qX)

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot, solo resta buscar la aprobación del cliente para dejar todo listo para desarrollo.
