### ISSUE TITLE
Realizar pruebas de funcionamiento en ambiente de pruebas del API de firma electronica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#26]
Se requiere realizar las pruebas de funcionamiento de la implementación para la nueva funcionalidad desarrollada en #18 en el ambiente de pruebas, se debe verificar que el registro en la tabla documento se esté creando inicialmente con el campo UID vacio y posteriormente se actualice dicho campo con el valor devuelto por Nuxeo, adicionalmente se debe verificar que la funcionalidad migrada hacia la nueva API de firma electronica funcione correctamente, es caso de encontraro errores realizar los respectivos ajustes.

**Sub Tareas**

- [x] Pruebas de funcionamiento en ambiente de pruebas.
- [x] Pruebas de interoperabilidad entre nueva API de firma electroncia y nueva funcionalidad del gestor documental.
- [x] Ajustes realizados en caso de ser necesario.
- [x] Documentación del issue con las pruebas y ajustes realizados en caso de ser necesario.

**Criterios de aceptación**

- [x] Pruebas realizadas en ambiente de pruebas.
- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Dependencias**

@diagutierrezro queda pendiente por realizar solicitudes para creación de infraestructura y posterior despliegue en ambiente de pruebas del API firma_electronica.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se realizaron las pruebas de la nueva funcionalidad en el gestor documental en pruebas, pero el despliegue a pruebas de la firma electronica no se finalizó correctamente por lo que no se pudieron realizar las pruebas.


![Image](https://github.com/udistrital/core_documentacion/assets/38676533/5bb80cfd-0dfb-4f5a-9cb6-c72a71f48c80)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 07/06/2024

Se realizó la prueba de interoperabilidad de firma electrónica y gestor documental en ambiente de pruebas de la siguiente manera:

El JSON que se usó para esta prueba se adjunta en un txt, en el cual se ingresa el base 64 del archivo de prueba que se utilizó en local:

[Prueba integracion.txt](https://github.com/user-attachments/files/15745275/Prueba.integracion.txt)

Se hizo uso de POSTMAN para realizar la petición:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/82e5fe28-0deb-4fad-bfd9-da60d0294948)

Se obtuvo como resultado un caso de éxito con un código 200:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/d7e007b3-7e2d-49c0-a5cb-f2eda8717026)

Se adjunta un txt con la respuesta de postman:

[responseAmbientePruebas.txt](https://github.com/user-attachments/files/15745283/responseAmbientePruebas.txt)
