### ISSUE TITLE
Implementar endpoint para obtención del listado de Apis a consultar.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#260]
Se requiere realizar la implementación del endpoint que retorna la información de las Apis a las que un cliente tiene acceso, para esto primero se debe realizar la implementación del envío de información utilizando el metodo de custom events desde el root hacia el microcliente y desde allí se consultará el endpoint creado por Jhon y se implementará para obtener el listado.

**Dependencias**
Para este issue se depende de la rapidez con la que se cree el endpoint que retorna las Apis.

**Sub Tareas**

- [x] Implementar custom events para enviar información desde el root hacia el mf.
- [x] Implementar endpoint para obtener listado de Apis.
- [x] Documentar issue con implementaciones realizadas.

**Criterios de aceptación**

- [x] Custom events desde root hacia mf implementado.
- [x] Endpoint de listado de apis implementado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Este es el código con custom events que se desarrollo para el oikos_root_mf, donde se llama a un endpoint de un bus de servicios, el cual retorna un listado con el nombre de apis:

import { registerApplication, start, mountRootParcel } from "single-spa";
import {
  constructApplications,
  constructRoutes,
  constructLayoutEngine,
} from "single-spa-layout";
import microfrontendLayout from "./microfrontend-layout.html";
import "./assets/styles/index.css";

let environment;

declare var isProd: boolean | undefined;
declare var isDev: boolean | undefined;
if (isProd) {
  environment = require("./environments/environment.production");
} else if (isDev) {
  environment = require("./environments/environment.development");
} else {
  environment = require("./environments/environment");
}

const data = {
  props: environment,
  loaders: {},
};

const routes = constructRoutes(microfrontendLayout, data);
const applications = constructApplications({
  routes,
  loadApp({ name }) {
    return System.import(name);
  },
});
const layoutEngine = constructLayoutEngine({ routes, applications });

applications.forEach(registerApplication);
layoutEngine.activate();
start();

async function fetchApiData() {
  const url =
    "http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/wso2/apis_cliente?cliente=e36v1MPQk2jbz9KM4SmKhk8Cyw0a";

  try {
    const response = await fetch(url);
    const textResponse = await response.text();

    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(textResponse, "application/xml");

    const apis = Array.from(xmlDoc.getElementsByTagName("api")).map((api) => ({
      version: api.getElementsByTagName("api_version")[0]?.textContent,
      nombre: api.getElementsByTagName("nombre")[0]?.textContent,
      entorno: api.getElementsByTagName("entorno")[0]?.textContent,
      contexto: api.getElementsByTagName("contexto")[0]?.textContent,
    }));

    console.log("Datos de la API:", apis);

    window.dispatchEvent(new CustomEvent("apiDataFetched", { detail: apis }));
  } catch (error) {
    console.error("Error al consultar la API:", error);
  }
}


window.addEventListener('appMounted', (event: Event) => {
  /*const customEvent = event as CustomEvent;
  if (customEvent.detail.appName === '@udistrital/auditoria-mf') {
    window.dispatchEvent(new CustomEvent('infoRoot', { detail: "Prueba desde Root con custom Events" }));
  }*/
  const customEvent = event as CustomEvent;
  if (customEvent.detail.appName === "@udistrital/auditoria-mf") {
    fetchApiData(); 
  }
});

window.addEventListener("apiDataFetched", (event: Event) => {
  const customEvent = event as CustomEvent;
  console.log("Datos recibidos en apiDataFetched:", customEvent.detail);
});

**Comment by JulianAvella** [comment]
Con el anterior código se esta generando un error ya que no retorna la información del endpoint del bus de servicios:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5fea3f2f-3d4d-401c-8897-0af7eeede182">
<img width="713" alt="image" src="https://github.com/user-attachments/assets/6ea71891-f03f-4a80-a393-35c0d35938ee">

Se evalua que el endpoint del bus de servicios este respodiendo desde postman:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/254ab455-4c4e-4b09-bb62-f16fbc304c35">

Por eso se esta probando la corrección de este error
