### ISSUE TITLE
Construir diagrama modular y de procesos del sistema auditoría

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#261]
Se requiere realizar la construcción de los diagramas modulares y de procesos del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se agrega los diagramas tanto modulares como de proceso

[Diagrama de proceso](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtCw9cep1kRIpBWb3dAwOfIBu7AbTrYvkC4QixXqTctaZQ?e=hxq0eH)
[Diagrama modular](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuPOMgdSxBVLr2jUL2xwIDMBnROaXNwfgWHXaoWt586plg?e=uU7HaY)


![Image](https://github.com/user-attachments/assets/41b1534a-d637-4f3c-b981-3276ea539a0a)
![Image](https://github.com/user-attachments/assets/00ca20d0-f0e5-4f93-899e-34fda4f8cb77)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
