### ISSUE TITLE
Iniciar mejoramiento en la visualización de información según el tipo de log.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#263]
Se requiere realizar un análisis sobre como se podría pulir la visualización del log según el tipo de log que se quiera consultar. Por ejemplo, si es un log de librería se puede separar la información según el usuario, el endpoint al que se apunta, información enviada, si se realiza hacia un CRUD pulir la consulta que se realiza, etc.

**Sub Tareas**

- [x] Analizar patrones para extraer datos de los logs.
- [x] Iniciar extracción de datos para pulir visualización.
- [x] Documentar extracciones realizados.

**Criterios de aceptación**

- [x] Patrones analizados
- [x] Extracción de datos iniciada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
@JulianAvella Te solicité que por favor documentaras la issue mientras se va desarrollando. Transcurrió el sprint completo y no se realizó documentación.

**Comment by JulianAvella** [comment]
Se realiza el ajuste para que en el campo de la petición realizada los datos del json se muestren de una forma más clara y limpia de carácteres:

* Peticiones post:

Asi queda con la data limpia
<img width="677" alt="image" src="https://github.com/user-attachments/assets/9c54df2d-25e8-4ce8-815e-7a38f8226c00">

Asi es como llega el log:

2024/11/08 17:05:28.797 [1;34m[I][0m [middleware.go:122]  @&polux_crud@&pruebasapi.intranetoas.udistrital.edu.co:8108@&/v1/solicitud_trabajo_grado@&POST@&2024-11-08 17:05:28.789526007 +0000 UTC m=+260034.098128219@&172.30.5.17@&Go-http-client/1.1@&@&map[RouterPattern:/v1/solicitud_trabajo_grado/ json:map[Data:{%!s(int=1968) 2024-11-08 17:05:30.911 +0000 UTC %!s(*models.ModalidadTipoSolicitud=&{13 4634 4602}) %!s(*models.TrabajoGrado=<nil>) 2024-3 {"ciudadNacimiento":"","correoPersonal":"","direccionResidencia":"","eps":"","fechaNacimiento":"","pasantiaInterna":false,"telefono":""}} Message:Registration successful Status:201 Success:%!s(bool=true)]]@$ 

* Petición get:

Asi queda con la data limpia
<img width="677" alt="image" src="https://github.com/user-attachments/assets/e10852c2-c3da-4666-b67e-d58f9a51e155">

Asi es como llega el log:

2024/11/08 16:01:23.605 [1;34m[I][0m [middleware.go:122]  @&polux_crud@&pruebasapi.intranetoas.udistrital.edu.co:8108@&/v1/respuesta_solicitud?query=EstadoSolicitud%3A4631%2CActivo%3Atrue&limit=0@&GET@&2024-11-08 16:01:23.570261394 +0000 UTC m=+256188.878863608@&181.237.95.115@&Synapse-PT-HttpComponents-NIO@&pruebasoaspolux2@&map[RouterPattern:/v1/respuesta_solicitud/ json:map[Data:[{%!s(int=3828) 2024-11-07 17:09:23.117 +0000 UTC 5-12 a mí 5-23 %!s(int=0) %!s(int=79702248) %!s(int=4631) %!s(*models.SolicitudTrabajoGrado=&{1959 {804000000 63866594465 0x1b2dc00} 0xc000976bd0 <nil> 2024-3 {"ciudadNacimiento":"","correoPersonal":"","direccionResidencia":"","eps":"","fechaNacimiento":"","pasantiaInterna":false,"telefono":""}}) %!s(bool=true)}] Message:Request successful Status:200 Success:%!s(bool=true)]]@$ 

* Petición que contiene error: 

Se genera una petición desde postman para generar error

<img width="650" alt="image" src="https://github.com/user-attachments/assets/ed09b4d9-babc-4287-a932-f76d1c33521e">

Pero no queda información del error, como se muestra en los logs, por no se logro mostrar información del error en el microcliente
<img width="757" alt="image" src="https://github.com/user-attachments/assets/29a055ed-032d-44eb-992b-26f76b3d6b08">

* Pull request:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/515ab49a-195e-4139-9d63-3f1054652289">
