### ISSUE TITLE
Levantar requerimientos respecto a LOGS para el sistema Auditoría

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#264]
Se requiere realizar el levantamiento de requerimientos frente a los LOGS necesarios en el sistema de auditoría con el cliente

**Sub Tareas**

- [x] Contactar con cliente 
- [x] Levantar los requerimientos frente a la necesidad
- [x] Documentar la información requerida 

**Criterios de aceptación**

- [x] Contacto con el cliente
- [x] Issue documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se adjunta un documento que explica la necesidad y asi mismo dejar evidencia de la aprobación del log

[documento de log auditoria](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Eec7O122lbVDiZZnhUYV6DwBoYawLykiBp4FBWFz8tOlXg?e=lg0EwE)

**Comment by jcmurilloa** [comment]
Investigación realizada asertivamente.
