### ISSUE TITLE
Analizar combinación de multiples filtros.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#267]
Se requiere realizar un análisis en la posibilidad de realizar diferentes combinaciones de filtros hacia AWS, por ejemplo los logs que contengan middleware y sean de tipo POST.

**Sub Tareas**

- [x] Análisis de combinación de filtros realizados.
- [x] Documentar opciones y/o limitantes encontradas.

**Criterios de aceptación**

- [x] Análisis realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 02/12/24

Se realiza el análisis y una prueba de los múltiples filtros con el método de start_query.

Para realizarlos es necesario solamente utilizar un **and** u otro operador lógico según se requiera y agregar otro parámetro para el filtro, es decir, por ejemplo:

![image](https://github.com/user-attachments/assets/052bc22a-85bd-453e-932a-957598914b9c)

En la línea 74 se tiene el filtro en el cual el mensaje del log contenga un GET pero se le agregó un **and** para también incluir en el filtro que los mensajes de los logs contuviesen middleware, así como se colocó un and ambas condiciones se deben cumplir para que el sistema traiga a los logs requeridos

Posteriormente se realizó la prueba del query anterior mostrado en el endpoint de prueba y el resultado fué exitoso:

![image](https://github.com/user-attachments/assets/9cd91962-296a-4097-8601-81dcf2cb1abd)

Se coloca el issue en in review
