### ISSUE TITLE
Implementación final de filtros.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#268]
Se requiere realizar la implementación final de filtros hacia el API MID de auditoría teniendo presente el análisis hecho en #265 y lo encontrado en #267, en este filtro se deben tener presente las diferentes busquedas realizadas según los mockups, tipo de logs, fecha y hora y según lo acordado con Maria Fernanda se deben consultar los logs de middleware.

Ajustar tipos de log que se muestran en el microcliente (GET, POST, PUT y DELETE)

**Sub Tareas**

- [x] Implementar filtros teniendo en cuenta los análisis y acuerdos realizados.
- [x] Realizar diferentes pruebas de funcionamiento.
- [x] Ajustar tipos de log en microcliente.

**Criterios de aceptación**

- [x] Implementación de filtros realizada.
- [x] Pruebas realizadas.
- [x] Tipos de log ajustados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 03/12/24

Se realiza la implementación de los filtros múltiples en el endpoint real, mediante la siguiente modificación en el query string:

![Captura de pantalla 2024-12-03 182414](https://github.com/user-attachments/assets/29ac8456-7d66-42de-8b44-3d62519e5407)

Así se buscará siempre los logs que contengan middleware, además de el patrón que el usuario seleccione en la interfaz de auditoria.

## Se realizan las pruebas:

**Se consultan los POST**:

![Captura de pantalla 2024-12-03 182713](https://github.com/user-attachments/assets/da6aa722-a7dc-489f-ba23-038f35f86a87)
![Captura de pantalla 2024-12-03 182709](https://github.com/user-attachments/assets/02e4c9c2-4665-4827-b57e-471f3da2bbfd)

**Se consultan los PUT**:

![Captura de pantalla 2024-12-03 182732](https://github.com/user-attachments/assets/6ac691a5-ffd6-4ebb-ab40-4cc017c1318f)
![Captura de pantalla 2024-12-03 182744](https://github.com/user-attachments/assets/fa7e9738-ed32-40e1-9a58-4d3da5438c60)

**Se consultan los GET**:

![Captura de pantalla 2024-12-03 182810](https://github.com/user-attachments/assets/5b1a70b2-42e1-4632-bef6-fabb38c4a9a8)
![Captura de pantalla 2024-12-03 182825](https://github.com/user-attachments/assets/56ed0758-47c0-4008-9c64-06a60e8fac88)


Por lo tanto queda pendiente la eliminación de la opción middleware de la lista desplegable de la interfaz de auditoría

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 04/12/2024

Se retira de la lista desplegable la opción de middleware, mediante el ajuste del arreglo de Strings tiposLogs:

![Captura de pantalla 2024-12-04 165705](https://github.com/user-attachments/assets/3ce6d149-9ce6-4cb0-a4ff-c100c2cc81ed)

Quedando el cliente de la siguiente manera:

![Captura de pantalla 2024-12-04 165659](https://github.com/user-attachments/assets/8b6ee0ae-0ac3-4c9e-b855-98f795f392cc)

Se deja en in review la issue
