### ISSUE TITLE
Continuar implementación de historico de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#269]
Se requiere realizar la continuación de la implementación del módulo de historico de espacios fisicos que se inició en #256, para este issue el alcance se requiere solucionar el error que se presenta en la edición de espacios fisicos debido a que se está reutilizando la misma vista. Adicional se requiere realizar la modificación en los años listados para que no se quemen dentro del código, se plantea realizar una petición ordenando por fecha de creación para traer el registro mas antiguo y se crea un listado de años hasta el año actual.

**Sub Tareas**

- [x] Solucionar error presentado en la edición de espacios fisicos.
- [x] Modificar listado de años.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Error solucionado.
- [x] Modificación de lista realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto obtención de datos de años

Se genera una petición que permite obtener la información de los espacios físicos relacionados con la tabla de asignación de espacio físico dependencia, organizados en orden descendente.

![Image](https://github.com/user-attachments/assets/4564011d-0983-426c-81eb-ccbb1d693634)

Se configurará la petición para obtener únicamente el primer resultado utilizando limit=1. En el frontend, se calculará el año actual y se determinará la cantidad de años transcurridos desde el año del primer registro obtenido hasta el año actual.

**Comment by xDa04vidx** [comment]
### Finalización de consulta de años
Se logra realizar los cálculos para obtener los años desde el primer registro hasta el año actual
![Image](https://github.com/user-attachments/assets/c7d57871-73a3-4872-8539-2c1ad2686478)

**Comment by xDa04vidx** [comment]
### Error edición
El error relacionado con la edición de espacios físicos se resuelve identificando y corrigiendo líneas de código que estaban comentadas. Además, se detectó que los tipos de espacios deben tener el atributo Activo configurado como true, ya que la lista utilizada para la búsqueda aplica esta condición. Esto asegura que solo los espacios físicos válidos y activos estén disponibles para su edición. 

Vista edición inicial:
![Image](https://github.com/user-attachments/assets/da4fde18-627f-44e6-8c37-c11f669a747c)

Vista edición se cambia el nombre, el tipo de espacio y se borra un campo:
![Image](https://github.com/user-attachments/assets/a2dc45fe-81bb-4428-84b9-2279b4538ebf)

Cambios realizados:
![Image](https://github.com/user-attachments/assets/b192d780-b12e-41e1-9957-ffc4b1d31407)

**Comment by xDa04vidx** [comment]
### Pull request
Se agregan los cambios al pull request existente en [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)

![Image](https://github.com/user-attachments/assets/2c7a8f0a-0079-4d0e-b658-6a70342ff912)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David
