### ISSUE TITLE
Iniciar pruebas de concepto para modificación de logs de auditoría

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#270]
Se requiere realizar pruebas de concepto realizando modificaciones en la librería de auditoría con el fin de mejorar la información suministrada en dichos logs y de esta manera aumentar la calidad de la información que se puede visualizar desde el cliente.

**Dependencias**
Es importante informar a Maria Fernanda de lo que se planea realizar para obtener apoyo por parte de ella principalmente para evitar desplegar errores ya que esta librería se utiliza actualmente en multiples APIs.

**Sub Tareas**

- [x] Realizar modificaciones en la librería con el fin de mejorar la información suministrada.
- [x] Realizar pruebas de los cambios realizados.
- [x] Documentar modificaciones y pruebas realizadas.

**Criterios de aceptación**

- [x] Modificaciones realizadas.
- [x] Pruebas realizadas.
- [x] Documentación realizada.
**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
** Avance 02/12/2024:**

Se clona el repositorio de polux_crud y utils_oas, luego se copia la carpeta de auditoria del repo utils_oas en el repo polux_crud, esto es con el fin de trabajar con el código de auditoria de forma local en el proyecto de prueba, en este caso es polux_crud.

Primero se verifica que el proyecto de polux_crud se este ejecutando sin errores en el entorno local de desarrollo, luego se agrega la carpeta copiada de auditoria y en la función que inicia el middleware se coloca un print para saber si se ejecuta sin errores el middleware de forma local:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/883dc11f-6eb4-4bb7-8467-75e7557ecb87">

**Comment by JulianAvella** [comment]
* **Actualización 04/12/2024**

Se modifica la función ListenRequest() y se agregan unas funciones auxiliares, para poder guardar la información del log en formato "clave" : "valor" en AWS.

Como responde el middleware sin hacerle cambios:

Middleware inicializado correctamente.
2024/12/03 15:36:20.628 [I] [asm_amd64.s:1571]  http server Running on http://:8080
2024-12-03T15:36:28-05:00 [INFO] X-Ray proxy using address : 3.81.69.43:2000
[ORM]2024/12/03 15:36:33  -[Queries/default] - [  OK /    db.Query /  5186.0ms] - [SELECT T0."id", T0."titulo", T0."modalidad", T0."estado_trabajo_grado", T0."distincion_trabajo_grado", T0."periodo_academico", T0."objetivo", T1."id", T1."nombre", T1."descripcion", T1."codigo_abreviacion", T1."activo" FROM "trabajo_grado" T0 LEFT OUTER JOIN "distincion_trabajo_grado" T1 ON T1."id" = T0."distincion_trabajo_grado" LIMIT 10]
2024/12/03 15:36:33.292 [D] [server.go:2916]  |            ::1| 200 | 5.187588736s|   match| GET      /v1/trabajo_grado   r:/v1/trabajo_grado/
2024/12/03 15:36:33.293 [I] [middleware.go:115]  @&polux_crud
@&localhost:8080
@&/v1/trabajo_grado?limit=10
@&GET
@&2024-12-03 15:36:33.292765761 -0500 -05 m=+15.721980246
@&::1
@&PostmanRuntime/7.43.0
@&Error wso2
@&map[RouterPattern:/v1/trabajo_grado/ json:map[Data:[{%!s(int=503) correos %!s(int=4604) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2023-1 obj} {%!s(int=87) PROPUESTA EXTERNA %!s(int=4601) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2023-3 OBJETIVOS} {%!s(int=68) pasantia doble %!s(int=4601) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2023-1 } {%!s(int=69) pasantia doble 2 %!s(int=4601) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2023-1 } {%!s(int=89) PROPUESTA EXTERNA %!s(int=4601) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2023-3 OBJETIVOS} {%!s(int=145) Aprobada la modalidad de cursar espacios académicos de posgrado %!s(int=4602) %!s(int=4570) %!s(*models.DistincionTrabajoGrado=<nil>) 2024-1 } {%!s(int=216) Espacios Académicos de Posgrado %!s(int=4602) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2024-1 } {%!s(int=164) Espacios Académicos de Posgrado %!s(int=4602) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2024-1 } {%!s(int=166) Espacios Académicos de Posgrado %!s(int=4602) %!s(int=4571) %!s(*models.DistincionTrabajoGrado=<nil>) 2024-1 } {%!s(int=146) Reprobada la modalidad de cursar espacios académicos de posgrado %!s(int=4602) %!s(int=4572) %!s(*models.DistincionTrabajoGrado=<nil>) 2024-1 }] Message:Request successful Status:200 Success:%!s(bool=true)]]@$  


Asi quedo respondiendo el middlware luego de hacer los cambios:


Listed buckets successfully
Middleware inicializado correctamente.
2024/12/03 15:49:41.574 [I] [asm_amd64.s:1571]  http server Running on http://:8080
2024-12-03T15:49:45-05:00 [INFO] X-Ray proxy using address : 3.81.69.43:2000
[ORM]2024/12/03 15:49:45  -[Queries/default] - [  OK /    db.Query /   229.4ms] - [SELECT T0."id", T0."titulo", T0."modalidad", T0."estado_trabajo_grado", T0."distincion_trabajo_grado", T0."periodo_academico", T0."objetivo", T1."id", T1."nombre", T1."descripcion", T1."codigo_abreviacion", T1."activo" FROM "trabajo_grado" T0 LEFT OUTER JOIN "distincion_trabajo_grado" T1 ON T1."id" = T0."distincion_trabajo_grado" LIMIT 10]
2024/12/03 15:49:45.357 [D] [server.go:2916]  |            ::1| 200 | 230.801414ms|   match| GET      /v1/trabajo_grado   r:/v1/trabajo_grado/
2024/12/03 15:49:45.357 [I] [middleware.go:172]  {
  "app_name": "polux_crud",
  "data": {
    "RouterPattern": "/v1/trabajo_grado/",
    "json": {
      "Data": [
        {
          "Id": 503,
          "Titulo": "correos",
          "Modalidad": 4604,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2023-1",
          "Objetivo": "obj"
        },
        {
          "Id": 87,
          "Titulo": "PROPUESTA EXTERNA",
          "Modalidad": 4601,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2023-3",
          "Objetivo": "OBJETIVOS"
        },
        {
          "Id": 68,
          "Titulo": "pasantia doble",
          "Modalidad": 4601,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2023-1",
          "Objetivo": ""
        },
        {
          "Id": 69,
          "Titulo": "pasantia doble 2",
          "Modalidad": 4601,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2023-1",
          "Objetivo": ""
        },
        {
          "Id": 89,
          "Titulo": "PROPUESTA EXTERNA",
          "Modalidad": 4601,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2023-3",
          "Objetivo": "OBJETIVOS"
        },
        {
          "Id": 145,
          "Titulo": "Aprobada la modalidad de cursar espacios académicos de posgrado",
          "Modalidad": 4602,
          "EstadoTrabajoGrado": 4570,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "Objetivo": ""
        },
        {
          "Id": 216,
          "Titulo": "Espacios Académicos de Posgrado",
          "Modalidad": 4602,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "Objetivo": ""
        },
        {
          "Id": 164,
          "Titulo": "Espacios Académicos de Posgrado",
          "Modalidad": 4602,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "Objetivo": ""
        },
        {
          "Id": 166,
          "Titulo": "Espacios Académicos de Posgrado",
          "Modalidad": 4602,
          "EstadoTrabajoGrado": 4571,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "Objetivo": ""
        },
        {
          "Id": 146,
          "Titulo": "Reprobada la modalidad de cursar espacios académicos de posgrado",
          "Modalidad": 4602,
          "EstadoTrabajoGrado": 4572,
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "DistincionTrabajoGrado": null,
          "PeriodoAcademico": "2024-1",
          "PeriodoAcademico": "2024-1",
          "Objetivo": ""
        }
        }
      ],
      "Message": "Request successful",
      "Status": "200",
      "Success": true
    }
  },
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
      "Status": "200",
      "Success": true
    }
  },
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
  "ip_user": "::1",
  "method": "GET",
  "user": "Error WSO2",
  "user_agent": "PostmanRuntime/7.43.0"
}
      "Status": "200",
      "Success": true
    }
  },
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
  "ip_user": "::1",
  "method": "GET",
  "user": "Error WSO2",
      "Status": "200",
      "Success": true
    }
  },
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
  "ip_user": "::1",
    }
  },
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
  "date": "2024-12-03T15:49:45-05:00",
  "end_point": "/v1/trabajo_grado?limit=10",
  "host": "localhost:8080",
  "host": "localhost:8080",
  "ip_user": "::1",
  "method": "GET",
  "user": "Error WSO2",
  "user_agent": "PostmanRuntime/7.43.0"
}

Nota uno: el cambio tiene un error, porque me duplica la información, ejemplo "host", "end_point", entre otros, se continua revisando el código para evitar este error.

Nota dos: Los cambios realizados se subieron en el archivo auditoria/middleware.go, dentro de la rama feature/Middleware-json, que esta en el repositorio utils_oas:

<img width="629" alt="image" src="https://github.com/user-attachments/assets/fde360bc-8120-4d68-a121-a8499e16da99">

**Comment by JulianAvella** [comment]
El error de los datos duplicados fue arreglado:

<img width="693" alt="image" src="https://github.com/user-attachments/assets/fbcf7e5a-75bc-44a0-92cd-5e945f5a34c9">
