### ISSUE TITLE
Realizar cambio de endpoint en xray (demonio ) y realizar las pruebas de mapeo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#271]
Se requiere realizar el cambio de endpoint en xray (demonio ) y realizar las pruebas de mapeo

**Sub Tareas**

- [x] Contactar con el responsable 
- [x] Generar el cambio de endpoint con acompañamiento de responsables
- [x] Realizar las pruebas de mapeo

**Criterios de aceptación**

- [x] Cambio de endpoint realizado
- [x] Documentación de pruebas de mapeo

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha agendado una reunión con Jaime y Mafe para realizar el cambio en conjunto con ellos y poder solventar inconvenientes o dudas

04/12/2024 a las 11:00 am
[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDE0ZTRmZjItZTYxNS00OTcwLTk0ZjMtNjUwZDZkYWQwM2I5%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha realizado los cambios , se deja el documento de evidencia y se espera responder el kanban para asignar el usuario a cloudwatch y así hacer monitoreo de la solución en diferentes apis por medio de logs 

[documento de cambio](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESbbRhIOnb5JiMsZ2il74QYB1YLQUm_K7r7smpfxS3PQQw?e=CB0Rqu)

**Comment by jcmurilloa** [comment]
De esta manera queda pendiente generar el respectivo monitoreo, buen trabajo @mantnicot
