### ISSUE TITLE
Iniciar ajustes finales para módulo de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#272]
Se requiere realizar los ajustes finales que se encontraban pendientes en el registro de espacios fisicos nuevos, estos cambios son:
- Quitar el botón para agregar campos nuevos, dejar únicamente campos existentes.
- Modificar la lógica en el Mid para que no cree nuevos campos sino que se asocien a campos ya existentes.
- Realizar modificaciones para activar y desactivar espacios fisicos, importante tener en cuenta que tambien se activan y desactivan las diferentes relaciones con las otras tablas (dependencias, campos, tipo de uso, etc).

**Sub Tareas**

- [x] Realizar ajustes indicados.
- [x] Realizar pruebas de funcionamiento correcto.
- [x] Documentar ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Vista de registro y edición de espacios físicos
Se realiza el ajusta de la visualización, se borra el botón y en el ts se quita la función que permitía registrar nuevos campos.

- Vista registrar:
  ![Image](https://github.com/user-attachments/assets/11b04ff3-8574-4ef2-aec8-81233d14b8e9)
  funcionamiento:
  - Selección:
    ![Image](https://github.com/user-attachments/assets/badfc211-57dd-43e7-a34e-8327246cbf14)

  - Muestra:
    ![Image](https://github.com/user-attachments/assets/54591626-b8ac-41de-9a37-4449e12bcd04)


- Vista editar:
  ![Image](https://github.com/user-attachments/assets/03d476b0-6542-4b78-a7b0-a50be5e6f21b)
  funcionamiento:
  - Selección:
    ![Image](https://github.com/user-attachments/assets/14fb76d2-2e5f-441a-ac98-992d97ab6c97)

  - Muestra:
    ![Image](https://github.com/user-attachments/assets/dd9f50e5-c708-49d8-b50a-e90b1213d8e2)

Por el momento solo se puede ver el funcionamiento en editar.

- Espacio inicial:
  ![Image](https://github.com/user-attachments/assets/18498291-7150-4d04-8e36-c4e7bac50abb)

- Se agrega un nuevo campo:
  ![Image](https://github.com/user-attachments/assets/cd788542-6bc4-4b46-9f62-02541445d21a)

- Se visualiza el nuevo campo:
  ![Image](https://github.com/user-attachments/assets/ce18c15c-ce34-425b-a017-992bdcc388b3)
  ![Image](https://github.com/user-attachments/assets/fc724b0f-d257-4e03-a91c-4dc4e7e9ca22)

**Comment by xDa04vidx** [comment]
### Registro mid

Se realizan los ajustes en el mid para que el registro se pueda realizar, pero con campos existentes, además se ajustan los rollbacks necesarios.

A continuación se muestra las diferentes respuestas

- Nuevo espacio físico sin errores.
  Respuesta API:
  ![Image](https://github.com/user-attachments/assets/13ae0350-ef52-4f9e-a51f-e2f85d2dda00)
  Base de datos:
  ![Image](https://github.com/user-attachments/assets/78ba73ff-f6c6-4445-aafa-8cddf245be44)
  el id del espacio creado es 1833
  ![Image](https://github.com/user-attachments/assets/78f2bacc-7c6c-42f3-a5bf-3b9fa54ef210)

- Nuevo espacio físico con un campo inexistente (primer campo).
  Respuesta API:
  ![Image](https://github.com/user-attachments/assets/53dca21a-6455-4b00-a61d-cdfe477d60d6)
  Base de datos:
  ![Image](https://github.com/user-attachments/assets/a209e83d-842c-49b6-83c7-a26b3af30031)
  No se crea el numero 8

- Nuevo espacio físico con un campo inexistente (segundo campo).
  Respuesta API:
  ![Image](https://github.com/user-attachments/assets/c58cd3ae-432e-40bc-b2fe-dda300f9881a)
  Base de datos:
  ![Image](https://github.com/user-attachments/assets/e78430b2-39e3-423e-9f49-264d30ac9f89)
  No se crea el numero 8.
  Se verifica con el segundo campo, dado que este es un error diferente, pues ya se creo un espacio fisico campo, por tal razón se debe entrar a borrarlo y luego seguir con los otros rollbacks

- Generación de error en la creación de la relación de campo espacio físico con campo.
  Error:
  ![Image](https://github.com/user-attachments/assets/456ce4fd-c9bc-41fd-9443-665e48a73620)
  Respuesta API:
  ![Image](https://github.com/user-attachments/assets/4dc3a6dc-04a0-4444-a057-a9eb7ab7e6ab)
  Base de datos:
  ![Image](https://github.com/user-attachments/assets/ea447280-0d66-4c65-858f-15c87836f6f9)
  No se crea el numero 8.

**Comment by xDa04vidx** [comment]
### Frontend Registro

Se realizan los cambios necesarios para el funcionamiento de creación de espacios físicos.

Vista inicial:
![Image](https://github.com/user-attachments/assets/761ca570-d302-4881-8473-33ff4ab08684)

Respuesta:
![Image](https://github.com/user-attachments/assets/4ded6ce9-1bc8-48ba-b1df-fe1a1396fc74)

- Base de datos:
  Espacio físico:
  ![Image](https://github.com/user-attachments/assets/95621ee8-242a-4846-a642-a1ec541e9e43)
  Espacio físico campo:
  ![Image](https://github.com/user-attachments/assets/da2b6790-867c-444e-a913-d843e603dd31)

**Comment by xDa04vidx** [comment]
### Activar y Desactivar espacio físico

Se logra realizar los endpoints para activar y desactivar el espacio físico, para ello se modifica varios registros de las tablas de espacio físico, tipo uso espacio físico, asignación espacio físico y espacio físico campo. También se tenían que realizar los rollbacks pertinentes, para ello se observo que la función necesaria para devolver el cambio era la misma que se utilizaba, así que para devolver el cambio se utilizaron las mismas funciones tanto en espacio físico, tipo uso espacio físico y asignación espacio físico, no obstante para la modificación de espacio físico campo se estableció una función especializada para el rollback, y después se llaman las otras funciones.

### Casos

- Desactivar un espacio físico
  Se modificara el espacio físico con id 1833, que actualmente tiene todas sus relaciones en activo true
  Api:
  ![Image](https://github.com/user-attachments/assets/eae006a3-8c5e-4cc4-9dfe-8a6a9532395b)

  Base de datos:
  - Espacio físico:
    ![Image](https://github.com/user-attachments/assets/7ec8f82a-3e43-4e90-acdd-8dd9d3f66535)
  - Asignación espacio físico dependencia:
    ![Image](https://github.com/user-attachments/assets/53bd318f-e518-4f67-a36d-e62ab4f463b4)
  - Tipo uso espacio físico:
    ![Image](https://github.com/user-attachments/assets/c52ab69e-25b1-4cd5-9ac6-fd55c159c92f)
  - Espacio físico campo:
    ![Image](https://github.com/user-attachments/assets/f01a7575-ba49-45d8-a803-f6901fb255ff)

- Activar un espacio físico
  Se modificara el espacio físico con id 1833, que actualmente tiene todas sus relaciones en activo false
  Api:
  ![Image](https://github.com/user-attachments/assets/fc336bd0-80bf-41b6-8853-c1716578a653)

  Base de datos:
  - Espacio físico:
    ![Image](https://github.com/user-attachments/assets/7bf67ec5-514d-4748-9d15-22102ecff4ff)
  - Asignación espacio físico dependencia:
    ![Image](https://github.com/user-attachments/assets/4eb1a047-550a-44a6-b6f9-2339c33e84b8)
  - Tipo uso espacio físico:
    ![Image](https://github.com/user-attachments/assets/9f216f03-71c2-472b-b551-32a0b0628253)
  - Espacio físico campo:
    ![Image](https://github.com/user-attachments/assets/934b07ee-52e0-4fe6-93ad-285f8e2c6f3f)

### Pruebas de error

Dado que tanto la activación como la desactivación de un espacio físico utilizan las mismas funciones, demostrar el fallo en un endpoint también aplica al otro. Dado que actualmente el espacio físico con id 1833 tiene sus relaciones en true, se tratara de desactivar este espacio.

- Error en modificar el espacio físico
  - Error en búsqueda:
    API:
      ![Image](https://github.com/user-attachments/assets/13e19629-66a6-4143-abb9-dd6796b62019)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/92e7278c-274c-48f9-9b33-bb6fa9f9ae91)

  - Error en modificación:
    API:
      ![Image](https://github.com/user-attachments/assets/f8159517-9583-4077-bb0a-1587945abf30)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/926f6a7a-df06-40fc-9d84-fcad37e59dbc)
 
  Se observa que el espacio físico queda como inicio.


- Error en modificar la asignación espacio físico dependencia
  - Error en búsqueda:
    API:
      ![Image](https://github.com/user-attachments/assets/8f285d5d-0563-4ede-a332-c0d9655b0e58)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/4518af75-87a2-4c23-905e-2e9949cf3314)
      ![Image](https://github.com/user-attachments/assets/72c958e0-3ae4-44c9-ac94-dae9898a8f2b)
      Se observa en las fechas de modificación que son los cambios mas recientes.

  - Error en modificación:
    API:
      ![Image](https://github.com/user-attachments/assets/acfdaf8d-5a0c-425c-bc9e-0573673b9d39)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/92f0a379-b8f2-4b06-8a7a-af39924b38c1)
      ![Image](https://github.com/user-attachments/assets/42d4ee79-a8f1-40b7-becd-d930a93057ce)
      Se observa en las fechas de modificación que son los cambios mas recientes.


- Error en modificar tipo uso espacio físico
  - Error en búsqueda:
    API:
      ![Image](https://github.com/user-attachments/assets/58dcfde6-5bc4-4467-8f15-cc9b6491b735)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/e1dfcdc0-d61f-4841-87ba-06c88da6e970)
      ![Image](https://github.com/user-attachments/assets/7a404919-c009-4114-a4c3-7f7b6a5f86da)
      ![Image](https://github.com/user-attachments/assets/19421d39-8116-4218-81bb-b805ef04f990)
      Se observa en las fechas de modificación que son los cambios mas recientes.

  - Error en modificación:
    API:
      ![Image](https://github.com/user-attachments/assets/95e55437-8792-415f-bb87-db64644b83f4)
    Base de datos:
      ![Image](https://github.com/user-attachments/assets/816b7a4f-df58-440f-aed2-cc63c3d051ed)
      ![Image](https://github.com/user-attachments/assets/02e45424-33c2-4bed-b7dc-9f01d62c5bbe)
      ![Image](https://github.com/user-attachments/assets/65e97b0a-a418-4c83-9a70-abf5d579833f)
      Se observa en las fechas de modificación que son los cambios mas recientes.

**Comment by xDa04vidx** [comment]
### Frontend

Se logra integrar el endpoint de activar y desactivar un espacio físico en el frontend.

- Desactivar dependencia
  Aviso de comprobación.
  ![Image](https://github.com/user-attachments/assets/94c74680-5d95-45a0-8eea-a4fd901aa6ba)

  Carga.
  ![Image](https://github.com/user-attachments/assets/bfcfc344-441e-4526-83f2-e07ccde5e5ff)
  
  Comprobación.
  ![Image](https://github.com/user-attachments/assets/86e07afa-d3ab-4822-a263-bd4652ce55e0)

  Base de datos.
  ![Image](https://github.com/user-attachments/assets/a5f2ab2e-f85b-4b95-b087-6a7e2f48ea9d)

- Activar dependencia
  Aviso de comprobación.
  ![Image](https://github.com/user-attachments/assets/47833ab4-b45d-424f-b34b-8900426c3f0d)

  Carga.
  ![Image](https://github.com/user-attachments/assets/479a969a-3026-4c5a-b623-fc4e5b21b085)
  
  Comprobación.
  ![Image](https://github.com/user-attachments/assets/e8fb5a4e-f87b-4fdd-ae08-0a921c93bf8f)

  Base de datos.
  ![Image](https://github.com/user-attachments/assets/b379e0fb-397b-4afa-b2bc-7bb5190bc772)

**Comment by xDa04vidx** [comment]
### Errores

Al desactivar un espacio físico, se inactivan automáticamente todas sus relaciones. Sin embargo, en las tablas relacionadas con asignación de espacio físico a dependencia, tipo de uso del espacio físico y espacio físico por campo, un espacio físico puede tener múltiples relaciones. Durante el proceso de activación, solo se está considerando el primer registro que se obtiene, lo que ocasiona que, en algunos casos, no se refleje correctamente el estado previo con las relaciones activas antes de la desactivación del espacio.

**Comment by xDa04vidx** [comment]
### Pull request

Se crea pull request en [espacios_fisicos_dependencias](https://github.com/udistrital/espacios_fisicos_dependencias)
![Image](https://github.com/user-attachments/assets/3b69d192-5469-48b1-abda-6cc8175dcf89)
