### ISSUE TITLE
Agregar logs de errores al campo de visualización de errores.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#273]
Se requiere realizar consulta de logs que contengan error para que sean mostrados en el respectivo campo e iniciar tratamiento de datos para que la visualización sea mejor, especificamente la del error.

**Sub Tareas**

- [x] Registrar logs de error en el campo destinado para esto.
- [x] Iniciar tratamiento de datos similar al realizado por Julian en la vista del detalle del log.
- [x] Realizar pruebas de funcionamiento.

**Criterios de aceptación**

- [x] Logs de error registrado.
- [x] Tratamiento de datos realizado.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 05/12/24

Se quita el límite de 20 registros en el query string:

![image](https://github.com/user-attachments/assets/afd84c84-fa26-47ed-a053-4da71c48b133)

Además se intenta forzar un error para polux crud test con un endpoint erróneo:

![image](https://github.com/user-attachments/assets/cffe890d-7b62-4306-90b7-ddc8ce357c2f)

Lo cual se ve reflejado en el Cloudwatch:

![image](https://github.com/user-attachments/assets/07cbf62b-476a-444f-8159-b7b10271714b)

Sin embargo como se evidencia en la imagen, ninguno de los logs de la prueba de forzado de error no es interceptada por el middleware por lo que el microcliente de auditoría no puede mostrar estos logs:

![image](https://github.com/user-attachments/assets/b6cf59ac-ae41-46b6-9af9-4ccc990ac15b)

Por lo que se está consultando con el líder de equipo para saber el cómo proceder

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/12/24

Con el líder de equipo se acordó descargar la librería de auditoría e integrarla de forma local a gestion_dependencias_mid para poder identificar la forma en la que el middle ware interceptaba los errores y como los mostraba en forma de logs. Así se realiza el proceso copiando la carpeta de auditoría a la raíz del proyecto del mid de dependencias:


![Captura de pantalla 2024-12-08 133447](https://github.com/user-attachments/assets/61ddee2d-0670-4e67-8206-f8deddb5dafc)

Y luego en el main.go se linkea el directorio en el que se encuentra la carpeta local:

![Captura de pantalla 2024-12-08 132432](https://github.com/user-attachments/assets/3e43fb9d-f4aa-4be7-8264-c643715e3fd3)

Hecho esto se empezó a realizar pruebas primero alterando el código de los servicios de búsqueda de dependencia. Siendo que los errores en los que por ejemplo los servicios no eran accesibles o bien, se cambiaban valores  en algunas variables no eran interceptados por el middleware si no que los errores eran mostrados e interceptados directamente por la consola.

Para ilustrar esto en uno de los intentos de forzar errores para ser interceptados por el middleware, se cambió el query que se enviaba por URL de búsqueda de nombre de dependencia para que en vez de que el query tuviese "Nombre" en la url, pasase a ser "NombreS" con s para forzar el error, de la siguiente manera:
 
![Captura de pantalla 2024-12-08 133502](https://github.com/user-attachments/assets/84bf7607-17c4-42b3-8f5c-29375a22ffa2)

Así se consigue un error:

![Captura de pantalla 2024-12-08 133745](https://github.com/user-attachments/assets/9e806b2c-d764-4953-8646-f0753dd75967)

Sin embargo en la consola se evidencia que el error no es interceptado por el middleware:

![Captura de pantalla 2024-12-08 133749](https://github.com/user-attachments/assets/6241206c-6609-47e4-9b06-55d3a8b7d4e5)

Luego se intentó cambiar las claves del JSON que se envía y al alterar la clave "Dependencia" y ponerlo como "Dependencias" lo que genera un error  de memoria interna que no es interceptado por el middleware:

![Captura de pantalla 2024-12-08 135710](https://github.com/user-attachments/assets/c2441c60-e21c-474e-9483-d03acc0c73b4)

Lo cual se muestra en consola así:

![Captura de pantalla 2024-12-08 135814](https://github.com/user-attachments/assets/eed4c96f-5228-499f-81c5-d980360fff38)

## Errores que si son interceptados por el middleware

Modificando las clave-valor anidadas genera una respuesta 200 de success a pesar de que en realidad genera un error y no se registra la dependencia en la base de datos. Sin embargo el error que se genera si se ve reflejado en el middleware:


![Captura de pantalla 2024-12-08 140004](https://github.com/user-attachments/assets/5cd6605f-d009-4721-80df-33655abe79fc)

![Captura de pantalla 2024-12-08 140013](https://github.com/user-attachments/assets/bf53f09a-1358-4b8f-9cea-be5b3b6d3ae3)

También se presenta cuando uno o varios datos que se envían generan conflictos en la base de datos o internamente en el flujo. Por ejemplo se colocó en TipoDependenciaIds se colocó un id que era imposible que existiese y en dependenciaAsociadaId se colocó otro ID tratando de que no coincidiera con ninguno, siendo que de nuevo, se genera un error que es interceptado por el middleware:

![Captura de pantalla 2024-12-08 155445](https://github.com/user-attachments/assets/cb05e381-a75a-4c76-995e-6792ccbf1132)

![Captura de pantalla 2024-12-08 155437](https://github.com/user-attachments/assets/3252ea2c-c3cc-4a1f-859b-8c19f903215c)


Hasta ahora no se ha reconocido otra alternativa además de las dos antes mencionadas pero se puede inferir que el middleware intercepta errores que tienen que ver con datos erróneos  o ausencia de ellos en las peticiones o bien, errores de estructura en las mismas

**Comment by diagutierrezro** [comment]
No se lograron capturar los errores por lo que se pasará a revisar la librería de auditoría en otra issue.
