### ISSUE TITLE
Realizar pruebas funcionales al sistema de Oikos - espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#274]
Se requiere realizar las pruebas funcionales y evidenciarlas en el formato de pruebas sobre el sistema de oikos en el segundo alcance de espacios fisicos

**Sub Tareas**

- [x] Desarrollar las pruebas funcionales
- [x] Documentar cada caso en el documento correspondiente
- [x] Generar los comentarios finales frente al equipo SoS

**Criterios de aceptación**

- [x] resultados de pruebas documentados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Las pruebas funcionales aún no se han podido desarrollar por parte de Cristian ya que aún no se realiza el respectivo despliegue en ambiente de pruebas del microcliente de espacios fisicos y el mid, estas solicitudes fueron realizadas desde el lunes tanto para [cliente](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=68262) como para [mid](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=68264) y si bien se conoce que ya se empezó a realizar el despliegue aún no se finaliza de manera satisfactoria.

**Comment by mantnicot** [comment]
Por cambios en XRAY ha impedido el despliegue para las pruebas , se hablado con MaFe para dar apoyo a la solución , por lo cual se busca volver a dejar el ambiente al original para habilitar el despliegue.

**Comment by mantnicot** [comment]
Se adjunta el documento para realizar las pruebas

[Documento de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET694s8GSipAmg2dupkppeEBPvnEh5RdqO1UmgeM6lhdpA?e=fVQZVv)

**Comment by mantnicot** [comment]
Se ha realizado las prueabs de oikos en espacios fisicos 
[documento de pruebas analista](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET694s8GSipAmg2dupkppeEBPvnEh5RdqO1UmgeM6lhdpA?e=IvQ5Rk)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, será insumo para el equipo de desarrollo.
