### ISSUE TITLE
Realizar pruebas unitarias al sistema de Oikos - espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#275]
Se requiere realizar las pruebas unitarias al mid de gestión de espacios fisicos, se puede usar como guía las pruebas realizadas en #202 y la idea general es probar las diferentes funciones que se tengan en el sistema.

**Sub Tareas**

- [x] Implementar pruebas unitarias en el mid de gestión de espacios fisicos.
- [x] Documentar las pruebas realizadas y los resultados obtenidos.

**Criterios de aceptación**

- [x] Pruebas unitarias implementadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Prueba sin errores en el registro del espacio físico

Se logra implementar este test, con orientación de @JulianAvella 

![Image](https://github.com/user-attachments/assets/c88a345e-a899-4bf3-a243-9cef15c135d7)

Se muestra que todo salió correcto.

**Nota**
Dado de que fue la primera implementación que hice, fue un poco confuso, por tal razón me demore en entender como se realizaba esta prueba.

**Comment by xDa04vidx** [comment]
### Adelanto
Se adelantan las pruebas unitarias sobre las funciones de

- Búsqueda
  ![Image](https://github.com/user-attachments/assets/1d511b51-799a-4419-bd9c-d9d9067155ed)

- Activación
  ![Image](https://github.com/user-attachments/assets/597acad5-1aaa-4156-b962-af3cb4e4d6a9)

- Desactivación
  ![Image](https://github.com/user-attachments/assets/eac8b52c-fc58-4f91-a76e-54e29e97d5cf)

**Comment by xDa04vidx** [comment]
### Adelanto

- Editar
  ![Image](https://github.com/user-attachments/assets/d0958cd3-3cc4-48c9-a573-cbc75701b9ab)
