### ISSUE TITLE
Finalizar implementación de endpoint para obtener listado de Apis

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#276]
Se requiere realizar la finalización de la implementación del endpoint que retorna el listado de Apis, el objetivo es consultar dicho endpoint, mostrar el listado para que lo seleccione el usuario y realizar la consulta de logs con el Api que haya seleccionado el usuario

**Sub Tareas**

- [x] Consultar endpoint y obtener el listado en formato JSON.
- [x] Agregar en el formulario un campo para mostrar el listado de las Apis que devuelve el endpoint.
- [x] Según la opción seleccionada modificar el archivo que consulta AWS para que ya no esté quemado polux_crud.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Endpoint consultado.
- [x] Formulario modificado.
- [x] Archivo de consulta hacia AWS modificado.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* Avance 09/12/2024:

Ya se logro el desarrollo para que el cliente oikos_root_mf obtenga los datos del endpoint creado "https://autenticacion.portaloas.udistrital.edu.co/apioas/roles/v1/apis_cliente" y se imprimen los datos en la consola del navegador para mostrar que si están llegando

<img width="959" alt="image" src="https://github.com/user-attachments/assets/94424e5c-1799-4c4a-8af7-563c5f3b2fd8">

**Comment by JulianAvella** [comment]
* **Avance 10/12/2024**:

Primero, no se muestra ningún error en la consola de navegación:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/691cf497-b69d-40bb-9b5d-6fd861f0a694">

Segundo, se le agrega una opción en los dos campos de selección, para indicar al usuario que es un campo seleccionable, estás opciones que se muestran no se pueden seleccionar porque están bloqueadas y tienen un fondo gris, las opciones que si se pueden seleccionar tiene un fondo azul: 

<img width="959" alt="image" src="https://github.com/user-attachments/assets/1b678e50-6adc-45d2-9978-96c3890c7c4a">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/ff3efd80-b7d6-4c0c-987f-0f9d826fa76e">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/b48d23e5-e14c-4f75-82e4-96fed4b9935c">

Tercero, la consulta que se hace al endpoint 'https://autenticacion.portaloas.udistrital.edu.co/apioas/roles/v1' ahora está desde el cliente de auditoria-mf, y ya no desde el cliente de oikos-root-mf

Cuarto, se agrega un campo llamado 'Nombre API' que es seleccionable:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/b4784fbe-45d3-4f12-90ec-96e970459345">

Quinto, el nombre de las apis que nos da la consulta del tercer punto, se selecciona solo los campos nombre y se muestran desde el nuevo campo creado, además los datos que viene con el nombre tiene un signo slash '/' al inicio del nombre, entonces este signo  se quita desde el código, con el fin de que solo le muestre al usuario el nombre de las apis sin carácteres especiales:

<img width="837" alt="image" src="https://github.com/user-attachments/assets/6559722c-c28d-420e-a62d-ef9bfcefa09a">

**Comment by JulianAvella** [comment]
* **Avance 11/12/2024:**

Primero: Se ajusta el cliente de oikos_root_mf para que mediante custom event, envie el clienteId del ambiente que esta ejecutando, al cliente de auditoria_mf, los datos que aparecen en la consola del navegador son los datos que recibe el cliente de auditoria_mf por parte del cliente de oikos_root_mf:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/077e1cad-3291-4bad-84e3-eebf9fb44495" />
<img width="723" alt="image" src="https://github.com/user-attachments/assets/bbfa5b66-d31e-4b2c-b608-c321452e697f" />
<img width="724" alt="image" src="https://github.com/user-attachments/assets/02c6de76-1d8d-4f7c-aee2-f4993d1c8906" />

Segundo: Se modifica la API auditoria_mid, para que reciba como parámetro el nombre de la API a la cual se le van a consultar los logs, además en el código al nombre de la api se le agrega al inicio del nombre '/ecs/' y al final '_prod', para que pueda buscar la api en AWS porque así estan guardadas:

<img width="678" alt="image" src="https://github.com/user-attachments/assets/8d563234-9a78-446c-903e-711a39d6ab0c" />
<img width="631" alt="image" src="https://github.com/user-attachments/assets/2b79e15e-44f1-4b06-8eb0-6af31c5e251c" />

Tercero: Se prueba con la api polux_crud:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/01c33574-5978-4340-9b82-ecadf6ca6959" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/840925a1-7cd3-4523-90d2-d338e8b55a86" />

**Comment by JulianAvella** [comment]
* **Github:**

Se sube el desarrollo del cliente de oikos_root_mf a la rama feature/Custom-event-auditoria:

<img width="656" alt="image" src="https://github.com/user-attachments/assets/fde59892-ddef-42b2-b3ca-851c6a30c397" />

Se crea un pull request hacia la rama develop del cliente de auditoria_mf:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/97760bee-6267-4942-991f-b6d1ac419b9d" />

Se crea un pull request hacia la rama develop de la API auditoria_mid:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/cc30ffd5-d401-457e-9d1a-de66e379c799" />

**Comment by JulianAvella** [comment]
Se ajustan y se suben a los mismos pull request, las correcciones que salieron del daily:

<img width="696" alt="image" src="https://github.com/user-attachments/assets/bac4da69-bd07-4b65-b0a5-dfe68d20bd8c" />
<img width="652" alt="image" src="https://github.com/user-attachments/assets/15ce1bf9-5b14-4386-9839-8747b766cb41" />
