### ISSUE TITLE
Revisar comportamiento de librería de auditoría en cuanto al manejo de errores.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#279]
Se requiere realizar la revisión de la librería de auditoría en el que se analizara como se manejan actualmente los errores generados por el Api para poder entender de una mejor manera este comportamiento y lograr replicar este tipo de errores.

**Sub Tareas**

- [x] Realizar revisión para verificar como se manejan los errores en la librería o si no existe un manejo y tocaría desarrollarlo.
- [x] Documentar hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 09/12/24

Se realiza un análisis inicial de la librería para identificar los puntos en los que pueda interceptar errores:

## En interceptor.go

Se tiene el siguiente fragmento de código:

![image](https://github.com/user-attachments/assets/a6d5ae66-5386-4f41-b56d-e3327c1c2cce)

La línea recover() se usa dentro de un bloque defer para capturar errores que ocurran. el problema es que no se realiza ningún procesamiento o registro del error, y no hay respuesta visual o registro en consola que indique que ocurrió un error ya que como se evidencia el bloque está vacío por lo que no hay código que analizar ni respuesta que mostrar.

Además el fragmento `request.SetHeader(ctx.Request.Header["Authorization"][0])`asegura que las solicitudes salientes que usan request incluyan el mismo encabezado Authorization que la solicitud original. Si el encabezado Authorization no existe o está vacío, este código podría lanzar un error de índice (index out of range), el cual se ha presentado en las pruebas de el issue [Agregar logs de errores al campo de visualización de errores.](https://github.com/udistrital/core_documentacion/issues/273)

## En middleware.go

No hay nada explícito relacionado con la intercepción o manejo de errores en las APIs o sus solicitudes. Este archivo únicamente contiene la lógica para insertar un middleware (InsertFilter) en el framework Beego para interceptar las solicitudes HTTP y registrar detalles relevantes, como los datos del usuario o el cuerpo de la solicitud.

El middleware registra información, pero no maneja errores ni excepciones relacionadas con las solicitudes. Para capturar errores de manera centralizada, se requeriría una lógica adicional, como el uso de recover() o manejo explícito de respuestas HTTP.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 10/12/24

Con ayuda del líder de equipo se hizo una revisión más detallada del estado de la librería, confirmando que los panic no son tratados de forma correcta por lo que el manejo de errores del middleware está incompleto:

Primero se colocaron varios println en diferentes partes de la librería de auditoría local que estaba en gestion dependencias mid:

![Captura de pantalla 2024-12-11 112826](https://github.com/user-attachments/assets/64caf0da-4d9a-4142-aa55-5cc3f117053b)
![Captura de pantalla 2024-12-11 112838](https://github.com/user-attachments/assets/67f91d82-6657-4ff8-9d08-978fbe2094f3)
![Captura de pantalla 2024-12-11 112843](https://github.com/user-attachments/assets/4ebc3234-4acf-44a4-88fb-c9fa11763f68)

Luego de esto se realizó unos cambios en la lógica de gestion dependencias mid (en el modelo estado y en donde se utilizaba para buscar una dependencia) para forzar un error y ver el comportamiento del sistema:

![Captura de pantalla 2024-12-11 113136](https://github.com/user-attachments/assets/a75f7cf9-7b92-4610-954b-36da3bcc84cf)
![Captura de pantalla 2024-12-11 113150](https://github.com/user-attachments/assets/2e321ef7-212c-4d2b-b441-5d312e048984)

La petición de prueba fue esta:

![image](https://github.com/user-attachments/assets/5df73f38-5b3b-4f43-a3ac-aefcfeee0e9c)

Y como se evidencia la librería de auditoría no ataja este panic ni genera un log de middleware:

![image](https://github.com/user-attachments/assets/7c8ba1cd-1be7-4103-aab4-af91c72568b7)

Sin embargo, se propuso modificar el ErrorController en utilidades.go con lo siguiente:

![image](https://github.com/user-attachments/assets/5141b586-58a2-4d49-8107-04ef22a70f4d)

Realizando la misma prueba se obtiene este resultado:

![image](https://github.com/user-attachments/assets/70f7af48-ffcd-4275-a4a2-d6d18a415c47)

El middleware muestra el error, por lo que se deduce que hay que ajustar el modo en que la librería captura y escucha los errores para que también pueda detectar Panics o Aborts.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/12/24

Se intentaron más métodos para lograr interceptar los errores. Se identificó también que lo más probable es que el errorController de utilidades.go estuviese interfiriendo con la librería de auditoría impidiendo que esta última pudiese capturar el error y mostrarlo en un log

Los metodos utilizados fueron los siguientes con el fin de tratar de interceptar el error antes de llegar a los abort del errorController:

![Captura de pantalla 2024-12-13 164827](https://github.com/user-attachments/assets/ffd0439f-21dc-423e-ae49-5b4c186a26ed)
![Captura de pantalla 2024-12-13 164834](https://github.com/user-attachments/assets/43cf637f-6b2b-4a1a-bd92-1132e9d59218)
![Captura de pantalla 2024-12-13 164839](https://github.com/user-attachments/assets/684b1e86-c546-44f3-8d58-86f47f45685e)
![Captura de pantalla 2024-12-13 164842](https://github.com/user-attachments/assets/3b139974-f529-4111-8da8-eec78f490822)

También se agregó un print en el errorController antes de llegar a los abort para identificar si los métodos implementados se ejecutaban antes o después de dicha acción:

![Captura de pantalla 2024-12-13 164909](https://github.com/user-attachments/assets/48ac3841-6317-478e-a62f-c68d1ce20e32)

El resultado sin embargo fué el mismo:

![Captura de pantalla 2024-12-13 164917](https://github.com/user-attachments/assets/e299dd0a-7167-4737-ac14-704f4f5109c1)

Sin embargo, si se modifica el ErrorController de esta forma:

![Captura de pantalla 2024-12-13 164950](https://github.com/user-attachments/assets/08e61156-1685-4fea-94ae-6319c409dfd3)

Sólo basta con que el método original de listenrequest esté activo para que funcione:

![Captura de pantalla 2024-12-13 164932](https://github.com/user-attachments/assets/4b81d23f-9f05-4003-89b2-db02d98d6f22)

Haciendo la prueba el log muestra el error exitosamente además de mostrarse en consola:

![Captura de pantalla 2024-12-13 165117](https://github.com/user-attachments/assets/4811c48c-ae79-4e6e-b1d7-e6fc04521938)

Sin embargo en postman la respuesta se muestra vacía:

![Captura de pantalla 2024-12-13 171330](https://github.com/user-attachments/assets/ef9b7c40-645d-4ea3-ab4c-e44cd433b410)

Por lo tanto se realizó una modificación adicional al Error Controller para que mostrase una respuesta:

![Captura de pantalla 2024-12-13 173559](https://github.com/user-attachments/assets/a404e879-ecb4-4125-aa7e-c7909338e023)

Así muestra exitosamente en postman el error como un json además de lo anterior visto:

![Captura de pantalla 2024-12-13 173602](https://github.com/user-attachments/assets/2c6df3e3-8e4e-4e16-a230-b4ad9c784f62)

Se informó al líder de equipo sobre esto y se está pensando agendar una reunión con Maria Fernanda para discutir lso cambios realizados y sus implicaciones
