### ISSUE TITLE
Proyectar formato de historias de usuario con cliente y equipo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#28]
Se requiere realizar la proyección y socialización del formato de historias de usuario con cliente y equipo

**Sub Tareas**

- [x] Proyección del formato de historias de usuario
- [x] Socialización del formato de historias de usuario con el cliente
- [x] Socialización del formato aprobado por el cliente con el equipo
- [x] Refinamiento y aprobación del formato por parte del equipo SoS

**Criterios de aceptación**

- [x] Formato de historia de usuario aprobado por los interesados
- [x] Formato de historia de usuario documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha generado la reunión con el cliente para el día 30/05/2024 a las 10:00 am para levantar los requerimientos sobre el cliente de OIKOS

**Comment by mantnicot** [comment]
Se ha realizado la reunión con el cliente 

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EftYe80P8o5LoJjEWE_emw4BddaC8dpqp9MaqY0Cjt6WuA?e=DncHbn)

Se puede seguir con el proceso de diseño de mock ups e historias de usuario

**Comment by mantnicot** [comment]
Se agrega el acta con las firmas del cliente

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZoO-TKCQexBsLHnO35y3d4BW3K6KT7hziBhLaRoRbjLpQ?e=pY7J8q)

**Comment by jcmurilloa** [comment]
Excelente trabajo Cristian!
