### ISSUE TITLE
Realizar prueba de implementación de librería de auditoría.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#280]
Se requiere realizar una prueba de implementación de los cambios realizados a la librería de auditoría, según lo acordado con Maria Fernanda se creará temporalmente una nueva carpeta de auditoría y se implementará en un Api que apuntará temporalmente a dicha librería para realizar pruebas y ajustar visualización de datos.

**Sub Tareas**

- [x] Crear nueva carpeta en repositorio de utils_oas con modificaciones realizadas.
- [x] Seleccionar un Api para hacer pruebas y cambiar la dirección que apunta hacia la libreria.
- [x] Ajustar visualización de la información que llega dentro del JSON en Data.
- [x] Probar las diferentes tipos de peticiones http.

**Criterios de aceptación**

- [x] Nueva carpeta creada en el repositorio.
- [x] Api modificada.
- [x] Visualización de información ajustada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
* **Avance 13/12/2024:**

Se crea el pull request a la rama master, con una carpeta llamada auditoriaPruebas, con el fin de enlazarla con un api
<img width="959" alt="image" src="https://github.com/user-attachments/assets/b07e4f88-7263-45b9-bb72-c0ada5ba394e" />

**Comment by JulianAvella** [comment]
* **Avance 15/12/2024**:

No se logra realizar la prueba de la implementación de la libreria de auditoria, porque una libreria que tienen las apis, esta fallando y no deja ejecutarlas, se hace la prueba en varias apis pero coloco como ejemplo el crud de oikos_api:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/c24d68e7-0c31-4244-b2ed-bae83db11930" />
<img width="676" alt="image" src="https://github.com/user-attachments/assets/0c47dc23-8980-4ade-bc8b-7125f96e906f" />


en la api de polux_crud:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/33498246-34e5-452a-8808-7e5785f1e7fb" />
<img width="673" alt="image" src="https://github.com/user-attachments/assets/e3a62bd2-bac2-4f8b-aaca-1aa23dc5cc9b" />

**Comment by diagutierrezro** [comment]
El error presentado se debe a diferentes cambios que se realizaron desde infraestructura ya que ahora se le asignan permisos a las Apis pero solo cuando están desplegadas, temporalmente la solución es comentarear la linea de X-Ray mientras se encuentra solución definitiva.
