### ISSUE TITLE
Consultar y definir la investigación sobre la caducidad de roles en SGA

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#282]
Se requiere realizar la consulta y definición de la caducidad de roles en SGA.

**Sub Tareas**

- [x] Contactar con responsable de la Universidad.
- [x] Adelantar la investigación relacionada con la caducidad de roles en Argo y Arka.
- [x] Proyectar documento derivado de la investigación.

**Criterios de aceptación**

- [x] Documento producto investigación.
- [x] Documento almacenado y compartido con desarrollo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha dado un primer acercamiento con Braian pero comenta que Milton es la única persona que pueda ayudar en ese tema . Se ha intentado comunicar con él ya desde la semana pasada , pero deja en visto los mensajes 

![Image](https://github.com/user-attachments/assets/184e6623-dd6a-4e60-be8e-2eb4a2b25a35)


![Image](https://github.com/user-attachments/assets/2bfb0a14-50c7-4774-8863-a6839bffc828)

**Comment by jcmurilloa** [comment]
Continuaremos intentando el contacto con el área, generando las respectivas evidencias de la falta de respuesta por parte del responsable.

**Comment by mantnicot** [comment]
Se pudo generar una reunión con el responsable y tambien nos acompaño el jefe de funcionamiento y así mismo la persona encargada de SISGPLAN 

La reunión concluyo que para realizar la caducidad de SISGPLAN pues sga requiere una investigación distitna pues muchos roles de ahí son de un sistema de autenticación antiguos y toca analizar si es necesario implementar pues se espera sacar pronto el sistema de SGA 2 


[Documento de SISGPLAN](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQHfwQL8z_RDjFQUvWNhV8UBjPoTznDZ6YMcBIl_rfc2Rw?e=5CtJLP)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, de esta manera se concluye que será necesario profundizar la investigación para lograr el objetivo en SISGPLAN.
