### ISSUE TITLE
Ajustes para finalización de espacios fisicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#283]
Se requiere realizar modificaciones finales para ajustar funcionalidades en el módulo de espacios fisicos. Para este issue se requiere:
- Realizar ajustes al momento de editar un espacio fisico, concretamente al modificar (adicionar o eliminar) campos.
- Agregar columna "Fecha de modificación" en la tabla de historico de espacios fisicos, esta columna hace referencia al campo fecha_creacion en la base de datos.
- Visualización de campos de tipo de edificación y tipo de terreno.

**Sub Tareas**

- [x] Realizar ajustes indicados para el módulo de espacios fisicos.
- [x] Realizar pruebas de correcto funcionamiento de los ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Avance
Se agrega nueva columna de fecha de modificación en la tabla de historico
![Image](https://github.com/user-attachments/assets/f7862ddb-aaf4-4089-9e9e-989dd522090a)
