### ISSUE TITLE
Revisar librería de auditoría para captura de errores (abort)

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#284]
Se requiere realizar el ajuste en la librería de auditoría de tal manera que se capturen los errores cuando las apis fallan y responden con un abort, esto es importante ya que actualmente cuando genera un error simplemente está saliendo de toda la ejecución pero no se captura nada desde el middleware

**Sub Tareas**

- [x] Ajustar librería para capturar errores de las Apis.
- [x] Realizar pruebas de errores generados y que sean capturados por el Api.

**Criterios de aceptación**

- [x] Librería ajustada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 11/12/24

Se realiza una primera implementación de una mejora para la librería de auditoría que permita capturar y mostrar como logs los errores productos de errores panic.

Primero se identificó que el interceptor en este caso no estaba siendo llamado correctamente en el main.go de gestion_dependencias_mid (la API que se está utilizando en local para pruebas), por lo que se coloca la expresión para que pueda funcionar:

![Captura de pantalla 2024-12-11 201300](https://github.com/user-attachments/assets/11cde550-5d15-49a2-8264-49fe33149e94)

Luego de esto se agrega una nueva función al middleware.go para crear un log con la información que se capture del error:

![Captura de pantalla 2024-12-11 201314](https://github.com/user-attachments/assets/4a5ea251-cd60-42e9-ae46-05a917eaae4e)

Y en el interceptor.go se llama a dicha función cuando detecte un error:

![Captura de pantalla 2024-12-11 201307](https://github.com/user-attachments/assets/5eb73e2c-0b3d-44c1-9d99-799de6f33933)

Así se realiza una prueba en la que se fuerza un panic:

![Captura de pantalla 2024-12-11 201250](https://github.com/user-attachments/assets/59240d93-1111-4e25-94c8-0906cd7d59b8)
![Captura de pantalla 2024-12-11 201247](https://github.com/user-attachments/assets/9ca9e25a-9e71-4987-8897-ffa1e15cee0e)

Como se evidencia el middleware logró interceptar el error. Sin embargo falta comprobar que el mensaje que muestre sea el correcto ya que como se evidencia hay una discrepancia del mensaje de error en consola y el que se muestra en el middleware, así que queda pendiente identificar si hay algo fallando en la lógica para que los mensajes de error coincidan

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 12/12/24

Se investigó y en una primera instancia se pensaba que la discrepancia de errores correspondía a que el middleware mostraba el error más reciente por lo que se hizo una prueba con un bearer token ya que al parecer el error out of index que mostraba el middleware se debía a la ausencia de este token:

![Captura de pantalla 2024-12-12 165931](https://github.com/user-attachments/assets/21d54b23-99ba-48c5-9800-31d5161914e6)

Sin embargo ahora al ya no existir este problema, ahora el middleware no intercepta nada, mostrando sólo el panic en consola:

![Captura de pantalla 2024-12-12 165921](https://github.com/user-attachments/assets/40662c18-b889-45e2-94d5-ee42ea8cb05b)

Se han estado intentando distintas formas de resolver esto y que detecte estos panics, una de ellas fué usando un recover global en middleware.go:

![Captura de pantalla 2024-12-12 165935](https://github.com/user-attachments/assets/b30e4a78-f753-4156-a6d8-f0f20aa6048e)

Sin embargo a pesar de entrar en el interceptor y en el recover global, sigue sin agarrar el error y por lo tanto no genera logs de ellos:

![Captura de pantalla 2024-12-12 170258](https://github.com/user-attachments/assets/6eb12180-a395-41ca-a7c8-b01ef8a3eea8)

Se sigue investigando e intentando resolver este asunto

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/12/24

Se intentaron más métodos para lograr interceptar los errores. Se identificó también que lo más probable es que el errorController de utilidades.go estuviese interfiriendo con la librería de auditoría impidiendo que esta última pudiese capturar el error y mostrarlo en un log

Los metodos utilizados fueron los siguientes con el fin de tratar de interceptar el error antes de llegar a los abort del errorController:

![Captura de pantalla 2024-12-13 164827](https://github.com/user-attachments/assets/ffd0439f-21dc-423e-ae49-5b4c186a26ed)
![Captura de pantalla 2024-12-13 164834](https://github.com/user-attachments/assets/43cf637f-6b2b-4a1a-bd92-1132e9d59218)
![Captura de pantalla 2024-12-13 164839](https://github.com/user-attachments/assets/684b1e86-c546-44f3-8d58-86f47f45685e)
![Captura de pantalla 2024-12-13 164842](https://github.com/user-attachments/assets/3b139974-f529-4111-8da8-eec78f490822)

También se agregó un print en el errorController antes de llegar a los abort para identificar si los métodos implementados se ejecutaban antes o después de dicha acción:

![Captura de pantalla 2024-12-13 164909](https://github.com/user-attachments/assets/48ac3841-6317-478e-a62f-c68d1ce20e32)

El resultado sin embargo fué el mismo:

![Captura de pantalla 2024-12-13 164917](https://github.com/user-attachments/assets/e299dd0a-7167-4737-ac14-704f4f5109c1)

Sin embargo, si se modifica el ErrorController de esta forma:

![Captura de pantalla 2024-12-13 164950](https://github.com/user-attachments/assets/08e61156-1685-4fea-94ae-6319c409dfd3)

Sólo basta con que el método original de listenrequest esté activo para que funcione:

![Captura de pantalla 2024-12-13 164932](https://github.com/user-attachments/assets/4b81d23f-9f05-4003-89b2-db02d98d6f22)

Haciendo la prueba el log muestra el error exitosamente además de mostrarse en consola:

![Captura de pantalla 2024-12-13 165117](https://github.com/user-attachments/assets/4811c48c-ae79-4e6e-b1d7-e6fc04521938)

Sin embargo en postman la respuesta se muestra vacía:

![Captura de pantalla 2024-12-13 171330](https://github.com/user-attachments/assets/ef9b7c40-645d-4ea3-ab4c-e44cd433b410)

Por lo tanto se realizó una modificación adicional al Error Controller para que mostrase una respuesta:

![Captura de pantalla 2024-12-13 173559](https://github.com/user-attachments/assets/a404e879-ecb4-4125-aa7e-c7909338e023)

Así muestra exitosamente en postman el error como un json además de lo anterior visto:

![Captura de pantalla 2024-12-13 173602](https://github.com/user-attachments/assets/2c6df3e3-8e4e-4e16-a230-b4ad9c784f62)

Se informó al líder de equipo sobre esto y se está pensando agendar una reunión con Maria Fernanda para discutir lso cambios realizados y sus implicaciones
