### ISSUE TITLE
Continuar prueba de implementación de librería.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#285]
Se requiere continuar con la implementación de la librería, se propone implementar temporalmente en polux_crud y/o gestion_dependencias_mid para realizar las respectivas pruebas de la implementación realizado y revisar el comportamiento del sistema desde el microcliente de auditoria, se requiere revisar los patrones utilizados y ajustarlos a la nueva estructura de respuesta que retorna la librería de auditoría.

Finalmente se requiere ajustar la vista del cliente para adaptar la información recibida desde el mid de auditoría y modificar las visualizaciones de la información y ajustar la tabla de respuesta.

Extraer el usuario de los logs y realizar petición al mid de autenticación para extraer los roles que tenga el usuario.

**Sub Tareas**

- [x] Implementar cambios de librería en Apis seleccionadas.
- [x] Realizar pruebas del comportamiento de la librería en el microcliente de auditoría.
- [x] Realizar ajustes necesarios para lograr el comportamiento esperado adaptandolo a los cambios realizados.
- [x] Ajustar vista del cliente para mostrar logs modificados.
- [x] Extraer roles del usuario que realiza la petición.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Pruebas realizadas.
- [x] Ajustes realizados.
- [x] Ajuste de vistas en el cliente realizados.
- [x] Extracción de roles del usuario realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se crea pull request para poder ver los logs que se guardan en aws en la parte test
<img width="959" alt="image" src="https://github.com/user-attachments/assets/0396b496-31ca-457b-941e-a9bc1fa0ac4d" />

**Comment by JulianAvella** [comment]
Con la implementación que se desarrollo, se estaba guardando la información en formato json, tipo clave : valor, pero no se estaba guardando en un solo log de aws, se estaba guardando en varios logs, por eso es un error al comportamiento que se espera:

![image](https://github.com/user-attachments/assets/5430e28a-0e55-4f94-b6f7-39cca5038341)

Ahora después de varios errores, pruebas y diferentes formas de guardar la información en un solo log de aws se tienen unas opciones:

<img width="791" alt="image" src="https://github.com/user-attachments/assets/10fa468d-ca08-4591-93f7-3111d7cb9678" />
<img width="776" alt="image" src="https://github.com/user-attachments/assets/ffd4ad2a-3ffd-4aa1-bb32-8eedd273429f" />

**Comment by JulianAvella** [comment]
Se crea pull request para la carpeta de prueba del middleware en el repositorio de utils_oas, esta versión es la que continua porque es la que cumple con el comportamiento esperado:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f9ef65ce-7dc0-447b-83a9-f4171252eca4" />

**Comment by JulianAvella** [comment]
Se crea una función en la api auditoria_mid, para extraer el o los los del usuario que aparece en el log guardado en aws:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/bfff0fe4-8bd6-4d62-9a3b-63fc41d14559" />

**Comment by JulianAvella** [comment]
En este comentario se coloca la modificación sobre la información, para que la data tenga una mejor visualización:

* Visualización de los datos en la petición HTTP GET:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/2810ca44-8968-49ba-b47a-b76002ebf536" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/34925c53-de54-4d09-9bce-61f961e3a16a" />

* Visualización de los datos en la petición HTTP POST:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f3d3760f-3996-497e-b622-664887318b35" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/8b2aafbe-5aa7-4bf8-ab4f-4304f43eb994" />

* Visualización de los datos en la petición HTTP PUT:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/3b67acf1-b843-4ea5-849a-361f376d8018" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/76d208a5-635c-4710-bba7-37ea6503205d" />

* Visualización de los datos en la petición HTTP DELETE:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f8a3485e-5fd8-490d-afe5-34ccf950e95a" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/380f5b91-194c-4f29-a330-a8d65b3588b6" />

**Comment by JulianAvella** [comment]
Además en la vista de los filtros, donde se buscan los logs, se quito el campo Rol - responsable y en la tabla donde se visualizan los logs buscados, que quito la columna Id

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5251ce55-e474-4041-b308-b878f7ac0ba7" />

**Comment by JulianAvella** [comment]
Se crea el pull request en el microcliente auditoria_mf:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5a26e5cb-bc61-402e-8741-ae5333b4885c" />

Se crea el pull request en la api auditoria_mid:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/22c19ee2-9e62-4454-88d6-639381247e4c" />
