### ISSUE TITLE
Presentación de propuesta de cambio para obtención de errores.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#286]
Se requiere realizar una presentación a Maria Fernanda para sustentarle los cambios que se proponen para realizar en el manejo de errores, el objetivo de la reunión es llegar a acuerdos para continuar con la implementación del manejo de errores orientado hacia el módulo de auditoría.

**Sub Tareas**

- [x] Realizar presentación.
- [x] Documentar los acuerdos a los que se lleguen.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/12/24

Se realiza la reunión y se llega al acuerdo de implementar los cambios en el error controller de utilidades.go de gestion_dependencias_mid en el error controller de util oas con la precaución de que debe ser uno de pruebas primero, y cuando se confirme su correcto funcionamiento se pasa al error controller original. También se acordó subir los ajustes a auditoría a otra rama distinta
