### ISSUE TITLE
Iniciar implementación de campos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#289]
Se requiere iniciar la implementación del nuevo alcance de campos en el cliente de Oikos, los mockups se encuentran en #259, en esta ocasión se irá implementando la vista junto con la lógica ya que unicamente requerirá consultas hacia el CRUD de Oikos.

**Sub Tareas**

- [x] Iniciar implementación de módulo de campos para la gestión de los mismos.
- [x] Documentar avances realizados en el módulo de campos.

**Criterios de aceptación**

- [x] Implementación de módulo de campos iniciado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha reiterado en varias ocasiones la necesidad de documentar correctamente las tareas en las issues, pero esto sigue sin cumplirse. La falta de documentación no solo afecta la trazabilidad y el seguimiento, sino que además compromete la calidad y la eficiencia del equipo. Esto es inaceptable pues estamos comprometidos en la buena evidencia del trabajo. Toda tarea debe contar con sus avances y detalles claramente registrados; de lo contrario, no se considerará como completa o avanzada.

**Comment by xDa04vidx** [comment]
### Avance
Se realiza vista inicial
![Image](https://github.com/user-attachments/assets/6d0f819c-6c0a-42c8-98cc-9fa9d652d7ef)

Los datos de la tabla son los campos reales, se cargan desde la base de datos de OIKOS.
Además cuando entra a la vista de campos, aparece un loader, y posteriormente el mensaje de éxito o error en el momento de traer los campos.
![Image](https://github.com/user-attachments/assets/35fbb3bd-3b78-4ab4-a82a-773ace981114)

**Creación**
Para la creación de campos, se utiliza el mismo formato de formularios, y se solicitan los datos de nombre, descripción y código de abreviación, siendo nombre y descripción los campos obligatorios del formulario, en caso de que estos estén vacíos, el botón estará deshabilitado.
![Image](https://github.com/user-attachments/assets/7532976c-3408-4e87-975c-3cc40604c305)

En el momento de crear un campo aparece un loader de creación y luego el respectivo mensaje de error o de éxito en la creación.
![Image](https://github.com/user-attachments/assets/ba2506f5-160a-4c22-8d9f-7140d474add1)

En ese momento de la creación se limpia el formulario y se recarga la tabla (se visualiza el campo creado)
![Image](https://github.com/user-attachments/assets/77a3a324-bf24-459f-991f-a294badea087)

**Comment by xDa04vidx** [comment]
### Vista editar
Se crea la vista de editar campos, y se obtienen los datos del campo seleccionado.
![Image](https://github.com/user-attachments/assets/899ee84b-1bc5-4aff-a08a-f9cbe6755c8f)

**Comment by xDa04vidx** [comment]
### Adelanto
Se realiza la edición de campos de manera correcta, este desarrollo se le muestra al líder @diagutierrezro, el cual dio algunas sugerencias sobre como mejorar la vista, en el momento de desarrollar estas sugerencias, el core-mf al cual se conecta el root se encuentra dando error:
![Image](https://github.com/user-attachments/assets/df86bd26-ee43-4c53-a3fc-3c7f0ac14feb)

Se tratará correr el core de manera local, para poder seguir con el desarrollo

**Comment by xDa04vidx** [comment]
### Finalización issue
Se logra:

- Editar el campo:
  Estado inicial del campo
  ![Image](https://github.com/user-attachments/assets/b08b422e-4aeb-4982-9a40-19b410d16f5b)
  Se borra el código de abreviación y se cambia el nombre y descripcion
  ![Image](https://github.com/user-attachments/assets/1061043e-adb8-4fb6-bd6a-063d95a03db1)
  Se da a editar (aparece mensaje de confirmación):
  ![Image](https://github.com/user-attachments/assets/497fa3e9-2708-4757-b88f-56e7066b9ffe)
  Se da en aceptar (aparece el loader y posteriormente el pop up de transacción exitosa):
  ![Image](https://github.com/user-attachments/assets/fde6f5e4-91bb-4512-94f4-fa9465649802)
  Al darle al botón de aceptar, se cierra el dialog de editar y se recarga la ventana principal:
  ![Image](https://github.com/user-attachments/assets/774de702-0188-49e3-8546-bc1a561c4821)
  Se visualiza el cambio:
  ![Image](https://github.com/user-attachments/assets/27842fbc-2783-4882-99f9-1811727cb021)
  En base de datos:
  ![Image](https://github.com/user-attachments/assets/48cb7851-b6c1-4465-b663-cac6daf4eff2)
  La fecha de modificación también cambio.

- Activar el campo:
  Estado inicial del campo
  ![Image](https://github.com/user-attachments/assets/baf88050-024a-4a6f-86d8-defce46e5e3d)
  Se presiona activar el campo (aparece mensaje de confirmación)
  ![Image](https://github.com/user-attachments/assets/c5e902fc-57ce-454d-a16e-9bf839f8104a)
  Se da en activar (aparece loader de activación seguido del popup de transacción exitosa):
  ![Image](https://github.com/user-attachments/assets/98cb04f3-734c-47c7-a484-a31d423b7023)
  Al darle aceptar se recarga la pagina inicial:
  ![Image](https://github.com/user-attachments/assets/fdcf17f7-86a0-4a07-b928-536ba630bf31)
  Se visualiza el cambio:
  ![Image](https://github.com/user-attachments/assets/aec5f0a7-a172-4aa7-b770-567fd29f3526)
  En base de datos:
  ![Image](https://github.com/user-attachments/assets/1f18fc22-07ef-4c5f-9d79-9873a7834493)
  La fecha de modificación también cambio.

- Desactivar el campo:
  Estado inicial del campo
  ![Image](https://github.com/user-attachments/assets/1aaa06b4-3b84-4391-a139-8203087f8254)
  Se presiona desactivar el campo (aparece mensaje de confirmación)
  ![Image](https://github.com/user-attachments/assets/852eb79b-6f33-4044-870d-16f6e566ca16)
  Se da en desactivar (aparece loader de desactivación seguido del popup de transacción exitosa):
  ![Image](https://github.com/user-attachments/assets/347c3941-8bd2-4b2a-b68c-82cde9b28fda)
  Al darle aceptar se recarga la pagina inicial:
  ![Image](https://github.com/user-attachments/assets/733b3d10-0177-45e5-8c91-ccde198c9be3)
  Se visualiza el cambio:
  ![Image](https://github.com/user-attachments/assets/ac30af73-2452-4e86-93f9-d1ce9de7e288)
  En base de datos:
  ![Image](https://github.com/user-attachments/assets/51441ffe-a48a-4925-a5ae-ae27d2c0de78)
  La fecha de modificación también cambio.

**Comment by xDa04vidx** [comment]
### Pull request

Se realiza pull request en [espacios_fisicos_dependencias_mf](https://github.com/udistrital/espacios_fisicos_dependencias_mf)
![Image](https://github.com/user-attachments/assets/bc757a78-5a2f-47ac-a350-5d9969b18ed5)

Para el pull request en el root se espera la solución del error en el core-mf

**Comment by xDa04vidx** [comment]
### Corrección código abreviación
Se corrigen los inputs de código de abreviación en creación y edición.
Este cambio queda integrado en el pull request anterior.
![Image](https://github.com/user-attachments/assets/00480daf-82e2-4b40-b32f-4a2d5df30ce9)
![Image](https://github.com/user-attachments/assets/75ff866d-5c96-405c-a7ab-b05e6e9d8632)
