### ISSUE TITLE
Implementación caducidad de roles en SISGPLAN

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#290]
Se requiere generar la respectiva gestión para iniciar la implementación de la caducidad de roles en SISGPLAN.

**Sub Tareas**

- [x] Contactar con el responsable para iniciar implementación.
- [x] Verificar y generar el seguimiento al proceso de implementación.

**Criterios de aceptación**

- [x] Implementación de caducidad realizada.
- [x] Anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha enviado el documento al Arquitecto y se espera la evidencia

**Comment by mantnicot** [comment]
Se espera recibir la  evidencia del arquitecto

**Comment by mantnicot** [comment]
Se realizo la implementación junto con el arquitecto

[Documento de implementación sisgnplan](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQHfwQL8z_RDjFQUvWNhV8UBjPoTznDZ6YMcBIl_rfc2Rw?e=v6zF9N)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
