### ISSUE TITLE
Seguimiento a cambio de variable de entorno en X-Ray

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#291]
Se requiere realizar el seguimiento a cambio de variable de entorno en X-Ray

**SubTareas**

- [x] Concertar reunión con el responsable.
- [x] Desarrollar la reunión con el cliente.
- [x] Actualizar el documento técnico
- [x] Exponer resultados a equipo SoS 

**Criterios de aceptación**

- [x] Documento técnico actulizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Despues de una reunión con Maria Fernanda y el equipo , se ayuda a definir lineamientos con el equipo

Tambien se hizo el siguiente texto para definir el cambio de los lineamientos

![Image](https://github.com/user-attachments/assets/81acb5ce-0e37-4427-be8c-cd314920a830)

[Documento de cambio de variable de entorno](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESbbRhIOnb5JiMsZ2il74QYB1YLQUm_K7r7smpfxS3PQQw?e=QWsESF)

**Comment by mantnicot** [comment]
Se ha devuelto los cambios pues esto a afectado el despliegue de OIKOS , por lo cual se deja en estand by hasta este despliegue

**Comment by mantnicot** [comment]
En caso de que haya problemas mientras se devuelve al estado normal de xray  se recomienda colocar el siguiente codigo en pruebas para los despliegues

go get -u github.com/udistrital/utils_oas

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, se requiere entonces de mayor tiempo de la contratación actual para lograr el objetivo.
