### ISSUE TITLE
Realizar prueba de implementación de errores en utils_oas

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#292]
Se requiere crear una carpeta de prueba para manejo de errores modificando el ErrorControlController para dejar de utilizar el panic y modificarlo por el SetStatus para comprobar el funcionamiento de la librería de auditoría con el cambio en el manejo de errores.

**Sub Tareas**

- [x] Subir carpeta a utils_oas con los cambios en errorctrl.
- [x] Realizar pruebas de funcionamiento correcto de las apis.
- [x] Comprobar funcionamiento correcto de la librería de auditoría capturando los errores.
- [x] Documentar cambios y pruebas realizadas.

**Criterios de aceptación**

- [x] Carpeta de utils_oas creada.
- [x] Pruebas de funcionamiento de apis realizadas.
- [x] Comprobación de libreria de auditoría realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 17/12/24

Se realizan los cambios acordados que surgieron de la reunión con Maria Fernanda:

## Carpeta de prueba en Util_oas con cambios a errorctrl

![image](https://github.com/user-attachments/assets/41b8e7a7-9db3-437a-847d-1bae603b87a8)

Cambios realizados:

![Captura de pantalla 2024-12-17 143353](https://github.com/user-attachments/assets/7cc59e3b-e91c-4696-83c2-00f965dd8a24)

## Cambios realizados en auditoría:

![Captura de pantalla 2024-12-17 143428](https://github.com/user-attachments/assets/ab054353-df3c-4b5e-a941-ff9621f5d47b)
![Captura de pantalla 2024-12-17 143446](https://github.com/user-attachments/assets/bb002505-2566-4895-9908-8057a5981a58)

## Prueba de funcionamiento de errorctrl con cambios de auditoría

Se realizan las siguientes modificaciones en la API getion_dependencias_mid en el controlador gestion.go para realizar la prueba con el errorctrl que se subió a util_oas:

Se importa el errorctrl de prueba:

![Captura de pantalla 2024-12-17 142852](https://github.com/user-attachments/assets/1ff52d47-de8c-4613-af07-069e4c9f2ce0)

En el código de busqueda de dependencias se modifica para que el errorctrl de prueba gestione los errores:

![Captura de pantalla 2024-12-17 142856](https://github.com/user-attachments/assets/1af573c9-dfba-4810-b529-a41a58391d90)

Se usa la librería de auditoria modificada en local.

## Prueba y resultados:

![Captura de pantalla 2024-12-17 142852](https://github.com/user-attachments/assets/81594750-b5c4-4778-aedb-cab6bffdad8b)
![Captura de pantalla 2024-12-17 142844](https://github.com/user-attachments/assets/35e13fab-6abb-445b-91c0-7d2da4abafb9)

Como se evidencia se realiza la prueba y se genera el log de error correctamente

## Nota:

Para que las funciones de auditoria funcionen bien, debe llamarse en el main.go no solamente el middleware si no el interceptor, similar a como se hace aquí:

![image](https://github.com/user-attachments/assets/1bf8630e-4a21-4163-be6a-7283ee2fb354)
