### ISSUE TITLE
Iniciar actualización de documentos para entrega de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#293]
Se requiere realizar la actualización de los documentos solicitados por funcionamiento para realizar la entrega de Oikos una vez se despliegue a producción, actualizar el documento de la [descripción tecnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EaEue48QVg9OlAc0nwqs1MgB_lO2_1K1nZrM1fsrvXjTtA?e=7mZ0xb) y la [aceptación de entregables.](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Ec_GZ88YGvJKvaYJsswjzm4BeLPUts3102uqUfHZI7-ssA?e=H5NDFC)

**Sub Tareas**

- [x] Actualizar documentos solicitados.

**Criterios de aceptación**

- [x] Actualización realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 22/12/24

Se realiza lo solicitado para los documentos referidos en el issue:

## Descripción técnica:

- Se agregaron los repositorios de espacios físicos al punto **1. Ubicación del repositorio de las API's**
- Se agregaron los endpoints y API's que utiliza el micro cliente de espacios físicos en el **punto 2 Apis y endpoints**.
- Se modificaron las columnas de los **roles** para agregar las funcionalidades de espacios físicos
- Se quitó de las **limitaciones** la ausencia de espacios físicos

## Aceptación de entregables:

- Se realiza una descripción de las funcionalidades de espacios físicos (gestión y registro, histórico y campos) en el apartado **1.Desarrollos efectuados para el sistema**
- Se realiza un breve resumen de lo anterior en la sección **2. Módulos entregados**
- No se identifican limitaciones adicionales

Los documentos quedaron en estado de revisión por parte del lider de equipo, por lo que se coloca la issue en in review en espera de posibles modificaciónes.
