### ISSUE TITLE
Realizar documento de plan de acción para MF de plantillas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#295]
Se requiere realizar un documento con el objetivo de elaborar un plan de acción para la creación de un microcliente de plantillas en el que se implementarán de manera visual las Apis de plantillas que existen actualmente, en este documento se debe agregar toda la información posible como pueden ser repositorios a utilizar, tecnologias, tiempos estiamados, etc.

**Sub Tareas**

- [x] Elaborar documento de plan de acción.

**Criterios de aceptación**

- [x] Documento elaborado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/12/24

Se realiza el documento en el que se expone el plan de acción, el cual tiene como contenido lo siguiente:

1. Análisis preliminar
2. Enlaces, repositorios y recursos
3. Plan de acción

En el plan de acción se tienen las siguientes etapas:

1.	Apropiación del sistema
2.	Diseño y planeación
3.	Pruebas de concepto
4.	Desarrollo y ajustes
5.	Pruebas de funcionamiento
6.	Ajustes y correcciones
7.	Presentación y revisión

Se describen las deudas técnicas, estado actual de sistema y las acciones requeridas de forma organizada así también como una estimación de tiempos de desarrollo.

Se envía al interno del líder de equipo el documento terminado para su revisión, ya que como se ha comentado previamente no poseo temporalmente acceso al correo corporativo de la universidad

**Comment by diagutierrezro** [comment]
El documento proporcionado por Andres es el [siguiente](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EcaGJjRv-w9CqETx1fQ-zKwBwkNrBAD2fwVVzT4kwQXj2w?e=LXBbUm).
