### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#3]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la reunión con el usuario el día 30/04/2024

Con las siguientes personas :

            - Diego Gutierrez
            - Kevin López Cardenas
            - Cristian Antonio Escorcia Blanco
            
Todo el compilado y resumen de la reunión se encuentra en la siguiente acta.

[Acta](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ee8KvZUz1lpGtNEd15Kw86cBAWQFUZhq8TtNSOVfPJ8Gcw?e=cFTyN4)

**Comment by jcmurilloa** [comment]
El acta cumple con lo solicitado
