### ISSUE TITLE
Corregir posición de firma electronica en documentos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#30]
Se requiere realizar la corrección en la posición de la firma electronica según lo que se encontró en #19 ya que la firma está quedando superposicionada

**Sub Tareas**

- [x] Realizar la corrección en la posición de la firma que se registra en el documento.
- [x] Realizar las respectivas pruebas una vez se realice la corrección para verificar el correcto funcionamiento.
- [x] Realizar la documentación.

**Criterios de aceptación**

- [x] Corrección realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 10/06/24

Se analizó el problema de las firmas electrónicas en cuanto a la posición del estampado, originalmente si había un espacio suficiente la firma quedaba muy pegada al texto, por ejemplo:

![Captura de pantalla 2024-06-10 105016](https://github.com/udistrital/core_documentacion/assets/77305100/72b1e0c2-a81c-49bd-a4cb-5f18c15bf04c)

O bien quedaba superpuesta al texto en varios casos:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/da2b225a-5fad-4ce3-be2e-3d55e9c70f86)

Se realizaron los análisis y testeos pertinentes y se llegó a la conclusión que el problema estaba en la variable que manejaba la posición en el eje Y de la firma al momento de estamparla, por lo que se realizó el respectivo análisis para identificarla, y al encontrarla, se comenzó a experimentar la modificación de dicha variable hasta encontrar un punto en el que se evidenciase una correcta implementación de la firma. Concretamente el cambio realizado es el siguiente:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/efaff2d9-a126-4de3-9c48-266185387880)

En el archivo firma_electronica.py de la api mid firma electrónica, en el método estamparFirmaElectronica, en la linea 352 se restan 40 unidades a las coordenadas en Y de la posición de la firma para ajustarla y que no quede sobre puesta o muy pegada al resto. Se resta por que dichas coordenadas se manejan invertidas por lo que si se resta, se coloca más abajo en el documento y si se suma más arriba.

Con esto se procede a realizar las pruebas del módulo, comentareando la parte en la que se consume a gestor documental para que estas pruebas no sean subidas a Nuxeo:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/02a62646-6f29-4f1a-b6a5-e5108b396728)

Toda la información de las pruebas se puede encontrar en el excel adjunto a este comentario, sin embargo en varios puntos a pesar de que la gran mayoría fueron casos de éxito se tuvo que ajustar el cambio realizado ya que en algunos casos la firma seguía montándose en el texto, a la final cuando todos los casos resultaron exitosos, el cambio quedó de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/ea1ca731-5686-4b3c-87af-fd3e7febb0ed)

Así se da por corregido el error y se envía a revisión, se adjunta Excel con las pruebas realizadas:

[Pruebas corrección firma electrónica.xlsx](https://github.com/user-attachments/files/15778237/Pruebas.correccion.firma.electronica.xlsx)

**Comment by Skyrus1203** [comment]
### ACTUALIZACION 12/06/24

Se realizan las correcciones necesarias para que el módulo de estampado de firma electrónica funcione correctamente. Se identificó que el problema venía de los métodos lastPageItems y signPosition de la clase ElectronicSign del archivo firma_electronica.py. Realizando pruebas se identificó que el método lastPageItems a pesar de que estuviese obteniendo correctamente el último elemento de la última página del pdf, no estaba obteniendo la posición correcta para la firma ya que al parecer, obtenía la posición superior del elemento, no la del final.

Por tanto se implementó el siguiente cambio:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/5e910225-74c9-4799-8dfc-8c3892586260)


Originalmente en la línea 63 se tenía como segundo argumento de isinstance el LTTextBox con sólo las líneas 67 y 68, y en el bbox de la línea 67 se tomaba la cuarta posición es decir el índice 3 habiendo dos argumentos que no se estaban utilizando:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/6d3afcf8-5503-417f-b80e-ad46bcde4a58)

Por lo tanto se hizo una investigación de la documentación y se encontró una jerarquía de elementos y componentes del contenido de un pdf , la cual se explica mejor con el siguiente gráfico:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/06d981cf-7a8f-454f-afce-84f05b897d2a)

En donde vemos que iterando los componentes superiores obtenemos los inferiores, por lo que dicha abstracción se implementó en el código y es lo que se ve en la corrección del código, en donde de cada párrafo se obtiene cada línea, y de esta se obtiene cada carácter hasta hall. Además se cambió el bbox para que tomara el índice 1, es decir el segundo elemento, el cual toma correctamente la posición inferior del último elemento.

Para el signPosition teníamos que en el for implementado, había un rango fijo:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3aa68e30-c552-447b-9a25-a731ef85f5a4)

Por lo que se cambió a un rango que se adaptara al set de coordenadas obtenidas en la función lastPageItems:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0d3d01fc-37a0-451e-8df5-c7683bbf273c)

Finalmente se hicieron pruebas para confirmar el correcto funcionamiento :

Se probó con un documento de dos páginas:

[FirmaPrueba2.pdf](https://github.com/user-attachments/files/15812623/FirmaPrueba2.pdf)

El resultado es el siguiente:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/7f4b2efc-0aa0-41c2-a9f6-7680e8294e50)

Luego se probó con el documento con el que había fallado haciendo las pruebas de funcionalidad:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/21677b68-52d4-46e6-a180-4c774336ae6e)

Se probó con el siguiente documento que también generaba conflicto:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/89ff77f4-8980-4f72-b6bd-6b87b3ee5255)

Este es el resultado corregido:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/d9a988cb-79b8-4b3b-9b81-fc60960d9a9a)

Finalmente se realizó una prueba con un texto de tres párrafos:

[FirmaPrueba1.pdf](https://github.com/user-attachments/files/15825276/FirmaPrueba1.pdf)

Este es el resultado:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3d4d3185-a417-4175-a2ad-9a1965c4467b)

Se da por cerrado el Issue
