### ISSUE TITLE
Migrar función de verificación hacia el Api de firma electronica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#31]
Se requiere realizar la migración de la función para verificación de la firma electronica hacia el Api de [firma_electronica_mid](https://github.com/udistrital/firma_electronica_mid), posteriormente agregar la ruta en el gestor documental para poder acceder a la función **getDocumentoNuxeoFormatted** realizandole el respectivo ajuste para que responda como un controlador con un json. Finalmente modificar la variable de entorno en el cliente para que ahora apunte hacia la funcionalidad de firma electronica y probar que funcione correctamente.

**Sub Tareas**

- [x] Migrar funcionalidad de **postVerify** 
- [x] Agregar ruta nueva en gestor documental para apuntar hacia la función getDocumentoNuxeoFormatted.
- [x] Ajustar la función getDocumentoNuxeoFormatted para que responda como los demás controladores.
- [x] Cambiar variable de entorno en cliente hacia nueva funcionalidad de firma_electronica.
- [x] Realizar pruebas.

**Criterios de aceptación**

- [x] Migración de funcionalidad realizada.
- [x] Ajustes en gestor documental realizados (rutas y funciones)
- [x] Ajuste en cliente de verificación realizado.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 05/06/2024

Se inicia con la migración de la función de verificación hacia la API firma electrónica.

Primero en gestor documental se crea una ruta nueva para que pueda ser accedida la función de obtención del documento de Nuxeo desde firma electrónica, función la cual será consumida desde la función de verificación que se migra a firma electrónica:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/e7ecf443-7213-421f-87a2-dc2cadc4b2ec)

Así con esto se actualiza el Swagger automáticamente quedando de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/72a2ec4b-ed89-47ab-9285-7da6ea6daa71)

En cuanto al método de getDocumentoNuxeoFormatted queda pendiente adaptarlo a la estructura de los demás controladores.

En firma electrónica se hizo la migración de la funcionalidad adaptando la llamada del método getDocumentoNuxeoFormatted para que apunte a gestor documental para consumirla:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2b1ff66a-624a-48fd-9d3e-98aaa23879ad)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f86ec110-3934-4e9d-a560-9dc713e637cd)

Hasta ahora en gestor documental se estaba recibiendo la firma para el verify por un Json, por lo que hasta confirmar si actualmente se hace de ese modo, se colocó un modelo en model_params de firma electrónica que sólo tuviese como campo la firma electrónica que recibe el método:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/6af08fe9-7c09-49be-9f87-a5c22f2a5f6a)

Por tanto este modelo se llama en el router de firma electrónica que agrega en enrutamiento al método de verificación trasladado:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/7e60556f-07f5-4de2-8987-5a1f60add4dd)

Así el Swagger se ve de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0cd12b25-74e9-425b-881b-b292195f596e)

También se hizo la clonación del repositorio del cliente de verificación y se cambió la variable de entorno que apuntaba a gestor documental en "**autenticacion.ts**" para realizar las pruebas en local:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/b25e4bfb-56fb-4000-aa51-5da63cb3cf17)

Así queda pendiente la adaptación del controlador de obtención de documento a nuxeo para que se acople a la estructura de los demás controladores y las pruebas en local

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 06/06/2024

Se realiza el ajuste al método de getDocumentNuxeoFormatted para que responda de la misma forma que los demás controladores:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/8c37b852-da92-4922-87e2-71cb404bbcc2)

Además se dio comienzo a las pruebas locales:

**PRUEBA 1:**

Se probó la ruta creada en gestor documental utilizando un UID de pruebas pasadas el cuál dio un caso de éxito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/1f6d6d89-ec32-4c12-b259-4b948b596856)

**PRUEBA 2:**

Se realizó la prueba del módulo de verificación desde firma electrónica utilizando una firma generada en pruebas anteriores, generando un internal server error:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/6a2515ac-78a0-4ce2-a369-dd909fd5588b)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/478d3d87-f458-40ae-8c26-ca84995930f4)

Se identificó que el problema es al momento de recibir el Json de respuesta que envía getDocumentNuxeoFormatted, ya que al momento de hacer la siguiente asignación en el módulo de verificación se agrega una "b" y unas comillas simples que envuelven todo el JSON y lo convierten en invalido para ser utilizado:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f1bd0c48-f942-4407-98c3-00606e1a1c9a)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/9ba2eff3-2990-41de-b836-2d724ece608e)

Cabe recalcar que esto también pasa en esta línea de código también en el módulo de verificación:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/cab1d8d3-28c5-4be9-8523-5a60898a0284)

Sin embargo no parece afectar realmente el funcionamiento de la misma por lo que se dejó tal cual como está.

Ahora para corregir este tema que afectaba al json se utilizó el siguiente conjunto de instrucciones:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/1c8a49de-3ce4-458d-a020-408cfaa29667)

Habiendo hecho esto se procede a la prueba 3 

**PRUEBA 3**

Se realiza nuevamente la prueba con los cambios establecidos y se consigue un caso de éxito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/201656d1-0b3d-4851-ba29-d9d899c87575)

Sin embargo para la última prueba que consistía en usar el cliente de verificación, no se pudo poner en funcionamiento el aplicativo por diferentes errores en cuando a versiones deprecadas de módulos de angular por lo que queda pendiente. El excel de las pruebas será subido en cuanto esta última prueba pueda ser realizada.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 07/06/2024

**Corrección de Gestor documental:**

Se logró identificar que lo que se estaba tratando de hacer mediante la creación de la ruta para el método de getDocumentNuxeoFormatted en gestor documental y la modificación de dicho método para que respondiese como los demás controladores no era necesaria, ya que el método getOne realizaba la función que se estaba requiriendo sin cambiar nada. Por tanto se revierten los cambios realizados borrando la ruta a  getDocumentNuxeoFormatted y devolviendo el método a su estado original. Por lo que sólo se cambia en firma electrónica mid la ruta a la que apunta el método verify hacia gestor documental para que apunte a la función getOne:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b7012fb3-c6c3-4430-9382-9030e6ce0925)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/bc507d97-166a-43e5-8050-ed9e05ed85a1)

**PRUEBA 4:**

Se prueban los ajustes antes mencionados consiguiendo un caso de éxito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0b5120ea-7354-4330-ac1b-44fbc2212203)

**AJUSTE DE CLIENTE DE VERIFICACIÓN**

En el cliente de verificación se modificaron 3 archivos:

- **autentitacion.ts**: Aquí se modificó la variable de entorno que apuntaba a gestor documental, cambiandole el nombre y corrigiendo el puerto para que apuntara ahora sí a firma electrónica:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/4c200dc6-b731-4d6e-9233-06bc291d6ba9)

- **gestorDocumentalHelper.ts**: Se le cambió el nombre a **firmaElectronicaHelper.ts** y se cambió tanto el nombre de la clase a exportar como el Path al que apuntaba para que dirigiera a firma electrónica:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/242b117d-a153-4fac-99c1-c313606070e1)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/ae74d190-607c-46b3-bbc5-c2bade97175c)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/55a243e1-d0db-4908-b5f7-8e2739d4d5d6)

- **verificar.component.ts**: Se cambió la importación de la clase de gestorDocumental a firma electrónica, así como la definición del objeto y los puntos en donde es llamado:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3b17c0e7-1974-4e24-a7bd-912b0d24fe37)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/10ba4076-6c1a-486a-9131-c0fbe6ea9296)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/6895a15d-b8c6-4900-9b65-bcbef78ea464)

Con estos ajustes realizados se prosiguió a realizar la última prueba:

**PRUEBA 5:**

Se ejecutó el cliente de verificación en local y se envió una firma para evidenciar que traiga correctamente el documento, obteniendo un caso de éxito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2c8285e0-816c-48b9-a185-500695af5b18)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/4c1d8c89-b6ca-4d3d-942d-185ed5f83e3f)



Con las pruebas concluidas se da por concluida la tarea, se adjunta Excel con las pruebas registradas:


[Pruebas locales verificacion firma electronica.xlsx](https://github.com/user-attachments/files/15745185/Pruebas.locales.verificacion.firma.electronica.xlsx)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres
