### ISSUE TITLE
Diseñar mockups de cliente OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#33]
Se requiere diseñar el mockup para el sistema oikos acorde a lo indicado en la reunión cliente. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al cliente.
- [x] Realizar ajustes según comentarios del cliente.
- [ ] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [ ] Mockup aprobado por cliente y equipo.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado los mockups del cliente de OIKOS y se han compartido con el equipo



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/7edb29af-690e-40b1-bdb0-71cd77fa0d11)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/d52acac6-3f2f-4a2c-8796-ff1c659099e6)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/d6b60a0b-1c19-41f6-a399-51047ff77366)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/f8f2343d-7c19-45d4-b732-04f50b63ea3d)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/e4283cb4-fe69-492e-be47-4ba5095a22fe)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/6175f113-66dd-4262-ac24-c5e891be7476)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/4dd99d06-7c10-4873-aa1d-4222be3a4fa3)



[CARPETA DE MOCKUPS](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkJyT74adTlMqzyXbPfa4YUBROUp4tlJDTjzPz4QqB7G3A?e=f67kR9)

**Comment by mantnicot** [comment]
Se han realizado los cambios de los mockups 

- Agregar al logotipo "y espacios físicos"
- Cambiar el nombre de los campos de Correo asociado a Correo institucional
- En la parte de búsqueda crear dos filtros nuevos
  * Tipo dependencia
  * Estado
- Se creo un nuevo submódulo de mapeo de información donde se podrá realizar dos acciones :
    * Búsqueda para generar el mapeo 
    * Búsqueda para editar el mapeo
- Se crearon junto con el submódulo de mapeo vistas especializadas dependiendo del tipo de dependencia : 
    * Si es académica , contendrá el código SNIES y el código interno
    * Si es Administrativa tendrá solo el código interno

[Carpeta de versión 2 OIKOS ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvVlEx7UBGVLkdDwvn-nR5oBb0zGwCqp2Z_pJ-5hILXfjQ?e=ZjQMJb)

![Image](https://github.com/udistrital/core_documentacion/assets/85162258/48238cc2-e78b-42ab-b5d5-bcafb2e959f3)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/17d24371-2028-49dc-87d3-f5fa9f2ce94e)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/12377b6c-755e-4778-a5db-e39ea81c8d14)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/922398e6-e117-4d2b-85fe-cc5786b6fa0d)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/19da24f4-fea6-4b62-85a6-73505375f737)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/8c167743-96d5-42c6-892b-000844b33c7c)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/3a29cd28-bbe0-4b3b-9b21-eca161276710)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/189eba8d-f9f5-41a9-9d98-eeec90c527aa)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/62a8617e-4f5b-4b88-830a-a0f779455f20)



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/7e145f6a-8183-4677-94d3-9793539cc34b)


Se queda a espera de aprobación por medio de whatsapp del cliente

**Comment by mantnicot** [comment]
Se crea el acta , falta firma del cliente

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcLPFv6cgUBNuty7UpmiTmEBcaAAE53npDgMzqYlkMl6gA?e=ORfOnu)

**Comment by mantnicot** [comment]
Se han aprobado los mockups de parte del cliente



![Image](https://github.com/udistrital/core_documentacion/assets/85162258/354d4fbe-2775-4025-b112-973670ce3353)

**Comment by jcmurilloa** [comment]
Que bien Cristian, a desarrollar entonces!

**Comment by mantnicot** [comment]
Se agrega el acta con la firma del cliente

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Ed4CDTSxRltGvh1v1jYG0x0BolQhCBswEnX03i_E4wTG_w?e=hbTLN2)
