### ISSUE TITLE
Actualización manuales e instructivos firma electrónica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#35]
Se requiere realizar la actualización manuales e instructivos firma electrónica

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Por cuestiones de permisos de parte de la persona encargada de los manuales, pues tiene día libre , entonces se organizo la reunión para el día 17/06/2024 a las 3 pm

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2Q0MzdkMGItYWZlOS00NTNiLTgxOTQtZjY3ZmY4MmU2OGZl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se deja la entrega del manual para el día 19/06/2024

**Comment by mantnicot** [comment]
Se comenta que se pueda llegar a implementar en la firma un hipervinculo directo al video de manual

**Comment by mantnicot** [comment]
Se ha creado el manual para el apartado de verifiación y se propone cambio de logo y depsues de eso hacer video de explicacion

[Manual](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXomccz0K1ZHpO4KL5oWwDgBAupPmJsdFXS67SojpSRpsg?e=dS5gaF)

**Comment by jcmurilloa** [comment]
Los manuales cuentan con la información consecuente, según lo revisado en la sesión del 21/06, el cambio de logo se visualizará en los video tutoriales. Muy buen trabajo @mantnicot!
