### ISSUE TITLE
Explicación de mockups y requerimientos para cliente de Oikos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#36]
Se requiere realizar una reunión junto con el analista @mantnicot para recibir explicación sobre los mockups del cliente y los requerimientos que va a tener el cliente de Oikos.

**Sub Tareas**

- [x] Concretar y realizar reunión con el analista para recibir la explicación necesaria.

**Criterios de aceptación**

- [x] Grabación de la reunión realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Reunión 
Se llevó a cabo una reunión con @mantnicot , durante la cual se explicaron los mockups y las funcionalidades del cliente de Oikos. Se formularon preguntas pertinentes, las cuales fueron respondidas de manera excelente, y se suministró el material base necesario para el próximo desarrollo. Además, se dejó en claro que cualquier duda posterior puede ser dirigida a @mantnicot .

**Link de la reunión**
El siguiente link se configuro para que @diagutierrezro tenga acceso a la grabación.

https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/SOCIALIZACI%C3%93N%20CLIENTE%20OIKOS-20240611_150102-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=zom01i&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by diagutierrezro** [comment]
Buen trabajo muchachos, gracias.
