### ISSUE TITLE
División del Cliente Oikos en Microfrontends - Microcliente Registro y gestión dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#37]
Se requiere realizar la planeación y estructuración para dividir el sistema Oikos en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

 - [x] Análisis del sistema Oikos microcliente de registro y gestión de dependencias
 - [x] Crear diagrama de componentes de la arquitectura para el microcliente de registro y gestión de dependencias.
 - [x] Listado de funcionalidades del microcliente.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/9b583abc-10a8-491c-9708-092430bb2c18)


se realiza diagrama de componentes para microcliente de registro y gestión de dependencias con sus componentes:

- REGISTRAR DEPENDENCIA
- VER ORGANIGRAMAS
- BUSCAR DEPENDENCIA
- GESTION DE DEPENDENCIAS

Este diagrama de componentes es preliminar y está sujeto a modificaciones.

**Comment by xDa04vidx** [comment]
**A continuación se muestran las funcionalidades preliminares de cada componente**
### Lista de funcionalidades
**Registrar dependencia**
- Registrar dependencia
- Se solicitará al usuario de manera obligatoria el nombre de la dependencia, el tipo de dependencia y la dependencia asociada. Además, el teléfono asociado y el correo institucional serán campos opcionales. Para los campos de nombre de la dependencia, teléfono asociado y correo institucional, se proporcionará asistencia mostrando la forma correcta de registrar la información.
**Ver organigramas**
- Mostrar organigramas
- Se mostrarán los tres organigramas de la Universidad (general, académico y administrativo). Cada uno de estos diagramas se creará desde la aplicación, mostrando únicamente las dependencias activas. Además, se deben gestionar correctamente las relaciones entre las dependencias asociadas.
**Buscar dependencia**
- Buscar dependencia
- Se podrá buscar la dependencia utilizando los campos de nombre de dependencia, tipo de dependencia, facultades, vicerrectorías y estado. Para los campos de nombre de dependencia, facultades y vicerrectorías, se proporcionará asistencia para mostrar la forma correcta de búsqueda. Además, para el campo de tipo de dependencia, se mostrará una lista en la que el usuario podrá seleccionar varias opciones. Para el campo de estado, se mostrarán dos opciones: activo o no activo.
- Cuando el usuario oprima el botón de buscar y se encuentren dependencias, estas se listarán en una tabla con las siguientes columnas: nombre, dependencias asociadas, tipo, estado y acciones.

**Gestión de Dependencias**
- Editar dependencia
- Se mostrará un nuevo formulario con los campos nombre de dependencia, tipo de dependencia, teléfono asociado, dependencia asociada y correo institucional, cada uno de estos campos precargados con los datos ya existentes. Para los campos de nombre de la dependencia, teléfono asociado y correo institucional, se proporcionará asistencia mostrando la forma correcta de registrar la información. Además, para el campo de tipo de dependencia, se mostrará una lista en la que el usuario podrá seleccionar varias opciones (se debe seleccionar al menos una). En el campo de dependencia asociada, se mostrará una lista con las dependencias activas.
- Activar dependencia
- Desactivar dependencia

**Comment by xDa04vidx** [comment]
Se corrige el diagrama de componentes, después de las correcciones suministradas por el analista @mantnicot 


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/91555da3-41ed-4dd1-834b-1f3ce6dd8465)

para este microcliente de registro y gestión de dependencias sus componentes son:

- REGISTRAR DEPENDENCIA
- GESTION DE DEPENDENCIAS

**Comment by xDa04vidx** [comment]
**Se corrige la lista de tareas**

### Lista de funcionalidades

**Registrar dependencia**

- Registrar dependencia
    - Se solicitará al usuario de manera obligatoria el nombre de la dependencia, el tipo de dependencia y la dependencia asociada. Además, el teléfono asociado y el correo institucional serán campos opcionales. Para los campos de nombre de la dependencia, teléfono asociado y correo institucional, se proporcionará asistencia mostrando la forma correcta de registrar la información.
    
**Gestión de Dependencias**

- Buscar dependencia
    - Se podrá buscar la dependencia utilizando los campos de nombre de dependencia, tipo de dependencia, facultades, vicerrectorías y estado. Para los campos de nombre de dependencia, facultades y vicerrectorías, se proporcionará asistencia para mostrar la forma correcta de búsqueda. Además, para el campo de tipo de dependencia, se mostrará una lista en la que el usuario podrá seleccionar varias opciones. Para el campo de estado, se mostrarán dos opciones: activo o no activo.
    - Cuando el usuario oprima el botón de buscar y se encuentren dependencias, estas se listarán en una tabla con las siguientes columnas: nombre, dependencias asociadas, tipo, estado y acciones.
- Mostrar organigramas
   - Se mostrarán los tres organigramas de la Universidad (general, académico y administrativo). Cada uno de estos diagramas se creará desde la aplicación, mostrando únicamente las dependencias activas. Además, se deben gestionar correctamente las relaciones entre las dependencias asociadas.
-Editar dependencia
    - Se mostrará un nuevo formulario con los campos nombre de dependencia, tipo de dependencia, teléfono asociado, dependencia asociada y correo institucional, cada uno de estos campos precargados con los datos ya existentes. Para los campos de nombre de la dependencia, teléfono asociado y correo institucional, se proporcionará asistencia mostrando la forma correcta de registrar la información. Además, para el campo de tipo de dependencia, se mostrará una lista en la que el usuario podrá seleccionar varias opciones (se debe seleccionar al menos una). En el campo de dependencia asociada, se mostrará una lista con las dependencias activas.
- Activar dependencia
- Desactivar dependencia

**Comment by diagutierrezro** [comment]
Buen trabajo David
