### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de muestra con cliente y funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#38]
Se requiere realizar la concertación, desarrollo y levantamiento acta acta de sesión de muestra con cliente y funcionamiento

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente y funcionamiento
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado la reunión para el día 18/06/2024 a las 10:00 am

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZmEyM2ViYzYtMWU0Ni00NWRkLWJiMjctOTZhYzY1ODZhZDc3%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente , a espera de firmas de los asistentes

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQ-nWS-r1hxClwY9GKfxOM4B9h_b6cnBtQtJaXsyzD_i0A?e=TRFAdQ)

**Comment by mantnicot** [comment]
Se sube el acta con las firmas correspondientes

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYwKgqRlSXpEhzsbaYf72xQBi891P1aW8UQwCkVGeZESBA?e=G2LTg8)

**Comment by jcmurilloa** [comment]
Gracias a tu idea de la aplicación, nos demoramos mucho menos en recoger estas frimas @mantnicot.
