### ISSUE TITLE
Pruebas funcionales firma electronica y verificación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#39]
Se requiere realizar las pruebas funcionales del sistema de firma electronica incluyendo la verificación

**Sub Tareas**

- [x] Probar el flujo completo desde la firma electronica hasta la verificación incluyendo pruebas de errores.
- [x] Registra las pruebas realizadas en el siguiente formato 
[Pruebas.Funcionales.xlsx](https://github.com/user-attachments/files/15795561/Pruebas.Funcionales.xlsx)

**Criterios de aceptación**

- [x] Pruebas funcionales realizadas.
- [x] Pruebas registradas según el formato e issue documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 11/06/24

Se iniciaron las pruebas funcionales de firma electrónica.

El primer set de pruebas se basó en enviarle a firma electrónica archivos en base 64 de otros formatos que no fuesen pdfs, en concreto se hizo pruebas con archivos excel, word e imagen, y en los tres casos el sistema identifica correctamente que los formatos no son válidos y devuelve un código 500 indicando que el archivo no es un pdf:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/5b67600b-3ec1-4ca2-a29b-0ce39eeeae31)

El siguiente set de pruebas consistió en enviar el JSON haciéndole falta un campo de los requeridos para su funcionamiento, se intercaló en cada prueba cada uno de los campos y para los campos IdTipoDocumento, nombre, file y metadatos el sistema devuelve un código 400 diciendo qué campos hicieron falta:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/d012aa94-5874-460c-8e65-e24b9a21a8da)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/8b799d18-3a94-4006-b9de-bb10728a9ce6)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/86b5ad98-39cd-4923-8440-edf7f8bdb271)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/47c53232-514c-490b-b3d6-e8931cf94c8d)

Para el resto de campos sale un código 500 sólo haciendo referencia al nombre del campo faltante pero no indicando este hecho:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/e5473d5f-5b74-445c-a0f0-1fabd3bf8a56)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/bfe5f2f4-aced-466a-a68f-4cbfb1ff7e98)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/c337cef6-2a60-4f96-8abd-056ac9a98aff)

Finalmente se hizo la prueba de funcionamiento completa en la que ese esperaba que el sistema guardara el registro del documento en la base de datos, se recibiese un código 200, se subiese a nuxeo y la firma estuviese colocada correctamente, todo lo anterior salvo el último punto fue un éxito:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/a0d165ef-b8bc-419b-8e5a-de22d4c605e6)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/441eb1d3-1a76-4e2d-98f9-0290f5d8d92c)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/fb268580-6553-4e58-bb09-8f867f4f075c)

Por tanto el issue udistrital/core_documentacion#30 se reabre hasta corregir este problema. Para este propósito se hizo contacto con el desarrollador del módulo para concertar una reunión explicativa del funcionamiento del módulo de firma y estampado, aún no se tiene respuesta. 

Por lo tanto queda pendiente la corrección de la firma, unos retoques a algunas excepciones para que sean más entendibles y realizar de nuevo las prueba final y la prueba del cliente de verificación, siendo que para este último ya se corrigió la variable de entorno que apuntaba a firma electrónica reemplazando la ruta local por una en despliegue:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/7b08822e-9ccc-4387-adb5-d5111a906e82)

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 11/06/24

Se iniciaron las pruebas de funcionamiento de firma electrónica.

El primer set de pruebas consistió en enviarle al sistema diferentes formatos al aceptado el cual es pdf, se le enviaron archivos en base 64 de .docx, .xlsx y .jpg y el sistema discriminó correctamente estos archivos y envió un código 500 puntualizando que dichos archivos no son pdfs:

![Captura de pantalla 2024-06-11 162954](https://github.com/udistrital/core_documentacion/assets/77305100/f1e41d08-fe10-4b90-bb8d-6a82c324aa05)


El siguiente set de pruebas consistió en enviar el JSON de firma electrónica sin algunos campos. Se probó intercaladamente quitando en orden cada uno de los campos haciendo que cada JSON careciese de un campo en cada envío cambiando el campo que faltaba. Para los campos IdDocumento, nombre, field y metadatos el mensaje de retorno es un 400 indicando que el campo correspondiente es requerido:


![Captura de pantalla 2024-06-11 172215](https://github.com/udistrital/core_documentacion/assets/77305100/5affe605-7fb1-4aca-8ab0-1fc07293fecb)
![Captura de pantalla 2024-06-11 163846](https://github.com/udistrital/core_documentacion/assets/77305100/6685de31-b434-497e-9a8a-169aed5fc257)
![Captura de pantalla 2024-06-11 164812](https://github.com/udistrital/core_documentacion/assets/77305100/beb82f60-103c-443f-8398-dd31b1990185)
![Captura de pantalla 2024-06-11 171930](https://github.com/udistrital/core_documentacion/assets/77305100/415221e0-aeed-417c-959b-e944b4a3a58c)


Para el resto de campos, el mensaje fue un código 500 indicando solamente el nombre del campo faltante:


![Captura de pantalla 2024-06-11 173535](https://github.com/udistrital/core_documentacion/assets/77305100/b446dccd-5f4e-4e54-b130-01ddfb088ddb)
![Captura de pantalla 2024-06-11 172855](https://github.com/udistrital/core_documentacion/assets/77305100/347d31ee-e732-433d-ad52-f2c771e2d8ea)
![Captura de pantalla 2024-06-11 173219](https://github.com/udistrital/core_documentacion/assets/77305100/ae06aa73-2aec-4748-8390-aa31a7d3f101)


Finalmente se hizo la prueba final completa de funcionalidad en la que se esperaba que el documento se guardase en la base de datos, se subiese a nuxeo, se obtuviese un código 200 y la firma estuviese bien puesta. Todo esto fue exitoso menos el último punto, ya que la firma se sigue montando sobre el texto a pesar de las pruebas y la corrección realizadas previamente:

![Captura de pantalla 2024-06-11 190806](https://github.com/udistrital/core_documentacion/assets/77305100/5930fab7-c23d-47a3-9042-ce3dcc9c163a)
![Captura de pantalla 2024-06-11 175524](https://github.com/udistrital/core_documentacion/assets/77305100/c86a322a-ae1e-4bc5-bf2b-236c73301f4c)
![Captura de pantalla 2024-06-11 175650](https://github.com/udistrital/core_documentacion/assets/77305100/0d75f6d7-b8f9-4d08-81d2-bea91ee79a52)


A raíz de esto se reabre el issue udistrital/core_documentacion#30 hasta que se logre corregir este apartado, se logró contactar al desarrollador del módulo de firma y estampado y se inició un contacto con el para concertar una reunión explicativa para tener más claro el funcionamiento de dicho módulo en aras de ahorrar tiempo al momento de realizar la corrección del error.

En cuanto a las pruebas de verificación ya se modificó la variable de entorno que apuntaba a firma electrónica por lo que la ruta que está ahora es la que apunta al entorno de despliegue, no el local:

![Captura de pantalla 2024-06-11 191212](https://github.com/udistrital/core_documentacion/assets/77305100/08af68e5-1264-4090-bb42-052b1b44b571)

Por tanto queda pendiente arreglar definitivamente el estampado de la firma, realizar de nuevo la prueba final de funcionamiento. probar el cliente de verificación y ajustar algunas respuestas de excepciones para que sean más entendibles

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 13/06/24

Se completaron las pruebas de funcionalidad de el módulo de firma electrónica y el módulo de verificación de firma electrónica:

Se añadieron manejos adicionales de excepciones para los campos faltantes del JSON en caso de que deban ser manejados:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/7ee3e748-6436-42e9-85a6-8309f33c8036)

Además se añadió validación de tipo de documento del base 64 para que la excepción se muestre correctamente y aborte la ejecución para que no se suba a nuxeo un archivo corrupto:

En controllerFirma:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/e32895ef-1537-40ae-a664-7ab172482633)

En archivo FirmaElectronica:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/1119f119-17ff-472c-bdc5-3cc90bb07eb8)

El módulo de firma electrónica terminó funcionando correctamente, además de que las pruebas de verificación de firma electrónica también fueron exitosas. Para más detalles se adjunta documento Excel con todas las pruebas realizadas:

[Pruebas de funcionalidad firma electrónica.xlsx](https://github.com/user-attachments/files/15825702/Pruebas.de.funcionalidad.firma.electronica.xlsx)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres
