### ISSUE TITLE
Apropiación de XRay

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#4]
Se requiere realizar la apropiación del sistema de XRay para lo que se requiere ver la grabación de la explicación de este sistema y posteriormente leer la documentación disponible.

**Sub Tareas**

- [x] Ver la [grabación ](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/EbDeOc4Tm_ZJjhrlzP6qeIEBDAVkvRyn44KljIIR_Fdzvw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view) de la socialización y empalme de XRay.
- [x] Leer la [documentación ](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CORE%2F2023) disponible sobre Xray
- [x] Clonar repositorio de utils_oas en la rama feature/xray

**Criterios de aceptación**

- [x] Repositorio clonado.
- [x] Apuntes importantes sobre lo entendido en la documentación y grabación. [Ejemplo](https://github.com/udistrital/core_documentacion/issues/2#issuecomment-2089264658)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by kikeavella** [comment]
Se hace la respectiva clonación del repositorio de utils_oas en la rama feature/xray:
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/294bce11-f4bb-4b59-a4a9-900242a51eea">
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/3305efd0-73da-4b2e-9ea1-6878b63fffab">

**Comment by kikeavella** [comment]
Coloco los apuntes más relevantes:

Generalidades:

El profe quiere una herramienta que nos permita saber cuando un api esta arriba o abajo y saber cuantas peticiones recibe cada api.

X-ray: es una herramienta de aws que permite monitoriar el estado de un api saber si esta arriba o abajo y cuantas peticiones recibe y de quien las recibe.

Se envia un correo cuando falla la api,el umbral es de un fallo.

--------------------------------------------------------------------------

Requerimientos:

Aumentar el tiempo que tiene amazon para guardar el historial de las peticiones a los endpoints.
Extender la trazabilidad de x-ray hasta las bases de datos, (quiere hacer investigación para saber como se hace, debido a que se usa una libreria externa para consultar las bd).
Enmascarar las apis, para que en ves de que muestren el host y el puerto que se conecto, muestre el host y el nombre de la api a la que se conecto.
En la libreria utils_oas, la parte de configuración de x-ray, la variable deamonaddr no quede quemada, sino como una variable de entorno.
Si en la configuración de una api, las respuestas las esta tomando desde utilidades.go y no desde utils-oas, la api no daría todos los valores necesarios, por eso abria que actualizar el api para que responda con los funciones de utils-oas/request/request_tools.go.

--------------------------------------------------------------------------

Archivo excel llamado cronograma de instrumentación y migración de apis con aws x-ray:

* La columna REFACTOR es para saber si ya esta manejando las fuciones de respuesta desde utils-oas/request/request_tools.go.
* La columna INSTRUMENTACIÓN es para saber si ya se coloco x-ray en el main.go

--------------------------------------------------------------------------

Archivo excel llamado Migración de utilidades de APIS_MID:

* Hacer un diccionario de métodos y colocar en la columna OBSERVACIÓN lo que hace el método relacionado.
