### ISSUE TITLE
Presentación de firma electronica a funcionamiento.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#44]
Se requiere realizar una presentación al equipo de funcionamiento donde se muestre el funcionamiento actual del sistema incluyendo la firma electronica y la posterior verificación.

**Sub Tareas**

- [x] Realizar presentación al equipo de funcionamiento.

**Criterios de aceptación**

- [x] Presentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 18/06/24

Se realizó la presentación y socialización de la firma electrónica a funcionamiento. Como conclusión se tiene que el alcance queda aprobado con la condición de que en el JSON de la respuesta se quite la llave privada por temas de seguridad. Por lo que se desarrolla dicho requerimiento de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/c60b973f-22e3-4fa2-a4fd-1588d8d8c365)

En el archivo controllerFirma.py se agregan estos fragmentos de código que permiten quitar dicha clave y valor del json de respuesta dando resultado lo siguiente:

 
![image](https://github.com/udistrital/core_documentacion/assets/77305100/0b949ef5-d060-4d87-a088-7b00ecf349ee)

Se suben los cambios al repositorio para agregar a pruebas

**Comment by diagutierrezro** [comment]
Muy buen trabajo en la presentación Andres, gracias
