### ISSUE TITLE
Realizar analisis para cliente de verificación con cargue del documento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#45]
Se requiere realizar el analisis inicial sobre como implementar en el cliente de verificación el nuevo alcance que se refiere a que la verificación se realice cargando el respectivo documento y que este realice la verificación.

Se solicita un documento tecnico donde se especifiquen los diferentes cambios a realizar en el cliente como en las Apis (si se considera necesario)

**Sub Tareas**

- [x] Realizar analisis de modificaciones necesarias para realizar verificación mediante cargue de documento.
- [x] Realizar documento tecnico con las modificaciones a realizar tanto en el cliente como en las Apis.

**Criterios de aceptación**

- [x] Analisis realizado.
- [x] Documento tecnico realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/06/24

Se comienza la identificación de los cambios a realizar.

Se identifica por el momento que se requieren hacer cambios en los siguientes archivos del cliente de verificacións:

- **verificar.component.html**: Aquí se deben colocar etiquetas adicionales para que se pueda mostrar tanto el campo por el cual se debe subir el documento a comparar, como la muestra en pantalla de el documento subido y el que hay en Nuxeo, se comenzaron a hacer adelantos en este aspecto.
- **verificar.component.scss**: Aquí se deben colocar los estilos pertinentes de las etiquetas agregadas al archivo html
- **verificar.component.ts**: En este archivo se debe colocar la lógica y la petición por la cual se envíe el base 64 del archivo subido para que sea comparado con el archivo en nuxeo gracias a firma electrónica.
- **app.module.ts**: Aquí se debe colocar los módulos que se instalen para complementar el desarrollo de la nueva funcionalidad.

Se identificó por el momento la necesidad de agregar al proyecto el módulo file input de angular material para cargar el pdf. Sin embargo al tratar de instalarlo se genera el siguiente error:

![Captura de pantalla 2024-06-24 164313](https://github.com/udistrital/core_documentacion/assets/77305100/6bbd548a-16c7-4382-ae40-4da3241b7adc)

Al modificar el package.json con la versión que el peer solicita:
![Captura de pantalla 2024-06-24 164234](https://github.com/udistrital/core_documentacion/assets/77305100/a4dd13c1-b423-4b69-81d3-3c8d3824d377)
Se obtiene el siguiente error:
![Captura de pantalla 2024-06-24 164223](https://github.com/udistrital/core_documentacion/assets/77305100/0a36a9b4-5c53-4448-890e-3fe8c5ec2f6b)


Se está definiendo la solución para dicho error, se baraja reinstalar Zone.js ya que es la única dependencia que genera error

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/06/24

Se logró arreglar el error del día anterior cambiando las versiones de angular y de node a las siguientes:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/93a1b06b-dc9a-4be0-b4f4-8a948c3e8787)

Sin embargo la librería de angular material que se pensaba usar para la implementación para el cargue del documento no funcionó correctamente por lo que se descarta y se está investigando en la documentación de angular una posibilidad que al parecer no necesita librerías externas, por lo que probablemente no se necesite por el momento modificar el archivo **app.module.ts**, siendo solamente necesario por el momento la modificación de los archivos en **src/app/pages/verificar** excepto **verificar-component.spec.ts** 

En cuanto a la API de firma electrónica mid, es necesario modificar el método de postVerify en controllerFirma.py para que se pueda realizar la captura del base 64 del archivo subido por el usuario y dependiendo de las validaciones que se especifiquen en la lógica de negocio responder de una forma u otra en base a si hay un archivo subido por el usuario o no, y si de haberlo, este coincide o no.

Queda pendiente la terminación del documento técnico en el que se especifiquen los cambios a realizar

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/06/24

Se terminó el documento técnico de los cambios a realizar habiéndose identificado en su elaboración un archivo más a modificar el cual se especifica en dicho informe, el cual se adjunta a continuación. Se pasa el issue a in review

[Cambios para nuevo alcance firma electrónica.docx](https://github.com/user-attachments/files/15993969/Cambios.para.nuevo.alcance.firma.electronica.docx)
