### ISSUE TITLE
Creación de formatos de historias de usuario para cliente Oikos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#46]
Se requiere realizar la creación de formatos de historias de usuario para cliente Oikos

**Sub Tareas**

- [x] Creación del formato historias de usuario para cliente Oikos 
- [x] Socialización del formatos historias de usuario
- [x] Aprobación del formato de historias de usuario

**Criterios de aceptación**

- [x] Formatos historias de usuario para cliente Oikos
- [x] Docuenmentación de formatos historias de usuario para cliente Oikos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado las primera versión de las historiras de usuario de OIKOS 

[Historias de usuario v1 ](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EUbOoXJBLGhChQFfd5Tgq_gBE1_d_tUEczIVkRWeSwN3yw?e=TpRoa4)

**Comment by jcmurilloa** [comment]
Muy buen trabajo!
