### ISSUE TITLE
Diseñar el mockup para la verificación del documento en firma electrónica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#47]
Se requiere diseñar el mockup para la verificación del documento en firma electrónica. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado la primera versión de mockups con base a los nuevos alcances planteados




![Image](https://github.com/udistrital/core_documentacion/assets/85162258/6fbc228d-ec39-4893-8966-a53da1aa865b)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/185b5073-1ec7-4753-8c7d-c652c7b70920)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/7842e8d4-82eb-4f46-b838-838cb39b8285)

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpmB_fcWAz1Pl5YMZ73r3eYBLl7zSjKOL4p3R33jJU2MXg?e=jwvYVf)

**Comment by jcmurilloa** [comment]
Revisado el mockup, se generan algunas recomendaciones por parte del equipo SoS para mostrar información adicional

**Comment by mantnicot** [comment]
Se ha realizado las actualizaciones del mockups 

![Image](https://github.com/udistrital/core_documentacion/assets/85162258/afe61b1d-5c65-4eb7-82f7-35fae5ede2a7)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/db5b9a5f-2137-4eaa-a38c-90306e753c90)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/2aa5d1c7-c8fb-4a7f-ac43-3fa30e78c2dc)
![Image](https://github.com/udistrital/core_documentacion/assets/85162258/6448e37a-6487-47ef-9c38-adfc2fecf248)

[Carpeta de mockups v2](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjjpWE2Je2FPmjSlcDf_zV8BrKVa8s5LM2zVeUzvzZ0tNg?e=vMa0f3)

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot!
