### ISSUE TITLE
División del Cliente Oikos en Microfrontends - Microcliente mapeo de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#48]
Se requiere realizar la planeación y estructuración para dividir el sistema Oikos en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

 - [x] Análisis del sistema Oikos microcliente de mapeo de dependencias.
 - [x] Crear diagrama de componentes de la arquitectura para el microcliente de mapeo de dependencias.
 - [x] Listado de funcionalidades del microcliente.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/9cfa552f-7ac6-40de-ab7e-b3e3948c5027)

se realiza diagrama de componentes para microcliente de mapeo de dependencias con sus componentes:

- BUSCAR DEPENDENCIA
- MAPEO DE DEPENDENCIAS

Este diagrama de componentes es preliminar y está sujeto a modificaciones.

**Comment by xDa04vidx** [comment]
Se corrige diagrama de componentes, después de las correcciones suministradas por el analista @mantnicot 


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/b021a367-db60-4512-9fb2-1550fde3804a)

para este microcliente de registro y gestión de dependencias sus componentes son:

- MAPEO DE DEPENDENCIAS

**Comment by xDa04vidx** [comment]
### Lista de funcionalidades
**Mapeo de Dependencias**

- Buscar dependencia
    - Se podrá buscar la dependencia utilizando los campos de nombre de dependencia, tipo de dependencia, facultades, vicerrectorías y estado. Para los campos de nombre de dependencia, facultades y vicerrectorías, se proporcionará una asistencia visual que brindará información para su correcto diligenciamiento. Además, para el campo de tipo de dependencia, se mostrará una lista desplegable donde el usuario podrá seleccionar una o varias opciones. En el campo de estado, se ofrecerán dos opciones: activo o no activo.
    - Cuando el usuario oprima el botón de buscar y se encuentren dependencias, estas se listarán en una tabla con las siguientes columnas: nombre, dependencias asociadas, tipo y acciones.

- Crear mapeo
   Para crear mapeo pueden existir dos casos, el caso para la dependencia académica y otro para la dependencia administrativa.
    - **Crear mapeo para dependencia académica** Se mostrara un formulario con los campos nombre dependencia, número de identificación interno y código snies. En el campo del nombre de la dependencia, se mantendrá estático el nombre de la dependencia, mientras que para los campos de número de identificación interno y código snies, se proporcionará una asistencia mostrando a que hace referencia ese campo.
    - **Crear mapeo para dependencia administrativa**  Se mostrara un formulario con los campos nombre dependencia y número de identificación interno. En el campo del nombre de la dependencia, se mantendrá estático el nombre de la dependencia, mientras que para el campo de número de identificación interno, se proporcionará una asistencia mostrando a que hace referencia ese campo.
    - Se mostrará un botón para crear el mapeo, este mostrara dos posibles resultados, uno para cuando se pudo realizar el mapeo y otro cuando sucede algún error.

- Editar mapeo
   Para editar mapeo pueden existir dos casos, el caso para la dependencia académica y otro para la dependencia administrativa.
    - **Editar mapeo para dependencia académica** Se mostrara un formulario con los campos nombre dependencia, número de identificación interno y código snies. En el campo del nombre de la dependencia, se mantendrá estático el nombre de la dependencia, mientras que para los campos de número de identificación interno y código snies, se proporcionará una asistencia mostrando a que hace referencia ese campo.
    - **Editar mapeo para dependencia administrativa**  Se mostrara un formulario con los campos nombre dependencia y número de identificación interno. En el campo del nombre de la dependencia, se mantendrá estático el nombre de la dependencia, mientras que para el campo de número de identificación interno, se proporcionará una asistencia mostrando a que hace referencia ese campo.
    - Se mostrará un botón para editar el mapeo, este mostrara dos posibles resultados, uno para cuando se pudo realizar la edición del mapeo y otro cuando sucede algún error.

**Comment by diagutierrezro** [comment]
Se cierra la tarea, buen trabajo David.
