### ISSUE TITLE
Agregar texto para indicar como verificar la firma electronica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#49]
Se requiere realizar los ajustes necesarios para agregar un texto al final del documento donde se especifique la ruta que deben seguir los usuarios para verificar la autenticidad de la firma. Esta ruta hace referencia el cliente de verificación que se encuentra en https://pruebasverificacion.portaloas.udistrital.edu.co

**Sub Tareas**

- [x] Realizar ajustes necesarios para agregar el texto indicado, se debe asegurar que el sistema siga verificando que tenga el espacio suficiente para agregar la firma electronica y adicinalmente el texto.
- [x] Realizar diferentes pruebas para verificar lo anterior.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 17/06/24

Se realizó la modificación de la firma electrónica para adicionar el enlace de verificación (por ahora el de pruebas) de tal forma que la firma queda de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b085398a-4fa3-455a-a1b5-1eb714a4adcd)

Se realizaron distintas pruebas del funcionamiento incluyendo las ya realizadas para la corrección de la posición y las pruebas de funcionamiento, algunas de las pruebas realizadas son las siguientes (Los íconos ||||||||| al final de las hojas son caracteres impresos en la parte superior del pie de página para motivos de pruebas):

**PRUEBA 1:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b8d19594-041f-44e7-9fa0-d5b0a30b5e4f)

**PRUEBA 2:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/c29d23c4-a03e-40f7-9d43-e5c4e5f54177)

**PRUEBA 3:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f491df20-fb3a-462c-bd8e-2777a2613e8e)

**PRUEBA 4:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b9de2993-edfe-4c88-b5f9-d19bb6917681)

**PRUEBA 5:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/3c4cc951-9a6a-4e79-ab4e-a74b333cc427)

**PRUEBA 6:**

![image](https://github.com/udistrital/core_documentacion/assets/77305100/2a106bc7-a011-45bf-aaac-e015f0bcf29e)


Con las pruebas realizadas y el funcionamiento correcto evidenciado se coloca en in review
