### ISSUE TITLE
Analisis de Oikos V1 en APIs

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#5]
Se requiere realizar el analisis del uso de Oikos V1 en las APIs y cliente de novedades y necesidades con el fin de tener claro en que puntos se realiza el uso de estas APIs y planear el cambio a V2

**Sub Tareas**

- [x] Clonar [cliente](https://github.com/udistrital/novedades_cliente) y [mid](https://github.com/udistrital/novedades_mid) de novedades.
- [x] Clonar [cliente](https://github.com/udistrital/necesidades_cliente) de necesidades.
- [x] Buscar en los environment el uso de Oikos V1 y realizar un listado de peticiones realizadas hacia Oikos V1. Por ejemplo: "Novedades cliente - carpeta directivas - necesidad - clase visualizar necesidad - linea 25"

**Criterios de aceptación**

- [x] Repositorios clonados.
- [x] Listado de peticiones realizadas haca Oikos V1 en los diferentes clientes y API

**Requerimientos**

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Análisis del cliente necesidades_cliente**
PDF: [necesidades_cliente.pdf](https://github.com/udistrital/core_documentacion/files/15215542/necesidades_cliente.pdf)
Link de OneDrive: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/ERu_wwFJnENEghTjMRG-cU4BLWB-VRrHACktjDIUnfgPQQ?e=7gpdGO

**Comment by xDa04vidx** [comment]
**Analisis del cliente novedades_cliente**
PDF: 
[novedades_cliente.pdf](https://github.com/udistrital/core_documentacion/files/15215867/novedades_cliente.pdf)
Link de OneDrive: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/EdqT7AqzBHVFvCmrirLNYskBMFySyxtJzOt2xF-l36PPZA?e=jaKwll

**Comment by xDa04vidx** [comment]
**Análisis de la API MID novedades_mid**

No se encontraron referencias a OIKOS en el API MID de novedades_mid

- Se revisó el archivo app.conf, pero no se encontraron referencias a "OIKOS".
![image](https://github.com/udistrital/core_documentacion/assets/168471458/432783d0-c7c8-4fb3-a199-190710ddabb5)

- Además, se realizó una búsqueda en todo el proyecto y no se encontraron referencias a la palabra "oikos".
![image](https://github.com/udistrital/core_documentacion/assets/168471458/1591b738-6d38-4aee-b01e-b2623304f72f)
