### ISSUE TITLE
Creación Microfrontend Oikos-Root-mf - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#50]
Se requiere realizar la estructuración inicial de los microfrontend para Oikos, iniciando con la creación del Root **oikos-root-mf**.

**Material de apoyo**
- [Aplicación Root](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/root_config.md)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [Creación Microfrontend Root-mf](https://github.com/udistrital/planeacion_cliente/issues/925)

**Especificaciones técnicas**

1. El repositorio para oikos-root-mf es:
2. Se requiere crear el cliente a partir de single-spa.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
4. Consumo del [core-mf](https://github.com/udistrital/core_mf_cliente)

**Sub Tareas**

- [x] Desarrollar microfrontend Root
- [x] Uso de estilos respectivos [assets](https://github.com/udistrital/assets)
- [x] Consumo de core-mf

**Dependendencias**
El lider @diagutierrezro debe crear el respectivo repositorio.

**Criterios de aceptación**

- [x] Cliente root creado
- [x] Consumo cliente core-mf

**Requerimientos**

- [x] Completar issue [División del Cliente Sísifo v1 en Microfrontends - Microcliente Plan mejoramiento PT2](https://github.com/udistrital/sisifo_documentacion/issues/9)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Avances creación Microcliente Oikos-root

1. A partir del material de apoyo, se logra realizar el root.
2. Se crea el microcliente con single-spa de acuerdo con las indicaciones, además se agregan variables de entorno y los assets.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/49b8675b-bd0f-4015-83c1-3fa301736fa2)

3. Se logra conectar el root con [core_mf_cliente](https://github.com/udistrital/core_mf_cliente)

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/5b946572-2069-4e1c-a8e6-8a4fa95ae197)

4. Las variables de entorno quedan con la estructura basica como se encontraba en [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/8a0fb0d9-9a94-4782-beb9-da3525e04ee3)

No obstante, se modifica el appname, para que el core, obtenga el nombre de la aplicacion y encuentre los iconos relacionados al cliente.

5. Para los estilos se utiliza la estructura que se encuentra en  [sga_cliente_root](https://github.com/udistrital/sga_cliente_root), se realiza un archivo index.css, donde se importan los estilos, y luego se importa en el archivo de udistrital-root-config
Estilos:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/82f9431b-7b2c-49c0-aaa4-872e3b77285a)
Importación:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/37742b1e-7472-4dc2-ae18-73e34ec755be)

**Nota**
Cabe aclarar que se utilizan los estilos de GAIA dado:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/cafc0501-57cb-4c8a-ad20-1cd6baa7ebf6)

6. Por ultimo se utiliza el nuevo icono de OIKOS para el favicon.ico
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/3445fbd2-b9fd-4954-a125-240c9d9064a9)

**Comment by xDa04vidx** [comment]
### Despliegue
Se muestra que el despliegue se realiza de manera correcta:

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/f06c6ea3-6565-4439-9ac8-381fcf6c2bda)

El botón de iniciar sesión, redirige al login de manera correcta.

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/89aea483-07af-4c0d-9b4d-3139cbe62e14)

El login se puede realizar de manera correcta, y se redirige al inicio de la aplicación:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/ef175139-545f-40c8-9e77-b9cba6c7aaf3)


Por ultimo, gracias a la extensión de single-spa inspector se comprueba que el microcliente core-mf, esta activo y funcionando.
 


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/067c7d97-d83d-404d-915b-8b6d867fea1f)

**Comment by xDa04vidx** [comment]
**Pendientes**
Queda pendiente la actualización de los logos de Oikos en los assets.

**Comment by xDa04vidx** [comment]
### Corrección de logos
Se verifica que los logos han sido actualizados

Inicio
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/b0519006-5737-45a9-aa3b-4ac2da416df7)

Después del inicio de sesión


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/d57f9eb0-f069-40cb-8b5d-30c3d36133af)

**Comment by xDa04vidx** [comment]
**Pull request**
Se realiza pull request de la rama donde se creo el proyecto (feature/creacion_root) a la rama de develop


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/3bb91b25-406a-443b-885f-b1da8b525950)

**Comment by diagutierrezro** [comment]
Queda pendiente por actualizar el README del repositorio, se asumirá en otro issue. Buen trabajo David.
