### ISSUE TITLE
Estimación de apis faltantes por instrumentalizar.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#52]
Se requiere realizar la estimación de las apis que aún no se encuentran instrumentalizadas con el fin de tener claro el tiempo faltante que puede tomar terminar la instrumentalización.

**Sub Tareas**

- [x] Actualizar estimación de Apis faltantes por instrumentalizar en el [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYHrM0PC9JtMlfe_H5zx6CYBlZWCAdqsQst2ysQoZDJd1w?e=2bb1Su).

**Criterios de aceptación**

- [x] Actualización de estimaciones en documento realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hace el respectivo análisis luego de ver el código fuente en github de cada api mid, donde el que más ocupa tiempo es arka mid por la cantidad de lógica que maneja, los que menos tiempo necesitan son sideap_mid, google_mid, plan_cuentas_mid, tesoreria_mid que tienen poca lógica o tienen parcialmente la implementación, algunos de los faltantes tienen una estructura no estandarizada ya que fueron desarrollados hace tiempo y varian un poco es la forma que está el código, otros faltantes tienen la estructura estandarizada a la forma actual y no tiene nada de la implementación, lo cual me llevo a la siguiente estimacíon de tiempo:

<img width="751" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/f5481ecc-30c8-4215-9e74-bf2e3439d516">
<img width="755" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/29e590df-349a-4e26-8f6d-d222470cb404">

**Comment by JulianAvella** [comment]
notificaciones_mid: Aparece en github que no se encuentra el repositorio, page not found. 
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/ab1969fd-382b-4b73-91c7-270bec6f026c">

api_mid_financiera: Dice que el repositorio esta archivado.
<img width="959" alt="image" src="https://github.com/udistrital/core_documentacion/assets/69371935/643ecb2e-bbbb-433e-83bd-a4103902c6d7">
