### ISSUE TITLE
Documentación tecnica para despliegue a producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#53]
Se requiere realizar la documentación requerida para realizar el despliegue a producción del sistema, se requiere realizar documentos similares a los que se encuentran en esta [carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo8tqC5GQnNKhI18i9nX0goBz1JCokLP5ujjCsv9yx5W8A?e=hvObqj) a excepción de la matriz de acceso considerando que el cliente no tiene funcionalidades diferenciadas según el usuario que ingrese.

**Sub Tareas**

- [x] Realizar documento de diagnostico final.
- [x] Realizar documento de casos de soporte.
- [x] Realizar documento de descripción - historicos.

**Criterios de aceptación**

- [x] Documentos realizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 20/06/24

Se realizaron los tres documentos asignados, por lo que se crea una carpeta en One drive para su fácil acceso. Se notifica al líder de equipo para realizar la revisión y aprobación de los documentos. La carpeta en la que se alojan los documentos es la siguiente:

https://udistritaleduco-my.sharepoint.com/:f:/g/personal/davagomezr_udistrital_edu_co/ElyySuKtGPtOminlFKMx4yYBCqZnbpe9OE_GHizqcrHHCw?e=3lGicW

**Comment by diagutierrezro** [comment]
Buen trabajo Andres
