### ISSUE TITLE
Proyectar documentación para el usuario sobre firma electrónica (presentación)

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#55]
Generar una investigación y proyectar un documento sobre la firma electrónica para la divulgación

**Comment by mantnicot** [comment]
Se ha creado la primera propuesta de documentación , se va a enviar la propuesta a Viviana con los comentarios dados por el equipo

[Documento de usuario](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQkXilD7tLRIvlANrDKuA3kBywPvUBzLkjKDm-w01rQMtw?e=RPOapc)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, este dcoumento es base para proyectar la presentación, también solicitada.

**Comment by jcmurilloa** [comment]
Por favor contactar a Viviana para continuar el trámite respectivo del compromiso.
