### ISSUE TITLE
Documentación del README para el repositorio oikos_root_mf

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#56]
Se requiere realizar la actualización del README siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md), se puede usar como ejemplo el README creado para el [root de auditoria](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf)

**Sub Tareas**

- [x] Actualizar README del repositorio oikos_root_mf
- [x] Realizar documentación.

**Criterios de aceptación**

- [x] README actualizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
Se actualiza el pull request de [oikos_root_mf](https://github.com/udistrital/oikos_root_mf)


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/d382213c-12a5-4d7b-883b-6af693ea1bcb)
