### ISSUE TITLE
Creación microcliente gestión y registro de dependencias - fase de registro

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#57]
Se requiere realizar la creación del microcliente de gestión y registro de dependencias que se ubicará en el siguiente [repositorio](https://github.com/udistrital/gestion_registro_dependencias_mf). Importante que la creación y configuración se realice usando el framework de single spa.

Posterior a la creación y configuración inicial se debe crear la estructura para el modulo de registro de dependencias siguiendo los mockups que se definieron en #33.

**Sub Tareas**

- [x] Creación y configuración del microcliente (la configuración incluye la conexión con el root).
- [x] Creación de la estructura inicial del modulo de registro de dependencias.
- [x] Pruebas de funcionamiento del microcliente en ambiente local.
- [x] Documentación del issue con creación, configuración y pruebas realizadas.

**Criterios de aceptación**

- [x] Creación y configuración del microcliente realizada.
- [x] Creación de estructura del modulo de registro de dependencias realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Creación de microcliente**
Se crea el microcliente siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/4d3ffde823373b5f020dd8ac8e224ad00eea2baa/single_spa/parcel.md).


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/a58416ae-556f-4e73-a1a2-05cb9bc32c01)


Se crea el proyecto y se realizan las sugerencias de los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/4d3ffde823373b5f020dd8ac8e224ad00eea2baa/single_spa/parcel.md):

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/8d09ca03-72b6-47af-a756-49862f340cab)

Se ejecuta correctamente:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/2eb542d9-fd0f-4661-9b4d-78801375c4da)

**Comment by xDa04vidx** [comment]
### Adelanto en el microcliente

Menú funcional y elementos del mookup puestos.
Pagina:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/fc63b25a-3306-4815-8f25-aa467dc0e24c)

Mookup:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/3651ad24-16fa-4413-803b-d7814d82e977)

Para las ayudas, se han tenido problemas con la herramienta matTooltip, pues no muestra la ayuda así fuera básica, se están evaluando otras estrategias para mostrar esta información, actualmente se muestra la ayuda, pero distorsiona los demás componentes:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/7ebf367d-f422-477f-994a-147d31694f84)

**Comment by jcmurilloa** [comment]
Ayer cerró el sprint 10, y esta issue, que pertenece al sprint 9 continúa in progress, por favor poner esfuerzos en completar y cerrar esta issue, junto a sus respectivos comentarios y documentación @xDa04vidx  @diagutierrezro

**Comment by diagutierrezro** [comment]
Se da por finalizada la tarea, el único punto faltante es la ventana informativa flotante que falta por ajustar por temas de estilos, se continúa con el resto de implementaciones y este estilo se ajustará despues.

**Comment by xDa04vidx** [comment]
### Solución a estilos faltantes

Se soluciona el problema del tooltip, para mostrar la respectiva ayuda en los campos necesarios

- Nombre dependencia:
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/ab78e5b5-7725-47bc-b06f-b44909905937)

- Telefono asociado   
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/f30c9b3e-f059-4a1c-a770-bfff24ebbcdd)

- Correo institucional
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/0e3f9f79-4e60-49db-86d9-78f1da27ef86)

Además, se realizan ajustes en los campos "Tipo de dependencia" y "Dependencia asociada". Para ello, se crean tablas en TypeScript que luego se utilizan en el HTML para generar las opciones de estos campos.

- Tipo dependencia
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/0140f878-8e3c-4138-b8d9-49a9cde8669e)

- Dependencia asociada
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/c193a8ae-1ae7-4b80-906b-cac8eac494c1)
