### ISSUE TITLE
Iniciar ajustes para nuevo alcance de verificación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#58]
Se requiere realizar ajustes para el nuevo alcance en el cliente de verificación teniendo en cuenta lo analizado en #45 donde se quiere agregar la verificación cargando un documento PDF en el cliente.

**Sub Tareas**

En el cliente se requiere:
- [x] Crear botón para cargar documento que se va a verificar.
- [x] Realizar conversión a base 64 del documento cargado.
- [x] Crear de manera inicial visualización en dos iframe, posteriormente se modificará el momento en el que se muestran.
- [x] Definir el json que se envía hacia el mid donde se envíe el base64 del documento que se carga, este json es el mismo que se envía en el endpoint de verificación 
- [x] Modificar mid para que reciba desde el cliente el json modificado.
- [x] Ajustar logica del mid y visualización en el cliente para que de respuesta de la verificación según los 3 casos acordados:
> - Cuando solo se envía el hash se mantiene el mismo comportamiento.
> - Cuando se envía hash y se carga un documento y los documentos coinciden.
> - Cuando se envía hash y se carga un documento pero los documentos no coinciden.

En el mid:
- [x] Ajustar el controlador de verificación para que reciba el json modificado que se envía desde el cliente.
- [x] Modificar respuesta del controlador hacia el cliente donde se determine si los documentos son iguales.

En general:
- [x] Realizar pruebas de funcionamiento en ambiente local.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Modificaciones en el cliente realizadas.
- [x] Modificaciones en el mid realizadas.
- [x] Pruebas en ambiente local realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 27/06/24

Se inició el desarrollo del nuevo alcance.

Se creó el botón de cargue del documento:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/d6bc72ac-3c21-4ee7-9559-de1c40724642)

El cual permite cargar el archivo correctamente:
![Captura de pantalla 2024-06-27 191444](https://github.com/udistrital/core_documentacion/assets/77305100/2f6f1d3b-e934-429e-8bb0-1412462bc38e)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/bdbf10e6-157e-4d83-af95-4622d6b48b90)

También ahora puede convertir a base 64 (se usa un textarea para mostrar el base 64 sólo para probar):

![image](https://github.com/udistrital/core_documentacion/assets/77305100/dea06628-d44f-4a34-b003-21c66570bd05)


También se logró mostrar dos pdfs paralelamente:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f30d2184-7352-4b55-a5be-bd06159fd642)

Para el botón se agregó el siguiente input:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/e04281f2-da13-47fb-9f27-df6d5c1e783a)
Con la siguiente lógica en el archivo typescript:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/bbe2e613-609b-45d6-8eb5-2d347d67320e)

Para convertir a base 64 se utilizan las siguientes dos funciones:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/d38be42e-53b1-4908-baae-48f8d038bacf)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/59ecc793-a320-499b-a229-8616ff454b37)

Para los pdf en paralelo se dispusieron de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/95a21a72-bf82-4996-8c02-e06c33ebfd06)

Con los siguientes Estilos:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/c1074fae-1e9f-4058-ab6c-8f747c2cced6)


Se sigue trabajando en el envío y recepción de respuestas modificados entre el cliente y la api firma electrónica

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 28/06/24

Se terminan de revisar los demás aspectos del Issue:

Se definió el JSON para enviar a firma electrónica MID (firmaElectronicaHelper.ts):

![image](https://github.com/udistrital/core_documentacion/assets/77305100/8d2cb81b-9055-4bf3-8ccc-d07420998de0)

Además el mid fué modificado para recibir el JSON (también se actualizó el Swagger en model_params.py):

![image](https://github.com/udistrital/core_documentacion/assets/77305100/a92053a5-54dc-4e5d-95d2-d7365ca70266)

También se agregó la lógica de comparación y se modificó el JSON que se envía al cliente de vuelta (controllerFirma.py):

![image](https://github.com/udistrital/core_documentacion/assets/77305100/8eb35ff1-5a1b-4cca-bebe-c95b5c1678a9)

En la respuesta se evidencian las claves agregadas al JSON (swagger firma electrónica):

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f4cbcc17-7040-4c0e-a3f9-1dabf0b00c8e)

En el cliente se ajustó la visualización dependiendo si son iguales o distintos los documentos o si bien sólo se sube uno por medio de un ngIf que tomara la variable booleana encargada de decir si los documentos son iguales o no, recibida desde el mid como parámetro para determinar cual etiqueta html mostrar (verificar.component.html): 

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f543dd61-0bec-4e47-8b91-4b1b44557ee4)

Así mismo se modificó verificar.component.ts para que reciba la nueva información desde el mid:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/b9fdd494-85ad-4b54-8638-649613d83fc9)

Al momento de documentar, no se puede mostrar el funcionamiento en tiempo real ya que hubo un problema en la generación de las credenciales en la VPN haciendo que se venciesen por lo que no se pudo tomar capturas específicas del funcionamiento, sin embargo se hicieron pruebas y hasta el momento el sistema está respondiendo correctamente en función de lo que se está pidiendo en el Issue.
