### ISSUE TITLE
Definir la necesidad respecto a caducidad de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#59]
Levantar los requerimientos sobre la firma electrónica en caducidad de roles dentro de la OATI

**Comment by mantnicot** [comment]
Se ha definido en la reunión de seguimiento de inversión el día 04/07/2024, que las personas que peuden ayudar en el levantamiento de información de caducidad de roles es Cristian Alape, Cristian Laguna y Jhon Castellanos

**Comment by mantnicot** [comment]
Se ha podido hablar con las personas y se ha podido dar claridad con respecto a la necesidad , el cual es poder dar fechas de expiración a ciertos roles de ciertos usuarios por medio de wso2 , cuya persona encarga en Jhon.

Se propone de parte de cristian laguna que se cree una consulta a argo que traiga la fecha de fin de contrato

La ruta sería entender como funciona el proceso de los roles , cuales serían los roles y/o usuarios que requieren esto y generar un plan de acción

**Comment by mantnicot** [comment]
Jhon castellanos comenta que lo mejor es hacer una reunión con funcionamiento para ver bajo que condiciones se haría esa caducidad de roles

**Comment by jcmurilloa** [comment]
@mantnicot excelente trabajo de esta manera el siguiente paso sera agendar esta sesión con Jhon.

**Comment by mantnicot** [comment]
Se habla con Adriana sobre el tema de condiciones de caducidad de roles y se habla de las novedades contractuales que puede tener un rol 

-  Por sesión , cuando hay entra a suplir a la persona
-  Por terminación , culminación del contrato anticipadamente , bilateral , no cumplimiento
-  Otros si , se aumenta el tiempo , valor y tiempo 
1. Presupuesto y tiempo en el otro si , para contratista 
2. Tiempo , para los proveedores
-Por suspensión , se deja en pausa el contrato y se retoma después de un tiempo , alargando el final del mismo

**Comment by mantnicot** [comment]
Se ha podido charlar con Jhon con respecto al tema , él ha comentado que la novedad de suspensión no tiene sentido que se quite el rol , pues volverá en algún momento , y comenta que para continuar con el proceso , se debe poder conseguir una consulta de novedades.


Se habla con Eduar y cuenta que esa consulta se puede realizar con Youssef , quien es el encargado de novedades contractuales.


Se intentara contactar con Youssef

**Comment by jcmurilloa** [comment]
Agradecemos tu gestión @mantnicot para continuar con este trámite, estaremos atentos a la continudad de la tarea.

**Comment by mantnicot** [comment]
Se ha podido hablar Youssef y me ha dado lo siguiente para la consulta :;

" _https://autenticacion.portaloas.udistrital.edu.co/apioas/novedades_mid/v1/novedad/319/2024

http://pruebasapi.intranetoas.udistrital.edu.co:8502/v1/novedad/319/2024

Mira ahí están los de autenticación y en pruebas por intranet_ "

Son endpoints que ya fueron suministrados a Jhon y dijo que con eso, ya era suficiente por ahora , por lo cual se espera a la entrega

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, se define la necesidad y se esta atento a la realización del cambio por parte del responsable.
