### ISSUE TITLE
Creación inicial de API firma electronica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#6]
Se requiere realizar la configuración inicial del API de firma electronica siguiendo la configuración presente en el API de [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid).

**Sub Tareas**

- [x] Creación del API firma_electronica.
- [x] Realizar configuración inicial basandose en el API gestor_documental_mid (sin tener todos los requerimientos, estos se agregarán de a poco despues para no tener que instalar requerimientos innecesarios.)

**Criterios de aceptación**

- [x] API creada.
- [x] Configuración realizada.
- [x] API ejecutandose. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
---------ESTRUCTURA DE LA API CREADA:-----------
![image](https://github.com/udistrital/core_documentacion/assets/77305100/03aaf51c-7388-4c29-b0c6-fd4e4c919804)

--------- DATOS PRELIMINARES DE PRUEBA ----------
![image](https://github.com/udistrital/core_documentacion/assets/77305100/93e1f890-0a26-4d66-934d-fa22876237c5)

--------- CONFIGURACIONES INICIALES -----------
Hasta ahora la única librería necesaria para correr la API es la de Flask:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/2352f18b-7874-4733-98db-7e92b3f02851)

Se rescataron las variables de entorno de la API Gestor documental MID:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/689c1957-bd99-4594-b055-237e59e795ea)

Las cuales son verificadas en el archivo conf.py en la carpeta conf 
![image](https://github.com/udistrital/core_documentacion/assets/77305100/b91d32b6-6c18-4bae-bf83-d320d319cbec)

Además, se tomaron la mayoría de métodos de gestión de errores del controller error.py (omitiendo el de Nuxeo)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/fc602990-496c-4584-8c33-2227e72ee386)

Para esta primera iteración de la API se obvia todo lo relacionado con Nuxeo y se centra en la funcionalidad básica de la API.

Se requiere tener Python 3 y pip3 para poder correr el proyecto (Se recomienda usar Postman o Insomnia para probar peticiones)

--------- ARCHIVOS Y FUNCIONAMIENTO -------------
****api.py*****
En app.py inicializamos la aplicación de servidor, revisamos errores y llamamos la función addRutas del router para hacer el routeo para finalmente correrla en el puerto 4000:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/095ad6d3-c31f-457a-8b37-bd51c2ca35c8)

****router.py****
Por medio de Blueprints realizamos la asignación a la variable que nos permite hacer el routeo y para verificar el funcionamiento hacemos routeo de los métodos principales de un CRUD
![image](https://github.com/udistrital/core_documentacion/assets/77305100/cb22b491-2077-4f9f-b8d1-9473e53e7d65)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/e56024b7-a9db-4fdc-a407-58de933e3af8)

****controllerPrueba.py****
Finalmente aquí realizamos toda la lógica de las peticiones devolviendo un json según sea el caso:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/210ddf30-6d74-4275-a220-627920a31a8c)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/1540fd17-aa24-4af9-9359-381c9d10d2ea)

**Comment by Skyrus1203** [comment]
------- FUNCIONAMIENTO DE LA API -----------
Se utilizará Post man para probar los diferentes métodos:

Ruta home:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/2f5d26c2-26f6-4fad-8f02-cf68556bd4cd)

GET ALL:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/44c21d55-5dc8-4437-a918-ad06337e5321)

GET ONE:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/a901c67d-bbc6-4597-a09b-e4a4307e0e6e)

POST:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/605f74ad-2bf7-449e-82fa-0665c841ead2)

PUT:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f2fad8c2-9e7d-4a79-80a0-f856f3648eea)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/3c2bbbe2-5c5a-413d-95f6-f393c8f95eef)

DELETE:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/f28832f1-9e59-4a99-a2a8-9163af7962fb)

Queda pendiente la implementación de Swagger
