### ISSUE TITLE
Continuar ajustes para nuevo alcance de cliente de verificación.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#60]
Se requiere realizar el ajuste en el cliente para que corresonda con los mockups realizados en #47, estas tareas incluyen intercambiar la posición de los documentos mostrados (el de nuxeo a la izquierda), ajustar textos y creación de las alertas dependiendo de el resultado.

**Sub Tareas**

- [x] Intercambiar posición de documentos.
- [x] Ajustar textos.
- [x] Creación de alertas.
- [x] Pruebas de funcionamiento local.

**Criterios de aceptación**

- [x] Ajustes al cliente realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 02/07/2024

Se realiza la corrección que quedó pendiente del sprint anterior en el cual se mostraba un bug visual en el que el sistema identificaba que se había subido un archivo sin haberlo luego de oprimir el botón volver al haber ingresado un documento una primera vez, ocasionando que en el caso de que el usuario no seleccionase de nuevo algún archivo se mostrase un iframe vacío y otro iframe con el pdf asignado a la firma, esto se corrigió inicializando todas las variables posibles en el método onVolver que dispara el botón volver en el cliente:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/35953ab4-bc6c-4af6-bd57-893d50c22022)

También se intercambia la posición de los PDFs al mostrar, se ajusta su tamaño y color de los textos sobre los iframes y se cambia también el contenido de los mismos:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/4f48286f-c870-401a-9549-b6bb89a9923d)

También se crean las alertas correspondientes a cada caso:

Si si la firma existe o los documentos son iguales:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/15d838d9-048f-448a-8a00-3d4c0db06836)

Si el contenido del documento subido por el usuario y el contenido del documento en nuxeo no coinciden:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/038d3f8b-4583-49e9-90c0-491c2b414dd4)

Si la firma no existe:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/e5ef463b-307a-470d-a5c8-b8fe8722b89f)

Como se evidenció en las capturas se probó en los tres casos y funciona correctamente, se pasa el issue a in review

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres
