### ISSUE TITLE
Creación de estructura para modulo de gestión de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#62]
Se requiere realizar la creación de la estructura para el módulo de gestión de dependencias teniendo en cuenta los mockups creados en #33, se crea el formulario inicial para la busqueda, posteriormente la creación de la tabla de dependencias resultantes de la consulta del formulario anterior y finalmente el formulario de edición de las dependencias.

**Sub Tareas**

- [x] Creación de formulario de busqueda inicial.
- [x] Creación de la tabla resultante de la busqueda.
- [x] Creación de formulario para edición de dependencias.
- [x] Pruebas en ambiente local de estructuras creadas correctamente.

**Criterios de aceptación**

- [x] Creación de formularios y tablas realizadas.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto modulo de gestión

Se enruta el modulo de gestión, y se verifica que el enrutamiento esta funcional.
Además se ubican los componentes del formulario para buscar dependencias, según esta en los mookups, hace falta crear la tabla de resultados y las funcionalidades inherentes a ella.
Pagina:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/a14fa625-52c2-4358-9f4b-db8a8ad5099d)

Mookup:
![Image](https://github.com/udistrital/core_documentacion/assets/168471458/1ffc2549-6ce4-49b3-b631-97fde021c05b)

**Comment by xDa04vidx** [comment]
### Adelantos
Se corrige el botón de buscar y se crea el botón de "Ver organigramas" junto con su botón de ayuda.

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/e5d37ccd-a519-45b2-bbe5-d9d3bde6d00f)

Se realizan los Tooltips para los campos del formulario y para la ayuda del organigrama.

- Nombre dependencia
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/75baf987-235d-4146-90b8-3844e01a0aac)

- Facultades
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/83b0d70f-f2e4-4510-982d-a4c526f64a93)

- Vicerectoria
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/04f59ab3-1ff6-4cfa-b4ad-a749e41b1f07)

- Organigrama
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/d0b09fed-eff8-450d-9e28-11f96bd4089b)

Además, se realizan ajustes en los campos "Tipo de dependencia". Para ello, se creo una tablas en TypeScript que luego se utilizan en el HTML para generar las opciones de este campo. 

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/93fbd339-0d4f-4a8e-b418-d50cf38c92f0)

Para el campo de estado, se crean las dos opciones para "Activo" y "No activo".

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/73e73d2e-45a7-4e9c-ab3b-427f7d0864d3)

**Comment by xDa04vidx** [comment]
### Estructura final para el modulo de gestión de dependencias
Vista inicial con tabla:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/2aa8a9d9-4686-4132-af11-4cf625852ccc)
La tabla tiene paginación y responde de manera correcta con la estructura que se pone en el ts.

Los iconos fueron aprobados para edición, activación y desactivación de dependencias.

Se logra crear el pop up para el botón de edición.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/695e3d9c-aeb6-4658-a94e-d3f9e98c9423)
