### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#63]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente para verificación documento firma electrónica.

**Sub Tareas**

- [ ] Concertar reunión con el cliente.
- [ ] Desarrollar la reunión con el cliente.
- [ ] Diligenciamiento y aprobación del formato de historias de usuario para verificación documento firma electrónica.
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by jcmurilloa** [comment]
@mantnicot Que ha sucedido con esta reunión?

**Comment by mantnicot** [comment]
Se habia establecido la reunión para el día 12/07/2024 a las 11 am
Pero por cuestiones de cambios de parte de las pruebas de carga y seguridad , se tuvo que aplazar , se comentara en esta issue cuando se vaya a realizar la nueva reunión

**Comment by jcmurilloa** [comment]
Se cierra la issue a razón de los imprevistos surgidos.
