### ISSUE TITLE
Desarrollar la exploración inicial de alternativas para mejorar el tiempo del demonio con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#64]
Se requiere realizar la exploración inicial de alternativas para mejorar el tiempo del demonio con el cliente.

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Exponer los resultados el equipo SoS

**Criterios de aceptación**

- [x] Información expuesta al equipo SoS en sesión.
- [x] Reunión y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido hablar con Jaime con respecto al requerimiento y en compañía e Maria Fernanda , se hablo de que Xray tiene la dirección quemada y que antes se intento cambiar pero por cuestiones de recursos no se pudo hacer el seguimiento pues hubo algún inconveniente con respecto a ese cambio , entonces se dejo quemada directamente sin variable de entorno o dinámica.

Por lo cual sería realizar de nuevo el ajuste de la dirección y revisar los errores para ver si mejora los tiempos de respuesta.

**Comment by jcmurilloa** [comment]
Pendiente refinar el requerimiento junto a @diagutierrezro y retomar con el responsable en funcionamiento.
