### ISSUE TITLE
Pruebas funcionamiento nuevo alcance cliente verificación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#65]
Se requiere realizar las pruebas de funcionamiento de lo desarrollado en el nuevo alcance del cliente de verificación, se debe seguir el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWzX9i21lq5FtuB6Q88I0AkB84n8yfJlc5Bmjy3-kZ5abg?e=4LILo3).

**Sub Tareas**

- [x] Pruebas de funcionamiento.

**Criterios de aceptación**

- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 03/07/24

Se realizan las pruebas de funcionamiento del nuevo alcance del módulo de verificación de firma electrónica en ambiente de pruebas, confirmando el funcionamiento correcto del módulo en los distintos escenarios posibles, se adjunta el documento en el que se registraron las pruebas:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/davagomezr_udistrital_edu_co/EXIRbnhrgqhFl33VRBAb-tgBtqLkd5iaAIa3DLAuHn_ZPA?e=i3gKEU

**Comment by diagutierrezro** [comment]
Se realizará presentación al gerente y analista para confirmar que todo está bien, buen trabajo.
