### ISSUE TITLE
Exploración inicial para instrumentalización de Apis en Python

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#66]
Se requiere realizar la exploración inicial para instrumentalizar Apis en python, tener en cuenta el [documento tecnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW-h4D4dgZBGsfJwUCMuonsBk7Ly--hWHr5G2v3iRQ78DA?e=oDdGGk) que se creó para Apis en GO y tener presente que se manejará la misma estructura, se crea el SDK en el repositorio de utils y se estandarizará las peticiones HTTP en ese mismo repositorio.

**Sub Tareas**

- [x] Exploración inicial de implementación.
- [x] Elaborar un documento donde se registre la información que se vaya encontrando.

**Criterios de aceptación**

- [x] Exploración inicial realizada.
- [x] Documento realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se realiza la exploración inicial para realizar la instrumentalización de Apis desarrolladas en Python, se plantea la misma idea de la instrumentalización con GO donde se crea el SDK en el repositorio de utils_oas junto con las funciones http que después serán implementadas en cada una de las Apis, la exploración inicial se hizo leyendo documentación de amazon https://docs.aws.amazon.com/es_es/xray/latest/devguide/xray-sdk-python.html y analizando el repositorio https://github.com/aws/aws-xray-sdk-python . Se debe analizar mas a fondo las funcionalidades que se deben implementar tanto en el sdk como en las funciones http

**Comment by JulianAvella** [comment]
Se realiza la exploración inicial para realizar la instrumentalización de Apis desarrolladas en Python, se plantea la misma idea de la instrumentalización con GO donde se crea el SDK en el repositorio de utils_oas junto con las funciones http que después serán implementadas en cada una de las Apis, la exploración inicial se hizo leyendo documentación de amazon https://docs.aws.amazon.com/es_es/xray/latest/devguide/xray-sdk-python.html y analizando el repositorio https://github.com/aws/aws-xray-sdk-python . Se debe analizar mas a fondo las funcionalidades que se deben implementar tanto en el sdk como en las funciones http

**Comment by diagutierrezro** [comment]
En otra issue se asumirá una investigación mas a fondo para revisar una implementación concreta de la instrumentalización para APIs en Python.
