### ISSUE TITLE
Construcción del acta de entregables firma electrónica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#67]
Se requiere elaborar el documento de acta de entregables para firma electrónica.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se crea el [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EVKJPydjPxBOldUqvgxPwgMB_h192kV1G0WuXUhHCQ7jlw?e=BbMm54), aún no está finalizado ya que se definió que se realizará una nueva reunión para mostrar el nuevo alcance de firma electrónica

**Comment by jcmurilloa** [comment]
Pendiente por favor @diagutierrezro modificar el documento teniendo en cuenta únicamente el primer alcance, y enviar a cliente y funcionamiento para revisión y suscripción.

**Comment by jcmurilloa** [comment]
Teniendo en cuenta lo comentado, remitir a funcionamiento el acta a mas tardar 8 de agosto.
