### ISSUE TITLE
Realizar la documentación derivada del fuera de servicio a desarrollar OIKOS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#68]
Se requiere realizar la documentación derivada del fuera de servicio a desarrollar OIKOS

**Sub Tareas**

- [x] Confirmar la fecha y horaro del fuera de servicio por parte de funcionamiento
- [ ] Recolectar la información derivada del fuera de servicio
- [ ] Generar la documentación derivada del fuera de servicio

**Criterios de aceptación**

- [ ] Documentación fuera de servicio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha aplazado la reunión por cuestiones de que actualmente se esta manejando varias cosas en producción y puede ser riesgoso tumbar las bd , por lo cual se espera un nuevo espacio de parte de funcionamiento

**Comment by jcmurilloa** [comment]
La issue se mueve de sprint debido a las razones expuestas por parte de funcionamiento.

**Comment by jcmurilloa** [comment]
Pendiente @mantnicot concertar una nueva ventana para el fuera de servicio con responsable de mantenimiento.

**Comment by mantnicot** [comment]
Se ha podido charlar con Eduar y comento que hablando con el profe daza se cuadraría para el sabado 20/07/2024 a las 6 pm

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDBjMWQxNDItYWQ0Ni00NDBlLThjMjYtMWVkMjQyOGZkM2Vl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by jcmurilloa** [comment]
Según información brindada por Eduar, este procedimiento se aplazó nuevamente, por lo que la issue queda abierta y se trasladará de sprint cuando se tenga nueva programación por parte del área encargada.

**Comment by mantnicot** [comment]
Se ha quedado a espera de la reunión de baja de servicio , pero por medio de telegram se ha comentado lo siguiente



![Image](https://github.com/user-attachments/assets/d4da3c2f-8cd0-4d25-9aae-70dd4eb0d207)


Según lo dicho, se aplazara para agosto , se queda a espera para documentar

**Comment by jcmurilloa** [comment]
Teniendo en cuenta los commits de la issue, se procede a cerrar y crear nuevamente cuando se programe una nueva fecha para el procedimiento.
