### ISSUE TITLE
Continuar investigación para implementación de X-Ray en Apis de Python

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#69]
Se requiere realizar una investigación mas a profundidad para continuar lo encontrado en #66 donde se analice como implementar el SDK en utils_oas y las funciones http en los diferentes mids

**Sub Tareas**

- [x] Crear un documento con lo investigado sobre como implementar el SDK y las funciones http

**Criterios de aceptación**

- [x] Documento realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
En el siguiente documento word de onedrive se puede visualizar y se va a colocar toda la investigación del sdk para python y como se puede aplicar según la infraestructura ya establecida por la universidad:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jerodrigueza_udistrital_edu_co/EW8oXnFAJ4tOsVfsI6kUqxwBwPDW-PudG9IF19kJWXG_gw?e=zqOd1c

**Comment by JulianAvella** [comment]
Se hace investagación primero en plataformas de video como youtube, y en el canal oficial de AWS no hay ejemplos de como impletar x-ray para python, tampoco en otros canales diferentes al de AWS.
Luego se mira en la plataforma oficial de AWS, y en lo leido se encuentra para lo que sirven las funciones generales para x-ray y sus requerimientos para algunas bibliotecas que se pueden usar en python, y falta por leer una documentación más específica.

**Comment by JulianAvella** [comment]
Como en la documentación de AWS se encontro lo que hacen las funciones de x-ray pero unos vagos ejemplos de implementación, se consulta en la tecnología de inteligencia artificial como chatgpt, y muestra como se puede implementar con base en la arquitectura ya establecida que usan las apis con go que ya tienen instrumentalización de x-ray, entonces se crearía un archivo con extención para python en "github.com/udistrital/utils_oas" donde estaría la configuración, sus funciones de segmentos y subsegmentos de x-ray y estas funciones serían importadas desde las apis en python, donde se plasma un ejemplo de como se importarían para sus peticiones http

**Comment by diagutierrezro** [comment]
Muy buen documento, gran trabajo Julian.
