### ISSUE TITLE
Actualizar el documento de APIs instrumentalizadas

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#7]
Se requiere realizar la actualización del documento de APIs instrumentalizadas con Xray.

**Especificaciones técnicas**
- El documento anterior se encuentra en https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BB6075D45-4358-46D2-932E-F82A799BC8DA%7D&file=Cronograma%20de%20Instrumentaci%C3%B3n%20y%20Migraci%C3%B3n%20de%20APIs%20con%20AWS%20X-Ray.xlsx&action=default&mobileredirect=true

**Sub Tareas**

- [x] Realizar una copia del documento anterior y crear una copia nueva para usarlo en vigencia 2024.
- [x] Verificar que las APIs que, según el documento anterior, ya se encuentran instrumentalizadas efectivamente lo estén.
- [x] Realizar una revisión exhaustiva de las APIs que, según el documento anterior, aún no se encuentran instrumentalizadas, esto teniendo en cuenta que según la reunión de [Socialización y empalme de Xray](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/EbDeOc4Tm_ZJjhrlzP6qeIEBDAVkvRyn44KljIIR_Fdzvw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view) este documento se encuentra desactualizado y posterior a esta revisión ir actualizando el documento nuevo que se usará para vigencia 2024

**Criterios de aceptación**

- [x] Documento nuevo de Instrumentalización de APIs realizado y actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by kikeavella** [comment]
Se hace el respectivo análisis de 128 apis en el siguiente archivo: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B4333EB81-F4C2-4C9B-95F7-BF1F9CF1E826%7D&file=Cronograma%20de%20Instrumentaci%C3%B3n%20y%20Migraci%C3%B3n%20de%20APIs%20con%20AWS%20X-Ray%202024.xlsx&action=default&mobileredirect=true

**Comment by jcmurilloa** [comment]
Por favor realizar comentarios de avances en las issues Julian Enrique
