### ISSUE TITLE
Implementar SDK para Python en utils_oas - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#70]
Se requiere realizar la implementación inicial del SDK para Python para empezar a entender de manera funcional el comportamiento de dicho sdk según lo investigado en #69, esta implementación se debe hacer en el repositorio de utils_oas a partir de la rama master se genera una nueva rama feature/sdk_python donde se realizarán los cambios.

**Sub Tareas**

- [x] Realizar una implementación inicial del SDK en python  nueva rama de repositorio de utils_oas.

**Criterios de aceptación**

- [x] Implentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
En el siguiente documento word de onedrive se puede visualizar y se va a colocar toda la investigación del sdk para python y como se puede aplicar según la infraestructura ya establecida por la universidad: 
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jerodrigueza_udistrital_edu_co/EW8oXnFAJ4tOsVfsI6kUqxwBwPDW-PudG9IF19kJWXG_gw?e=zqOd1c

**Comment by JulianAvella** [comment]
Se hace investagación primero en plataformas de video como youtube, y en el canal oficial de AWS no hay ejemplos de como impletar x-ray para python, tampoco en otros canales diferentes al de AWS.
Luego se mira en la plataforma oficial de AWS, y en lo leido se encuentra para lo que sirven las funciones generales para x-ray y sus requerimientos para algunas bibliotecas que se pueden usar en python, y falta por leer una documentación más específica.

**Comment by JulianAvella** [comment]
Se crea una nueva rama en utils_oas llamada x-ray-python para subir la configuración del sdk en lenguaje python, donde se encuentran las funciones que hacen una configuración, inicializa la sesión y hace la integración con aws, después estable el entorno,  luego inicializa y finaliza un segmento y también para un subsegmento, despues una función para manejer el error 500, el código es el siguiente: 
import os
import boto3
from aws_xray_sdk.core import xray_recorder, patch_all
from aws_xray_sdk.core.lambda_launcher import LambdaContext
from aws_xray_sdk.core import exceptions
from aws_xray_sdk.ext.flask.middleware import XRayMiddleware
from flask import Flask, request, g
from botocore.config import Config

# Inicializa la aplicación Flask
app = Flask(__name__)

# Configuración de X-Ray
def init_xray():
    os.environ['AWS_XRAY_DEBUG_MODE'] = 'TRUE'
    
    xray_recorder.configure(
        #service='my_service',
        daemon_address='3.81.69.43:2000',  
        sampling=True,
    )
    
    patch_all()
    XRayMiddleware(app, xray_recorder)

init_xray()

# Setup AWS session and clients with X-Ray integration
def setup_aws_clients():
    session = boto3.Session(profile_name='default')
    config = Config(region_name='us-east-1')
    
    ecr_client = session.client('ecr', config=config)
    ecs_client = session.client('ecs', config=config)
    
    xray_recorder.configure(service='ecr')
    xray_recorder.configure(service='ecs')
    
    return ecr_client, ecs_client

ecr_client, ecs_client = setup_aws_clients()

# Setup environment from Parameter Store
def setup_environment():
    session = boto3.Session(profile_name='default')
    ssm_client = session.client('ssm', region_name='us-east-1')
    
    parameter = ssm_client.get_parameter(
        Name='/prepod/utils_oas/xray/DaemonAddr',
        WithDecryption=True
    )
    
    daemon_addr = parameter['Parameter']['Value']
    os.environ['DAEMON_ADDR'] = daemon_addr
    return daemon_addr

# Segments and subsegments
@app.before_request
def begin_segment():
    segment = xray_recorder.begin_segment(name=request.host, traceid=request.headers.get('X-Amzn-Trace-Id'))
    g.segment = segment

@app.after_request
def end_segment(response):
    segment = getattr(g, 'segment', None)
    if segment:
        segment.put_http_meta('request', {
            'url': request.url,
            'method': request.method,
            'user_agent': request.headers.get('User-Agent')
        })
        segment.put_http_meta('response', {
            'status': response.status_code
        })
        xray_recorder.end_segment()
    return response

def begin_subsegment(name, method, url, status):
    subsegment = xray_recorder.begin_subsegment(name=name)
    subsegment.put_http_meta('request', {
        'method': method,
        'url': url
    })
    subsegment.put_http_meta('response', {
        'status': status
    })
    return subsegment

def end_subsegment(subsegment, status, error=None):
    if error:
        subsegment.add_exception(error)
    subsegment.put_http_meta('response', {
        'status': status
    })
    xray_recorder.end_subsegment()

def update_state(status, error):
    segment = getattr(g, 'segment', None)
    if segment:
        segment.put_http_meta('response', {
            'status': status
        })
        if error:
            segment.add_exception(error)

@app.route('/')
def index():
    with xray_recorder.in_segment('index_segment') as segment:
        segment.put_metadata('method', request.method)
        segment.put_metadata('url', request.url)
        return 'Hello, X-Ray!', 200

@app.errorhandler(500)
def handle_500_error(error):
    segment = getattr(g, 'segment', None)
    if segment:
        update_state(500, error)
    return str(error), 500

if __name__ == '__main__':
    app.run(debug=True)

**Comment by diagutierrezro** [comment]
Se continuará implementación #80

**Comment by JulianAvella** [comment]
Se hace la implementación en la api llamada gestor_documental_mid, y dentro se crea una carpeta xray y dentro tiene dos archivos, uno llamado xray.py que tiene la configuración del sdk de xray y el segundo archivo llamado request_tools.py que tiene las funciones generalizadas para las peticiones http con la llamada del archivo de configuración de xray, entonces para inicializar xray en la api se modifica el archivo de inicio llamado api.py y queda así: import os
from flask import Flask
from conf import conf
from routers import router
from controllers import error
from xray.xray import init_xray
conf.checkEnv()

nuxeo = conf.init_nuxeo()
app = Flask(__name__)

# Inicializamos X-Ray
init_xray(app)

router.addRouting(app, nuxeo)
error.add_error_handler(app)

#print(app.url_map)

if __name__ == '__main__':
    
    #app.debug = True
    app.run(host='0.0.0.0', port=int(os.environ['API_PORT']))

y el archivo llamado document.py que esta dentro de carpeta controllers, el cual hace peticiones http, y se comenta algunas llamadas http y se remplaza por las peticiones con xray del archivo request_tools: la petición get queda así; #res_doc_crud = requests.get(str(os.environ['DOCUMENTOS_CRUD_URL'])+'/documento?query=Activo:true,Enlace:'+uid)
        url = str(os.environ['DOCUMENTOS_CRUD_URL']) + '/documento?query=Activo:true,Enlace:' + uid y la petición post queda así: #resPost = requests.post(str(os.environ['DOCUMENTOS_CRUD_URL'])+'/documento', json=DicPostDoc).content
                resPost = post_json(str(os.environ['DOCUMENTOS_CRUD_URL']) + '/documento', DicPostDoc)

Falta hacer unas pruebas con datos para las peticiones http y si en aws se reconoce la configuración del xray
