### ISSUE TITLE
Iniciar analisis para implementación de multiples firmantes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#71]
Se requiere realizar el analisis inicial para realizar la implementación de multiples firmantes, se debe tener en cuenta que se debe ir almacenando a los firmantes y la firma no se estampará hasta que el último firmante lo haga.

**Sub Tareas**

- [x] Realizar documento donde se especifiquen los cambios tecnicos que se implementarían para ir almacenando las firmas y cuando firme la última persona se obtenga la información de todos los anteriores para realizar la firma final.

**Criterios de aceptación**

- [x] Documento de analisis realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 14/07/24

Se realizan diferentes reuniones tanto con el líder de grupo como con la persona que estuvo a cargo anteriormente del módulo de firma electrónica, para poder definir mejor las estrategias por las cuales se podría abordar este nuevo alcance. Como conclusión de dichas reuniones, se llegó a la conclusión de que lo más óptimo que se puede realizar es relegar la responsabilidad del manejo y la recopilación de los múltiples firmantes a cada sistema/cliente. Esto por las siguientes razones:

- La persistencia de los firmantes y representantes ya es manejada en la base de datos de documentos.
- Cada cliente/sistema define sus propios firmantes y su propio flujo
- El proceso de firma se maneja por estados, a medida que cada persona va revisando el documento para dar su aval el proceso asociado al documento cambia de estado.
- Cuando un documento o proceso está en estado final significa que ya todos los firmantes hicieron la revisión del documento y dieron su aval por lo que se trae su información y se realiza la solicitud
- Los Roles y dependencias no cambian con el tiempo, es decir independientemente del sistema, los cargos, roles y demás información se extraen del mismo lugar.

Así los ajustes necesarios se deben realizar en los clientes de ser necesarios, y se debe verificar que la API de firma electrónica ya maneja múltiples firmantes, por lo cual se procedió a probar y se logró un resultado exitoso:

![Captura de pantalla 2024-07-11 135048](https://github.com/user-attachments/assets/6a2be2c6-a395-4f59-8e0e-58416e6ec622)

 Por lo tanto en cuanto a la API de firma no deben realizarse ajustes por el momento ya que como se evidenció funciona correctamente. 
Por lo tanto queda definido un análisis preliminar que debe dar paso a un análisis más riguroso del flujo de trabajo a seguir para poder implementar los cambios necesarios en los clientes para que manejen los múltiples firmantes
