### ISSUE TITLE
Crear microcliente de mapeo de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#72]
Se requiere realizar la creación del microcliente de mapeo de dependencias que se ubicará en el siguiente [repositorio](https://github.com/udistrital/mapeo_dependencias_mf). Importante que la creación y configuración se realice usando el framework de single spa.

**Sub Tareas**

- [x] Creación y configuración del microcliente (la configuración incluye la conexión con el root).
- [x] Pruebas de funcionamiento del microcliente en ambiente local.
- [x] Documentación del issue con creación, configuración y pruebas realizadas.

**Criterios de aceptación**

- [x] Creación y configuración del microcliente realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Creación de microcliente de mapeo de dependencias.

Se crea la opción en el menú:

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/7f5258e7-656e-4080-b61a-b7119981dbe4)

Se crea la aplicación con single-spa, con la siguiente configuración:

![Image](https://github.com/udistrital/core_documentacion/assets/168471458/a64d4bb7-1927-4b83-9c61-20b88b0f6727)

Se pone en funcionamiento el microcliente:


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/217ae7be-cd90-4174-a510-775f8d51a0f7)

**Comment by xDa04vidx** [comment]
**Se crea pull request**


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/d144b034-7d0b-445b-9e89-7f25668eeaa7)
