### ISSUE TITLE
Crear estructura inicial de mf mapeo de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#73]
Se requiere realizar la creación de la estrucutra inicial del mf de mapeo de dependencias siguiendo los mockups realizados en #33.

**Sub Tareas**

- [x] Realizar estructura inicial del cliente.

**Criterios de aceptación**

- [x] Estructura inicial realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto
Se ha creado la estructura del formulario para la búsqueda de dependencias, junto con la tabla resultante de dicha búsqueda. La tabla incluye paginación y se han añadido iconos para generar y editar el mapeo de dependencias.


![Image](https://github.com/udistrital/core_documentacion/assets/168471458/baa4f744-d74a-4aa1-ad8d-08d8fc17d678)


Además ya se encuentran en funcionamiento las ayudas del tooltip

- Facultades:
  ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/1f66c4c4-94a0-4b5e-b6f3-80c61d694122)


- Nombre dependencia:
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/27de84fa-da18-4153-bd57-6e93a166809d)

- Vicerrectoría:
   ![Image](https://github.com/udistrital/core_documentacion/assets/168471458/9cc1f097-b03d-422f-8719-4d75129c2e2a)

**Comment by xDa04vidx** [comment]
### ESTRUCTURA FINAL

Se logró crear el diálogo o el pop-up para las acciones de editar y crear mapeo.

Después de realizar un análisis junto a @diagutierrezro, se concluyó que es más eficiente crear un solo componente para generar y editar mapeo, dado que el formulario es el mismo y se envía la información del ítem que se está seleccionando.

En este caso, se utilizaron las dependencias de la facultad de teatro y música como dependencias académicas, y las dependencias de la facultad de pintura y danza como dependencias administrativas, para cumplir con los casos dados.

**ACADÉMICO**
- GENERAR MAPEO 
![Image](https://github.com/user-attachments/assets/f213822e-fb24-4286-b590-718f6c19ed22)

- EDITAR MAPEO
![Image](https://github.com/user-attachments/assets/b90215d4-ac9b-41fb-8dc4-5068f58c0b1c)

**ADMINISTRATIVO**
- GENERAR MAPEO
![Image](https://github.com/user-attachments/assets/7417bda8-1177-4e69-88ac-0395e7e343fd)

- EDITAR MAPEO
![Image](https://github.com/user-attachments/assets/a4ec5abf-8908-40fa-b460-1c1718f83b30) 

**TOOLTIP**
Además se crearon las ayudas para los campos de número de identificación interno y código SNIES.

- Número de identificación interno
![Image](https://github.com/user-attachments/assets/69691c45-1a35-4b8b-88ed-d40aa6aa7431)

- Código SNIES
![Image](https://github.com/user-attachments/assets/636291d1-613c-47c7-8084-8501423438a9)

Se ubicaron los mensajes en la parte izquierda del botón de ayuda, ya que en pantallas más pequeñas, los mensajes se muestran de manera más adecuada en esta posición.
