### ISSUE TITLE
Realizar ajustes de hallazgos en pruebas de carga y seguridad

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#74]
Se requiere realizar los ajustes solicitados despues de la realización de pruebas de carga y seguridad, se requiere actualizar el README del cliente de verificación, usar como guia el creado en el siguiente [repositorio](https://github.com/udistrital/oikos_root_mf/tree/feature/creacion_root).

**Sub Tareas**

- [x] Ajuste del README para cliente de verificación siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md).

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/07/2024

Se realiza el ajuste al Readme del cliente de verificación para mostrar la información pertinente del proyecto, procurando también que dicho Readme cumpla con los lineamientos:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/8625764f-a25c-43fd-8078-e90f2f07a47a)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/6e69c6d6-61ec-4571-ba48-03b4fbf8b0b9)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/5ff54f45-4fab-42e9-89eb-9d15438f629b)

**Comment by diagutierrezro** [comment]
Buen trabajo Andres, se cierra issue.
