### ISSUE TITLE
Analizar cliente de evaluación para implementación de firma electronica en módulo de certificaciones.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#75]
Se requiere realizar el analisis de como implementar la firma electronica en el módulo de certificaciones, para esto es necesario clonar el [repositorio](https://github.com/udistrital/evaluacion_cliente/tree/develop) y ejecutar el cliente para familiarizarse con el funcionamiento y realizar el respectivo análisis.

El link del cliente en ambiente de pruebas es https://pruebasevaluacion.portaloas.udistrital.edu.co/

**Sub Tareas**

- [x] Clonar repositorio de evaluacion_cliente.
- [x] Ejecutar el proyecto y familiarizarse con el cliente.
- [x] Realizar análisis de como implementar la firma electrónica en el módulo de certificaciones y documentar los cambios a realizar em el issue.

**Criterios de aceptación**

- [x] Ejecución y familiarización del proyecto realizada.
- [x] Análisis de implementación de firma electrónica realizada.
- [x] Documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 08/07/24

Se descarga el repositorio de evaluacion_cliente y se intenta hacer correr:

Al ejecutar el npm install arrojaba un error de que python2 no se encontraba en PATH. Al instalarlo se vuelve a correr el npm install y contrario a lo que dice el readme, por defecto el proyecto usa el angular 7.3.10 (se probó con angular 8 como dice el readme y angular 8.3.29 y con ninguno funcionó)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/e0eaade4-7cfb-413b-82fa-9ee5480adf72)

Por lo tanto se usó el angular 7.3.10 para este proyecto, finalmente se realiza el ng serve y el servicio se ejecuta y funciona por lo menos en un vistazo superficial:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/0885638a-02c1-415f-95d5-73d1e5e23c6d)
![image](https://github.com/udistrital/core_documentacion/assets/77305100/b873367e-2fcc-4cc6-8a11-bfda51908fec)

Queda pendiente revisar más a fondo el funcionamiento del cliente en ejecución y realizar el análisis pertinente para la implementación de firma electrónica

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 09/07/24

Se realiza el análisis correspondiente al cliente de evaluación en el apartado de la implementación de la firma electrónica.

Se logró identificar que en la ubicación del proyecto **src/app@core/utils** se encuentra un archivo llamado **gestor-documental.service.ts** que se encarga de manejar los diferentes endpoints a los métodos de gestor documental mid. Dentro de este se encuentra el método **uploadFilesElectronicSign** el cual se encarga de apuntar al método de gestor documental mid que se encargaba de la firma electrónica. Por tanto es este método el que se debe ajustar.

Sin embargo, por buenas prácticas no sería correcto apuntar a un endpoint de otro mid (firma electrónica mid) dentro del service de gestor documental, por lo que sería necesario crear otro service para alojar el endpoint de firma electrónica y así poderlo referenciar en los archivos que estén utilizando dicho método, estos archivos son:

- crear-certificacion.component.ts
- crear-certificacion-sin-novedades.component.ts
- realizar-evaluacion.component.ts

Una vez realizados estos cambios se debe probar que en efecto se esté manejando correctamente la firma electrónica.

**Comment by diagutierrezro** [comment]
Buen análisis, la implementación se realiza en otro issue.
