### ISSUE TITLE
Realizar cambio de firma electronica en cliente de evaluación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#76]
Se requiere realizar el cambio de firma electrónica según lo analizado en #75 donde se debe modificar la firma electronica para que se haga mediante el Api de firma_electronica_mid, tener presente que el comportamiento del cliente no se debe modificar. El certificado que se va a modificar es el que se genera para CPS que se accede en el menú de certificaciones.

**Sub Tareas**

- [x] Cambio a cliente de verificación para firma electrónica.
- [x] Prueba de funcionamiento correcto con la nueva firma electrónica.

**Criterios de aceptación**

- [x] Cambio a cliente realizado.
- [x] Prueba de funcionamiento realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 09/07/24

Se realiza la implementación de firma electrónica en el cliente de verificación:

Primero que todo se creó en el directorio **src/app@core/utils** un nuevo service llamado **firma_electronica.service.ts** el cual aloja dos métodos:

## fileToBase64: 
Se encarga de convertir un archivo a base 64:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/ae6cbc04-1a1c-49bf-84e5-ad8fd64dcb89)

## uploadFilesElectronicSign: 
Se encarga de apuntar al endpoint de firma electrónica mid que se encarga de la generación y estampado de la firma

![image](https://github.com/udistrital/core_documentacion/assets/77305100/d2cc93a8-c657-4eb1-8126-f8df7c309a15)

También se agregó una variable de entorno que apunta a firma electrónica mid:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/392947a8-8342-4ae7-967c-73a4cbbd98d5)

También se realizaron las respectivas referencias a este nuevo endpoint en los archivos **crear-certificacion.component.ts**, **crear-certificacion-sin-novedad.component.ts** y **realizar-evaluacion.component.ts**, en cuyo caso para todos, los cambios son los mismos:

1. Se hace un import:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/940d4dc1-5d61-4308-a028-4334466a7484)

2. Se crea una variable privada en el constructor:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/68589cb7-c80c-448e-bf0a-2749046ffae8)

3. Se reemplaza objeto de gestor por el de firma:
![image](https://github.com/udistrital/core_documentacion/assets/77305100/f577c2b6-2bb3-49c1-adb9-bcffd539200e)

Por lo tanto el cliente funcionando queda de la siguiente manera:

![image](https://github.com/udistrital/core_documentacion/assets/77305100/b310a75e-5029-4331-9916-362caf7555db)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/8e9be760-37d5-43b6-9e0f-52b291428b46)

![image](https://github.com/udistrital/core_documentacion/assets/77305100/87b85319-2399-4f02-8367-7853aa84ce2d)

**Comment by diagutierrezro** [comment]
Queda pendiente el envío a ambiente de pruebas ya que falta aprobación por unos cambios anteriores que habían en el cliente.
