### ISSUE TITLE
Iniciar investigación para implementar visualización en forma de organigrama para las dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#77]
Se requiere realizar una investigación inicial para poder implementar la visualización en forma de organigrama de las dependencias para el mf de creación y gestión de dependencias, revisar si la libreria **ngx-org-chart** puede servir para la implementación, es posible que toque realizar un tratamiento de datos para que estos lleguen en cierto formato pero esto se realizaría en el mid.

**Sub Tareas**

- [x] Analisis para realizar implementación de visualización de organigramas.
- [x] Documentar en el issue las posibilidades encontradas con los detalles que implicaría cada una.

**Criterios de aceptación**

- [x] Analisis realizado.
- [x] Investigación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Investigación
Se encuentran 2 herramientas con las cuales se pueden realizar el organigrama, el analisis se encuentra en el siguiente documento

- PDF
[Investigación organigrama.pdf](https://github.com/user-attachments/files/16242214/Investigacion.organigrama.pdf)


- ONEDRIVE
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/davariasc_udistrital_edu_co/EV3GYeYTDrhGjNUbR6bb-cQB1kX-smzab-nKVJ-Qc_lXrQ?e=iznxKL

**Comment by diagutierrezro** [comment]
Buen trabajo David, se tendrá en cuenta esto y se definirá que herramienta usar, esto se trabajará en otras issues.
