### ISSUE TITLE
Ajustes posteriores a pruebas de carga y seguridad - Parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#79]
Se requiere realizar la continuación de los ajustes a los sistemas según lo encontrado en el [informe](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/mfavendannom_udistrital_edu_co/ET1xyPMtyXxLirw-nviG1_IBydviAKtjOGO74ntki8rJew) posterior a las pruebas de carga y seguridad.

Se debe modificar el error a mostrar cuando no se pone el campo de representantes en el json del POST ya que arroja un error 500 y este se asocia a un error del servidor lo cual no aplica para este caso, en el mismo informe se muestra la manera correcta en la que debe responder cuando no hay representantes.

![Image](https://github.com/user-attachments/assets/c9b6f692-7ebd-4015-a6da-321b2b69e8f9)

Por lo que es necesario que cuando no hayan firmantes el error sea similar.

Una vez solucionado el error anterior revisar la configuración de los dominios permitidos en CORS en el api de firma_electronica_mid ya que actualmente permite peticiones de todos los dominios con "*" por lo que se debe restringir para peticiones de dominios que finalicen en **_udistrital.edu.co_**. Tener en mente la posibilidad de manejar por variable de entorno el entorno, es decir, si es desarrollo se puede mantener el * para aceptar cualquier dominio pero si es ambiente de producción que solo acepte el dominio definido.

Tambien se debe corregir el error 500 que se genera cuando llega una firma vacía, en este caso el error debería ser un 400 ya que no es error de servidor.

Finalmente se debe crear un popup para indicarle al usuario que el código es invalido ya que actualmente el cliente se queda estatico cuando la firma no tiene un formato valido.

**Sub Tareas**

- [x] Modificar error al momento de no poner firmantes en el JSON de envío para firma electrónica.
- [x] Modificar dominios aceptados.
- [x] Modificar error al momento de que llega una firma vacía.
- [x] Crear popup para indicar al usuario que ingrese un código valido.
- [x] Pruebas de funcionamiento en local y en ambiente de pruebas, para esto se debe envíar a pruebas los cambios realizados.

**Criterios de aceptación**

- [x] Modificaciones realizadas.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 16/07/24

Se realizan los ajustes descritos:

Primero se realizan las correcciones de los códigos 500. Primero en la ausencia de firmantes en la API mid firma electrónica, para lo cual se corrigió la excepción de dicho caso que no estaba retornando correctamente el código 400, por lo tanto ahora quedó funcional:

![Captura de pantalla 2024-07-15 205538](https://github.com/user-attachments/assets/9f5ddef2-ba82-44d4-b0dc-c2893301f63b)

También se ajustó de una vez el código 500 que generaba el cliente de verificación cuando se enviaba un Json con la firma vacía:

![Captura de pantalla 2024-07-15 205529](https://github.com/user-attachments/assets/e175937d-6e5b-4c53-8802-a6949376b988)


También se realizaron los cambios al CORS utilizando una variable de entorno la cual es la siguiente:

![image](https://github.com/user-attachments/assets/2eab1503-6864-410b-8dcc-323083534e45)

Y los cambios al manejo de los dominios es el siguiente:

![image](https://github.com/user-attachments/assets/decd6dfe-014d-457d-8019-f8a2995fc8bd)

Queda pendiente verificar si estos últimos cambios funcionan

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 17/07/24

Se realiza pull request de los cambios hechos el día anterior. Queda pendiente verificar el funcionamiento correcto de los cambios en el CORS y además actualizar este Issue con las tareas de los errores 500 del cliente de verificación, la agregación de un pop up que indique que la firma digitada debe ser válida y la modificación de los endpoints

**Comment by Skyrus1203** [comment]
### ACTUALIZACION 18/07/24

Se dejan evidencias de la creación de pop up y se realiza el pull request para verificar funcionamiento de lo realizado en ambiente de pruebas:

![image](https://github.com/user-attachments/assets/636d26ea-a85a-47a4-8cd2-796a4f19c178)

**Comment by diagutierrezro** [comment]
Se validan los cambios realizados, muchas gracias Andres.
