### ISSUE TITLE
Realizar cambio de versión de Oikos en cliente de novedades

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#8]
Se requiere realizar el cambio de versionado en el cliente de novedades y posteriormente realizar las respectivas pruebas para comprobar que el sistema sigue funcionando correctamente.

**Sub Tareas**
- [x] Realizar el cambio de versión de Oikos en el cliente de novedades.
- [x] Realizar prueba completa del sistema para comprobar que funciona correctamente.

**Criterios de aceptación**
- [x] Cambios de versión de Oikos realizado.
- [x] Pruebas realizadas documentadas.

**Requerimientos**
No aplica

**Dependencias**
Por desconocimiento del funcionamiento del cliente de novedades se solicitará reunión con el último desarrollador que trabajó con este cliente para que nos colabore con la realización de las pruebas, por lo que la finalización de este issue está sujeta a disponibilidad de el.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
**Pruebas del cambio de versiones**
En una reunión pactada entre Diego Alejandro Gutierrez, Youssef Alejandro Ortiz (Especialista en el cliente de necesidades), y David Arias, se llegaron a las siguientes conclusiones:

- La única tabla a la que hacen referencia las solicitudes en el cliente, dentro de la base de datos de Oikos, es "dependencia".
- Al analizar las respuestas entre las distintas versiones de las búsquedas que se realizan dentro del cliente, se observa que no hay cambios significativos entre ellas. En esencia, ambas versiones ofrecen lo mismo, con la diferencia de que la v2 incluye campos parametrizados como "activo", "fecha de modificación" y "fecha de creación".
- Se llevaron a cabo pruebas de funcionamiento del cliente y no se encontraron inconvenientes.

La grabación de la reunión se encuentra en el siguiente link:
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/diagutierrezr_udistrital_edu_co/EU_JOdiONFNOqgUltAuZQSYB_dnlnvxU531uQNWfjR5TLw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view
