### ISSUE TITLE
Realizar implementación inicial para visualización de organigramas de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#81]
Se requiere realizar la implementación inicial de la  herramienta definida **(Organization Chart)** según lo analizado en #77 para visualizar los organigramas de las dependencias, inicialmente se plantea manejar datos de pruebas en el cliente para probar la visualización y mas adelante se realizará la lógica para hacer el tratamiento de datos y recibir los datos como se esperan.

**Sub Tareas**

- [x] Realizar esquema inicial para visualización de organigrama.

**Criterios de aceptación**

- [x] Esquema inicial de organigrama realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Adelanto
**Visualización**
Se logra crear los organigramas para esta sección, utilizando la libreria [organizationChart](https://primeng.org/organizationchart) 
![Image](https://github.com/user-attachments/assets/89d9bd0b-92b0-4796-bd3d-e6800441223c)

Se generan tres organigramas idénticos (General, Académico y Administrativo) para facilitar la visualización de cada uno de ellos.

- General
![Image](https://github.com/user-attachments/assets/d225fb33-c076-4eb8-aa7a-79d1f8abdc8f)

- Academico
![Image](https://github.com/user-attachments/assets/1005a09a-750f-45bc-a395-333dfdaf1280)

- Administrativo
![Image](https://github.com/user-attachments/assets/d659059c-1aa3-4b48-aedb-fbb6fe63c7b3)

**Estructura de datos**
Se ha creado una lista preliminar de dependencias que se procesa para generar el organigrama. A continuación, se detalla esta lista:

```bash
dependencias = [
    {
      dependencia: "Consejo Superior Universitario",
      tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL",
      hijos:[
        {
          dependencia:"Consejo Academico",
          tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL"
        },
        {
          dependencia:"Consejo Participacion Universitaria",
          tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL"
        },
        {
          dependencia:"Consejo Gestión Institucional",
          tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL"
        },
        {
          dependencia:"Rectoria",
          tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL",
          hijos:[
            {
              dependencia:"Oficina Control Interno",
              tipo: "GESTION DE EVALUACION Y CONTROL"
            },
            {
              dependencia:"Oficina Control Interno Disciplinario",
              tipo: "CONTROL DISCIPLINARIO"
            },
            {
              dependencia:"Oficina Asesora Planeacion",
              tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL"
            },
            {
              dependencia: "Oficina Asesora Tecnologías e Información",
              tipo: "GESTION DE LOS SISTEMAS DE INFORMACION Y LAS TELECOMUNICACIONES"
            },
            {
              dependencia: "Secretaria General",
              tipo: "PLANEACION ESTRATEGICA E INSTITUCIONAL",
              hijos:[
                {
                  dependencia: "Oficina Asesora Juridica",
                  tipo: "GESTION JURIDICA"
                },
                {
                  dependencia:"Programa Quejas, Reclamos y Atención al Ciudadano",
                  tipo: "SERVICIO AL CIUDADANO"
                },
                {
                  dependencia:"Proyecto Actas, Archivo y Microfilmacion",
                  tipo: "GESTION DOCUMENTAL"
                }
              ]
            },
            {
              dependencia:"Programa Relaciones Internacionales e Interinstitucionales",
              tipo:"INTERINSTITUCIONIZACION E INTERNACIONALIZACION"
            }
          ]
        }
      ]
    }
  ]
```

Esta lista de diccionarios consta de dos elementos obligatorios: 'dependencia', que incluye el nombre de la dependencia, y 'tipo', que especifica el tipo asociado. El tipo se define para implementar estilos distintos en los nodos del organigrama. El tercer elemento son los 'hijos', donde cada hijo sigue la misma estructura que su padre.

**Comment by xDa04vidx** [comment]
### Problemas
Actualmente se esta enfrentando un problema con las líneas conectoras del organigrama, las cuales están siendo generadas por la implementación de la librería. Se esta trabajando en la solución de este error.

**Comment by xDa04vidx** [comment]
**Se crea pull request**
![image](https://github.com/user-attachments/assets/2af320b7-5c74-4f84-b34c-c4ce7a512f57)

**Comment by diagutierrezro** [comment]
Queda pendiente por aprobar el PR, gracias David.
