### ISSUE TITLE
Revisión documento depreciación de API´s

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#82]
Se requiere realizar la revisión del documento relacionado con la depreciación de API´s con el fin de depurar la información requerida

**Sub Tareas**

- [x] Revisar cada API y generar el comentario según cada caso

**Criterios de aceptación**

- [x] Documento de depreciación actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se actualiza el [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EfZVSP1VSotOjJwh1-k4XvgBi2Gs7G8t5gV2PZwcBKeEGg?e=tUDMyy) de inventario de Apis para depreciar.

Inicialmente se revisa Apis que se encuentren en el listado que no deban ser depreciadas encontrado core_amazon_crud tanto en pruebas como en producción el cual se usa para el aplicativo de resoluciones V2.

**Comment by diagutierrezro** [comment]
Se realiza reunión de depreciación de Apis donde se revisan proximas Apis a ser depreciadas, se define preguntar a los encargados de SGA por algunas Apis para asegurarse por completo de que pueden ser depreciadas, finalmente se acuerda que se realizarán reuniones la semana siguiente para depreciar algunas Apis de SGA y KRONOS

**Comment by jcmurilloa** [comment]
Buen trabajo @diagutierrezro. Según la reunión desarrollada, por favor en sesión SOS posterior, generar los respectivos comentarios derivados de esta reunión, para evaluar la respectiva asignación de issues en los siguientes sprint.
