### ISSUE TITLE
Agregar lógica para registro de dependencias - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#83]
Se requiere realizar la fase inicial de la adición de la lógica para el registro de dependencias, inicialmente se obtendrá la información de los tipos de dependencia y las dependencias para poner la información en los respectivos seleccionables.

**Sub Tareas**

- [x] Llenar desplegable de tipos de dependencias.
- [x] Llenar desplegable de dependencias con la información de dependencias activas.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Desplegables con información correcta.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Resumen de la tarea
Se utiliza como base el microcliente de [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf), para poder realizar las consultas, por ello se crean dos archivos para realizar peticiones:

- requestManager.ts 
![Image](https://github.com/user-attachments/assets/fabfba5c-80ad-45a6-940c-d307600527de)
- errorManager.ts
![Image](https://github.com/user-attachments/assets/86a9cae9-363d-4d83-9823-f916502c49bb)

Despues se realiza el servicio de oikos, en este caso se crea el archivo de oikosService
![Image](https://github.com/user-attachments/assets/b0f5b503-37cc-44c1-a31e-c85209cd9a14)

Con este archivo, se puede reutilizar las peticiones a oikos en las diferentes vistas.

La variable de entorno que se utiliza para las peticiones viene dada por
```bash
OIKOS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/oikos_crud_api/v2/'
```

Por ultimo se realizan las respectivas peticiones a las tablas de  dependencias y tipo_dependencia de la base de datos de oikos.

Se observa un correcto funcionamiento en la vista:

- Dependencia asociada
![Image](https://github.com/user-attachments/assets/c54de50d-e91b-4363-a5b0-644a1a79ccc6)
Para este resultado el query viene dado por:
```bash
dependencia?query=Activo:true&limit=-1
```

- Tipo dependencia
![Image](https://github.com/user-attachments/assets/56f0dea7-40ec-47aa-81ac-d7d3817c00ce)
Para este resultado el query viene dado por:
```bash
tipo_dependencia
```

**Comment by diagutierrezro** [comment]
Gran trabajo David, se continuará la implementación de lógica en un nuevo issue.
