### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de entrega de implementación de firma electrónica en certificaciones CPS con funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#84]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de entrega de implementación de firma electrónica en certificaciones CPS con funcionamiento

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha contactado con la persona a cargo de funcionamiento , se espera poder obtener respuesta

**Comment by mantnicot** [comment]
Se ha podido obtener respuesta y se realizara la reunión el día 29/07/2024 a las 10 am , se agendará el día de mañana

**Comment by mantnicot** [comment]
Se ha agendado la reunión

[Link de reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2IyOWVhMDQtNmExMi00YTVmLWFmODgtYWZhM2QxZjQ0ZmNk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha podido realizar la reunión con funcionamiento y se han dado comentarios positivos con el recibimiento de la implementación, se agrega el link de la reunión junto con el acta de entregables 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2IyOWVhMDQtNmExMi00YTVmLWFmODgtYWZhM2QxZjQ0ZmNk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)


[Issue de acta de entregable](https://github.com/udistrital/core_documentacion/issues/67)

**Comment by jcmurilloa** [comment]
Relacionando la grabación en el acta de entregables, se queda a la espera de la recolección de firmas por parte de los asistentes a la reunión, así como una sesión de muestra con la dirección de contratación. Buen trabajo @mantnicot.
