### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento con responsable SGA en funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#85]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con responsable SGA en funcionamiento

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha intentado realizar el contacto con el responsable desde el día 19/07/2024, a lo cual se responde 



![Image](https://github.com/user-attachments/assets/65775291-10ed-494f-978a-665c296b3b0f)

Ya que se nota que hay poco espacio en la agenda se sigue comentando , buscando el espacio 


![Image](https://github.com/user-attachments/assets/8297958f-9a96-4489-83fe-8ef9bb695932)

en esta búsqueda , dispone un espacio inmediato pero no se puede realizar la reunión por cuestiones de reuniones dele quipo y se sigue buscando el espacio , pero no hay respuesta hasta el día de hoy 24/07/2024




![Image](https://github.com/user-attachments/assets/d0fd8511-ec17-4878-8bdb-e7876270ebf8)

**Comment by jcmurilloa** [comment]
Por favor seguir intentando la concertación de la reunión con el responsable @mantnicot, en caso de no recibir respuestas, continuar registrando la evidencia de la gestión en esta issue.

**Comment by mantnicot** [comment]
Se ha intentado gestionar espacios con la persona , pero solo escribe cuando esta sobre tiempo y no es posible organizar los espacios , por lo cual se sigue intentando poder organizar con tiempo o que se pueda sobre el tiempo cuando el lider , el analista y la persona puedan reunirse 



![Image](https://github.com/user-attachments/assets/6f19f805-89df-4fe7-adf4-502ecc9b65c1)

**Comment by jcmurilloa** [comment]
Teniendo en cuenta lo sustentado, se generará contacto con el patrocinador del proyecto para lograr generar la interacción requerida con el responsable

**Comment by mantnicot** [comment]
Se ha generado el acta , se espera aprobación del gerente para su envio a firmas

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ebg1rxavVqNCtW82Lj00BuQBnxR2eRQ5gjuDQ2f-PMkpNA?e=US7mdh)

**Comment by jcmurilloa** [comment]
Tras unas pqeueñas modificaciones realizadas de mi parte, se da VoBo para recolección de firmas.

**Comment by mantnicot** [comment]
Se ha recolectado todas las firmas del acta

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXHK1zOL_JNKoyjPJlhcDL8BzNjWNWwMTGtLfcxOEklQaw?e=mbX9ED)

**Comment by jcmurilloa** [comment]
Excelente @mantnicot!
