### ISSUE TITLE
Ajustes posteriores a pruebas de carga y seguridad - parte 3

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#86]
Se requiere realizar la revisión final de los ajustes solicitados por pruebas de carga y seguridad, estos cambios son el análisis de dependencias que puedan ser actualizadas y finalmente realizar las pruebas de funcionamiento del cambio realizado de CORS.

**Sub Tareas**

- [x] Ajustar bugs y code smells mostrados en analisis de sonarqube en el [informe](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/mfavendannom_udistrital_edu_co/ET1xyPMtyXxLirw-nviG1_IBydviAKtjOGO74ntki8rJew?e=pGysxj).
- [x] Realizar pruebas de funcionamiento correcto de restricción de dominios en CORS.

**Criterios de aceptación**

- [x] Bugs y code smell solucionados.
- [x] Pruebas de CORS realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Dependencias**

Por parte de @diagutierrezro se deben solicitar el cargue de las nuevas variables de entorno de ENVIRONMENT para funcionamiento de CORS

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 23/07/24

Se realiza el ajuste de la gran mayoría de los bugs y code smells detectados por sonar Qube, en total estos fueron los archivos modificados:

![image](https://github.com/user-attachments/assets/4205d414-978b-4d31-bf88-927ac47c47b9)

Estos archivos cubren casi la totalidad de los bugs exceptuando los relacionados a Nebular ya que estos se deben a que el sonar qube no se configuró para detectar los componentes de Nebular como válidos. Y en cuanto a los code Smell quedan pendientes dos por las siguientes razones:

![image](https://github.com/user-attachments/assets/0514ceb6-6eba-441a-a8bc-da2cfcc325f6)

Este css de load.components.scss que está ubicado en src/app/@core/load tiene unos estilos duplicados sin embargo el contenido es distinto y ya que el linter no permite que los atributos se repitan bajo un mismo estilo se dejó como estaba hasta determinar cual de los dos debe mantenerse o si se debe dejar inmutado.

Luego está el archivo src/app/@core/data/models/configuracion_crud.ts en el cual sonar qube dice que la variable Menu ya fué declarada indicando que se está asignando dos veces, sin embargo no se logró identificar en que parte del código esto sucede:

![image](https://github.com/user-attachments/assets/7ce4e2cf-59cd-4f89-b65d-d09ee1efc820)
![image](https://github.com/user-attachments/assets/eacecef8-5f0d-490c-910a-69f64b078634)
![image](https://github.com/user-attachments/assets/6aca490b-ac90-43a2-add6-c0e87881b288)

Como se ve, sólo está presente al hacer el export enum y el export class menu por lo que al no estar seguro de como proceder se dejó un comentario //NOSONAR hasta que se confirme que es un falso positivo o se determine que cambio debe hacerse, se hizo el respectivo pull request de los avances

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/07/24

Se terminan de cerrar los dos code smell pendientes. El tema de configuracion_crud.ts se tomó como un falso positivo y el tema de load.component.scss se manejó de la siguiente manera:



![Image](https://github.com/user-attachments/assets/4405cda9-7d87-4ea1-b33a-18978ddf2fc8)

ASí se unifican estilos por lo que solo queda pendiente probar el funcionamiento del CORS

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/07/24

Se realizan las pruebas del funcionamiento del filtro del CORS utilizando el cliente de verificación en loca es decir con la siguiente url :
![image](https://github.com/user-attachments/assets/c8352503-9372-4c69-8ff2-cfbb42379403)


1. Con la variable de entorno seteada para que deje pasar cualquier url:

![image](https://github.com/user-attachments/assets/073d3bb8-d7a6-4667-9f84-80dbb280cc94)


2. Con la variable de entorno seteada para que sólo deje pasar dominios udistrital:

![image](https://github.com/user-attachments/assets/8b1a9723-8e43-4045-acd4-80a33a18daf0)

![image](https://github.com/user-attachments/assets/939a8f93-1716-4fc5-b780-414042156b12)


Por lo tanto se comprueba el funcionamiento correcto del filtro y se pasa a in review

**Comment by diagutierrezro** [comment]
Se realizará reunión con Maria Fernanda para comentarle los bugs referentes a etiquetas de nebular que se muestran en el sonarqube y para mostrarle las demás correcciones realizads. Muy buen trabajo Andres.
