### ISSUE TITLE
Iniciar pruebas de implementación de X-Ray en Api de gestor documental.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#87]
Se requiere realizar las pruebas de implementación de lo desarrollado en #80 donde se use el SDK y los request creados, inicialmente se realizará la implementación en el Api de [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid), por favor documentar todo lo que vaya surgiendo.

**Sub Tareas**

- [x] Realizar pruebas de implementación del SDK y request en el Api definida.
- [x] Documentar todo lo que suceda en dichas pruebas (sea exitoso o un error).

**Criterios de aceptación**

- [x] Pruebas de implementación realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Cuando se ejecuta la api de gestor documental con la implementación de xray salen los siguientes errores: 
<img width="715" alt="image" src="https://github.com/user-attachments/assets/866019ac-ea7f-425a-a44a-1bf89de84bbc">
Estos errores no salen cuando se ejecuta la api sin la implementación

**Comment by JulianAvella** [comment]
Por el anterior error las peticiones no funcionan porque la api no se ejecuta: 
<img width="659" alt="image" src="https://github.com/user-attachments/assets/d58893e6-ffa7-48b9-8a41-86f491bf8d42">

**Comment by JulianAvella** [comment]
Ya fue solucionado los errores anteriores y tengo un error para la configuración e iniciar la sesión de aws: 
<img width="596" alt="image" src="https://github.com/user-attachments/assets/93192c7a-bc10-40b0-86c4-a3daf757e7ea">

**Comment by JulianAvella** [comment]
Petición http get con integración del sdk de xray: 
<img width="656" alt="image" src="https://github.com/user-attachments/assets/22ac78e0-8437-4ab8-8fff-e6f2d9cd4457">
<img width="914" alt="image" src="https://github.com/user-attachments/assets/4d11e4b5-cfa0-4dc4-abd6-a4dfbf46c7b8">

Petición http post con integración del sdk de xray: 
<img width="640" alt="image" src="https://github.com/user-attachments/assets/e1f083a7-72b4-481e-b78d-c47dd75a335f">
<img width="914" alt="image" src="https://github.com/user-attachments/assets/f3348ca2-2985-4ed1-a8ae-9422158a7040">

**Comment by JulianAvella** [comment]
Implementación del sdk de x-ray en la api gestor_documental_mid:
<img width="602" alt="image" src="https://github.com/user-attachments/assets/17c35721-5e63-42db-9a82-432057a6ae60">

**Comment by diagutierrezro** [comment]
Gracias Julian, unicamente falta el metodo de PUT por ser implementado, se asumirá en otro issue.
