### ISSUE TITLE
Agregar lógica en el mid para registro de dependencias

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#88]
Se requiere finalizar la implementación de la logica iniciada en #83, se debe crear una nueva Api mid para realizar el registro de la dependencia agregando la información correspondiente en la tabla dependencia, dependencia_padre y dependencia_tipo_dependencia la cual se manejará desde un mid a traves de una transacción.

**Sub Tareas**

- [x] Crear estructura inicial del mid, importante tener versión 1.18 de GO para la compatibilidad con X-Ray.
- [x] Crear controlador para la transacción de la creación de la dependencia, se puede usar como guia las transacciones realizadas en [polux_mid](https://github.com/udistrital/polux_mid/blob/master/helpers/tr_solicitud.go).
- [x] Crear servicio para manejar la lógica requerida en la transacción.
- [x] Probar funcionamiento de la transacción, incluidos los rollback.

**Criterios de aceptación**

- [x] Estructura inicial del mid creada.
- [x] Controlador creado.
- [x] Servicio creado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Endpoint creado

Se crea la lógica para realizar la petición de crear una nueva dependencia,  con su correspondiente relación con las tablas dependencia_tipo_dependencia y dependencia_padre. 

**Endpoint en funcionamiento**
Se debe apuntar al endpoint gestion_dependencias_mid/RegistrarDependencia, esta solicitud de manera exitosa tendrá la siguiente respuesta 
![Image](https://github.com/user-attachments/assets/14d27a0d-fe00-43e3-bfd6-5df87b31decf)

**Manejo de errores**
Se crea una lógica en cascada en donde si algo falla se mostrara el mensaje de error correspondiente al fallo. Existen varios puntos de posibles errores:

- Cuando no exista el tipo de dependencia solicitado, se mostrara un 404 con el mensaje de "No se encontró el tipo de dependencia".
- Cuando no exista la dependencia asociada, se mostrara un 404 con el mensaje "no se encontró la dependencia asociada"
- Cuando no se puedan crear los registros de dependencia, dependencia_tipo_dependencia y dependencia_padre, en estos casos se mostrara un 404 con el mensaje del error correspondiente a la petición de creación.

**Rollbacks**
Se crearon 3 rollbacks, uno para borrar el registro creado de la dependencia, el siguiente para el registro de dependencia_tipo_dependencia y el ultimo para el registro de dependencia_padre. 
Para mostrar su funcionamiento se modifica el endpoint y se ponen los ids de los registros creados, y se llama el ultimo rollback que anida los otros.


![Image](https://github.com/user-attachments/assets/875488eb-7820-4e50-97c4-2e105bd5b3c3)

y se comprueba al hacer las búsquedas individuales

- Dependencia
![Image](https://github.com/user-attachments/assets/0ce31de5-a9aa-475f-9572-daebcc5db1cc)

- Dependencia_tipo_dependencia
![Image](https://github.com/user-attachments/assets/bfa9f426-aaf3-4e6f-8bc3-72fe56038a37)

- Dependencia_padre
![Image](https://github.com/user-attachments/assets/c5fc1b37-c88c-49ed-9c98-6e8661d26c19)

**Nota**
Se mantienen los prints para que se pueda saber cuales registros se crearon.

**Comment by diagutierrezro** [comment]
Se debe realizar implementación en otra issue, buen trabajo.

**Comment by xDa04vidx** [comment]
### Pull request
Se crea pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)

![Image](https://github.com/user-attachments/assets/0e11be9a-1883-4827-b93b-87fd80a6fa03)
