### ISSUE TITLE
Ajustar metodo de firma electronica para cambios posteriores en verificación

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#89]
Se requiere realizar los cambios de la firma electronica según lo acordado con Maria Fernanda donde se define modificar el proceso de la firma electronica con los siguientes cambios:
- El documento ya no se aplanará debido a que con la verificación por llaves se puede verificar que le documento no se haya modificado.
- Anterior a realizar la firma electronica se agregará en el documento a firmar la estampa con la información de la firma (firmantes, representantes, tipo documento, código).
- Posterior a la estampa se realizará el proceso de firma electronica donde se crearán las llaves y la firma como tal.

**Sub Tareas**

- [x] Realizar el proceso de estampa antes de la firma electrónica.
- [x] Realizar el proceso de firma electronica.
- [x] Eliminar el paso de aplanado del documento.
- [x] Probar funcionamiento correcto de la firma.

**Criterios de aceptación**

- [x] Cambios al proceso de firma realizados.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 24/07/24

Se realizan los ajustes iniciales en firma para poder cambiar la verificación posteriormente:

1. Se logra estampar antes de firmar:

![image](https://github.com/user-attachments/assets/00052c40-f5af-4e8a-9e15-32d65639e1be)

Para esto se necesitó crear en documentosCrud un endpoint para poder actualizar el registro de la firma ya que es necesario el id del registro en BD de la firma para poder estampar el documento. Si bien el modelo ya estaba creado el método, en el controlador fué necesario crear el endpoint así:

![image](https://github.com/user-attachments/assets/c9a1c02d-0266-4435-9051-973ec474f813)

De esa forma se puede crear un registro inicial en la tabla de firma_electronica que retorne el id sin necesidad de tener llaves ni código de autenticidad desde el inicio. Posteriormente cuando ya se tienen estos datos se actualiza el registro:

![image](https://github.com/user-attachments/assets/f12b5c35-3e45-494d-aec7-3ac78b322dbb)

2. El proceso de firma electrónica se realiza común y corriente

![image](https://github.com/user-attachments/assets/01b35a04-4040-4aff-ada9-c4e093402a30)

![image](https://github.com/user-attachments/assets/82c1ac23-0913-419d-8342-5aef93b51140)

3. El documento ya no se aplana y ahora tanto el id de la firma como el enlace a verificación se estampan de una vez, reduciendo el número de pasos y pdfs temporales que el sistema genera:

![image](https://github.com/user-attachments/assets/6939b436-4daf-4627-b2f1-13aca72edb5c)

![image](https://github.com/user-attachments/assets/2d5ed726-b1b2-41dd-ab80-6e57029d8295)

Por lo tanto se envía a in review este Issue

**Comment by diagutierrezro** [comment]
Aún no se envía el cambio a pruebas debido a que primero se desplegará en producción la versión 1 que fue aprobada por funcionamiento donde aún se aplana el documento.
