### ISSUE TITLE
Agregar lógica para registro de dependencias - Parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#90]
Se requiere implementar la lógica creada en #88 para realizar el registro de una nueva dependencia. Se debe ajustar el json según lo definido en el mid y al presionar el botón "registrar dependencia" se llame a la transacción creada en el mid y se realizacen los respectivos registros en las tablas.

**Sub Tareas**

- [x] Implementación de lógica creada en el mid.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Funcionamiento correcto

Se integra al cliente el funcionamiento del registro de la dependencia.

- Creacion del json para el envio del post
Se crea en el cliente el json para el correcto funcionamiento, se muestra por medio de la consola la creacion correcta.
![Image](https://github.com/user-attachments/assets/982e44b9-dc4c-4ae9-a2cb-3287e6227c7f)

Se comprueba que la dependencia con Id 9 es Secretaria General
![Image](https://github.com/user-attachments/assets/191a73e9-3d5b-436c-9062-88e326c3df29)

Se comprueba que el tipo de dependencia con Id 2 es Facultad
![Image](https://github.com/user-attachments/assets/6b10f108-2b94-45e0-ac35-ff3d95ae6a48)

- PopUp para registro correcto o incorrecto
Se crean los PopUp en la logica para los dos casos
![Image](https://github.com/user-attachments/assets/56154ac7-3b72-4c02-964c-cd53d0a79bcc)

- Envio correcto y prueba creacion 
Se muestra el PopUp correcto para la creacion
![Image](https://github.com/user-attachments/assets/fded42dc-e4e2-4e78-8484-eed0bfcd7059)
y se ve en el mid el correcto funcionamiento
![Image](https://github.com/user-attachments/assets/4cd674fc-abc2-4bf4-a70b-9df1f935a122)
Se verifica la creación
![Image](https://github.com/user-attachments/assets/3b6ca3b2-d3a8-47df-b777-7c9d2948e52c)

**Comment by xDa04vidx** [comment]
### Errores
Se están teniendo complicaciones en el caso de error, no se esta mostrando el PopUp correspondiente, se esta trabajando en solucionar este error.

**Comment by xDa04vidx** [comment]
### Se soluciona el error para tratar los errores del mid

Se logra solucionar el error explicado en el anterior comentario
![Image](https://github.com/user-attachments/assets/29582297-fa74-4550-a710-5b901781688c)

**Comment by diagutierrezro** [comment]
Muy buen trabajo David
