### ISSUE TITLE
Corregir errores que vayan surgiendo en pruebas de SDK

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#91]
Se requiere realizar la corrección de los erores que vayan surgiendo a medida que se realizan pruebas de funcionamiento de X-Ray en Apis con python. Para esto por favor documentar el error encontrado y en caso de que la solución ya se encuentre ponerla tambien.

**Sub Tareas**

- [x] Documentar errores encontrados.
- [x] Solución de errores.

**Criterios de aceptación**

- [x] Errores encontrados.
- [x] Errores solucionados.
- [x] Documentación de errores y soluciones realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Surgieron varios errores, uno de los más demorados en solucionar fue la configuración del sdk de x-ray ya que no conectaba con aws, se soluciono, otro de los errores era que en aws no quedaba el registro de todas las peticiones que se hacian a la api es decir que si se hacian 4 peticiones http a la api, en aws se registraba solo una petición, también se soluciono: 
<img width="744" alt="image" src="https://github.com/user-attachments/assets/ee5e257a-ce43-4038-8835-77fcfb1b278f">
Ahora se esta terminando las pruebas con las peticiones post y put que tienen las funciones del sdk

**Comment by JulianAvella** [comment]
Petición http get con integración del sdk de xray: 
<img width="656" alt="image" src="https://github.com/user-attachments/assets/22ac78e0-8437-4ab8-8fff-e6f2d9cd4457">
<img width="914" alt="image" src="https://github.com/user-attachments/assets/4d11e4b5-cfa0-4dc4-abd6-a4dfbf46c7b8">

Petición http post con integración del sdk de xray: 
<img width="640" alt="image" src="https://github.com/user-attachments/assets/e1f083a7-72b4-481e-b78d-c47dd75a335f">
<img width="914" alt="image" src="https://github.com/user-attachments/assets/f3348ca2-2985-4ed1-a8ae-9422158a7040">

**Comment by diagutierrezro** [comment]
Unicamente falta el metodo de PUT por ser implementado, se asumirá en otro issue.
