### ISSUE TITLE
Realizar ajustes en metodo de verificación - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#92]
Se requiere realizar la investigación y ajuste para realizar la verificación de la firma electronica mediante la llave pública y la firma que se almacenan en la base de datos con las cuales se hace la verificación y se compara los hash.

**Sub Tareas**

- [x] Realizar investigación para realizar verificación de firma.
- [x] Realizar ajuste para verificar firma.
- [x] Documentar avances realizados.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Ajuste inicial realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 25/07/24

Se realiza el análisis preliminar para poder realizar la verificación utilizando la llave pública. Se generan dos documentos con el nuevo proceso de firma electrónica para realizar distintas pruebas. Sin embargo realizando análisis con ellos se determinó que se debe ajustar el método de verificación de firma electrónica ya que hay un fragmento de código que retorna un código 400 si la firma no está en los metadatos de la tabla de documentos del registro, por lo que todos los documentos generados a partir del cambio de persistencia de esta información siempre mandará código 400.

![image](https://github.com/user-attachments/assets/d692f194-6590-42fd-b0ba-7f94dd192e02)
 
![image](https://github.com/user-attachments/assets/c107e60b-0927-4eaa-b2e2-780a74dfd28f)

Ejemplo: Arriba registro posterior al cambio de persistencia, abajo registro anterior:

![image](https://github.com/user-attachments/assets/cc06d757-19c2-4e51-9e3d-ac5fee786e47)


Se realizará el ajuste de este apartado y se continuará con el análisis para la implementación de la nueva verificación

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 26/07/24

Se realiza el análisis e implementación de la nueva verificación.

Primero se ajusta el pendiente del día anterior ahora verificando la presencia del enlace a nuxeo:

![image](https://github.com/user-attachments/assets/d26f749b-5bbd-480b-9c00-d57b7c7fb97f)

Permitiendo así que el método funcione correctamente con los ajustes de persistencia implementados.

Posteriormente con ayuda del líder de equipo se logró implementar una verificación que se basa en el hash de la firma yla llave pública del registro del documento en la base de datos y el documento subido por el usuario en base 64:

![image](https://github.com/user-attachments/assets/78ff47da-3485-4536-b978-cb90d97a98f6)

Se probó su funcionamiento resultando en casos exitosos en el funcionamiento:

Con código y archivo iguales:

![image](https://github.com/user-attachments/assets/3f609683-4530-4dfd-9bdb-139fb8f7b17f)

Con código y archivo distintos:

![image](https://github.com/user-attachments/assets/eb6e70c7-5bf6-4bed-8620-57d7484cbc9f)

Con sólo código:

![image](https://github.com/user-attachments/assets/384c1d4d-e916-43b9-a26b-54990bb31bf3)

Por lo tanto se pasa el issue a in review

**Comment by diagutierrezro** [comment]
Se verifica correctamente la implementación de la verificación mediante llave_publica y firma para realizar dicha verificación. Gracias Andres.
