### ISSUE TITLE
Realizar ajuste en gestor documental para recibir otro tipo de documentos que no sean PDF.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#93]
Se requiere realizar el ajuste en el Api del gestor_documental_mid para que este permita cargar hacia núxeo otros documentos que no sean PDF como pueden ser word, excel, pptx.

**Sub Tareas**

- [x] Realizar investigación para definir en el gestor_documenta_mid alguna manera en la que se pueda detectar le extensión de un documento que llega en base64.
- [x] Implementar la lógica para detectar la extensión de un documento.
- [x] Revisar que sea posible en nuxeo en cargue de documentos que no sean PDF .
- [x] Realizar pruebas de correcto funcionamiento.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Implementación de lógica realizada.
- [x] Revisión de cargue de documentos no PDF realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/07/24

Se realizó la investigación del cargue de múltiples formatos en gestor documental.

Se encontró dentro de la API un endpoint llamado "uploadAnyFormat" dentro de gestor documental el cual es el siguiente:

![Captura de pantalla 2024-07-29 164850](https://github.com/user-attachments/assets/3f84c2e7-e243-429c-bd27-c7569b984e9a)

Dicho método se analizó y se estableció que podía servir como requerimiento para este Issue, por lo que se comenzó a probar con los siguientes formatos: docx (Word), PNG, JPG y xlsx (Excel). Se utilizó Postman para este propósito utilizando un json similar al siguiente en cada pruba (cambiando nombre, descripción y base 64):

![Captura de pantalla 2024-07-29 164047](https://github.com/user-attachments/assets/82471938-1abd-4b48-b7f3-c34ae5b8c910)

**Archivo de Word (docx):**

Se subió a Nuxeo un archivo de word y el sistema lo cargó correctamente mostrandose incluso la vista previa en la plataforma:

![Captura de pantalla 2024-07-29 163224](https://github.com/user-attachments/assets/4d053da3-7fbc-4e1d-a676-efb67807fe9c)

El archivo fué descargado y abierto para verificar su integridad y el mismo estaba en perfecto estado:

![image](https://github.com/user-attachments/assets/9cc32111-50d2-480b-86b3-fdf034f6335e)

**Archivo PNG:**

Se cargó una imagen en formato PNG para probar si el sistema la aceptaba, el archivo fué cargado exitosamente y se mostraba su vista previa de igual forma:

![Captura de pantalla 2024-07-29 163608](https://github.com/user-attachments/assets/16326224-40ef-453c-83a6-c33fb21a80c7)

De igual manera, se descargó y comprobó la integridad del archivo:

![Captura de pantalla 2024-07-29 171444](https://github.com/user-attachments/assets/9b1cc2c5-a891-4056-b001-4a322ba34881)

**Archivo JPG:**

Se cargó otra imagen en JPG obteniendo los mismos resultados de éxito:

![Captura de pantalla 2024-07-29 164156](https://github.com/user-attachments/assets/dba96887-47d3-42f3-983f-3a842f4881cc)

Se descargó y comprobó la integridad del archivo:

![image](https://github.com/user-attachments/assets/bb5d4d3c-eaae-47b2-a0bb-fdabf2eab73a)

**Archivo XLSX (Excel):**

Finalmente se usó un archivo de excel para probar. Como en los casos anteriores, el sistema aceptó el archivo e incluso mostraba la vista previa:

![Captura de pantalla 2024-07-29 164521](https://github.com/user-attachments/assets/5a1874c1-daf4-4fe2-870d-052b1678bad7)

Al descargar y abrir el archivo funcionó correctamente:

![image](https://github.com/user-attachments/assets/192d975e-97fd-47ee-9333-7490a1721cb9)


Las respuestas que arroja el método tienen la siguiente forma:

![Captura de pantalla 2024-07-29 164459](https://github.com/user-attachments/assets/cf575fe0-4bb7-4486-9329-d2c559791fe0)
![Captura de pantalla 2024-07-29 164505](https://github.com/user-attachments/assets/5ac67a0f-d946-429e-8199-83a8fc69b3b2)

Por lo tanto, como requerimiento es necesario que en el nombre que se envía en el json se especifique el formato en el que está el archivo, y obviamente el base64 del archivo en cuestión como datos de mayor relevancia.

Finalmente se identifica la presencia de la llave privada del documento en la respuesta del método, además de que la firma electrónica se está guardando solamente en la tabla de documento, por lo que puede ser un detalle a ajustar, sin embargo, el método cumple con los requerimientos para solucionar la problemática planteada en este issue

**Comment by diagutierrezro** [comment]
Se usa este endpoint encontrado para el sistema de pólux, funciona correctamente. Muy buen trabajo Andres.
