### ISSUE TITLE
Implementar función PUT para X-Ray

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#94]
Se requiere realizar la implementación con X-Ray de la funcionalidad http para los PUT que se realicen desde las Apis de python.

**Sub Tareas**

- [x] Implementación de funcionalidad PUT realizada.
- [x] Prueba de funcionamiento con Api gestor_documental_mid.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Se hace la implementación de la función put_json con el inicio y finalización del segmento para xray:
<img width="399" alt="image" src="https://github.com/user-attachments/assets/d25c838a-b566-4e46-9625-a30a2a5e0378">

Además se hacen las respectivas pruebas de la función con postman:
<img width="639" alt="image" src="https://github.com/user-attachments/assets/fcc1cc08-2f5b-4a37-8462-cbd95d605b84">

Nota: se demoro un poco más porque aparecieron unos errores como que la data no la tomaba de una forma correcta y unos errores 500: 
{
    "Status": "500",
    "Error": "'Response' object is not subscriptable"
}

**Comment by diagutierrezro** [comment]
Se comprueba correcto funcionamiento del PUT, gracias Julian.
