### ISSUE TITLE
Realizar la investigación relacionada con sistemas que requieran múltiples firmantes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/core_documentacion#95]
Se requiere realizar la investigación relacionada con sistemas que requieran múltiples firmantes.

**Sub Tareas**

- [x] Repasar la documentación relacionada con el negocio.
- [x] Generar contacto con responsables para requerir información.
- [x] Alimentar el documento según la información recopilada.
- [x] Definir los sistemas que implementarían múltiples firmantes.

**Criterios de aceptación**

- [x] Documento con la información requerida.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se va a realizar un listado con base a información dada por compañeros de la oficina 

[Documento del listado](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXDhMoMra59JgVQrIRRCAbIBc_rHkfGBpmc030l8iXRIMA?e=eay7VS)

**Comment by jcmurilloa** [comment]
Según lo repasado, se recomienda continuar la investigación con más actores relacionados para la referencia de los sistemas.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, pendiente definir prioridades de implementación con patrocinador del proyecto
