### ISSUE TITLE
Realizar investigación para implementar X-Ray python mediante librería.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#96]
Se requiere realizar investigación sobre como crear una librería en python donde se incluirá el archivo request y de configuración SDK por lo que se hace necesario investigar como crear una librería para python la cual se debe instalar despues con "pip install ..." y de esta manera realizar una prueba de concepto posteriormente.

**Sub Tareas**

- [x] Realizar investigación para crear librería de python.
- [x] Documentar las tareas que se tendrían que realizar para implementar estos archivos como una librería.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JulianAvella** [comment]
Para crear la libreria donde estara el sdk de python y su configuración con aws para xray:

Paso 1, estructura del proyecto:

xray_libreria/
├── xray_libreria/
│   ├── __init__.py
│   ├── request_tools.py
│   ├── xray.py
├── README.md
├── setup.py

Paso 2, archivo setup.py, es esencial para empaquetar y distribuir la librería:

from setuptools import setup, find_packages

setup(
    name='xray_libreria',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'requests',
        'boto3',
        'aws-xray-sdk',
        'flask'
    ],
    description='Libreria con el sdk y su configuración de xray',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='url del repositorio en github',  
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)

Paso 3, empaquetar la librería, en el directorio principal del proyecto (el que contiene setup.py) se ejecuta:

python setup.py sdist bdist_wheel

Nota paso 3: Esto creará un directorio dist/ que contiene los archivos empaquetados de la librería.

Paso 4, para probar la instalación de la librería, se usa pip:

pip install url de github/dist/xray_library-0.1.0-py3-none-any.whl

**Comment by diagutierrezro** [comment]
La implementación se realizará en otros issue.
