### ISSUE TITLE
Creación de lógica necesaria para gestión de dependencias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#98]
Se requiere realizar la lógica para el gestión de dependencias siguiendo los [mockups](https://github.com/udistrital/core_documentacion/issues/33) donde se iniciará con la realización del filtro para obtener el listado de dependencias, se debe tener en cuenta que este filtro debe ser dinámico ya que no es obligatorio llenar todos los campos para realizar la consulta, dicha consulta debe hacerse hacia la tabla dependencia_padre para realizar subconsultas desde allí. Una vez se obtenga el tipo de dependencia junto con la información de la dependencia se deben realizar consultas a la tabla dependencia_padre para obtener la información de la dependencia padre de cada una de las dependencias.

**Sub Tareas**

- [x] Crear estructura a recibir por parte del mid la cual llegará posteriormente desde el cliente en una petición POST, con la información que llegue en ese JSON se realizará el string de consulta que se enviará despues al crud de Oikos.
- [x] Realizar petición al CRUD con el query creado anteriormente.
- [x] El mid debe retornar un json con la información de cada dependencia incluyendo lo que se encuentra en dependencia_padre y dependencia_tipo_dependencia.

**Criterios de aceptación**

- [x] Estructura inicial para recibir petición desde el mid creada.
- [x] Petición al CRUD realizada.
- [x] Respuesta del mid realizada de manera correcta.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by xDa04vidx** [comment]
### Para búsqueda por nombre

Se realiza búsqueda para el caso que se pasa el nombre

![Image](https://github.com/user-attachments/assets/49e7f34d-ffd2-44d0-a8e9-51f2b4ba77fa)
**Data**
```bash
{
    "Data": [
        {
            "Dependencia": {
                "Id": 47,
                "Nombre": "EGRESADOS",
                "TelefonoDependencia": "",
                "CorreoElectronico": "",
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "DependenciaTipoDependencia": null
            },
            "DependenciaAsociada": {
                "Id": 8,
                "Nombre": "VICERRECTORIA ACADEMICA",
                "TelefonoDependencia": "3239300 Secretaria: 1901 - Asistente 1910 - Contratación 1904 - Fax/Saber Pro 1916",
                "CorreoElectronico": "vicerrecacad@udistrital.edu.co",
                "Activo": true,
                "FechaCreacion": "2022-07-06T19:45:10.995513Z",
                "FechaModificacion": "2022-07-06T19:45:10.995513Z",
                "DependenciaTipoDependencia": null
            },
            "TipoDependencia": [
                {
                    "Id": 12,
                    "Nombre": "LABORATORIO",
                    "Descripcion": "",
                    "CodigoAbreviacion": "",
                    "Activo": false,
                    "FechaCreacion": "0001-01-01T00:00:00Z",
                    "FechaModificacion": "0001-01-01T00:00:00Z"
                }
            ],
            "Estado": true
        }
    ],
    "Message": "Resultado de busqueda",
    "Status": 201,
    "Success": true
}
```

**Nota:**
Se esta teniendo problemas con las dependencias que tienen espacio en su nombre, se esta trabajando en su solución.

Se esta manejando la siguiente estructura de json para la peticion:
![Image](https://github.com/user-attachments/assets/f28ee85f-26b0-47ae-a61c-0d188868eade)

**Comment by xDa04vidx** [comment]
### Adelanto
Se logra realizar las búsquedas para tipo de dependencia, facultad, vicerrectoría y estado, se mantiene el formato de la búsqueda por nombre, y se comprueba que se puede realizar la petición con todos los campos, de manera individual y combinada.

**Búsqueda por tipo**
![Image](https://github.com/user-attachments/assets/3af5a186-9011-4308-9762-b671675cc509)

**Búsqueda por nombre y tipo**
![Image](https://github.com/user-attachments/assets/2d042922-1542-4b43-b5df-01f1eb111c1f)
El contenido se suma y se realiza comprobación para que no existan repetidos.

**Búsqueda por Facultad**
![Image](https://github.com/user-attachments/assets/14cf60e7-216f-4175-8ea3-4117e4f78dce)

**Búsqueda por Vicerrectoría**
![Image](https://github.com/user-attachments/assets/e3179f64-ce79-40e1-846c-13b42eb44339)

**Búsqueda por estado**
En este caso se realizo una corrección en la forma de enviar el json.
![Image](https://github.com/user-attachments/assets/27a650de-6b0d-46e1-88e5-161786ccffa3)

La respuesta se tarda un poco dado que todas las dependencias tienen el estado en true
![Image](https://github.com/user-attachments/assets/69ab7a71-6567-45e4-b530-f4aeac3c9155)

**Búsqueda con todos los campos**
![Image](https://github.com/user-attachments/assets/ae7d5bf2-fca3-401e-ace1-48718c8ecce8)


**Estructura de Json final**
![Image](https://github.com/user-attachments/assets/9e6ac898-2027-48e2-a1a2-88ef6b054888)

**Comment by xDa04vidx** [comment]
### Corrección espacios en el nombre

Se corrige el error


![Image](https://github.com/user-attachments/assets/59442a06-9818-4f0b-99e9-e45ec310d4ed)

**Comment by xDa04vidx** [comment]
### Pull request
Se realiza pull request en [gestion_dependencias_mid](https://github.com/udistrital/gestion_dependencias_mid)
![Image](https://github.com/user-attachments/assets/a14824f1-8676-428f-ba36-c863f33fa8cd)
