### ISSUE TITLE
Probar minuciosamente funcionamiento de verificación.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/core_documentacion#99]
Se requiere realizar unas pruebas minuciosas del funcionamiento del cliente de verificación realizando cambios pequeños a los documentos firmados y comprobando que el cliente funcione de manera correcta.

**Sub Tareas**

- [x] Pruebas minuciosas al cliente de verificación

**Criterios de aceptación**

- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Skyrus1203** [comment]
### ACTUALIZACIÓN 29/07/24

Para la prueba minuciosa del cliente de verificación con el nuevo método de verificación de llave pública implementado, se modificó un archivo pdf firmado con PDF24 agregandole un espacio vacío encima del espacio entre párrafos en la zona encerrada en rojo:

![image](https://github.com/user-attachments/assets/cc40c896-bab8-4978-bd12-32dde7bce13a)

Ese archivo modificado se guardó como "prueba1 modificado.pdf" esto con el fin de confirmar que se puede detectar incluso el más mínimo cambio.

Posteriormente se ingresa el código de autenticación con el archivo pdf modificado:

![image](https://github.com/user-attachments/assets/afd7fbed-a594-4e13-a154-360e82df021b)

Con el siguiente resultado:

![image](https://github.com/user-attachments/assets/e2fec35a-205f-4442-954b-c660423a41a8)

Ahora bien si cargamos el archivo prueba1.pdf el cual es el archivo original de donde proviene la firma:

![image](https://github.com/user-attachments/assets/40b7d4a3-949d-472a-9c34-e9667fb51956)


Obtenemos el siguiente resultado:

![image](https://github.com/user-attachments/assets/b89b8a15-da2c-435b-ab85-fc3bb7ef2dfe)


Por lo tanto se confirma que cualquier diferencia podrá ser detectada por el nuevo método de verificación. Se pasa este issue a in review

**Comment by diagutierrezro** [comment]
Se verifica correctamente que la verificación por llaves detecta cambios pequeños en el documento.
